/* Cognitive Fusion Questionnaire, CFQ-7 (Gillanders et al. 2014) — libero. IT: Oppo et al. (2019). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.cfq = {
  code: "CFQ", theme: "teal", n: 7,
  labels: {
    en: ["Never true", "Very seldom true", "Seldom true", "Sometimes true", "Frequently true", "Almost always true", "Always true"],
    it: ["Mai vera", "Molto raramente vera", "Raramente vera", "A volte vera", "Spesso vera", "Quasi sempre vera", "Sempre vera"]
  },
  items: {
    en: ["My thoughts cause me distress or emotional pain.", "I get so caught up in my thoughts that I am unable to do the things that I most want to do.", "I over-analyse situations to the point where it's unhelpful to me.", "I struggle with my thoughts.", "I get upset with myself for having certain thoughts.", "I tend to get very entangled in my thoughts.", "It's such a struggle to let go of upsetting thoughts even when I know that letting go would be helpful."],
    it: ["I miei pensieri mi causano disagio o dolore emotivo.", "Mi faccio prendere talmente dai miei pensieri da non riuscire a fare le cose che desidero di più.", "Analizzo troppo le situazioni, al punto che non mi è utile.", "Lotto con i miei pensieri.", "Mi arrabbio con me stesso per avere certi pensieri.", "Tendo a rimanere molto intrappolato nei miei pensieri.", "Lasciar andare i pensieri che mi turbano è una tale lotta, anche quando so che lasciarli andare mi aiuterebbe."]
  },
  text: {
    it: { kicker: "Fusione cognitiva", title: "Quanto ti credono i tuoi pensieri?", lede: "7 affermazioni, 1 minuto. Il CFQ misura la «fusione cognitiva»: quanto resti intrappolato nei pensieri e li tratti come fatti. È il gemello dell'AAQ-II nel modello ACT.", meta: ["7 domande", "~1 minuto"], instr: "Per ogni frase indica <b>quanto è vera per te</b>, da 1 (mai vera) a 7 (sempre vera).", how: "Il punteggio va da 7 a 49; più è alto, più i pensieri ti catturano. Nei campioni di popolazione generale la media è intorno a 20–24, nei campioni clinici intorno a 35. Non esistono soglie diagnostiche: le fasce qui sono orientative. Fusione alta e evitamento esperienziale (AAQ-II) alto tendono ad andare insieme.", cite: "Gillanders, D. T., et al. (2014). The development and initial validation of the Cognitive Fusion Questionnaire. Behavior Therapy, 45, 83-101. Versione italiana: Oppo et al. (2019). Uso libero." },
    en: { kicker: "Cognitive fusion", title: "How much do your thoughts run you?", lede: "7 statements, 1 minute. The CFQ measures “cognitive fusion”: how entangled you get in your thoughts and how much you treat them as facts. It is the AAQ-II's twin in the ACT model.", meta: ["7 questions", "~1 minute"], instr: "For each statement, indicate <b>how true it is for you</b>, from 1 (never true) to 7 (always true).", how: "The score runs from 7 to 49; the higher, the more your thoughts capture you. In general-population samples the mean is around 20–24, in clinical samples around 35. There are no diagnostic thresholds: the bands here are orientative. High fusion and high experiential avoidance (AAQ-II) tend to go together.", cite: "Gillanders, D. T., et al. (2014). The development and initial validation of the Cognitive Fusion Questionnaire. Behavior Therapy, 45, 83-101. Free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Fusione cognitiva", en: "Cognitive fusion" }, items: [1,2,3,4,5,6,7], mode: "sum", range: [7, 49],
    bands: [
      { max: 20, name: { it: "Bassa", en: "Low" }, text: { it: "I pensieri passano senza catturarti troppo: riesci a vederli come pensieri, non come verità.", en: "Thoughts pass without capturing you too much: you can see them as thoughts, not truths." } },
      { max: 30, name: { it: "Nella media", en: "Average" }, text: { it: "Come la maggior parte delle persone: a volte resti impigliato, a volte riesci a prendere distanza.", en: "Like most people: sometimes you get tangled, sometimes you manage to step back." } },
      { max: 40, name: { it: "Alta", en: "High" }, text: { it: "I pensieri ti trattengono spesso e li vivi come fatti. Nel modello ACT è il punto su cui si lavora per primo: imparare a osservarli («sto avendo il pensiero che…») invece di combatterli.", en: "Thoughts often hold you and you experience them as facts. In the ACT model this is where the work starts: learning to observe them (“I'm having the thought that…”) instead of fighting them." } },
      { max: 49, name: { it: "Molto alta", en: "Very high" }, text: { it: "Nella fascia dei campioni clinici: la lotta con i pensieri occupa molto spazio. Parlarne con un professionista formato in ACT o terapia cognitiva è la mossa sensata.", en: "In the range of clinical samples: the struggle with thoughts takes up a lot of room. Talking to a professional trained in ACT or cognitive therapy is the sensible move." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.cfq.approf = {
  it: {
    title: "La fusione cognitiva: quando il pensiero diventa il mondo",
    intro: `<p>Il CFQ misura la <span class="t" data-tip="Fusione cognitiva: essere così presi da un pensiero da trattarlo come realtà letterale, lasciando che detti il comportamento. È un concetto chiave dell'ACT.">fusione cognitiva</span>, un concetto centrale dell'<span class="t" data-tip="Acceptance and Commitment Therapy: terapia cognitivo-comportamentale di terza ondata (Steven Hayes) centrata sul rapporto con i pensieri, non sul loro contenuto.">ACT</span>. Fondersi con un pensiero significa scambiarlo per la realtà: «sono un fallito» non è più una frase che passa nella mente, è un fatto da cui agire. Il suo opposto è la <span class="t" data-tip="Defusione: fare un passo indietro e vedere un pensiero come un evento mentale (parole, immagini) che va e viene, senza per forza crederci o obbedirgli.">defusione</span>. È il gemello dell'<span class="t" data-tip="Acceptance and Action Questionnaire-II: misura l'evitamento esperienziale. Fusione ed evitamento tendono ad andare insieme, ed è per questo che i due strumenti sono imparentati.">AAQ-II</span>: dove quello guarda all'evitamento delle emozioni, il CFQ guarda alla presa dei pensieri. Fu sviluppato e validato da <span class="t" data-tip="David Gillanders e colleghi (2014): svilupparono e validarono il Cognitive Fusion Questionnaire, arrivando a una versione breve e robusta a sette item.">Gillanders e colleghi</span> nel 2014.</p>`,
    blocks: [
      { h: "Fusione, non contenuto", html: `<p>Ecco la distinzione decisiva: il CFQ non misura <em>cosa</em> pensi (se i pensieri sono tristi, ansiosi, autocritici) ma <em>come</em> li tieni: come verità letterali o come eventi mentali. Due persone con lo stesso pensiero cupo — «non ce la farò» — possono differire enormemente: una ci si fonde e si blocca, l'altra lo nota passare e agisce lo stesso. Il bersaglio del test è la <b>relazione</b> con il pensiero, non il pensiero.</p>` },
      { h: "La defusione: cambiare rapporto, non contenuto", html: `<p>Qui l'ACT si stacca dalla <span class="t" data-tip="Ristrutturazione cognitiva: tecnica della terapia cognitiva classica che mette in discussione un pensiero e ne valuta la verità per sostituirlo con uno più realistico.">ristrutturazione cognitiva</span> della terapia cognitiva classica. Non si discute se il pensiero sia vero: si cambia il modo di tenerlo. Un piccolo spostamento linguistico — da «sono inutile» a «sto avendo il pensiero che sono inutile» — crea distanza. Alcune tecniche di <span class="t" data-tip="Deliteralizzazione: togliere a una parola il suo peso di verità. Ripetere ad alta voce una parola per trenta secondi la trasforma in puro suono: un esercizio classico che risale a Titchener.">deliteralizzazione</span>, come ripetere una parola finché diventa solo un suono, mostrano quanto sia arbitrario il potere che diamo alle parole.</p>` },
      { h: "Perché conta: fusione e sofferenza", html: `<p>La fusione è uno degli ingranaggi che trasformano un pensiero negativo in sofferenza duratura: fa da <span class="t" data-tip="Mediatore: variabile che spiega il legame tra due cose. Negli studi ACT la fusione media in parte il passaggio da pensieri negativi a ansia e depressione.">mediatore</span> tra i pensieri difficili e il disagio. Fusione alta ed evitamento esperienziale alto (AAQ-II) viaggiano insieme, e nell'ACT sono spesso il primo punto su cui si lavora: prima si impara a osservare i pensieri, poi si agisce verso ciò che conta.</p>` }
    ],
    beyond: `<ul>
      <li><b>Fusione contro terapia cognitiva.</b> La CBT classica cambia il contenuto del pensiero («è davvero vero?»); l'ACT ne cambia la presa («è solo un pensiero»). Due logiche diverse, spesso efficaci entrambe.</li>
      <li><b>La deliteralizzazione.</b> L'esercizio di ripetere una parola fino a svuotarla di significato risale a Titchener, oltre un secolo fa: mostra che il peso di verità di una parola è un'abitudine, non una proprietà della parola.</li>
      <li><b>Il legame con l'AAQ-II.</b> CFQ e AAQ-II correlano tra loro molto forte: fusione ed evitamento sono facce vicine dello stesso processo, e questa vicinanza è insieme una conferma teorica e un problema di misura.</li>
      <li><b>Non è una diagnosi.</b> Non esistono soglie cliniche per il CFQ; le fasce sono orientative e il punteggio è sensibile al momento.</li>
    </ul>`,
    taratura: `<p>Il CFQ-7 è breve, affidabile (coerenza interna alta, intorno a .88-.90) e con una struttura a un solo fattore che regge bene in campioni diversi: dal punto di vista psicometrico è uno strumento pulito. Il limite è lo stesso delle altre misure di processo dell'ACT: si sovrappone molto all'AAQ-II e alle misure generali di disagio e nevroticismo, quindi la sua <span class="t" data-tip="Validità discriminante: quanto una misura si distingue da costrutti vicini. Per il CFQ è il punto debole, come per l'AAQ-II.">validità discriminante</span> è discutibile. Non ci sono soglie diagnostiche: le fasce sono indicative, non verdetti. Non è, in nessun caso, una diagnosi.</p>`,
    reading: [
      "Gillanders, D. T., et al. (2014). The development and initial validation of the Cognitive Fusion Questionnaire. <em>Behavior Therapy</em>, 45, 83-101.",
      "Hayes, S. C., Luoma, J. B., Bond, F. W., Masuda, A. & Lillis, J. (2006). Acceptance and Commitment Therapy: model, processes and outcomes. <em>Behaviour Research and Therapy</em>, 44, 1-25.",
      "Oppo, A., et al. (2019). The Italian version of the Cognitive Fusion Questionnaire. <em>Journal of Contextual Behavioral Science</em>."
    ]
  },
  en: {
    title: "Cognitive fusion: when a thought becomes the world",
    intro: `<p>The CFQ measures <span class="t" data-tip="Cognitive fusion: being so caught in a thought that you treat it as literal reality, letting it dictate behaviour. A key concept in ACT.">cognitive fusion</span>, a central idea in <span class="t" data-tip="Acceptance and Commitment Therapy: a third-wave cognitive-behavioural therapy (Steven Hayes) focused on our relationship with thoughts, not their content.">ACT</span>. To fuse with a thought is to mistake it for reality: "I'm a failure" is no longer a sentence passing through the mind, it's a fact you act from. Its opposite is <span class="t" data-tip="Defusion: stepping back to see a thought as a mental event (words, images) that comes and goes, without necessarily believing or obeying it.">defusion</span>. It's the twin of the <span class="t" data-tip="Acceptance and Action Questionnaire-II: measures experiential avoidance. Fusion and avoidance tend to travel together, which is why the two instruments are related.">AAQ-II</span>: where that looks at avoiding emotions, the CFQ looks at the grip of thoughts. It was developed and validated by <span class="t" data-tip="David Gillanders and colleagues (2014) developed and validated the Cognitive Fusion Questionnaire, arriving at a robust seven-item short form.">Gillanders and colleagues</span> in 2014.</p>`,
    blocks: [
      { h: "Fusion, not content", html: `<p>Here's the decisive distinction: the CFQ doesn't measure <em>what</em> you think (whether thoughts are sad, anxious, self-critical) but <em>how</em> you hold them: as literal truths or as mental events. Two people with the same dark thought — "I won't make it" — can differ enormously: one fuses with it and freezes, the other notices it pass and acts anyway. The test's target is the <b>relationship</b> with the thought, not the thought.</p>` },
      { h: "Defusion: changing the relationship, not the content", html: `<p>Here ACT parts from the <span class="t" data-tip="Cognitive restructuring: a classic cognitive-therapy technique that questions a thought and weighs its truth to replace it with a more realistic one.">cognitive restructuring</span> of classic cognitive therapy. You don't debate whether the thought is true: you change how you hold it. A small linguistic shift — from "I'm useless" to "I'm having the thought that I'm useless" — creates distance. Some <span class="t" data-tip="Deliteralization: stripping a word of its weight of truth. Repeating a word aloud for thirty seconds turns it into pure sound: a classic exercise going back to Titchener.">deliteralization</span> techniques, like repeating a word until it becomes just a sound, show how arbitrary the power we give words is.</p>` },
      { h: "Why it matters: fusion and distress", html: `<p>Fusion is one of the gears that turn a negative thought into lasting distress: it acts as a <span class="t" data-tip="Mediator: a variable that explains the link between two things. In ACT studies fusion partly mediates the path from negative thoughts to anxiety and depression.">mediator</span> between difficult thoughts and suffering. High fusion and high experiential avoidance (AAQ-II) travel together, and in ACT they're often the first thing worked on: first you learn to observe thoughts, then you act towards what matters.</p>` }
    ],
    beyond: `<ul>
      <li><b>Fusion versus cognitive therapy.</b> Classic CBT changes the content of the thought ("is it really true?"); ACT changes its grip ("it's only a thought"). Two different logics, often both effective.</li>
      <li><b>Deliteralization.</b> The exercise of repeating a word until it empties of meaning goes back to Titchener, over a century ago: it shows that a word's weight of truth is a habit, not a property of the word.</li>
      <li><b>The link with the AAQ-II.</b> CFQ and AAQ-II correlate very strongly: fusion and avoidance are neighbouring faces of the same process, and that closeness is both a theoretical confirmation and a measurement problem.</li>
      <li><b>Not a diagnosis.</b> There are no clinical cut-offs for the CFQ; the bands are orientative and the score is sensitive to the moment.</li>
    </ul>`,
    taratura: `<p>The CFQ-7 is short, reliable (high internal consistency, around .88-.90) and with a single-factor structure that holds up well across samples: psychometrically it's a clean instrument. Its limit is the one shared by other ACT process measures: it overlaps heavily with the AAQ-II and with general measures of distress and neuroticism, so its <span class="t" data-tip="Discriminant validity: how far a measure distinguishes itself from nearby constructs. For the CFQ it's the weak point, as for the AAQ-II.">discriminant validity</span> is debatable. There are no diagnostic thresholds: the bands are indicative, not verdicts. It is, in no case, a diagnosis.</p>`,
    reading: [
      "Gillanders, D. T., et al. (2014). The development and initial validation of the Cognitive Fusion Questionnaire. <em>Behavior Therapy</em>, 45, 83-101.",
      "Hayes, S. C., Luoma, J. B., Bond, F. W., Masuda, A. & Lillis, J. (2006). Acceptance and Commitment Therapy: model, processes and outcomes. <em>Behaviour Research and Therapy</em>, 44, 1-25.",
      "Oppo, A., et al. (2019). The Italian version of the Cognitive Fusion Questionnaire. <em>Journal of Contextual Behavioral Science</em>."
    ]
  },
  pt: {
    title: "A fusão cognitiva: quando o pensamento vira o mundo",
    intro: `<p>O CFQ mede a <span class="t" data-tip="Fusão cognitiva: estar tão preso a um pensamento a ponto de tratá-lo como realidade literal, deixando que ele dite o comportamento. É um conceito-chave da ACT.">fusão cognitiva</span>, um conceito central da <span class="t" data-tip="Acceptance and Commitment Therapy: terapia cognitivo-comportamental de terceira onda (Steven Hayes) centrada na relação com os pensamentos, não no seu conteúdo.">ACT</span>. Fundir-se com um pensamento é confundi-lo com a realidade: «sou um fracasso» deixa de ser uma frase que passa na mente e vira um fato a partir do qual se age. Seu oposto é a <span class="t" data-tip="Desfusão: dar um passo atrás e ver um pensamento como um evento mental (palavras, imagens) que vem e vai, sem necessariamente acreditar nele ou obedecê-lo.">desfusão</span>. É o gêmeo do <span class="t" data-tip="Acceptance and Action Questionnaire-II: mede a evitação experiencial. Fusão e evitação tendem a andar juntas, e por isso os dois instrumentos são aparentados.">AAQ-II</span>: onde este olha para a evitação das emoções, o CFQ olha para o domínio dos pensamentos. Foi desenvolvido e validado por <span class="t" data-tip="David Gillanders e colegas (2014) desenvolveram e validaram o Cognitive Fusion Questionnaire, chegando a uma versão curta e robusta de sete itens.">Gillanders e colegas</span> em 2014.</p>`,
    blocks: [
      { h: "Fusão, não conteúdo", html: `<p>Eis a distinção decisiva: o CFQ não mede <em>o que</em> você pensa (se os pensamentos são tristes, ansiosos, autocríticos) mas <em>como</em> você os segura: como verdades literais ou como eventos mentais. Duas pessoas com o mesmo pensamento sombrio — «não vou conseguir» — podem diferir enormemente: uma se funde e trava, a outra o nota passar e age mesmo assim. O alvo do teste é a <b>relação</b> com o pensamento, não o pensamento.</p>` },
      { h: "A desfusão: mudar a relação, não o conteúdo", html: `<p>Aqui a ACT se separa da <span class="t" data-tip="Reestruturação cognitiva: técnica da terapia cognitiva clássica que questiona um pensamento e avalia sua verdade para substituí-lo por um mais realista.">reestruturação cognitiva</span> da terapia cognitiva clássica. Não se discute se o pensamento é verdadeiro: muda-se o modo de segurá-lo. Um pequeno deslocamento linguístico — de «sou inútil» para «estou tendo o pensamento de que sou inútil» — cria distância. Algumas técnicas de <span class="t" data-tip="Desliteralização: tirar de uma palavra o seu peso de verdade. Repetir uma palavra em voz alta por trinta segundos a transforma em puro som: um exercício clássico que remonta a Titchener.">desliteralização</span>, como repetir uma palavra até virar só um som, mostram como é arbitrário o poder que damos às palavras.</p>` },
      { h: "Por que conta: fusão e sofrimento", html: `<p>A fusão é uma das engrenagens que transformam um pensamento negativo em sofrimento duradouro: faz de <span class="t" data-tip="Mediador: variável que explica o vínculo entre duas coisas. Nos estudos ACT a fusão medeia em parte a passagem de pensamentos negativos a ansiedade e depressão.">mediador</span> entre os pensamentos difíceis e o mal-estar. Fusão alta e evitação experiencial alta (AAQ-II) andam juntas, e na ACT costumam ser o primeiro ponto de trabalho: primeiro se aprende a observar os pensamentos, depois se age em direção ao que importa.</p>` }
    ],
    beyond: `<ul>
      <li><b>Fusão contra terapia cognitiva.</b> A TCC clássica muda o conteúdo do pensamento («é mesmo verdade?»); a ACT muda o seu domínio («é só um pensamento»). Duas lógicas diferentes, muitas vezes eficazes ambas.</li>
      <li><b>A desliteralização.</b> O exercício de repetir uma palavra até esvaziá-la de sentido remonta a Titchener, há mais de um século: mostra que o peso de verdade de uma palavra é um hábito, não uma propriedade da palavra.</li>
      <li><b>O vínculo com o AAQ-II.</b> CFQ e AAQ-II correlacionam entre si muito forte: fusão e evitação são faces vizinhas do mesmo processo, e essa proximidade é ao mesmo tempo uma confirmação teórica e um problema de medida.</li>
      <li><b>Não é um diagnóstico.</b> Não existem limiares clínicos para o CFQ; as faixas são orientativas e o escore é sensível ao momento.</li>
    </ul>`,
    taratura: `<p>O CFQ-7 é breve, confiável (consistência interna alta, em torno de .88-.90) e com uma estrutura de fator único que se sustenta bem em amostras diversas: do ponto de vista psicométrico é um instrumento limpo. Seu limite é o mesmo das outras medidas de processo da ACT: sobrepõe-se muito ao AAQ-II e às medidas gerais de sofrimento e neuroticismo, então sua <span class="t" data-tip="Validade discriminante: o quanto uma medida se distingue de construtos próximos. Para o CFQ é o ponto fraco, como para o AAQ-II.">validade discriminante</span> é discutível. Não há limiares diagnósticos: as faixas são indicativas, não veredictos. Não é, em nenhum caso, um diagnóstico.</p>`,
    reading: [
      "Gillanders, D. T., et al. (2014). The development and initial validation of the Cognitive Fusion Questionnaire. <em>Behavior Therapy</em>, 45, 83-101.",
      "Hayes, S. C., Luoma, J. B., Bond, F. W., Masuda, A. & Lillis, J. (2006). Acceptance and Commitment Therapy: model, processes and outcomes. <em>Behaviour Research and Therapy</em>, 44, 1-25.",
      "Oppo, A., et al. (2019). The Italian version of the Cognitive Fusion Questionnaire. <em>Journal of Contextual Behavioral Science</em>."
    ]
  }
};
