/* DASS-21 (Lovibond & Lovibond 1995) — pubblico dominio. IT: Bottesi et al. (2015); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.dass21 = {
  code: "DASS-21", theme: "slate", sensitive: true, n: 21, values: [0, 1, 2, 3],
  labels: {
    en: ["Did not apply to me at all", "Applied to me to some degree, or some of the time", "Applied to me to a considerable degree, or a good part of time", "Applied to me very much, or most of the time"],
    it: ["Non mi è mai successo", "Mi è successo qualche volta", "Mi è successo con una certa frequenza", "Mi è successo quasi sempre"]
  },
  items: {
    en: ["I found it hard to wind down", "I was aware of dryness of my mouth", "I couldn't seem to experience any positive feeling at all", "I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)", "I found it difficult to work up the initiative to do things", "I tended to over-react to situations", "I experienced trembling (e.g. in the hands)", "I felt that I was using a lot of nervous energy", "I was worried about situations in which I might panic and make a fool of myself", "I felt that I had nothing to look forward to", "I found myself getting agitated", "I found it difficult to relax", "I felt down-hearted and blue", "I was intolerant of anything that kept me from getting on with what I was doing", "I felt I was close to panic", "I was unable to become enthusiastic about anything", "I felt I wasn't worth much as a person", "I felt that I was rather touchy", "I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)", "I felt scared without any good reason", "I felt that life was meaningless"],
    it: ["Ho avuto difficoltà a rilassarmi", "Mi sono accorto di avere la bocca secca", "Non riuscivo a provare alcuna emozione positiva", "Ho avuto difficoltà a respirare (per esempio respiro molto veloce, fiato corto senza sforzo fisico)", "Ho trovato difficile prendere l'iniziativa per fare le cose", "Ho avuto la tendenza a reagire in modo esagerato alle situazioni", "Ho avuto tremori (per esempio alle mani)", "Ho sentito di consumare molta energia nervosa", "Ero preoccupato per situazioni in cui avrei potuto farmi prendere dal panico e rendermi ridicolo", "Ho sentito di non avere nulla da aspettarmi dal futuro", "Mi sono accorto di agitarmi", "Ho trovato difficile rilassarmi", "Mi sono sentito scoraggiato e triste", "Non tolleravo nulla che mi impedisse di continuare quello che stavo facendo", "Ho sentito di essere vicino al panico", "Non riuscivo a entusiasmarmi per nulla", "Ho sentito di valere poco come persona", "Ho sentito di essere piuttosto suscettibile", "Mi sono accorto del battito del mio cuore senza sforzo fisico (per esempio sensazione di battito accelerato o di un battito saltato)", "Mi sono sentito spaventato senza un buon motivo", "Ho sentito che la vita non aveva senso"]
  },
  text: {
    it: { kicker: "Depressione, ansia, stress", title: "Com'è andata l'ultima settimana?", lede: "21 affermazioni, 4 minuti. La DASS-21 misura tre stati distinti — depressione, ansia e stress — con soglie di gravità pubblicate. Uno screening, non una diagnosi.", meta: ["21 domande", "~4 minuti", "3 scale", "Screening"], instr: "Per ogni frase indica quanto ti si è applicata <b>nell'ultima settimana</b>. Non ci sono risposte giuste o sbagliate; non fermarti troppo su ciascuna.", how: "Tre punteggi (ogni sottoscala ha 7 domande; il totale viene moltiplicato per 2 per confrontarlo con la versione lunga, quindi va da 0 a 42). Fasce degli autori — Depressione: 0–9 normale, 10–13 lieve, 14–20 moderata, 21–27 grave, 28+ estremamente grave. Ansia: 0–7, 8–9, 10–14, 15–19, 20+. Stress: 0–14, 15–18, 19–25, 26–33, 34+. «Grave» indica la distanza dalla popolazione generale, non una diagnosi clinica.", cite: "Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales (2nd ed.). Psychology Foundation, Sydney. Pubblico dominio. Versione italiana: Bottesi et al. (2015)." },
    en: { kicker: "Depression, anxiety, stress", title: "How was the past week?", lede: "21 statements, 4 minutes. The DASS-21 measures three distinct states — depression, anxiety and stress — with published severity thresholds. A screening tool, not a diagnosis.", meta: ["21 questions", "~4 minutes", "3 scales", "Screening"], instr: "For each statement, indicate how much it applied to you <b>over the past week</b>. There are no right or wrong answers; do not spend too long on any one.", how: "Three scores (each subscale has 7 questions; the total is multiplied by 2 to compare with the long version, so it runs from 0 to 42). Authors' bands — Depression: 0–9 normal, 10–13 mild, 14–20 moderate, 21–27 severe, 28+ extremely severe. Anxiety: 0–7, 8–9, 10–14, 15–19, 20+. Stress: 0–14, 15–18, 19–25, 26–33, 34+. “Severe” indicates distance from the general population, not a clinical diagnosis.", cite: "Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales (2nd ed.). Psychology Foundation, Sydney. Public domain." }
  },
  scales: [
    { key: "d", name: { it: "Depressione", en: "Depression" }, items: [3, 5, 10, 13, 16, 17, 21], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 9, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 13, name: { it: "Lieve", en: "Mild" }, text: { it: "Un po' sopra la norma: umore basso e poca energia in questa settimana.", en: "Slightly above the norm: low mood and little energy this week." } },
      { max: 20, name: { it: "Moderata", en: "Moderate" }, text: { it: "Sintomi depressivi chiari. Se durano più di due settimane, parlane con il medico o con uno psicologo.", en: "Clear depressive symptoms. If they last more than two weeks, talk to a doctor or a psychologist." } },
      { max: 27, name: { it: "Grave", en: "Severe" }, text: { it: "Sintomi che pesano molto. Chiedere aiuto ora è la mossa giusta.", en: "Symptoms that weigh heavily. Asking for help now is the right move." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: parla oggi con un professionista o con i numeri qui sotto.", en: "Very far from the norm: talk to a professional or the numbers below today." } }] },
    { key: "a", name: { it: "Ansia", en: "Anxiety" }, items: [2, 4, 7, 9, 15, 19, 20], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 7, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 9, name: { it: "Lieve", en: "Mild" }, text: { it: "Un po' di attivazione fisica in più del solito.", en: "A bit more physical arousal than usual." } },
      { max: 14, name: { it: "Moderata", en: "Moderate" }, text: { it: "Sintomi d'ansia chiari, anche fisici (respiro, cuore, tremori). L'ansia risponde bene ai trattamenti.", en: "Clear anxiety symptoms, physical ones too (breathing, heart, trembling). Anxiety responds well to treatment." } },
      { max: 19, name: { it: "Grave", en: "Severe" }, text: { it: "Ansia intensa e frequente: vale un colloquio con un professionista.", en: "Intense, frequent anxiety: worth a conversation with a professional." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: chiedi aiuto.", en: "Very far from the norm: ask for help." } }] },
    { key: "s", name: { it: "Stress", en: "Stress" }, items: [1, 6, 8, 11, 12, 14, 18], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 14, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 18, name: { it: "Lieve", en: "Mild" }, text: { it: "Tensione e irritabilità un po' sopra la norma.", en: "Tension and irritability slightly above the norm." } },
      { max: 25, name: { it: "Moderato", en: "Moderate" }, text: { it: "Difficoltà a rilassarsi, reazioni esagerate, nervi tesi: guarda cosa sta caricando la settimana.", en: "Difficulty relaxing, over-reactions, frayed nerves: look at what is loading the week." } },
      { max: 33, name: { it: "Grave", en: "Severe" }, text: { it: "Stress alto e persistente: alleggerire qualcosa e chiedere aiuto sono entrambe buone mosse.", en: "High, persistent stress: lightening the load and asking for help are both good moves." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: chiedi aiuto.", en: "Very far from the norm: ask for help." } }] }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.dass21.approf = {
  it: {
    title: "Depressione, ansia e stress: perché insieme",
    intro: `<p>La DASS non misura tre disturbi, ma tre <b>stati emotivi</b> vicini che spesso si confondono. Nasce dal tentativo di Lovibond e Lovibond di separare ciò che depressione e ansia hanno in comune da ciò che le distingue, seguendo il <span class="t" data-tip="Clark e Watson (1991): un modello che spiega perché ansia e depressione si somigliano tanto. Condividono l'affetto negativo; la depressione ha in più poca affettività positiva, l'ansia ha in più l'attivazione fisiologica.">modello tripartito</span> di Clark e Watson. È uno strumento di <span class="t" data-tip="Un filtro che misura intensità e gravità degli stati emotivi, non un test che assegna una diagnosi. Un risultato alto è un invito a guardarci meglio.">screening</span> dimensionale: dà tre punteggi di gravità, non tre etichette.</p>`,
    blocks: [
      { h: "Perché tre scale e non una", html: `<p>Ansia e depressione si sovrappongono perché condividono l'<span class="t" data-tip="La tendenza generale a provare emozioni spiacevoli — paura, tristezza, tensione, senso di colpa. È il terreno comune di quasi tutti i disturbi emotivi e la ragione per cui si presentano spesso insieme.">affetto negativo</span>: è il terreno comune. Ciò che le separa è specifico. La depressione porta con sé una bassa <span class="t" data-tip="La capacità di provare entusiasmo, energia, piacere e interesse. Nella depressione crolla: è l'anedonia. L'ansia, invece, la lascia relativamente intatta.">affettività positiva</span> — spento l'entusiasmo, l'anedonia. L'ansia porta con sé l'<span class="t" data-tip="L'attivazione del corpo di fronte a una minaccia: cuore accelerato, respiro corto, tremori, bocca secca. È il segno fisico specifico dell'ansia, assente nella depressione pura.">attivazione fisiologica</span> — cuore, respiro, tremori. La DASS costruisce le sue scale proprio intorno a questa idea: catturare il tronco comune e i due rami specifici.</p>` },
      { h: "Le tre scale in breve", html: `<p><b>Depressione</b>: la scala misura la bassa affettività positiva — mancanza di senso, di valore, di slancio, <span class="t" data-tip="Dal greco senza piacere: la perdita della capacità di provare gusto per ciò che prima piaceva. È il segno centrale della bassa affettività positiva.">anedonia</span>. <b>Ansia</b>: misura l'attivazione fisiologica e la paura situazionale — sintomi del corpo e timore di perdere il controllo. <b>Stress</b>: misura la tensione persistente — difficoltà a rilassarsi, irritabilità, reazioni esagerate, nervi tesi. Le prime due scale colgono i due poli specifici; la terza coglie l'attivazione cronica non specifica, che fa da ponte tra le altre due.</p>` },
      { h: "Lo stress come terza dimensione", html: `<p>Lo stress nella DASS non è l'evento esterno, ma lo <b>stato di tensione</b> che ne deriva: essere sempre sul filo, saltare per poco, non riuscire a staccare. È la dimensione più vicina all'<span class="t" data-tip="La sovrapposizione tra due misure che dovrebbero essere distinte. La scala Stress della DASS correla molto con depressione e ansia, perché misura in gran parte la stessa tensione di fondo.">affetto negativo generale</span>, e per questo tende a salire insieme alle altre due. Aiuta a vedere quando il carico è tensione irritabile piuttosto che umore basso o paura del corpo.</p>` },
      { h: "Il ×2 e le soglie", html: `<p>La DASS-21 è la versione breve della <span class="t" data-tip="La versione originale a 42 item, con 14 domande per scala. La DASS-21 la dimezza e per questo il punteggio grezzo va moltiplicato per due.">DASS-42</span>: ogni scala ha 7 domande invece di 14, così il punteggio grezzo viene <b>moltiplicato per due</b> per confrontarlo con le fasce e le norme originali. Le soglie (normale, lieve, moderato, grave, estremamente grave) non sono confini diagnostici: dicono quanto ci si allontana dalla popolazione generale. Grave significa lontano dalla media, non malato.</p>` }
    ],
    beyond: `<ul>
      <li><b>Misura uno stato, non un tratto.</b> Le domande riguardano l'ultima settimana; i punteggi cambiano con il periodo. La DASS serve a seguire l'andamento nel tempo, non a definire chi sei.</li>
      <li><b>La scala Stress è la meno specifica.</b> È quella più vicina al <span class="t" data-tip="Il tratto di personalità che descrive la tendenza stabile a provare emozioni negative. È lo sfondo su cui poggiano molti disturbi emotivi.">nevroticismo</span> e all'affetto negativo generale: alta quasi sempre quando le altre due sono alte.</li>
      <li><b>La depressione si vede dal segno che manca.</b> Non è solo tristezza in più, è entusiasmo in meno: la scala Depressione della DASS è costruita apposta per cogliere quel vuoto, non il pianto.</li>
      <li><b>Tre numeri, una lettura sola.</b> Il profilo conta più dei singoli punteggi: quale scala domina, e di quanto, dice più del totale. Ma resta un punto di partenza per una conversazione, non una diagnosi.</li>
    </ul>`,
    taratura: `<p>La DASS-21 ha ottime proprietà psicometriche: coerenza interna alta su tutte e tre le scale e struttura a tre fattori replicata in molti Paesi. Il limite onesto è che le tre scale <b>correlano parecchio tra loro</b>, soprattutto Depressione e Stress: la separazione è reale ma imperfetta, coerente con l'idea che condividano l'affetto negativo. Non è uno strumento diagnostico: è un'autodescrizione dell'ultima settimana, e le fasce di gravità indicano la distanza dalla norma, non una malattia. Serve per aprire una conversazione con un professionista, non per sostituirla.</p>`,
    reading: [
      "Lovibond, S. H. & Lovibond, P. F. (1995). <em>Manual for the Depression Anxiety Stress Scales</em> (2ª ed.). Psychology Foundation, Sydney.",
      "Clark, L. A. & Watson, D. (1991). Tripartite model of anxiety and depression. <em>Journal of Abnormal Psychology</em>, 100, 316-336.",
      "Henry, J. D. & Crawford, J. R. (2005). The short-form version of the DASS-21. <em>British Journal of Clinical Psychology</em>, 44, 227-239."
    ]
  },
  en: {
    title: "Depression, anxiety and stress: why together",
    intro: `<p>The DASS does not measure three disorders, but three neighbouring <b>emotional states</b> that are often confused. It grew out of Lovibond and Lovibond's attempt to separate what depression and anxiety share from what tells them apart, following Clark and Watson's <span class="t" data-tip="Clark and Watson (1991): a model explaining why anxiety and depression resemble each other so much. They share negative affect; depression adds low positive affect, anxiety adds physiological arousal.">tripartite model</span>. It is a dimensional <span class="t" data-tip="A filter that measures the intensity and severity of emotional states, not a test that assigns a diagnosis. A high result is an invitation to look more closely.">screening</span> tool: it gives three severity scores, not three labels.</p>`,
    blocks: [
      { h: "Why three scales, not one", html: `<p>Anxiety and depression overlap because they share <span class="t" data-tip="The general tendency to feel unpleasant emotions — fear, sadness, tension, guilt. It is the common ground of nearly all emotional disorders and the reason they so often appear together.">negative affect</span>: that is the common ground. What separates them is specific. Depression brings low <span class="t" data-tip="The capacity to feel enthusiasm, energy, pleasure and interest. In depression it collapses: that is anhedonia. Anxiety, by contrast, leaves it relatively intact.">positive affect</span> — enthusiasm switched off, anhedonia. Anxiety brings <span class="t" data-tip="The body's activation in the face of a threat: racing heart, short breath, trembling, dry mouth. It is the specific physical sign of anxiety, absent in pure depression.">physiological arousal</span> — heart, breathing, trembling. The DASS builds its scales around exactly this idea: capture the common trunk and the two specific branches.</p>` },
      { h: "The three scales in brief", html: `<p><b>Depression</b>: the scale measures low positive affect — lack of meaning, worth, drive, <span class="t" data-tip="From the Greek for without pleasure: the loss of the capacity to enjoy what used to please. It is the central sign of low positive affect.">anhedonia</span>. <b>Anxiety</b>: it measures physiological arousal and situational fear — bodily symptoms and dread of losing control. <b>Stress</b>: it measures persistent tension — trouble relaxing, irritability, over-reactions, frayed nerves. The first two scales catch the two specific poles; the third catches the non-specific chronic arousal that bridges them.</p>` },
      { h: "Stress as a third dimension", html: `<p>Stress in the DASS is not the external event but the <b>state of tension</b> that follows: always on edge, jumping at little, unable to switch off. It is the dimension closest to <span class="t" data-tip="The overlap between two measures that ought to be distinct. The DASS Stress scale correlates strongly with depression and anxiety, because it largely measures the same underlying tension.">general negative affect</span>, and so it tends to rise together with the other two. It helps you see when the load is irritable tension rather than low mood or bodily fear.</p>` },
      { h: "The ×2 and the thresholds", html: `<p>The DASS-21 is the short form of the <span class="t" data-tip="The original 42-item version, with 14 questions per scale. The DASS-21 halves it, which is why the raw score is multiplied by two.">DASS-42</span>: each scale has 7 questions instead of 14, so the raw score is <b>multiplied by two</b> to compare it with the original bands and norms. The thresholds (normal, mild, moderate, severe, extremely severe) are not diagnostic boundaries: they say how far you sit from the general population. Severe means far from the average, not ill.</p>` }
    ],
    beyond: `<ul>
      <li><b>It measures a state, not a trait.</b> The questions ask about the past week; the scores change with the period. The DASS is for tracking the trend over time, not for defining who you are.</li>
      <li><b>The Stress scale is the least specific.</b> It is the one closest to <span class="t" data-tip="The personality trait describing the stable tendency to feel negative emotions. It is the backdrop on which many emotional disorders rest.">neuroticism</span> and to general negative affect: almost always high when the other two are high.</li>
      <li><b>Depression shows in what is missing.</b> It is not just extra sadness, it is less enthusiasm: the DASS Depression scale is built precisely to catch that emptiness, not the tears.</li>
      <li><b>Three numbers, one reading.</b> The profile matters more than the single scores: which scale dominates, and by how much, says more than the total. But it remains a starting point for a conversation, not a diagnosis.</li>
    </ul>`,
    taratura: `<p>The DASS-21 has excellent psychometric properties: high internal consistency on all three scales and a three-factor structure replicated across many countries. The honest limit is that the three scales <b>correlate substantially with each other</b>, especially Depression and Stress: the separation is real but imperfect, consistent with the idea that they share negative affect. It is not a diagnostic tool: it is a self-report of the past week, and the severity bands indicate distance from the norm, not an illness. It is for opening a conversation with a professional, not replacing one.</p>`,
    reading: [
      "Lovibond, S. H. & Lovibond, P. F. (1995). <em>Manual for the Depression Anxiety Stress Scales</em> (2nd ed.). Psychology Foundation, Sydney.",
      "Clark, L. A. & Watson, D. (1991). Tripartite model of anxiety and depression. <em>Journal of Abnormal Psychology</em>, 100, 316-336.",
      "Henry, J. D. & Crawford, J. R. (2005). The short-form version of the DASS-21. <em>British Journal of Clinical Psychology</em>, 44, 227-239."
    ]
  },
  pt: {
    title: "Depressão, ansiedade e estresse: por que juntos",
    intro: `<p>A DASS não mede três transtornos, mas três <b>estados emocionais</b> vizinhos que costumam se confundir. Nasceu da tentativa de Lovibond e Lovibond de separar o que depressão e ansiedade têm em comum do que as distingue, seguindo o <span class="t" data-tip="Clark e Watson (1991): um modelo que explica por que ansiedade e depressão se parecem tanto. Compartilham o afeto negativo; a depressão acrescenta baixo afeto positivo, a ansiedade acrescenta a ativação fisiológica.">modelo tripartite</span> de Clark e Watson. É um instrumento de <span class="t" data-tip="Um filtro que mede a intensidade e a gravidade dos estados emocionais, não um teste que atribui um diagnóstico. Um resultado alto é um convite a olhar melhor.">triagem</span> dimensional: dá três pontuações de gravidade, não três rótulos.</p>`,
    blocks: [
      { h: "Por que três escalas e não uma", html: `<p>Ansiedade e depressão se sobrepõem porque compartilham o <span class="t" data-tip="A tendência geral de sentir emoções desagradáveis — medo, tristeza, tensão, culpa. É o terreno comum de quase todos os transtornos emocionais e a razão de aparecerem tantas vezes juntos.">afeto negativo</span>: é o terreno comum. O que as separa é específico. A depressão traz um baixo <span class="t" data-tip="A capacidade de sentir entusiasmo, energia, prazer e interesse. Na depressão desaba: é a anedonia. A ansiedade, por outro lado, a deixa relativamente intacta.">afeto positivo</span> — entusiasmo desligado, anedonia. A ansiedade traz a <span class="t" data-tip="A ativação do corpo diante de uma ameaça: coração acelerado, falta de ar, tremores, boca seca. É o sinal físico específico da ansiedade, ausente na depressão pura.">ativação fisiológica</span> — coração, respiração, tremores. A DASS constrói suas escalas em torno dessa ideia: captar o tronco comum e os dois ramos específicos.</p>` },
      { h: "As três escalas em resumo", html: `<p><b>Depressão</b>: a escala mede o baixo afeto positivo — falta de sentido, de valor, de impulso, <span class="t" data-tip="Do grego sem prazer: a perda da capacidade de sentir gosto pelo que antes agradava. É o sinal central do baixo afeto positivo.">anedonia</span>. <b>Ansiedade</b>: mede a ativação fisiológica e o medo situacional — sintomas do corpo e receio de perder o controle. <b>Estresse</b>: mede a tensão persistente — dificuldade de relaxar, irritabilidade, reações exageradas, nervos à flor da pele. As duas primeiras escalas captam os dois polos específicos; a terceira capta a ativação crônica inespecífica, que faz a ponte entre as outras duas.</p>` },
      { h: "O estresse como terceira dimensão", html: `<p>O estresse na DASS não é o evento externo, mas o <b>estado de tensão</b> que dele resulta: estar sempre no limite, saltar por pouco, não conseguir desligar. É a dimensão mais próxima do <span class="t" data-tip="A sobreposição entre duas medidas que deveriam ser distintas. A escala Estresse da DASS correlaciona muito com depressão e ansiedade, porque mede em boa parte a mesma tensão de fundo.">afeto negativo geral</span>, e por isso tende a subir junto com as outras duas. Ajuda a ver quando a carga é tensão irritável, e não humor baixo ou medo do corpo.</p>` },
      { h: "O ×2 e as faixas", html: `<p>A DASS-21 é a versão curta da <span class="t" data-tip="A versão original de 42 itens, com 14 perguntas por escala. A DASS-21 a reduz à metade, por isso a pontuação bruta é multiplicada por dois.">DASS-42</span>: cada escala tem 7 perguntas em vez de 14, então a pontuação bruta é <b>multiplicada por dois</b> para ser comparada com as faixas e as normas originais. As faixas (normal, leve, moderado, grave, extremamente grave) não são fronteiras diagnósticas: dizem o quanto a pessoa se afasta da população geral. Grave significa longe da média, não doente.</p>` }
    ],
    beyond: `<ul>
      <li><b>Mede um estado, não um traço.</b> As perguntas se referem à última semana; as pontuações mudam com o período. A DASS serve para acompanhar a evolução no tempo, não para definir quem você é.</li>
      <li><b>A escala Estresse é a menos específica.</b> É a mais próxima do <span class="t" data-tip="O traço de personalidade que descreve a tendência estável a sentir emoções negativas. É o pano de fundo sobre o qual muitos transtornos emocionais se apoiam.">neuroticismo</span> e do afeto negativo geral: quase sempre alta quando as outras duas estão altas.</li>
      <li><b>A depressão se vê pelo sinal que falta.</b> Não é só tristeza a mais, é entusiasmo a menos: a escala Depressão da DASS é feita de propósito para captar esse vazio, não o choro.</li>
      <li><b>Três números, uma leitura só.</b> O perfil importa mais que as pontuações isoladas: qual escala domina, e por quanto, diz mais que o total. Mas continua sendo um ponto de partida para uma conversa, não um diagnóstico.</li>
    </ul>`,
    taratura: `<p>A DASS-21 tem ótimas propriedades psicométricas: consistência interna alta nas três escalas e estrutura de três fatores replicada em muitos países. O limite honesto é que as três escalas <b>correlacionam bastante entre si</b>, sobretudo Depressão e Estresse: a separação é real, mas imperfeita, coerente com a ideia de que compartilham o afeto negativo. Não é um instrumento diagnóstico: é uma autodescrição da última semana, e as faixas de gravidade indicam a distância da norma, não uma doença. Serve para abrir uma conversa com um profissional, não para substituí-la.</p>`,
    reading: [
      "Lovibond, S. H. & Lovibond, P. F. (1995). <em>Manual for the Depression Anxiety Stress Scales</em> (2ª ed.). Psychology Foundation, Sydney.",
      "Clark, L. A. & Watson, D. (1991). Tripartite model of anxiety and depression. <em>Journal of Abnormal Psychology</em>, 100, 316-336.",
      "Henry, J. D. & Crawford, J. R. (2005). The short-form version of the DASS-21. <em>British Journal of Clinical Psychology</em>, 44, 227-239."
    ]
  }
};
