/* DASS-21 (Lovibond & Lovibond 1995) — pubblico dominio. IT: Bottesi et al. (2015); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.dass21 = {
  code: "DASS-21", theme: "slate", sensitive: true, n: 21, values: [0, 1, 2, 3],
  labels: {
    en: ["Did not apply to me at all", "Applied to me to some degree, or some of the time", "Applied to me to a considerable degree, or a good part of time", "Applied to me very much, or most of the time"],
    it: ["Non mi è mai successo", "Mi è successo qualche volta", "Mi è successo con una certa frequenza", "Mi è successo quasi sempre"]
  },
  items: {
    en: ["I found it hard to wind down", "I was aware of dryness of my mouth", "I couldn't seem to experience any positive feeling at all", "I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)", "I found it difficult to work up the initiative to do things", "I tended to over-react to situations", "I experienced trembling (e.g. in the hands)", "I felt that I was using a lot of nervous energy", "I was worried about situations in which I might panic and make a fool of myself", "I felt that I had nothing to look forward to", "I found myself getting agitated", "I found it difficult to relax", "I felt down-hearted and blue", "I was intolerant of anything that kept me from getting on with what I was doing", "I felt I was close to panic", "I was unable to become enthusiastic about anything", "I felt I wasn't worth much as a person", "I felt that I was rather touchy", "I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)", "I felt scared without any good reason", "I felt that life was meaningless"],
    it: ["Ho avuto difficoltà a rilassarmi", "Mi sono accorto di avere la bocca secca", "Non riuscivo a provare alcuna emozione positiva", "Ho avuto difficoltà a respirare (per esempio respiro molto veloce, fiato corto senza sforzo fisico)", "Ho trovato difficile prendere l'iniziativa per fare le cose", "Ho avuto la tendenza a reagire in modo esagerato alle situazioni", "Ho avuto tremori (per esempio alle mani)", "Ho sentito di consumare molta energia nervosa", "Ero preoccupato per situazioni in cui avrei potuto farmi prendere dal panico e rendermi ridicolo", "Ho sentito di non avere nulla da aspettarmi dal futuro", "Mi sono accorto di agitarmi", "Ho trovato difficile rilassarmi", "Mi sono sentito scoraggiato e triste", "Non tolleravo nulla che mi impedisse di continuare quello che stavo facendo", "Ho sentito di essere vicino al panico", "Non riuscivo a entusiasmarmi per nulla", "Ho sentito di valere poco come persona", "Ho sentito di essere piuttosto suscettibile", "Mi sono accorto del battito del mio cuore senza sforzo fisico (per esempio sensazione di battito accelerato o di un battito saltato)", "Mi sono sentito spaventato senza un buon motivo", "Ho sentito che la vita non aveva senso"]
  },
  text: {
    it: { kicker: "Depressione, ansia, stress", title: "Com'è andata l'ultima settimana?", lede: "21 affermazioni, 4 minuti. La DASS-21 misura tre stati distinti — depressione, ansia e stress — con soglie di gravità pubblicate. Uno screening, non una diagnosi.", meta: ["21 domande", "~4 minuti", "3 scale", "Screening"], instr: "Per ogni frase indica quanto ti si è applicata <b>nell'ultima settimana</b>. Non ci sono risposte giuste o sbagliate; non fermarti troppo su ciascuna.", how: "Tre punteggi (ogni sottoscala ha 7 domande; il totale viene moltiplicato per 2 per confrontarlo con la versione lunga, quindi va da 0 a 42). Fasce degli autori — Depressione: 0–9 normale, 10–13 lieve, 14–20 moderata, 21–27 grave, 28+ estremamente grave. Ansia: 0–7, 8–9, 10–14, 15–19, 20+. Stress: 0–14, 15–18, 19–25, 26–33, 34+. «Grave» indica la distanza dalla popolazione generale, non una diagnosi clinica.", cite: "Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales (2nd ed.). Psychology Foundation, Sydney. Pubblico dominio. Versione italiana: Bottesi et al. (2015)." },
    en: { kicker: "Depression, anxiety, stress", title: "How was the past week?", lede: "21 statements, 4 minutes. The DASS-21 measures three distinct states — depression, anxiety and stress — with published severity thresholds. A screening tool, not a diagnosis.", meta: ["21 questions", "~4 minutes", "3 scales", "Screening"], instr: "For each statement, indicate how much it applied to you <b>over the past week</b>. There are no right or wrong answers; do not spend too long on any one.", how: "Three scores (each subscale has 7 questions; the total is multiplied by 2 to compare with the long version, so it runs from 0 to 42). Authors' bands — Depression: 0–9 normal, 10–13 mild, 14–20 moderate, 21–27 severe, 28+ extremely severe. Anxiety: 0–7, 8–9, 10–14, 15–19, 20+. Stress: 0–14, 15–18, 19–25, 26–33, 34+. “Severe” indicates distance from the general population, not a clinical diagnosis.", cite: "Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales (2nd ed.). Psychology Foundation, Sydney. Public domain." }
  },
  scales: [
    { key: "d", name: { it: "Depressione", en: "Depression" }, items: [3, 5, 10, 13, 16, 17, 21], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 9, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 13, name: { it: "Lieve", en: "Mild" }, text: { it: "Un po' sopra la norma: umore basso e poca energia in questa settimana.", en: "Slightly above the norm: low mood and little energy this week." } },
      { max: 20, name: { it: "Moderata", en: "Moderate" }, text: { it: "Sintomi depressivi chiari. Se durano più di due settimane, parlane con il medico o con uno psicologo.", en: "Clear depressive symptoms. If they last more than two weeks, talk to a doctor or a psychologist." } },
      { max: 27, name: { it: "Grave", en: "Severe" }, text: { it: "Sintomi che pesano molto. Chiedere aiuto ora è la mossa giusta.", en: "Symptoms that weigh heavily. Asking for help now is the right move." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: parla oggi con un professionista o con i numeri qui sotto.", en: "Very far from the norm: talk to a professional or the numbers below today." } }] },
    { key: "a", name: { it: "Ansia", en: "Anxiety" }, items: [2, 4, 7, 9, 15, 19, 20], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 7, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 9, name: { it: "Lieve", en: "Mild" }, text: { it: "Un po' di attivazione fisica in più del solito.", en: "A bit more physical arousal than usual." } },
      { max: 14, name: { it: "Moderata", en: "Moderate" }, text: { it: "Sintomi d'ansia chiari, anche fisici (respiro, cuore, tremori). L'ansia risponde bene ai trattamenti.", en: "Clear anxiety symptoms, physical ones too (breathing, heart, trembling). Anxiety responds well to treatment." } },
      { max: 19, name: { it: "Grave", en: "Severe" }, text: { it: "Ansia intensa e frequente: vale un colloquio con un professionista.", en: "Intense, frequent anxiety: worth a conversation with a professional." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: chiedi aiuto.", en: "Very far from the norm: ask for help." } }] },
    { key: "s", name: { it: "Stress", en: "Stress" }, items: [1, 6, 8, 11, 12, 14, 18], mode: "sum", multiply: 2, range: [0, 42], bands: [
      { max: 14, name: { it: "Normale", en: "Normal" }, text: { it: "Nella fascia della popolazione generale.", en: "In the general-population range." } },
      { max: 18, name: { it: "Lieve", en: "Mild" }, text: { it: "Tensione e irritabilità un po' sopra la norma.", en: "Tension and irritability slightly above the norm." } },
      { max: 25, name: { it: "Moderato", en: "Moderate" }, text: { it: "Difficoltà a rilassarsi, reazioni esagerate, nervi tesi: guarda cosa sta caricando la settimana.", en: "Difficulty relaxing, over-reactions, frayed nerves: look at what is loading the week." } },
      { max: 33, name: { it: "Grave", en: "Severe" }, text: { it: "Stress alto e persistente: alleggerire qualcosa e chiedere aiuto sono entrambe buone mosse.", en: "High, persistent stress: lightening the load and asking for help are both good moves." } },
      { max: 42, name: { it: "Estremamente grave", en: "Extremely severe" }, text: { it: "Molto lontano dalla norma: chiedi aiuto.", en: "Very far from the norm: ask for help." } }] }
  ]
};
