/* Emotion Regulation Questionnaire (Gross & John 2003) — libero per uso non commerciale. IT: Balzarotti, John & Gross (2010). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.erq = {
  code: "ERQ", theme: "rose", n: 10, sexNorms: true,
  norms: { reap: { all: { m: 4.61, sd: 0.94 }, m: { m: 4.60, sd: 0.94 }, f: { m: 4.61, sd: 0.95 } }, supp: { all: { m: 3.31, sd: 1.17 }, m: { m: 3.64, sd: 1.11 }, f: { m: 3.14, sd: 1.18 } } },
  labels: {
    en: ["Strongly disagree", "Disagree", "Somewhat disagree", "Neutral", "Somewhat agree", "Agree", "Strongly agree"],
    it: ["Fortemente in disaccordo", "In disaccordo", "Un po' in disaccordo", "Neutrale", "Un po' d'accordo", "D'accordo", "Fortemente d'accordo"]
  },
  items: {
    en: ["When I want to feel more positive emotion (such as joy or amusement), I change what I'm thinking about.", "I keep my emotions to myself.", "When I want to feel less negative emotion (such as sadness or anger), I change what I'm thinking about.", "When I am feeling positive emotions, I am careful not to express them.", "When I'm faced with a stressful situation, I make myself think about it in a way that helps me stay calm.", "I control my emotions by not expressing them.", "When I want to feel more positive emotion, I change the way I'm thinking about the situation.", "I control my emotions by changing the way I think about the situation I'm in.", "When I am feeling negative emotions, I make sure not to express them.", "When I want to feel less negative emotion, I change the way I'm thinking about the situation."],
    it: ["Quando voglio provare più emozioni positive (come gioia o divertimento), cambio quello a cui sto pensando.", "Tengo le mie emozioni per me.", "Quando voglio provare meno emozioni negative (come tristezza o rabbia), cambio quello a cui sto pensando.", "Quando provo emozioni positive, faccio attenzione a non esprimerle.", "Quando affronto una situazione stressante, mi sforzo di pensarci in un modo che mi aiuti a restare calmo.", "Controllo le mie emozioni non esprimendole.", "Quando voglio provare più emozioni positive, cambio il modo in cui penso alla situazione.", "Controllo le mie emozioni cambiando il modo in cui penso alla situazione in cui mi trovo.", "Quando provo emozioni negative, mi assicuro di non esprimerle.", "Quando voglio provare meno emozioni negative, cambio il modo in cui penso alla situazione."]
  },
  text: {
    it: { kicker: "Regolazione emotiva", title: "Come gestisci le emozioni?", lede: "10 affermazioni, 2 minuti. L'ERQ di Gross distingue due strategie: rivalutare la situazione (ripensarla) e sopprimere l'espressione (non farla vedere).", meta: ["10 domande", "~2 minuti", "2 strategie"], instr: "Le frasi riguardano la tua <b>vita emotiva</b>: come controlli e regoli le emozioni. Alcune parlano dell'esperienza interna, altre dell'espressione verso gli altri. Per ognuna indica quanto sei d'accordo.", how: "Due punteggi da 1 a 7, ciascuno la media delle sue domande. Rivalutazione cognitiva (6 domande): media adulti circa 4,6. Soppressione espressiva (4 domande): media circa 3,6 per gli uomini e 3,1 per le donne. La rivalutazione è associata a più emozioni positive e relazioni migliori; la soppressione a più tensione interna e minore vicinanza. Non sono buone o cattive in assoluto: dipende dal contesto.", cite: "Gross, J. J., & John, O. P. (2003). Individual differences in two emotion regulation processes. Journal of Personality and Social Psychology, 85, 348-362. Versione italiana: Balzarotti, John & Gross (2010). Uso libero non commerciale." },
    en: { kicker: "Emotion regulation", title: "How do you handle your emotions?", lede: "10 statements, 2 minutes. Gross's ERQ separates two strategies: reappraising the situation (rethinking it) and suppressing expression (not letting it show).", meta: ["10 questions", "~2 minutes", "2 strategies"], instr: "The statements concern your <b>emotional life</b>: how you control and regulate your emotions. Some are about your inner experience, others about expression towards others. Indicate how much you agree with each.", how: "Two scores from 1 to 7, each the mean of its questions. Cognitive reappraisal (6 questions): adult mean about 4.6. Expressive suppression (4 questions): mean about 3.6 for men and 3.1 for women. Reappraisal is linked to more positive emotion and better relationships; suppression to more inner tension and less closeness. Neither is good or bad in itself: it depends on context.", cite: "Gross, J. J., & John, O. P. (2003). Individual differences in two emotion regulation processes. Journal of Personality and Social Psychology, 85, 348-362. Free for non-commercial use." }
  },
  scales: [
    { key: "reap", name: { it: "Rivalutazione cognitiva", en: "Cognitive reappraisal" }, items: [1,3,5,7,8,10], mode: "mean", range: [1, 7],
      bands: [
        { max: 3.9, name: { it: "Bassa", en: "Low" }, text: { it: "Ripensi raramente le situazioni per cambiare quello che provi: le emozioni ti arrivano così come sono. È la strategia più allenabile: chiedersi «come altro potrei vedere questa cosa?» è già un inizio.", en: "You rarely rethink situations to change what you feel: emotions arrive as they are. It is the most trainable strategy: asking “how else could I see this?” is already a start." } },
        { max: 5.3, name: { it: "Nella media", en: "Average" }, text: { it: "Usi la rivalutazione come la maggior parte delle persone: a volte riesci a vedere le cose da un'altra angolazione, a volte no.", en: "You use reappraisal like most people: sometimes you manage to see things from another angle, sometimes not." } },
        { max: 7, name: { it: "Alta", en: "High" }, text: { it: "Ripensare le situazioni ti viene naturale: è la strategia più associata a benessere e buone relazioni.", en: "Rethinking situations comes naturally to you: it is the strategy most linked to well-being and good relationships." } }
      ] },
    { key: "supp", name: { it: "Soppressione espressiva", en: "Expressive suppression" }, items: [2,4,6,9], mode: "mean", range: [1, 7],
      bands: [
        { max: 2.6, name: { it: "Bassa", en: "Low" }, text: { it: "Quello che provi si vede: esprimi le emozioni con facilità. Gli altri ti leggono, e questo favorisce la vicinanza.", en: "What you feel shows: you express emotions easily. Others can read you, which fosters closeness." } },
        { max: 4.3, name: { it: "Nella media", en: "Average" }, text: { it: "A volte trattieni, a volte lasci vedere: una dose di soppressione nella norma.", en: "Sometimes you hold back, sometimes you let it show: a normal dose of suppression." } },
        { max: 7, name: { it: "Alta", en: "High" }, text: { it: "Tendi a non far vedere quello che provi, positive comprese. Protegge nell'immediato ma costa: più tensione interna e gli altri che ti sentono distante.", en: "You tend not to show what you feel, positive emotions included. It protects in the moment but has a cost: more inner tension and others feeling you are distant." } }
      ] }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.erq.approf = {
  it: {
    title: "Regolare le emozioni: due strade",
    intro: `<p>L'ERQ nasce dal <span class="t" data-tip="Modello di processo di James Gross: un'emozione si sviluppa nel tempo, dalla situazione all'attenzione alla valutazione fino alla risposta. In ogni punto si può intervenire, con costi diversi.">modello di processo</span> di <span class="t" data-tip="James Gross, psicologo di Stanford: ha fondato la ricerca moderna sulla regolazione delle emozioni e ideato l'Emotion Regulation Questionnaire nel 2003.">James Gross</span>. Un'emozione non è un lampo istantaneo: si costruisce in fasi, e a seconda di dove intervieni la regolazione costa poco o molto. Il questionario isola le due strategie più studiate: la <span class="t" data-tip="Rivalutazione cognitiva: ripensare il significato di una situazione prima che l'emozione sia piena, per cambiare ciò che si prova. È una strategia a monte, antecedente.">rivalutazione cognitiva</span>, che agisce presto sul significato, e la <span class="t" data-tip="Soppressione espressiva: trattenere la manifestazione esterna dell'emozione quando è già in corso. È una strategia a valle, sulla risposta.">soppressione espressiva</span>, che agisce tardi, solo sull'espressione. Non sono buone o cattive in assoluto: cambiano di prezzo a seconda del momento.</p>`,
    blocks: [
      { h: "Cinque famiglie di strategie", html: `<p>Gross ordina la regolazione lungo la vita dell'emozione: <b>scegliere la situazione</b> (evitare o cercare un contesto), <b>modificarla</b> (cambiare ciò che accade), <b>spostare l'attenzione</b> (distrarsi o concentrarsi), <b>cambiare la valutazione</b> (la rivalutazione) e infine <b>modulare la risposta</b> (la soppressione). Le prime quattro agiscono <em>prima</em> che l'emozione divampi; l'ultima <em>dopo</em>. L'ERQ misura una <span class="t" data-tip="A monte: si interviene presto, prima che l'emozione sia piena (come la rivalutazione). A valle: si interviene tardi, quando l'emozione c'è già (come la soppressione).">strategia a monte e una a valle</span>: è questa collocazione a spiegare perché costano così diversamente.</p>` },
      { h: "Perché la rivalutazione costa meno", html: `<p>Ripensare il significato di una situazione la intercetta <em>prima</em> che l'emozione sia a pieno regime: cambi ciò che senti alla radice. In laboratorio la rivalutazione è associata a più emozioni positive, minore attivazione fisiologica e una migliore memoria di ciò che è accaduto; nelle misure di vita, a più benessere e relazioni più solide. È anche la strategia più <b>allenabile</b>: chiedersi «in che altro modo posso leggere questa cosa?» è già l'inizio.</p>` },
      { h: "Il conto nascosto della soppressione", html: `<p>Trattenere l'espressione agisce quando l'emozione c'è già: spegne la faccia, non il fuoco. L'esperienza interna non cala — spesso aumenta — e sale l'<span class="t" data-tip="Attivazione del sistema nervoso simpatico: la componente fisiologica dell'attivazione (battito, sudore, tensione). La soppressione la lascia salire o la aumenta, mentre riduce solo ciò che si vede.">attivazione fisiologica</span>. C'è anche un costo sociale e cognitivo: chi sopprime durante una conversazione ricorda peggio i dettagli, e l'altro lo percepisce più distante e meno in sintonia. Protegge nell'immediato, ma il conto arriva.</p>` },
      { h: "La bravura è la flessibilità", html: `<p>Nessuna strategia è giusta sempre. Reprimere la rabbia in una riunione può essere saggio; farlo ogni sera con chi ami logora il legame. Per gli stress <b>incontrollabili e intensi</b>, a volte la distrazione batte la rivalutazione. La competenza vera è la <span class="t" data-tip="Flessibilità regolatoria: la capacità di scegliere la strategia adatta al contesto e di cambiarla se non funziona, invece di usare sempre la stessa. È un predittore di adattamento migliore della singola strategia.">flessibilità regolatoria</span>: scegliere lo strumento giusto per il momento, e cambiarlo quando non funziona.</p>` }
    ],
    beyond: `<ul>
      <li><b>La cultura conta.</b> La soppressione pesa meno dove è la norma: in campioni di cultura più interdipendente il suo legame con il minor benessere è più debole (Butler, Soto e colleghi). Non è una legge universale.</li>
      <li><b>Differenze di genere.</b> In media gli uomini riportano più soppressione delle donne, differenza in parte legata alle norme su cosa è lecito mostrare.</li>
      <li><b>La rivalutazione non è magia.</b> Davanti a uno stress ad alta intensità e non controllabile, allontanare l'attenzione può funzionare meglio del ripensarlo (Sheppes): la strategia migliore dipende dall'intensità.</li>
      <li><b>Regolare non è reprimere.</b> L'obiettivo non è smettere di sentire, ma che l'emozione resti utile: a volte significa lasciarla esistere, non spegnerla.</li>
    </ul>`,
    taratura: `<p>L'ERQ misura le <b>strategie abituali dichiarate</b>, non la capacità reale di usarle: è un autoresoconto. Le due scale sono affidabili (<span class="t" data-tip="Coerenza interna: quanto le domande di una stessa scala si muovono insieme. Un valore alto indica che misurano davvero la stessa cosa.">coerenza interna</span> buona, un po' più alta per la rivalutazione che per la soppressione, che ha solo quattro item). Il vantaggio della rivalutazione è ben documentato in laboratorio, ma i legami con il benessere sono <span class="t" data-tip="Correlazionale: mostra che due cose vanno insieme, non che una causa l'altra. Chi sta meglio può rivalutare di più, non solo il contrario.">correlazionali</span> e di dimensione da piccola a moderata, e dipendono dal contesto. La lettura da evitare è «soppressione = male, rivalutazione = bene»: entrambe sono strumenti, e conta quando li usi.</p>`,
    reading: [
      "Gross, J. J. & John, O. P. (2003). Individual differences in two emotion regulation processes. <em>Journal of Personality and Social Psychology</em>, 85, 348-362.",
      "Gross, J. J. (2015). Emotion regulation: current status and future prospects. <em>Psychological Inquiry</em>, 26, 1-26.",
      "Webb, T. L., Miles, E. & Sheeran, P. (2012). Dealing with feeling: a meta-analysis of emotion regulation strategies. <em>Psychological Bulletin</em>, 138, 775-808."
    ]
  },
  en: {
    title: "Regulating emotion: two routes",
    intro: `<p>The ERQ grows out of <span class="t" data-tip="James Gross, a Stanford psychologist, founded the modern study of emotion regulation and created the Emotion Regulation Questionnaire in 2003.">James Gross's</span> <span class="t" data-tip="Gross's process model: an emotion unfolds over time, from situation to attention to appraisal to response. You can intervene at each point, at different costs.">process model</span>. An emotion isn't an instant flash: it builds in stages, and where you step in decides whether regulation costs little or a lot. The questionnaire isolates the two most-studied strategies: <span class="t" data-tip="Cognitive reappraisal: rethinking the meaning of a situation before the emotion is full-blown, to change what you feel. An upstream, antecedent strategy.">cognitive reappraisal</span>, which works early on meaning, and <span class="t" data-tip="Expressive suppression: holding back the outward show of an emotion that is already underway. A downstream strategy, on the response.">expressive suppression</span>, which works late, only on the display. Neither is good or bad in itself: their price changes with the moment.</p>`,
    blocks: [
      { h: "Five families of strategies", html: `<p>Gross lines regulation up along the life of an emotion: <b>selecting the situation</b> (avoiding or seeking a context), <b>modifying it</b> (changing what happens), <b>shifting attention</b> (distracting or focusing), <b>changing the appraisal</b> (reappraisal), and finally <b>modulating the response</b> (suppression). The first four act <em>before</em> the emotion flares; the last <em>after</em>. The ERQ measures one <span class="t" data-tip="Upstream: you step in early, before the emotion is full-blown (like reappraisal). Downstream: you step in late, when the emotion is already there (like suppression).">upstream and one downstream strategy</span>: this placement is what explains their very different costs.</p>` },
      { h: "Why reappraisal costs less", html: `<p>Rethinking a situation's meaning catches it <em>before</em> the emotion is at full strength: you change what you feel at the root. In the lab reappraisal is linked to more positive emotion, less physiological arousal and better memory of what happened; in life measures, to more well-being and stronger relationships. It's also the most <b>trainable</b> strategy: asking "how else could I read this?" is already the start.</p>` },
      { h: "The hidden bill of suppression", html: `<p>Holding back expression acts when the emotion is already there: it dims the face, not the fire. The inner experience doesn't drop — it often rises — and <span class="t" data-tip="Sympathetic nervous system activation: the physiological side of arousal (heart rate, sweat, tension). Suppression lets it rise or increases it, while reducing only what shows.">physiological arousal</span> climbs. There's a social and cognitive cost too: people who suppress during a conversation remember its details worse, and the other person feels them more distant and less in tune. It protects in the moment, but the bill arrives.</p>` },
      { h: "The skill is flexibility", html: `<p>No strategy is right always. Holding back anger in a meeting can be wise; doing it every evening with someone you love wears the bond down. For <b>uncontrollable, intense</b> stressors, distraction sometimes beats reappraisal. The real competence is <span class="t" data-tip="Regulatory flexibility: the capacity to pick the strategy that fits the context and switch it when it isn't working, rather than always using the same one. It predicts adjustment better than any single strategy.">regulatory flexibility</span>: choosing the right tool for the moment, and changing it when it fails.</p>` }
    ],
    beyond: `<ul>
      <li><b>Culture matters.</b> Suppression weighs less where it's the norm: in more interdependent cultural samples its link with lower well-being is weaker (Butler, Soto and colleagues). It isn't a universal law.</li>
      <li><b>Gender differences.</b> On average men report more suppression than women, a difference tied partly to norms about what it's acceptable to show.</li>
      <li><b>Reappraisal isn't magic.</b> Facing a high-intensity, uncontrollable stressor, turning attention away can work better than rethinking it (Sheppes): the best strategy depends on intensity.</li>
      <li><b>Regulating isn't repressing.</b> The goal isn't to stop feeling but to keep the emotion useful: sometimes that means letting it exist, not switching it off.</li>
    </ul>`,
    taratura: `<p>The ERQ measures <b>habitual, self-reported strategies</b>, not the actual ability to use them: it's a self-report. The two scales are reliable (good <span class="t" data-tip="Internal consistency: how much the items of one scale move together. A high value means they really measure the same thing.">internal consistency</span>, a little higher for reappraisal than for suppression, which has only four items). Reappraisal's advantage is well documented in the lab, but its links with well-being are <span class="t" data-tip="Correlational: shows that two things go together, not that one causes the other. People who feel better may reappraise more, not only the reverse.">correlational</span> and small-to-moderate, and depend on context. The reading to avoid is "suppression = bad, reappraisal = good": both are tools, and what matters is when you use them.</p>`,
    reading: [
      "Gross, J. J. & John, O. P. (2003). Individual differences in two emotion regulation processes. <em>Journal of Personality and Social Psychology</em>, 85, 348-362.",
      "Gross, J. J. (2015). Emotion regulation: current status and future prospects. <em>Psychological Inquiry</em>, 26, 1-26.",
      "Webb, T. L., Miles, E. & Sheeran, P. (2012). Dealing with feeling: a meta-analysis of emotion regulation strategies. <em>Psychological Bulletin</em>, 138, 775-808."
    ]
  },
  pt: {
    title: "Regular as emoções: dois caminhos",
    intro: `<p>O ERQ nasce do <span class="t" data-tip="Modelo de processo de James Gross: uma emoção se desenvolve no tempo, da situação à atenção à avaliação até a resposta. Em cada ponto se pode intervir, com custos diferentes.">modelo de processo</span> de <span class="t" data-tip="James Gross, psicólogo de Stanford: fundou a pesquisa moderna sobre regulação das emoções e criou o Emotion Regulation Questionnaire em 2003.">James Gross</span>. Uma emoção não é um relâmpago instantâneo: constrói-se em fases, e conforme onde você intervém a regulação custa pouco ou muito. O questionário isola as duas estratégias mais estudadas: a <span class="t" data-tip="Reavaliação cognitiva: repensar o significado de uma situação antes de a emoção estar plena, para mudar o que se sente. É uma estratégia a montante, antecedente.">reavaliação cognitiva</span>, que age cedo sobre o significado, e a <span class="t" data-tip="Supressão expressiva: conter a manifestação externa da emoção quando ela já está em curso. É uma estratégia a jusante, sobre a resposta.">supressão expressiva</span>, que age tarde, só sobre a expressão. Nenhuma é boa ou má em si: seu preço muda conforme o momento.</p>`,
    blocks: [
      { h: "Cinco famílias de estratégias", html: `<p>Gross alinha a regulação ao longo da vida da emoção: <b>escolher a situação</b> (evitar ou buscar um contexto), <b>modificá-la</b> (mudar o que acontece), <b>deslocar a atenção</b> (distrair-se ou concentrar-se), <b>mudar a avaliação</b> (a reavaliação) e por fim <b>modular a resposta</b> (a supressão). As primeiras quatro agem <em>antes</em> de a emoção irromper; a última <em>depois</em>. O ERQ mede uma <span class="t" data-tip="A montante: intervém-se cedo, antes de a emoção estar plena (como a reavaliação). A jusante: intervém-se tarde, quando a emoção já existe (como a supressão).">estratégia a montante e uma a jusante</span>: é essa posição que explica por que custam tão diferente.</p>` },
      { h: "Por que a reavaliação custa menos", html: `<p>Repensar o significado de uma situação a intercepta <em>antes</em> de a emoção estar a pleno vapor: você muda o que sente na raiz. No laboratório a reavaliação associa-se a mais emoções positivas, menor ativação fisiológica e melhor memória do que aconteceu; nas medidas de vida, a mais bem-estar e relações mais sólidas. É também a estratégia mais <b>treinável</b>: perguntar-se «de que outro modo posso ler isto?» já é o começo.</p>` },
      { h: "A conta escondida da supressão", html: `<p>Conter a expressão age quando a emoção já existe: apaga o rosto, não o fogo. A experiência interna não cai — muitas vezes aumenta — e sobe a <span class="t" data-tip="Ativação do sistema nervoso simpático: a parte fisiológica da ativação (batimento, suor, tensão). A supressão a deixa subir ou a aumenta, enquanto reduz só o que se vê.">ativação fisiológica</span>. Há também um custo social e cognitivo: quem suprime durante uma conversa lembra pior os detalhes, e o outro o percebe mais distante e menos em sintonia. Protege no imediato, mas a conta chega.</p>` },
      { h: "A habilidade é a flexibilidade", html: `<p>Nenhuma estratégia é certa sempre. Conter a raiva numa reunião pode ser sábio; fazê-lo toda noite com quem se ama desgasta o vínculo. Para estresses <b>incontroláveis e intensos</b>, às vezes a distração vence a reavaliação. A competência verdadeira é a <span class="t" data-tip="Flexibilidade regulatória: a capacidade de escolher a estratégia adequada ao contexto e trocá-la se não funcionar, em vez de usar sempre a mesma. Prevê adaptação melhor que qualquer estratégia isolada.">flexibilidade regulatória</span>: escolher a ferramenta certa para o momento, e mudá-la quando falha.</p>` }
    ],
    beyond: `<ul>
      <li><b>A cultura conta.</b> A supressão pesa menos onde é a norma: em amostras de cultura mais interdependente seu vínculo com menor bem-estar é mais fraco (Butler, Soto e colegas). Não é uma lei universal.</li>
      <li><b>Diferenças de gênero.</b> Em média os homens relatam mais supressão que as mulheres, diferença ligada em parte às normas sobre o que é aceitável mostrar.</li>
      <li><b>A reavaliação não é mágica.</b> Diante de um estresse de alta intensidade e não controlável, afastar a atenção pode funcionar melhor que repensá-lo (Sheppes): a melhor estratégia depende da intensidade.</li>
      <li><b>Regular não é reprimir.</b> O objetivo não é parar de sentir, mas manter a emoção útil: às vezes isso significa deixá-la existir, não apagá-la.</li>
    </ul>`,
    taratura: `<p>O ERQ mede as <b>estratégias habituais declaradas</b>, não a capacidade real de usá-las: é um autorrelato. As duas escalas são confiáveis (boa <span class="t" data-tip="Consistência interna: o quanto os itens de uma mesma escala se movem juntos. Um valor alto indica que medem de fato a mesma coisa.">consistência interna</span>, um pouco mais alta para a reavaliação que para a supressão, que tem só quatro itens). A vantagem da reavaliação é bem documentada no laboratório, mas os vínculos com o bem-estar são <span class="t" data-tip="Correlacional: mostra que duas coisas andam juntas, não que uma causa a outra. Quem está melhor pode reavaliar mais, não só o contrário.">correlacionais</span> e de tamanho pequeno a moderado, e dependem do contexto. A leitura a evitar é «supressão = mal, reavaliação = bem»: ambas são ferramentas, e o que importa é quando você as usa.</p>`,
    reading: [
      "Gross, J. J. & John, O. P. (2003). Individual differences in two emotion regulation processes. <em>Journal of Personality and Social Psychology</em>, 85, 348-362.",
      "Gross, J. J. (2015). Emotion regulation: current status and future prospects. <em>Psychological Inquiry</em>, 26, 1-26.",
      "Webb, T. L., Miles, E. & Sheeran, P. (2012). Dealing with feeling: a meta-analysis of emotion regulation strategies. <em>Psychological Bulletin</em>, 138, 775-808."
    ]
  }
};
