/* Emotion Regulation Questionnaire (Gross & John 2003) — libero per uso non commerciale. IT: Balzarotti, John & Gross (2010). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.erq = {
  code: "ERQ", theme: "rose", n: 10,
  labels: {
    en: ["Strongly disagree", "Disagree", "Somewhat disagree", "Neutral", "Somewhat agree", "Agree", "Strongly agree"],
    it: ["Fortemente in disaccordo", "In disaccordo", "Un po' in disaccordo", "Neutrale", "Un po' d'accordo", "D'accordo", "Fortemente d'accordo"]
  },
  items: {
    en: ["When I want to feel more positive emotion (such as joy or amusement), I change what I'm thinking about.", "I keep my emotions to myself.", "When I want to feel less negative emotion (such as sadness or anger), I change what I'm thinking about.", "When I am feeling positive emotions, I am careful not to express them.", "When I'm faced with a stressful situation, I make myself think about it in a way that helps me stay calm.", "I control my emotions by not expressing them.", "When I want to feel more positive emotion, I change the way I'm thinking about the situation.", "I control my emotions by changing the way I think about the situation I'm in.", "When I am feeling negative emotions, I make sure not to express them.", "When I want to feel less negative emotion, I change the way I'm thinking about the situation."],
    it: ["Quando voglio provare più emozioni positive (come gioia o divertimento), cambio quello a cui sto pensando.", "Tengo le mie emozioni per me.", "Quando voglio provare meno emozioni negative (come tristezza o rabbia), cambio quello a cui sto pensando.", "Quando provo emozioni positive, faccio attenzione a non esprimerle.", "Quando affronto una situazione stressante, mi sforzo di pensarci in un modo che mi aiuti a restare calmo.", "Controllo le mie emozioni non esprimendole.", "Quando voglio provare più emozioni positive, cambio il modo in cui penso alla situazione.", "Controllo le mie emozioni cambiando il modo in cui penso alla situazione in cui mi trovo.", "Quando provo emozioni negative, mi assicuro di non esprimerle.", "Quando voglio provare meno emozioni negative, cambio il modo in cui penso alla situazione."]
  },
  text: {
    it: { kicker: "Regolazione emotiva", title: "Come gestisci le emozioni?", lede: "10 affermazioni, 2 minuti. L'ERQ di Gross distingue due strategie: rivalutare la situazione (ripensarla) e sopprimere l'espressione (non farla vedere).", meta: ["10 domande", "~2 minuti", "2 strategie"], instr: "Le frasi riguardano la tua <b>vita emotiva</b>: come controlli e regoli le emozioni. Alcune parlano dell'esperienza interna, altre dell'espressione verso gli altri. Per ognuna indica quanto sei d'accordo.", how: "Due punteggi da 1 a 7, ciascuno la media delle sue domande. Rivalutazione cognitiva (6 domande): media adulti circa 4,6. Soppressione espressiva (4 domande): media circa 3,6 per gli uomini e 3,1 per le donne. La rivalutazione è associata a più emozioni positive e relazioni migliori; la soppressione a più tensione interna e minore vicinanza. Non sono buone o cattive in assoluto: dipende dal contesto.", cite: "Gross, J. J., & John, O. P. (2003). Individual differences in two emotion regulation processes. Journal of Personality and Social Psychology, 85, 348-362. Versione italiana: Balzarotti, John & Gross (2010). Uso libero non commerciale." },
    en: { kicker: "Emotion regulation", title: "How do you handle your emotions?", lede: "10 statements, 2 minutes. Gross's ERQ separates two strategies: reappraising the situation (rethinking it) and suppressing expression (not letting it show).", meta: ["10 questions", "~2 minutes", "2 strategies"], instr: "The statements concern your <b>emotional life</b>: how you control and regulate your emotions. Some are about your inner experience, others about expression towards others. Indicate how much you agree with each.", how: "Two scores from 1 to 7, each the mean of its questions. Cognitive reappraisal (6 questions): adult mean about 4.6. Expressive suppression (4 questions): mean about 3.6 for men and 3.1 for women. Reappraisal is linked to more positive emotion and better relationships; suppression to more inner tension and less closeness. Neither is good or bad in itself: it depends on context.", cite: "Gross, J. J., & John, O. P. (2003). Individual differences in two emotion regulation processes. Journal of Personality and Social Psychology, 85, 348-362. Free for non-commercial use." }
  },
  scales: [
    { key: "reap", name: { it: "Rivalutazione cognitiva", en: "Cognitive reappraisal" }, items: [1,3,5,7,8,10], mode: "mean", range: [1, 7],
      bands: [
        { max: 3.9, name: { it: "Bassa", en: "Low" }, text: { it: "Ripensi raramente le situazioni per cambiare quello che provi: le emozioni ti arrivano così come sono. È la strategia più allenabile: chiedersi «come altro potrei vedere questa cosa?» è già un inizio.", en: "You rarely rethink situations to change what you feel: emotions arrive as they are. It is the most trainable strategy: asking “how else could I see this?” is already a start." } },
        { max: 5.3, name: { it: "Nella media", en: "Average" }, text: { it: "Usi la rivalutazione come la maggior parte delle persone: a volte riesci a vedere le cose da un'altra angolazione, a volte no.", en: "You use reappraisal like most people: sometimes you manage to see things from another angle, sometimes not." } },
        { max: 7, name: { it: "Alta", en: "High" }, text: { it: "Ripensare le situazioni ti viene naturale: è la strategia più associata a benessere e buone relazioni.", en: "Rethinking situations comes naturally to you: it is the strategy most linked to well-being and good relationships." } }
      ] },
    { key: "supp", name: { it: "Soppressione espressiva", en: "Expressive suppression" }, items: [2,4,6,9], mode: "mean", range: [1, 7],
      bands: [
        { max: 2.6, name: { it: "Bassa", en: "Low" }, text: { it: "Quello che provi si vede: esprimi le emozioni con facilità. Gli altri ti leggono, e questo favorisce la vicinanza.", en: "What you feel shows: you express emotions easily. Others can read you, which fosters closeness." } },
        { max: 4.3, name: { it: "Nella media", en: "Average" }, text: { it: "A volte trattieni, a volte lasci vedere: una dose di soppressione nella norma.", en: "Sometimes you hold back, sometimes you let it show: a normal dose of suppression." } },
        { max: 7, name: { it: "Alta", en: "High" }, text: { it: "Tendi a non far vedere quello che provi, positive comprese. Protegge nell'immediato ma costa: più tensione interna e gli altri che ti sentono distante.", en: "You tend not to show what you feel, positive emotions included. It protects in the moment but has a cost: more inner tension and others feeling you are distant." } }
      ] }
  ]
};
