/* Five Facet Mindfulness Questionnaire – 15 item (Baer et al. 2006; forma breve Baer et al. 2012 / Gu et al. 2016) — libero per uso non commerciale. IT: traduzione propria (versione italiana del FFMQ-39: Giovannini et al. 2014). Ordine: osservare, descrivere, agire con consapevolezza, non giudicare, non reagire, ripetuto ×3. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.ffmq15 = {
  code: "FFMQ-15", theme: "teal", n: 15, reverse: [3, 4, 7, 8, 9, 13, 14],
  labels: {
    en: ["Never or very rarely true", "Rarely true", "Sometimes true", "Often true", "Very often or always true"],
    it: ["Mai o molto raramente vero", "Raramente vero", "A volte vero", "Spesso vero", "Molto spesso o sempre vero"]
  },
  items: {
    en: ["When I take a shower or bath, I stay alert to the sensations of water on my body.", "I'm good at finding words to describe my feelings.", "I don't pay attention to what I'm doing because I'm daydreaming, worrying, or otherwise distracted.", "I tell myself I shouldn't be feeling the way I'm feeling.", "When I have distressing thoughts or images, I “step back” and am aware of the thought or image without getting taken over by it.", "I notice how foods and drinks affect my thoughts, bodily sensations, and emotions.", "I have trouble thinking of the right words to express how I feel about things.", "I do jobs or tasks automatically, without being aware of what I'm doing.", "I believe some of my thoughts are abnormal or bad and I shouldn't think that way.", "When I have distressing thoughts or images I am able just to notice them without reacting.", "I pay attention to sensations, such as the wind in my hair or sun on my face.", "Even when I'm feeling terribly upset, I can find a way to put it into words.", "I find myself doing things without paying attention.", "I think some of my emotions are bad or inappropriate and I shouldn't feel them.", "When I have distressing thoughts or images, I just notice them and let them go."],
    it: ["Quando faccio la doccia o il bagno, resto attento alle sensazioni dell'acqua sul mio corpo.", "Sono bravo a trovare le parole per descrivere i miei sentimenti.", "Non presto attenzione a quello che faccio perché sto sognando a occhi aperti, mi preoccupo o sono distratto in altro modo.", "Mi dico che non dovrei sentirmi come mi sento.", "Quando ho pensieri o immagini che mi turbano, «faccio un passo indietro» e ne sono consapevole senza farmi travolgere.", "Noto come cibi e bevande influenzano i miei pensieri, le mie sensazioni corporee e le mie emozioni.", "Faccio fatica a trovare le parole giuste per esprimere quello che provo riguardo alle cose.", "Svolgo lavori o compiti in automatico, senza essere consapevole di quello che faccio.", "Credo che alcuni miei pensieri siano anormali o cattivi e che non dovrei pensare in quel modo.", "Quando ho pensieri o immagini che mi turbano, riesco semplicemente a notarli senza reagire.", "Presto attenzione alle sensazioni, come il vento tra i capelli o il sole sul viso.", "Anche quando sono terribilmente turbato, riesco a trovare un modo per esprimerlo a parole.", "Mi ritrovo a fare le cose senza prestare attenzione.", "Penso che alcune mie emozioni siano cattive o inappropriate e che non dovrei provarle.", "Quando ho pensieri o immagini che mi turbano, li noto e basta, e li lascio andare."]
  },
  text: {
    it: { kicker: "Mindfulness in 5 sfaccettature", title: "Le cinque sfaccettature", lede: "15 affermazioni, 2 minuti. Il FFMQ misura la mindfulness come cinque abilità distinte: osservare, descrivere, agire con consapevolezza, non giudicare, non reagire.", meta: ["15 domande", "~2 minuti", "5 sfaccettature"], instr: "Per ogni frase indica <b>quanto è generalmente vera per te</b>, da 1 (mai o molto raramente) a 5 (molto spesso o sempre).", how: "Cinque punteggi, ognuno la media di 3 domande da 1 a 5 (7 domande sono invertite); più alto = più mindful. Non esistono soglie ufficiali: le fasce qui sono orientative (sotto 2,5 bassa, 2,5–3,5 media, sopra 3,5 alta). Tra gli studenti la media complessiva è intorno a 3,2. Le sfaccettature crescono in modo diverso con la pratica: «osservare» è quella più influenzata dalla meditazione.", cite: "Baer, R. A., Smith, G. T., Hopkins, J., Krietemeyer, J., & Toney, L. (2006). Using self-report assessment methods to explore facets of mindfulness. Assessment, 13, 27-45. Forma a 15 item: Baer et al. (2012); Gu et al. (2016), Psychological Assessment. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Mindfulness in 5 facets", title: "The five facets", lede: "15 statements, 2 minutes. The FFMQ measures mindfulness as five distinct skills: observing, describing, acting with awareness, nonjudging, nonreactivity.", meta: ["15 questions", "~2 minutes", "5 facets"], instr: "For each statement, indicate <b>how generally true it is of you</b>, from 1 (never or very rarely) to 5 (very often or always).", how: "Five scores, each the mean of 3 questions from 1 to 5 (7 questions are reverse-keyed); higher = more mindful. There are no official thresholds: the bands here are orientative (below 2.5 low, 2.5–3.5 average, above 3.5 high). Among students the overall mean is around 3.2. The facets grow differently with practice: “observing” is the one most affected by meditation.", cite: "Baer, R. A., Smith, G. T., Hopkins, J., Krietemeyer, J., & Toney, L. (2006). Using self-report assessment methods to explore facets of mindfulness. Assessment, 13, 27-45. 15-item form: Baer et al. (2012); Gu et al. (2016), Psychological Assessment. Free for non-commercial use." }
  },
  scales: (function () {
    const B = (lo, mid, hi) => [{ max: 2.49, name: { it: "Bassa", en: "Low" }, text: lo }, { max: 3.5, name: { it: "Media", en: "Average" }, text: mid }, { max: 5, name: { it: "Alta", en: "High" }, text: hi }];
    return [
      { key: "obs", name: { it: "Osservare", en: "Observing" }, items: [1, 6, 11], mode: "mean", range: [1, 5], bands: B({ it: "Le sensazioni del corpo e dell'ambiente ti passano accanto senza che le noti.", en: "Bodily and environmental sensations pass by without you noticing them." }, { it: "Noti quello che senti quanto la maggior parte delle persone.", en: "You notice what you sense as much as most people." }, { it: "Sei molto attento a sensazioni, suoni e dettagli: la sfaccettatura che la meditazione allena di più.", en: "You are very attentive to sensations, sounds and details: the facet meditation trains most." }) },
      { key: "desc", name: { it: "Descrivere", en: "Describing" }, items: [2, 7, 12], mode: "mean", range: [1, 5], bands: B({ it: "Trovare le parole per quello che provi ti costa: un'abilità che si allena scrivendo o parlandone.", en: "Finding words for what you feel is hard for you: a skill trained by writing or talking about it." }, { it: "Dai un nome a quello che provi quanto la maggior parte delle persone.", en: "You name what you feel as much as most people." }, { it: "Metti in parole le emozioni con facilità, anche quelle difficili.", en: "You put emotions into words easily, even difficult ones." }) },
      { key: "aware", name: { it: "Agire con consapevolezza", en: "Acting with awareness" }, items: [3, 8, 13], mode: "mean", range: [1, 5], bands: B({ it: "Molto pilota automatico: fai le cose mentre la mente è altrove.", en: "A lot of autopilot: you do things while your mind is elsewhere." }, { it: "Presente quando conta, in automatico nella routine.", en: "Present when it counts, on autopilot in routine." }, { it: "Sei nel presente mentre agisci, più della maggior parte delle persone.", en: "You are present while you act, more than most people." }) },
      { key: "nonj", name: { it: "Non giudicare", en: "Nonjudging" }, items: [4, 9, 14], mode: "mean", range: [1, 5], bands: B({ it: "Giudichi quello che provi: certi pensieri ed emozioni ti sembrano sbagliati. È la sfaccettatura più legata al benessere.", en: "You judge what you feel: some thoughts and emotions seem wrong to you. This is the facet most linked to well-being." }, { it: "A volte ti critichi per quello che provi, a volte lo lasci essere.", en: "Sometimes you criticise yourself for what you feel, sometimes you let it be." }, { it: "Lasci che pensieri ed emozioni ci siano senza etichettarli come sbagliati.", en: "You let thoughts and emotions be there without labelling them wrong." }) },
      { key: "nonr", name: { it: "Non reagire", en: "Nonreactivity" }, items: [5, 10, 15], mode: "mean", range: [1, 5], bands: B({ it: "I pensieri che turbano ti trascinano: la distanza da essi si costruisce con la pratica.", en: "Distressing thoughts carry you away: distance from them is built with practice." }, { it: "A volte riesci a osservare un pensiero difficile senza reagire, a volte ti prende.", en: "Sometimes you can observe a hard thought without reacting, sometimes it takes you." }, { it: "Osservi i pensieri difficili e li lasci andare: la sfaccettatura più protettiva contro il rimuginio.", en: "You observe difficult thoughts and let them go: the facet most protective against rumination." }) }
    ];
  })()
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.ffmq15.approf = {
  it: {
    title: "Le cinque sfaccettature, in profondità",
    intro: `<p>Verso la metà degli anni Duemila esistevano già diversi questionari sulla mindfulness, ognuno con la sua idea di cosa fosse. <span class="t" data-tip="Ruth Baer, psicologa clinica dell'Università del Kentucky, studia la misurazione della mindfulness e le terapie che la usano.">Ruth Baer</span> e colleghi (2006) fecero una cosa semplice e ingegnosa: presero cinque di quelle scale, le somministrarono insieme e le passarono a un'<span class="t" data-tip="Tecnica statistica che raggruppa molte domande in poche dimensioni di fondo, guardando quali variano insieme. Da cinque questionari fece emergere cinque fattori.">analisi fattoriale</span>. Ne uscirono cinque dimensioni ricorrenti — <b>osservare, descrivere, agire con consapevolezza, non giudicare, non reagire</b> — che diventarono il <span class="t" data-tip="Five Facet Mindfulness Questionnaire: 39 item nella versione originale, 15 nella forma breve validata da Gu e colleghi nel 2016.">FFMQ</span>. È la fotografia più usata della mindfulness come insieme di abilità distinte, non come blocco unico.</p>`,
    blocks: [
      { h: "Che cosa misura ogni sfaccettatura", html: `<p>Le cinque non misurano la stessa cosa. <b>Osservare</b> è accorgersi di sensazioni, suoni, odori, emozioni; <b>descrivere</b> è saperli mettere in parole; <b>agire con consapevolezza</b> è l'opposto del <span class="t" data-tip="Fare le cose mentre la mente è altrove: mangiare, guidare, ascoltare senza esserci. Lo misura anche la MAAS.">pilota automatico</span>; <b>non giudicare</b> è non bollare come sbagliati i propri pensieri ed emozioni; <b>non reagire</b> è lasciar passare un pensiero difficile senza esserne trascinati. Le ultime due sono <span class="t" data-tip="Descrivono l'atteggiamento con cui stai nell'esperienza, non quanto la noti. La MAAS, per esempio, copre l'attenzione ma non queste.">di atteggiamento</span> e sono quelle più legate al benessere; le prime tre riguardano piuttosto il contatto con l'esperienza.</p>` },
      { h: "L'enigma dell'Osservare", html: `<p>La sfaccettatura più discussa è <b>osservare</b>. Ci si aspetterebbe che notare di più l'esperienza faccia bene sempre; invece, in chi <span class="t" data-tip="Persone senza pratica di meditazione. Nei loro dati la sfaccettatura osservare correla poco o male con il resto e a volte va con più sintomi, non meno.">non medita</span>, un punteggio alto in osservare può accompagnarsi a più ansia e sintomi, non a meno. La spiegazione più accreditata: notare senza avere anche non giudizio e non reattività significa <em>monitorare</em> l'esperienza con allarme — accorgersi di ogni battito, ogni sensazione, e spaventarsene. Nei <span class="t" data-tip="Chi ha una pratica regolare di meditazione. In loro osservare si integra con le altre sfaccettature e diventa adattivo.">meditatori</span>, invece, osservare si aggancia alle sfaccettature di atteggiamento e diventa una risorsa. Per questo alcuni ricercatori la escludono dal punteggio totale nei campioni non clinici.</p>` },
      { h: "Un totale o cinque numeri?", html: `<p>Da qui una domanda aperta: ha senso sommare le cinque in un punteggio unico? Se osservare cambia segno a seconda di chi risponde, il totale mescola cose che non vanno nella stessa direzione. Molti studi preferiscono guardare le sfaccettature separatamente, o usare un totale a quattro escludendo osservare. La <span class="t" data-tip="Quanto le cinque sfaccettature vanno d'accordo tra loro. Non giudicare e non reagire correlano bene; osservare è la più isolata.">struttura interna</span> del FFMQ è uno dei temi più studiati e discussi della misurazione della mindfulness.</p>` },
      { h: "Cosa muove la pratica", html: `<p>La pratica non sposta tutto insieme. La <span class="t" data-tip="La meditazione seduta strutturata, come nell'MBSR, distinta dalle pratiche informali sparse nella giornata.">meditazione formale</span> tende ad alzare per prime osservare e non reagire; agire con consapevolezza e non giudicare crescono più lentamente e sono quelli che meglio predicono il calo di ansia e depressione. Sapere <em>quale</em> sfaccettatura è bassa è più utile del punteggio complessivo: indica dove la pratica ha margine.</p>` }
    ],
    beyond: `<ul>
      <li><b>Perché la forma breve.</b> I 15 item (tre per sfaccettatura) di Gu e colleghi nascono per contesti dove i 39 originali erano troppo lunghi; reggono bene, ma con meno precisione per singola sfaccettatura.</li>
      <li><b>Descrivere e alessitimia.</b> La sfaccettatura descrivere è quasi l'inverso dell'alessitimia, la difficoltà a riconoscere e nominare le emozioni: chi la ha bassa fatica a dire cosa prova.</li>
      <li><b>Il rischio della desiderabilità.</b> «Non giudico i miei pensieri» è una frase che suona virtuosa: come ogni self-report, il FFMQ risente di quanto vuoi apparire consapevole.</li>
      <li><b>Non serve meditare per averlo alto.</b> Alcune persone sono naturalmente non giudicanti e presenti senza aver mai meditato: la mindfulness disposizionale esiste a prescindere dalla pratica.</li>
    </ul>`,
    taratura: `<p>Il FFMQ è lo strumento multidimensionale di riferimento e ha una buona base psicometrica, ma con un punto debole noto: la sfaccettatura osservare si comporta in modo instabile fuori dai meditatori, tanto che la sua correlazione con il resto e con il benessere cambia di segno tra campioni. Nella forma breve, tre item per dimensione sono pochi per una misura fine: leggi le cinque come indicazioni di tendenza, non come punteggi di precisione. Non esistono soglie cliniche ufficiali, e le fasce che vedi qui sono orientative.</p>`,
    reading: [
      "Baer, R. A. et al. (2006). Using self-report assessment methods to explore facets of mindfulness. <em>Assessment</em>, 13, 27-45.",
      "Gu, J. et al. (2016). Examining the factor structure of the FFMQ short form. <em>Psychological Assessment</em>, 28, 791-802.",
      "Baer, R. A. (2003). Mindfulness training as a clinical intervention. <em>Clinical Psychology: Science and Practice</em>, 10, 125-143."
    ]
  },
  en: {
    title: "The five facets, in depth",
    intro: `<p>By the mid-2000s several mindfulness questionnaires already existed, each with its own idea of what mindfulness was. <span class="t" data-tip="Ruth Baer, clinical psychologist at the University of Kentucky, studies the measurement of mindfulness and the therapies that use it.">Ruth Baer</span> and colleagues (2006) did something simple and clever: they took five of those scales, gave them together and ran a <span class="t" data-tip="A statistical technique that groups many questions into a few underlying dimensions by seeing which ones vary together. From five questionnaires it produced five factors.">factor analysis</span>. Five recurring dimensions came out — <b>observing, describing, acting with awareness, nonjudging, nonreactivity</b> — which became the <span class="t" data-tip="Five Facet Mindfulness Questionnaire: 39 items in the original, 15 in the short form validated by Gu and colleagues in 2016.">FFMQ</span>. It is the most used picture of mindfulness as a set of distinct skills rather than a single block.</p>`,
    blocks: [
      { h: "What each facet measures", html: `<p>The five do not measure the same thing. <b>Observing</b> is noticing sensations, sounds, smells, emotions; <b>describing</b> is being able to put them into words; <b>acting with awareness</b> is the opposite of <span class="t" data-tip="Doing things while the mind is elsewhere: eating, driving, listening without being there. The MAAS measures this too.">autopilot</span>; <b>nonjudging</b> is not branding your own thoughts and emotions as wrong; <b>nonreactivity</b> is letting a difficult thought pass without being swept away by it. The last two are <span class="t" data-tip="They describe the attitude you take toward experience, not how much you notice it. The MAAS, for example, covers attention but not these.">attitudinal</span> and are the ones most linked to well-being; the first three concern contact with experience.</p>` },
      { h: "The riddle of Observing", html: `<p>The most debated facet is <b>observing</b>. You would expect that noticing experience more is always good; yet in <span class="t" data-tip="People without meditation practice. In their data the observing facet correlates weakly or oddly with the rest and sometimes goes with more symptoms, not fewer.">non-meditators</span> a high observing score can go with more anxiety and symptoms, not less. The leading explanation: noticing without also having nonjudging and nonreactivity means <em>monitoring</em> experience with alarm — registering every heartbeat, every sensation, and being frightened by it. In <span class="t" data-tip="People with a regular meditation practice. In them observing integrates with the other facets and becomes adaptive.">meditators</span>, instead, observing hooks onto the attitudinal facets and becomes a resource. This is why some researchers drop it from the total score in non-clinical samples.</p>` },
      { h: "One total or five numbers?", html: `<p>Hence an open question: does it make sense to sum the five into one score? If observing flips sign depending on who answers, the total mixes things that do not point the same way. Many studies prefer to look at the facets separately, or use a four-facet total excluding observing. The <span class="t" data-tip="How well the five facets agree with one another. Nonjudging and nonreactivity correlate well; observing is the most isolated.">internal structure</span> of the FFMQ is one of the most studied and debated topics in mindfulness measurement.</p>` },
      { h: "What practice moves", html: `<p>Practice does not shift everything at once. <span class="t" data-tip="Structured sitting meditation, as in MBSR, distinct from informal practices scattered through the day.">Formal meditation</span> tends to raise observing and nonreactivity first; acting with awareness and nonjudging grow more slowly and are the ones that best predict drops in anxiety and depression. Knowing <em>which</em> facet is low is more useful than the overall score: it shows where practice has room.</p>` }
    ],
    beyond: `<ul>
      <li><b>Why the short form.</b> Gu and colleagues' 15 items (three per facet) were built for settings where the original 39 were too long; they hold up well, but with less precision per facet.</li>
      <li><b>Describing and alexithymia.</b> The describing facet is almost the inverse of alexithymia, the difficulty in recognising and naming emotions: those low on it struggle to say what they feel.</li>
      <li><b>The desirability risk.</b> "I do not judge my thoughts" is a virtuous-sounding statement: like any self-report, the FFMQ is affected by how mindful you want to appear.</li>
      <li><b>You need not meditate to score high.</b> Some people are naturally nonjudging and present without ever having meditated: dispositional mindfulness exists regardless of practice.</li>
    </ul>`,
    taratura: `<p>The FFMQ is the reference multidimensional instrument and has a good psychometric base, but with a known weak spot: the observing facet behaves unstably outside meditators, so much so that its correlation with the rest and with well-being changes sign across samples. In the short form, three items per dimension are few for a fine measure: read the five as tendencies, not precision scores. There are no official clinical thresholds, and the bands here are orientative.</p>`,
    reading: [
      "Baer, R. A. et al. (2006). Using self-report assessment methods to explore facets of mindfulness. <em>Assessment</em>, 13, 27-45.",
      "Gu, J. et al. (2016). Examining the factor structure of the FFMQ short form. <em>Psychological Assessment</em>, 28, 791-802.",
      "Baer, R. A. (2003). Mindfulness training as a clinical intervention. <em>Clinical Psychology: Science and Practice</em>, 10, 125-143."
    ]
  },
  pt: {
    title: "As cinco facetas, em profundidade",
    intro: `<p>Por volta da metade dos anos 2000 já existiam vários questionários de atenção plena, cada um com sua ideia do que ela era. <span class="t" data-tip="Ruth Baer, psicóloga clínica da Universidade do Kentucky, estuda a medição da atenção plena e as terapias que a utilizam.">Ruth Baer</span> e colegas (2006) fizeram algo simples e engenhoso: pegaram cinco dessas escalas, aplicaram juntas e as submeteram a uma <span class="t" data-tip="Técnica estatística que agrupa muitas perguntas em poucas dimensões de fundo, observando quais variam juntas. De cinco questionários fez emergir cinco fatores.">análise fatorial</span>. Surgiram cinco dimensões recorrentes — <b>observar, descrever, agir com consciência, não julgar, não reagir</b> — que se tornaram o <span class="t" data-tip="Five Facet Mindfulness Questionnaire: 39 itens na versão original, 15 na forma breve validada por Gu e colegas em 2016.">FFMQ</span>. É a fotografia mais usada da atenção plena como um conjunto de habilidades distintas, não como um bloco único.</p>`,
    blocks: [
      { h: "O que cada faceta mede", html: `<p>As cinco não medem a mesma coisa. <b>Observar</b> é perceber sensações, sons, cheiros, emoções; <b>descrever</b> é saber colocá-los em palavras; <b>agir com consciência</b> é o oposto do <span class="t" data-tip="Fazer as coisas com a mente em outro lugar: comer, dirigir, ouvir sem estar presente. A MAAS também mede isso.">piloto automático</span>; <b>não julgar</b> é não rotular como errados os próprios pensamentos e emoções; <b>não reagir</b> é deixar passar um pensamento difícil sem ser arrastado por ele. As duas últimas são <span class="t" data-tip="Descrevem a atitude com que você está na experiência, não o quanto a percebe. A MAAS, por exemplo, cobre a atenção mas não estas.">de atitude</span> e são as mais ligadas ao bem-estar; as três primeiras dizem respeito ao contato com a experiência.</p>` },
      { h: "O enigma do Observar", html: `<p>A faceta mais discutida é <b>observar</b>. Seria de esperar que perceber mais a experiência fizesse sempre bem; no entanto, em quem <span class="t" data-tip="Pessoas sem prática de meditação. Nos seus dados a faceta observar correlaciona pouco ou mal com o resto e às vezes acompanha mais sintomas, não menos.">não medita</span>, um escore alto em observar pode vir acompanhado de mais ansiedade e sintomas, não de menos. A explicação mais aceita: perceber sem ter também não julgamento e não reatividade significa <em>monitorar</em> a experiência com alarme — notar cada batida, cada sensação, e se assustar com isso. Nos <span class="t" data-tip="Quem tem prática regular de meditação. Neles observar se integra às outras facetas e se torna adaptativo.">meditadores</span>, ao contrário, observar se engata nas facetas de atitude e vira um recurso. Por isso alguns pesquisadores a excluem do escore total em amostras não clínicas.</p>` },
      { h: "Um total ou cinco números?", html: `<p>Daí uma pergunta em aberto: faz sentido somar as cinco num escore único? Se observar muda de sinal conforme quem responde, o total mistura coisas que não apontam na mesma direção. Muitos estudos preferem olhar as facetas separadamente, ou usar um total de quatro excluindo observar. A <span class="t" data-tip="O quanto as cinco facetas concordam entre si. Não julgar e não reagir correlacionam bem; observar é a mais isolada.">estrutura interna</span> do FFMQ é um dos temas mais estudados e discutidos da medição da atenção plena.</p>` },
      { h: "O que a prática move", html: `<p>A prática não desloca tudo de uma vez. A <span class="t" data-tip="A meditação sentada estruturada, como no MBSR, distinta das práticas informais espalhadas pelo dia.">meditação formal</span> tende a elevar primeiro observar e não reagir; agir com consciência e não julgar crescem mais devagar e são os que melhor predizem a queda de ansiedade e depressão. Saber <em>qual</em> faceta está baixa é mais útil do que o escore geral: indica onde a prática tem margem.</p>` }
    ],
    beyond: `<ul>
      <li><b>Por que a forma breve.</b> Os 15 itens (três por faceta) de Gu e colegas nascem para contextos em que os 39 originais eram longos demais; funcionam bem, mas com menos precisão por faceta.</li>
      <li><b>Descrever e alexitimia.</b> A faceta descrever é quase o inverso da alexitimia, a dificuldade de reconhecer e nomear emoções: quem a tem baixa custa a dizer o que sente.</li>
      <li><b>O risco da desejabilidade.</b> «Não julgo meus pensamentos» é uma frase que soa virtuosa: como todo autorrelato, o FFMQ sofre com o quanto você quer parecer consciente.</li>
      <li><b>Não é preciso meditar para tê-lo alto.</b> Algumas pessoas são naturalmente não julgadoras e presentes sem nunca ter meditado: a atenção plena disposicional existe independentemente da prática.</li>
    </ul>`,
    taratura: `<p>O FFMQ é o instrumento multidimensional de referência e tem uma boa base psicométrica, mas com um ponto fraco conhecido: a faceta observar se comporta de modo instável fora dos meditadores, a ponto de sua correlação com o resto e com o bem-estar mudar de sinal entre amostras. Na forma breve, três itens por dimensão são poucos para uma medida fina: leia as cinco como tendências, não como escores de precisão. Não existem limiares clínicos oficiais, e as faixas aqui são orientativas.</p>`,
    reading: [
      "Baer, R. A. et al. (2006). Using self-report assessment methods to explore facets of mindfulness. <em>Assessment</em>, 13, 27-45.",
      "Gu, J. et al. (2016). Examining the factor structure of the FFMQ short form. <em>Psychological Assessment</em>, 28, 791-802.",
      "Baer, R. A. (2003). Mindfulness training as a clinical intervention. <em>Clinical Psychology: Science and Practice</em>, 10, 125-143."
    ]
  }
};
