/* Five Facet Mindfulness Questionnaire – 15 item (Baer et al. 2006; forma breve Baer et al. 2012 / Gu et al. 2016) — libero per uso non commerciale. IT: traduzione propria (versione italiana del FFMQ-39: Giovannini et al. 2014). Ordine: osservare, descrivere, agire con consapevolezza, non giudicare, non reagire, ripetuto ×3. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.ffmq15 = {
  code: "FFMQ-15", theme: "teal", n: 15, reverse: [3, 4, 7, 8, 9, 13, 14],
  labels: {
    en: ["Never or very rarely true", "Rarely true", "Sometimes true", "Often true", "Very often or always true"],
    it: ["Mai o molto raramente vero", "Raramente vero", "A volte vero", "Spesso vero", "Molto spesso o sempre vero"]
  },
  items: {
    en: ["When I take a shower or bath, I stay alert to the sensations of water on my body.", "I'm good at finding words to describe my feelings.", "I don't pay attention to what I'm doing because I'm daydreaming, worrying, or otherwise distracted.", "I tell myself I shouldn't be feeling the way I'm feeling.", "When I have distressing thoughts or images, I “step back” and am aware of the thought or image without getting taken over by it.", "I notice how foods and drinks affect my thoughts, bodily sensations, and emotions.", "I have trouble thinking of the right words to express how I feel about things.", "I do jobs or tasks automatically, without being aware of what I'm doing.", "I believe some of my thoughts are abnormal or bad and I shouldn't think that way.", "When I have distressing thoughts or images I am able just to notice them without reacting.", "I pay attention to sensations, such as the wind in my hair or sun on my face.", "Even when I'm feeling terribly upset, I can find a way to put it into words.", "I find myself doing things without paying attention.", "I think some of my emotions are bad or inappropriate and I shouldn't feel them.", "When I have distressing thoughts or images, I just notice them and let them go."],
    it: ["Quando faccio la doccia o il bagno, resto attento alle sensazioni dell'acqua sul mio corpo.", "Sono bravo a trovare le parole per descrivere i miei sentimenti.", "Non presto attenzione a quello che faccio perché sto sognando a occhi aperti, mi preoccupo o sono distratto in altro modo.", "Mi dico che non dovrei sentirmi come mi sento.", "Quando ho pensieri o immagini che mi turbano, «faccio un passo indietro» e ne sono consapevole senza farmi travolgere.", "Noto come cibi e bevande influenzano i miei pensieri, le mie sensazioni corporee e le mie emozioni.", "Faccio fatica a trovare le parole giuste per esprimere quello che provo riguardo alle cose.", "Svolgo lavori o compiti in automatico, senza essere consapevole di quello che faccio.", "Credo che alcuni miei pensieri siano anormali o cattivi e che non dovrei pensare in quel modo.", "Quando ho pensieri o immagini che mi turbano, riesco semplicemente a notarli senza reagire.", "Presto attenzione alle sensazioni, come il vento tra i capelli o il sole sul viso.", "Anche quando sono terribilmente turbato, riesco a trovare un modo per esprimerlo a parole.", "Mi ritrovo a fare le cose senza prestare attenzione.", "Penso che alcune mie emozioni siano cattive o inappropriate e che non dovrei provarle.", "Quando ho pensieri o immagini che mi turbano, li noto e basta, e li lascio andare."]
  },
  text: {
    it: { kicker: "Mindfulness in 5 sfaccettature", title: "Le cinque sfaccettature", lede: "15 affermazioni, 2 minuti. Il FFMQ misura la mindfulness come cinque abilità distinte: osservare, descrivere, agire con consapevolezza, non giudicare, non reagire.", meta: ["15 domande", "~2 minuti", "5 sfaccettature"], instr: "Per ogni frase indica <b>quanto è generalmente vera per te</b>, da 1 (mai o molto raramente) a 5 (molto spesso o sempre).", how: "Cinque punteggi, ognuno la media di 3 domande da 1 a 5 (7 domande sono invertite); più alto = più mindful. Non esistono soglie ufficiali: le fasce qui sono orientative (sotto 2,5 bassa, 2,5–3,5 media, sopra 3,5 alta). Tra gli studenti la media complessiva è intorno a 3,2. Le sfaccettature crescono in modo diverso con la pratica: «osservare» è quella più influenzata dalla meditazione.", cite: "Baer, R. A., Smith, G. T., Hopkins, J., Krietemeyer, J., & Toney, L. (2006). Using self-report assessment methods to explore facets of mindfulness. Assessment, 13, 27-45. Forma a 15 item: Baer et al. (2012); Gu et al. (2016), Psychological Assessment. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Mindfulness in 5 facets", title: "The five facets", lede: "15 statements, 2 minutes. The FFMQ measures mindfulness as five distinct skills: observing, describing, acting with awareness, nonjudging, nonreactivity.", meta: ["15 questions", "~2 minutes", "5 facets"], instr: "For each statement, indicate <b>how generally true it is of you</b>, from 1 (never or very rarely) to 5 (very often or always).", how: "Five scores, each the mean of 3 questions from 1 to 5 (7 questions are reverse-keyed); higher = more mindful. There are no official thresholds: the bands here are orientative (below 2.5 low, 2.5–3.5 average, above 3.5 high). Among students the overall mean is around 3.2. The facets grow differently with practice: “observing” is the one most affected by meditation.", cite: "Baer, R. A., Smith, G. T., Hopkins, J., Krietemeyer, J., & Toney, L. (2006). Using self-report assessment methods to explore facets of mindfulness. Assessment, 13, 27-45. 15-item form: Baer et al. (2012); Gu et al. (2016), Psychological Assessment. Free for non-commercial use." }
  },
  scales: (function () {
    const B = (lo, mid, hi) => [{ max: 2.49, name: { it: "Bassa", en: "Low" }, text: lo }, { max: 3.5, name: { it: "Media", en: "Average" }, text: mid }, { max: 5, name: { it: "Alta", en: "High" }, text: hi }];
    return [
      { key: "obs", name: { it: "Osservare", en: "Observing" }, items: [1, 6, 11], mode: "mean", range: [1, 5], bands: B({ it: "Le sensazioni del corpo e dell'ambiente ti passano accanto senza che le noti.", en: "Bodily and environmental sensations pass by without you noticing them." }, { it: "Noti quello che senti quanto la maggior parte delle persone.", en: "You notice what you sense as much as most people." }, { it: "Sei molto attento a sensazioni, suoni e dettagli: la sfaccettatura che la meditazione allena di più.", en: "You are very attentive to sensations, sounds and details: the facet meditation trains most." }) },
      { key: "desc", name: { it: "Descrivere", en: "Describing" }, items: [2, 7, 12], mode: "mean", range: [1, 5], bands: B({ it: "Trovare le parole per quello che provi ti costa: un'abilità che si allena scrivendo o parlandone.", en: "Finding words for what you feel is hard for you: a skill trained by writing or talking about it." }, { it: "Dai un nome a quello che provi quanto la maggior parte delle persone.", en: "You name what you feel as much as most people." }, { it: "Metti in parole le emozioni con facilità, anche quelle difficili.", en: "You put emotions into words easily, even difficult ones." }) },
      { key: "aware", name: { it: "Agire con consapevolezza", en: "Acting with awareness" }, items: [3, 8, 13], mode: "mean", range: [1, 5], bands: B({ it: "Molto pilota automatico: fai le cose mentre la mente è altrove.", en: "A lot of autopilot: you do things while your mind is elsewhere." }, { it: "Presente quando conta, in automatico nella routine.", en: "Present when it counts, on autopilot in routine." }, { it: "Sei nel presente mentre agisci, più della maggior parte delle persone.", en: "You are present while you act, more than most people." }) },
      { key: "nonj", name: { it: "Non giudicare", en: "Nonjudging" }, items: [4, 9, 14], mode: "mean", range: [1, 5], bands: B({ it: "Giudichi quello che provi: certi pensieri ed emozioni ti sembrano sbagliati. È la sfaccettatura più legata al benessere.", en: "You judge what you feel: some thoughts and emotions seem wrong to you. This is the facet most linked to well-being." }, { it: "A volte ti critichi per quello che provi, a volte lo lasci essere.", en: "Sometimes you criticise yourself for what you feel, sometimes you let it be." }, { it: "Lasci che pensieri ed emozioni ci siano senza etichettarli come sbagliati.", en: "You let thoughts and emotions be there without labelling them wrong." }) },
      { key: "nonr", name: { it: "Non reagire", en: "Nonreactivity" }, items: [5, 10, 15], mode: "mean", range: [1, 5], bands: B({ it: "I pensieri che turbano ti trascinano: la distanza da essi si costruisce con la pratica.", en: "Distressing thoughts carry you away: distance from them is built with practice." }, { it: "A volte riesci a osservare un pensiero difficile senza reagire, a volte ti prende.", en: "Sometimes you can observe a hard thought without reacting, sometimes it takes you." }, { it: "Osservi i pensieri difficili e li lasci andare: la sfaccettatura più protettiva contro il rimuginio.", en: "You observe difficult thoughts and let them go: the facet most protective against rumination." }) }
    ];
  })()
};
