/* GAD-7 (Spitzer, Kroenke, Williams & Löwe 2006) — Pfizer, uso libero. Versione italiana ufficiale (phqscreeners). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.gad7 = {
  code: "GAD-7", theme: "slate", sensitive: true, n: 7, values: [0, 1, 2, 3],
  labels: { en: ["Not at all", "Several days", "More than half the days", "Nearly every day"], it: ["Mai", "Alcuni giorni", "Più della metà dei giorni", "Quasi ogni giorno"] },
  items: {
    en: ["Feeling nervous, anxious, or on edge", "Not being able to stop or control worrying", "Worrying too much about different things", "Trouble relaxing", "Being so restless that it's hard to sit still", "Becoming easily annoyed or irritable", "Feeling afraid as if something awful might happen"],
    it: ["Sentirsi nervoso, ansioso o teso", "Non riuscire a smettere di preoccuparsi o a tenere sotto controllo le preoccupazioni", "Preoccuparsi troppo per varie cose", "Avere difficoltà a rilassarsi", "Essere talmente irrequieto da far fatica a stare seduto fermo", "Infastidirsi o irritarsi facilmente", "Avere paura che possa succedere qualcosa di terribile"]
  },
  text: {
    it: { kicker: "Ansia · screening", title: "Quanta ansia, nelle ultime due settimane?", lede: "7 domande, 1 minuto. Il GAD-7 è il questionario di screening per l'ansia generalizzata usato in tutto il mondo. Dice se vale la pena parlarne, non fa diagnosi.", meta: ["7 domande", "~1 minuto", "Screening"], instr: "Nelle <b>ultime due settimane</b>, con quale frequenza ti hanno dato fastidio i seguenti problemi?", how: "Il punteggio va da 0 a 21: 0–4 minimo, 5–9 lieve, 10–14 moderato, 15–21 grave. Da 10 in su i medici approfondiscono. Il GAD-7 coglie bene anche altri disturbi d'ansia (panico, ansia sociale): un punteggio alto dice che l'ansia pesa, non di quale tipo sia.", cite: "Spitzer, R. L., Kroenke, K., Williams, J. B. W., & Löwe, B. (2006). A brief measure for assessing generalized anxiety disorder: the GAD-7. Archives of Internal Medicine, 166, 1092-1097. © Pfizer, uso libero." },
    en: { kicker: "Anxiety · screening", title: "How anxious, over the last two weeks?", lede: "7 questions, 1 minute. The GAD-7 is the generalised-anxiety screening questionnaire used worldwide. It tells you whether it is worth talking about; it is not a diagnosis.", meta: ["7 questions", "~1 minute", "Screening"], instr: "Over the <b>last two weeks</b>, how often have you been bothered by the following problems?", how: "The score runs from 0 to 21: 0–4 minimal, 5–9 mild, 10–14 moderate, 15–21 severe. From 10 up, clinicians follow up. The GAD-7 also picks up other anxiety disorders (panic, social anxiety): a high score says anxiety weighs on you, not which kind it is.", cite: "Spitzer, R. L., Kroenke, K., Williams, J. B. W., & Löwe, B. (2006). A brief measure for assessing generalized anxiety disorder: the GAD-7. Archives of Internal Medicine, 166, 1092-1097. © Pfizer, free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Sintomi d'ansia", en: "Anxiety symptoms" }, items: [1,2,3,4,5,6,7], mode: "sum", range: [0, 21],
    bands: [
      { max: 4, name: { it: "Minimo", en: "Minimal" }, text: { it: "Ansia minima o assente nelle ultime due settimane.", en: "Minimal or no anxiety over the last two weeks." } },
      { max: 9, name: { it: "Lieve", en: "Mild" }, text: { it: "Ansia lieve: tensione e preoccupazioni ci sono ma restano gestibili.", en: "Mild anxiety: tension and worries are there but remain manageable." } },
      { max: 14, name: { it: "Moderato", en: "Moderate" }, text: { it: "Ansia moderata: la soglia da cui i medici approfondiscono. Parlarne con il medico o con uno psicologo è la mossa sensata; l'ansia risponde bene ai trattamenti.", en: "Moderate anxiety: the threshold at which clinicians follow up. Talking to a doctor or a psychologist is the sensible move; anxiety responds well to treatment." } },
      { max: 21, name: { it: "Grave", en: "Severe" }, text: { it: "Ansia grave, che probabilmente sta condizionando le giornate. Chiedi aiuto: è uno dei problemi che si trattano meglio.", en: "Severe anxiety, probably shaping your days. Ask for help: it is one of the most treatable problems." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.gad7.approf = {
  it: {
    title: "L'ansia, quando diventa un problema",
    intro: `<p>Il GAD-7 è nato nel 2006 dalla stessa famiglia del PHQ, per misurare in poche righe il <span class="t" data-tip="Generalized Anxiety Disorder: ansia e preoccupazione eccessive e difficili da controllare, presenti per la maggior parte dei giorni per almeno sei mesi, con sintomi come tensione, irritabilità e difficoltà a rilassarsi.">disturbo d'ansia generalizzata</span>. Le sette domande coprono i suoi segni principali: nervosismo, <span class="t" data-tip="Il rimuginare: pensieri di preoccupazione che si rincorrono, spesso sul futuro, difficili da fermare. È il motore centrale dell'ansia generalizzata.">preoccupazione incontrollabile</span>, tensione, irrequietezza, irritabilità, senso che stia per succedere qualcosa di brutto. È uno strumento di <span class="t" data-tip="Un filtro rapido che segnala chi merita un approfondimento, non un test che assegna una diagnosi. Un risultato alto è un invito a parlarne.">screening</span>: dice se e quanto l'ansia pesa, non quale disturbo sia né se ci sia un disturbo.</p>`,
    blocks: [
      { h: "Che cos'è l'ansia patologica", html: `<p>L'ansia in sé è utile: è il sistema di allarme che ci prepara a una minaccia. Diventa un problema per due segni insieme. Primo, la paura è <b>sproporzionata</b> rispetto al pericolo reale, o scatta anche senza pericolo. Secondo, per ridurla la persona comincia a <span class="t" data-tip="Evitare luoghi, situazioni o pensieri che attivano l'ansia. Riduce il disagio subito, ma nel tempo allarga la paura e restringe la vita: è il meccanismo che mantiene i disturbi d'ansia.">evitare</span>, e l'evitamento cresce, restringendo la vita. La combinazione allarme esagerato più evitamento che si allarga è ciò che distingue la normale apprensione dai disturbi d'ansia veri e propri.</p>` },
      { h: "Le soglie", html: `<p>Il totale va da 0 a 21, con tre gradini: 5 (lieve), 10 (moderato), 15 (grave). La soglia più usata è <b>10</b>: da lì in su conviene approfondire. A quel <span class="t" data-tip="Il valore soglia oltre il quale il risultato è considerato positivo. Abbassarlo trova più casi veri ma anche più falsi allarmi; alzarlo fa il contrario.">cut-off</span> il GAD-7 ha buona <span class="t" data-tip="La capacità di individuare chi ha davvero il disturbo, cioè pochi casi che sfuggono.">sensibilità</span> e discreta <span class="t" data-tip="La capacità di escludere chi non ha il disturbo, cioè pochi falsi allarmi.">specificità</span> per l'ansia generalizzata. Il numero misura l'intensità del disagio nelle ultime due settimane, non la sua causa.</p>` },
      { h: "Non solo ansia generalizzata", html: `<p>Anche se è tarato sull'ansia generalizzata, il GAD-7 coglie bene altri disturbi della stessa area: il <span class="t" data-tip="Attacchi improvvisi di paura intensa con sintomi fisici (cuore, respiro, vertigini). Spesso si sviluppa la paura della paura stessa: il timore che l'attacco torni.">disturbo di panico</span>, l'<span class="t" data-tip="Paura intensa del giudizio e dell'esposizione sociale, con evitamento di situazioni in cui ci si sente osservati.">ansia sociale</span> e in parte lo stress post-traumatico. Per questo un punteggio alto dice che l'ansia pesa, ma non di quale tipo: è un buon rilevatore di ampio spettro, non un test specifico. Distinguere le forme è compito del colloquio.</p>` },
      { h: "La rimuginazione", html: `<p>Il cuore dell'ansia generalizzata è la <span class="t" data-tip="Catena di pensieri e se: e se succedesse questo, e se andasse male quello. Dà l'illusione di prepararsi, ma non porta a una soluzione e mantiene attivo l'allarme.">rimuginazione</span>, il loop dei e se che promette di prepararti al peggio e invece tiene solo acceso l'allarme. Si distingue dal problem-solving per un segno semplice: il problem-solving arriva a un passo concreto e si ferma, la rimuginazione gira e non atterra mai. Riconoscere questa differenza è uno dei primi passi di ogni terapia dell'ansia.</p>` }
    ],
    beyond: `<ul>
      <li><b>La versione più corta.</b> Le prime due domande formano il GAD-2, uno screening ultra-rapido usato quando il tempo è poco: se scatta, si prosegue con le altre cinque.</li>
      <li><b>Ansia e depressione viaggiano insieme.</b> Condividono una base comune di affetto negativo e spesso si presentano nella stessa persona; è normale che GAD-7 e PHQ-9 salgano insieme. Sono due espressioni vicine, non due mondi separati.</li>
      <li><b>L'evitamento alimenta la paura.</b> Ogni volta che eviti, l'ansia cala subito ma la paura si rafforza. Per questo il trattamento più efficace fa il contrario: l'<span class="t" data-tip="Esporsi in modo graduale e controllato a ciò che si teme, senza fuggire, finché l'allarme scende da solo. È l'ingrediente attivo della terapia cognitivo-comportamentale per l'ansia.">esposizione graduale</span> insegna al sistema che la minaccia non arriva.</li>
      <li><b>Tra i più trattabili.</b> I disturbi d'ansia rispondono bene alla terapia cognitivo-comportamentale e ai farmaci; individuarli presto abbassa molto la sofferenza.</li>
    </ul>`,
    taratura: `<p>Il GAD-7 è uno degli screening per l'ansia più validati e usati, con buona attendibilità e soglie replicate in molte lingue. Due limiti onesti. Primo: è uno screening, non una diagnosi, e nella popolazione generale molti punteggi sopra 10 non corrispondono a un disturbo d'ansia vero e proprio. Secondo: coglie il disagio in modo ampio ma poco specifico — la sua <span class="t" data-tip="La capacità di uno strumento di distinguere un costrutto da un altro simile. Il GAD-7 correla molto con le misure di depressione: separa bene l'ansia dal benessere, meno bene l'ansia dalla depressione.">validità discriminante</span> rispetto alla depressione è limitata, perché ansia e depressione si sovrappongono. È un'autodescrizione delle ultime due settimane: apre la conversazione, non la chiude.</p>`,
    reading: [
      "Spitzer, R. L., Kroenke, K., Williams, J. B. W. & Löwe, B. (2006). The GAD-7. <em>Archives of Internal Medicine</em>, 166, 1092-1097.",
      "Plummer, F. et al. (2016). Screening for anxiety disorders with the GAD-7. <em>General Hospital Psychiatry</em>, 39, 24-31.",
      "Kroenke, K. et al. (2007). Anxiety disorders in primary care. <em>Annals of Internal Medicine</em>, 146, 317-325."
    ]
  },
  en: {
    title: "Anxiety, when it becomes a problem",
    intro: `<p>The GAD-7 was born in 2006 from the same family as the PHQ, to measure in a few lines <span class="t" data-tip="Generalized Anxiety Disorder: excessive, hard-to-control anxiety and worry present most days for at least six months, with symptoms such as tension, irritability and trouble relaxing.">generalised anxiety disorder</span>. Its seven questions cover the main signs: nervousness, <span class="t" data-tip="Worry: chains of worried thoughts, often about the future, hard to stop. It is the central engine of generalised anxiety.">uncontrollable worry</span>, tension, restlessness, irritability, the sense that something awful might happen. It is a <span class="t" data-tip="A quick filter that flags who deserves a closer look, not a test that assigns a diagnosis. A high result is an invitation to talk.">screening</span> tool: it says whether and how much anxiety weighs, not which disorder it is or whether there is one.</p>`,
    blocks: [
      { h: "What pathological anxiety is", html: `<p>Anxiety itself is useful: it is the alarm system that readies us for a threat. It becomes a problem through two signs together. First, the fear is <b>disproportionate</b> to the real danger, or fires with no danger at all. Second, to reduce it the person starts to <span class="t" data-tip="Avoiding places, situations or thoughts that set off anxiety. It eases the discomfort at once, but over time it widens the fear and shrinks life: it is the mechanism that keeps anxiety disorders going.">avoid</span>, and the avoidance grows, narrowing life. The combination of an oversized alarm plus spreading avoidance is what separates ordinary apprehension from anxiety disorders proper.</p>` },
      { h: "The thresholds", html: `<p>The total runs from 0 to 21, in three steps: 5 (mild), 10 (moderate), 15 (severe). The most-used threshold is <b>10</b>: from there up, following up is advised. At that <span class="t" data-tip="The threshold above which a result counts as positive. Lowering it finds more true cases but also more false alarms; raising it does the reverse.">cut-off</span> the GAD-7 has good <span class="t" data-tip="The ability to catch those who really have the disorder, so few cases slip through.">sensitivity</span> and fair <span class="t" data-tip="The ability to rule out those who don't have the disorder, so few false alarms.">specificity</span> for generalised anxiety. The number measures the intensity of distress over the last two weeks, not its cause.</p>` },
      { h: "Not only generalised anxiety", html: `<p>Although it is tuned to generalised anxiety, the GAD-7 also picks up other disorders in the same area: <span class="t" data-tip="Sudden attacks of intense fear with physical symptoms (heart, breathing, dizziness). Often a fear of the fear develops: dread that the attack will return.">panic disorder</span>, <span class="t" data-tip="Intense fear of judgement and social exposure, with avoidance of situations where one feels watched.">social anxiety</span> and partly post-traumatic stress. So a high score says anxiety weighs, but not of which kind: it is a good broad-spectrum detector, not a specific test. Telling the forms apart is the job of an interview.</p>` },
      { h: "Worry", html: `<p>The heart of generalised anxiety is <span class="t" data-tip="A chain of what-ifs: what if this happens, what if that goes wrong. It gives the illusion of preparing, but reaches no solution and keeps the alarm switched on.">worry</span>, the loop of what-ifs that promises to ready you for the worst and instead only keeps the alarm on. It differs from problem-solving by one simple sign: problem-solving reaches a concrete next step and stops, worry spins and never lands. Recognising that difference is one of the first steps of any anxiety treatment.</p>` }
    ],
    beyond: `<ul>
      <li><b>The shorter version.</b> The first two questions form the GAD-2, an ultra-quick screen used when time is short: if it triggers, you go on to the other five.</li>
      <li><b>Anxiety and depression travel together.</b> They share a common base of negative affect and often appear in the same person; it is normal for GAD-7 and PHQ-9 to rise together. They are two near expressions, not two separate worlds.</li>
      <li><b>Avoidance feeds the fear.</b> Every time you avoid, anxiety drops at once but the fear strengthens. That is why the most effective treatment does the opposite: <span class="t" data-tip="Facing what you fear gradually and in a controlled way, without fleeing, until the alarm drops on its own. It is the active ingredient of cognitive-behavioural therapy for anxiety.">graded exposure</span> teaches the system that the threat does not arrive.</li>
      <li><b>Among the most treatable.</b> Anxiety disorders respond well to cognitive-behavioural therapy and to medication; catching them early cuts the suffering sharply.</li>
    </ul>`,
    taratura: `<p>The GAD-7 is one of the most validated and widely used anxiety screens, with good reliability and thresholds replicated across many languages. Two honest limits. First: it is a screen, not a diagnosis, and in the general population many scores above 10 do not correspond to an actual anxiety disorder. Second: it catches distress broadly but not specifically — its <span class="t" data-tip="A tool's ability to tell one construct from another similar one. The GAD-7 correlates strongly with depression measures: it separates anxiety from well-being well, anxiety from depression less well.">discriminant validity</span> against depression is limited, because anxiety and depression overlap. It is a self-report of the last two weeks: it opens the conversation, it does not close it.</p>`,
    reading: [
      "Spitzer, R. L., Kroenke, K., Williams, J. B. W. & Löwe, B. (2006). The GAD-7. <em>Archives of Internal Medicine</em>, 166, 1092-1097.",
      "Plummer, F. et al. (2016). Screening for anxiety disorders with the GAD-7. <em>General Hospital Psychiatry</em>, 39, 24-31.",
      "Kroenke, K. et al. (2007). Anxiety disorders in primary care. <em>Annals of Internal Medicine</em>, 146, 317-325."
    ]
  },
  pt: {
    title: "A ansiedade, quando vira um problema",
    intro: `<p>O GAD-7 nasceu em 2006 da mesma família do PHQ, para medir em poucas linhas o <span class="t" data-tip="Generalized Anxiety Disorder: ansiedade e preocupação excessivas e difíceis de controlar, presentes na maioria dos dias por pelo menos seis meses, com sintomas como tensão, irritabilidade e dificuldade de relaxar.">transtorno de ansiedade generalizada</span>. As sete perguntas cobrem seus sinais principais: nervosismo, <span class="t" data-tip="O ruminar: cadeias de pensamentos de preocupação, muitas vezes sobre o futuro, difíceis de parar. É o motor central da ansiedade generalizada.">preocupação incontrolável</span>, tensão, inquietação, irritabilidade, a sensação de que algo ruim vai acontecer. É um instrumento de <span class="t" data-tip="Um filtro rápido que sinaliza quem merece uma avaliação mais detalhada, não um teste que atribui um diagnóstico. Um resultado alto é um convite a conversar.">triagem</span>: diz se e o quanto a ansiedade pesa, não qual transtorno é nem se há um.</p>`,
    blocks: [
      { h: "O que é a ansiedade patológica", html: `<p>A ansiedade em si é útil: é o sistema de alarme que nos prepara para uma ameaça. Vira problema por dois sinais juntos. Primeiro, o medo é <b>desproporcional</b> ao perigo real, ou dispara mesmo sem perigo. Segundo, para reduzi-lo a pessoa começa a <span class="t" data-tip="Evitar lugares, situações ou pensamentos que ativam a ansiedade. Alivia o desconforto na hora, mas com o tempo amplia o medo e encolhe a vida: é o mecanismo que mantém os transtornos de ansiedade.">evitar</span>, e a evitação cresce, estreitando a vida. A combinação de alarme exagerado mais evitação que se amplia é o que distingue a apreensão normal dos transtornos de ansiedade propriamente ditos.</p>` },
      { h: "As faixas", html: `<p>O total vai de 0 a 21, em três degraus: 5 (leve), 10 (moderado), 15 (grave). A faixa mais usada é <b>10</b>: dali para cima recomenda-se aprofundar. Nesse <span class="t" data-tip="O valor limiar acima do qual o resultado é considerado positivo. Baixá-lo encontra mais casos verdadeiros, mas também mais alarmes falsos; elevá-lo faz o contrário.">ponto de corte</span> o GAD-7 tem boa <span class="t" data-tip="A capacidade de identificar quem realmente tem o transtorno, ou seja, poucos casos escapam.">sensibilidade</span> e razoável <span class="t" data-tip="A capacidade de excluir quem não tem o transtorno, ou seja, poucos alarmes falsos.">especificidade</span> para a ansiedade generalizada. O número mede a intensidade do sofrimento nas últimas duas semanas, não a sua causa.</p>` },
      { h: "Não só ansiedade generalizada", html: `<p>Embora calibrado para a ansiedade generalizada, o GAD-7 também capta outros transtornos da mesma área: o <span class="t" data-tip="Ataques súbitos de medo intenso com sintomas físicos (coração, respiração, tontura). Muitas vezes desenvolve-se o medo do próprio medo: o receio de que o ataque volte.">transtorno de pânico</span>, a <span class="t" data-tip="Medo intenso do julgamento e da exposição social, com evitação de situações em que a pessoa se sente observada.">ansiedade social</span> e em parte o estresse pós-traumático. Por isso uma pontuação alta diz que a ansiedade pesa, mas não de que tipo: é um bom detector de amplo espectro, não um teste específico. Distinguir as formas é tarefa da entrevista.</p>` },
      { h: "A ruminação", html: `<p>O coração da ansiedade generalizada é a <span class="t" data-tip="Cadeia de e ses: e se acontecer isto, e se aquilo der errado. Dá a ilusão de estar se preparando, mas não chega a uma solução e mantém o alarme aceso.">ruminação</span>, o loop dos e se que promete prepará-lo para o pior e, em vez disso, só mantém o alarme ligado. Distingue-se da resolução de problemas por um sinal simples: a resolução de problemas chega a um passo concreto e para, a ruminação gira e nunca aterrissa. Reconhecer essa diferença é um dos primeiros passos de qualquer terapia da ansiedade.</p>` }
    ],
    beyond: `<ul>
      <li><b>A versão mais curta.</b> As duas primeiras perguntas formam o GAD-2, uma triagem ultrarrápida usada quando o tempo é curto: se dispara, segue-se com as outras cinco.</li>
      <li><b>Ansiedade e depressão viajam juntas.</b> Compartilham uma base comum de afeto negativo e muitas vezes aparecem na mesma pessoa; é normal que GAD-7 e PHQ-9 subam juntos. São duas expressões próximas, não dois mundos separados.</li>
      <li><b>A evitação alimenta o medo.</b> Cada vez que você evita, a ansiedade cai na hora, mas o medo se fortalece. Por isso o tratamento mais eficaz faz o contrário: a <span class="t" data-tip="Expor-se de forma gradual e controlada ao que se teme, sem fugir, até o alarme baixar sozinho. É o ingrediente ativo da terapia cognitivo-comportamental para a ansiedade.">exposição gradual</span> ensina ao sistema que a ameaça não chega.</li>
      <li><b>Entre os mais tratáveis.</b> Os transtornos de ansiedade respondem bem à terapia cognitivo-comportamental e à medicação; identificá-los cedo reduz muito o sofrimento.</li>
    </ul>`,
    taratura: `<p>O GAD-7 é uma das triagens de ansiedade mais validadas e usadas, com boa confiabilidade e faixas replicadas em muitas línguas. Dois limites honestos. Primeiro: é uma triagem, não um diagnóstico, e na população geral muitas pontuações acima de 10 não correspondem a um transtorno de ansiedade propriamente dito. Segundo: capta o sofrimento de forma ampla, mas pouco específica — sua <span class="t" data-tip="A capacidade de um instrumento de distinguir um construto de outro parecido. O GAD-7 correlaciona muito com as medidas de depressão: separa bem a ansiedade do bem-estar, menos bem a ansiedade da depressão.">validade discriminante</span> em relação à depressão é limitada, porque ansiedade e depressão se sobrepõem. É uma autodescrição das últimas duas semanas: abre a conversa, não a encerra.</p>`,
    reading: [
      "Spitzer, R. L., Kroenke, K., Williams, J. B. W. & Löwe, B. (2006). The GAD-7. <em>Archives of Internal Medicine</em>, 166, 1092-1097.",
      "Plummer, F. et al. (2016). Screening for anxiety disorders with the GAD-7. <em>General Hospital Psychiatry</em>, 39, 24-31.",
      "Kroenke, K. et al. (2007). Anxiety disorders in primary care. <em>Annals of Internal Medicine</em>, 146, 317-325."
    ]
  }
};
