/* Irrational Procrastination Scale, IPS (Steel 2010) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.ips = {
  code: "IPS", theme: "plum", n: 9, reverse: [2, 6, 9],
  labels: { en: ["Very seldom or not true of me", "Seldom true of me", "Sometimes true of me", "Often true of me", "Very often true, or true of me"], it: ["Molto raramente o mai vero per me", "Raramente vero", "A volte vero", "Spesso vero", "Molto spesso o sempre vero per me"] },
  items: {
    en: ["I put things off so long that my well-being or efficiency unnecessarily suffers.", "If there is something I should do, I get to it before attending to lesser tasks.", "My life would be better if I did some activities or tasks earlier.", "When I should be doing one thing, I will do another.", "At the end of the day, I know I could have spent the time better.", "I spend my time wisely.", "I delay tasks beyond what is reasonable.", "I procrastinate.", "I do everything when I believe it needs to be done."],
    it: ["Rimando le cose così a lungo che il mio benessere o la mia efficienza ne soffrono inutilmente.", "Se c'è qualcosa che dovrei fare, la faccio prima di dedicarmi a compiti meno importanti.", "La mia vita sarebbe migliore se facessi alcune attività o compiti prima.", "Quando dovrei fare una cosa, ne faccio un'altra.", "A fine giornata so che avrei potuto usare meglio il tempo.", "Uso il mio tempo con saggezza.", "Rimando i compiti oltre il ragionevole.", "Procrastino.", "Faccio tutto quando credo che vada fatto."]
  },
  text: {
    it: { kicker: "Procrastinazione", title: "Quanto rimandi?", lede: "9 affermazioni, 1 minuto. L'IPS di Piers Steel misura la procrastinazione «irrazionale»: rimandare pur sapendo che ci si rimette.", meta: ["9 domande", "~1 minuto"], instr: "Per ogni frase indica quanto è vera per te, pensando a come ti comporti <b>di solito</b>.", how: "Il punteggio va da 9 a 45 (3 affermazioni sono invertite). La media negli adulti è intorno a 27; sopra 33 circa sei tra il quarto di persone che rimanda di più, sotto 21 tra chi rimanda meno. La procrastinazione cronica è legata più alla regolazione delle emozioni (evitare il disagio del compito) che alla gestione del tempo.", cite: "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? Personality and Individual Differences, 48, 926-934. Uso libero; traduzione italiana propria." },
    en: { kicker: "Procrastination", title: "How much do you put things off?", lede: "9 statements, 1 minute. Piers Steel's IPS measures “irrational” procrastination: delaying while knowing you will be worse off.", meta: ["9 questions", "~1 minute"], instr: "For each statement, indicate how true it is of you, thinking about how you <b>usually</b> behave.", how: "The score runs from 9 to 45 (3 statements are reverse-keyed). The adult mean is around 27; above about 33 you are in the quarter of people who procrastinate most, below 21 among those who procrastinate least. Chronic procrastination is tied more to emotion regulation (avoiding the discomfort of the task) than to time management.", cite: "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? Personality and Individual Differences, 48, 926-934. Free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Procrastinazione", en: "Procrastination" }, items: [1,2,3,4,5,6,7,8,9], mode: "sum", range: [9, 45],
    bands: [
      { max: 20, name: { it: "Bassa", en: "Low" }, text: { it: "Fai le cose quando vanno fatte: rimandare non è un tuo problema.", en: "You do things when they need doing: putting off is not your problem." } },
      { max: 33, name: { it: "Nella media", en: "Average" }, text: { it: "Rimandi come la maggior parte delle persone: qualche compito scivola, ma il grosso arriva in tempo.", en: "You put things off like most people: some tasks slip, but the bulk gets done on time." } },
      { max: 45, name: { it: "Alta", en: "High" }, text: { it: "Tra chi rimanda di più: il rinvio ti costa in benessere e risultati. Funziona meglio ridurre il disagio del primo passo (compiti piccoli, tempo limitato) che cercare più disciplina.", en: "Among those who procrastinate most: delay costs you in well-being and results. Reducing the discomfort of the first step (small tasks, limited time) works better than seeking more discipline." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.ips.approf = {
  it: {
    title: "La procrastinazione, in profondità",
    intro: `<p>Il fenomeno è antico: i greci lo chiamavano <span class="t" data-tip="Akrasia: agire contro il proprio giudizio migliore pur sapendo cosa sarebbe meglio fare. Ne discutevano già Socrate e Aristotele.">akrasia</span>, la debolezza della volontà, fare il contrario di quello che sappiamo essere meglio. In psicologia lo mette a fuoco <span class="t" data-tip="Piers Steel, psicologo canadese; la sua meta-analisi del 2007 su centinaia di studi è il punto di riferimento sul tema, insieme alla teoria che ne ha ricavato.">Piers Steel</span> con una meta-analisi (2007) e con questa scala. La definizione tecnica è precisa: la procrastinazione è un <span class="t" data-tip="Il ritardo è scelto liberamente e la persona si aspetta di stare peggio per averlo scelto. È questo a distinguerla da un rinvio saggio o inevitabile.">ritardo volontario e controproducente</span> — rimandare qualcosa che intendevi fare, pur aspettandoti di rimetterci. Non ogni rinvio lo è: rimandare con criterio è saggezza, non procrastinazione.</p>`,
    blocks: [
      { h: "Non è pigrizia", html: `<p>Il malinteso più radicato è confonderla con la <span class="t" data-tip="Il pigro non vuole agire e non ne soffre. Il procrastinatore vuole agire, sa che dovrebbe, e proprio per questo sta male mentre non lo fa.">pigrizia</span>. Sono opposte nell'esperienza: il pigro è in pace con il suo non fare, il procrastinatore no. Vuole fare, sa che dovrebbe, si è ripromesso di iniziare — e non inizia, con un peso addosso che il pigro non conosce. La procrastinazione è un conflitto interno, non un'assenza di motivazione: è proprio il divario tra intenzione e azione a definirla.</p>` },
      { h: "L'equazione della procrastinazione", html: `<p>Steel ha riassunto le cause in una formula, la <span class="t" data-tip="Temporal Motivation Theory: la motivazione a fare un compito cresce con l'aspettativa di riuscirci e con quanto la ricompensa ci piace, e cala con l'impulsività e con quanto è lontana nel tempo.">teoria della motivazione temporale</span>. La voglia di fare una cosa aumenta se ti aspetti di riuscirci e se il risultato ti interessa, e diminuisce con l'<span class="t" data-tip="La tendenza a farsi trascinare dall'impulso del momento e a preferire la ricompensa immediata. È il tratto più legato alla procrastinazione.">impulsività</span> e con la distanza temporale della ricompensa. Ecco perché rimandi la scadenza lontana e ti attivi solo all'ultimo: man mano che il termine si avvicina, il valore del compito nel presente sale finché supera la tentazione. Chi procrastina di più è spesso chi <span class="t" data-tip="Sconto temporale: la tendenza a svalutare fortemente le ricompense future rispetto a quelle immediate. Più è ripido, più il futuro pesa poco oggi.">svaluta il futuro</span> più ripidamente.</p>` },
      { h: "Il vero motore: le emozioni", html: `<p>La svolta più recente sposta l'accento dal tempo alle emozioni. Secondo <span class="t" data-tip="Fuschia Sirois e Timothy Pychyl (2013): la procrastinazione non è un problema di gestione del tempo ma di regolazione delle emozioni. Si rimanda per non sentire il disagio del compito.">Sirois e Pychyl</span>, non rimandi il compito: rimandi l'<em>emozione</em> che il compito ti fa provare — noia, ansia, frustrazione, paura di non essere all'altezza. Procrastinare è una forma di <span class="t" data-tip="Regolazione delle emozioni: le strategie con cui gestiamo ciò che proviamo. Procrastinare ne è una a corto raggio: fa stare meglio adesso e peggio dopo.">regolazione delle emozioni</span> a corto raggio — cedere per stare bene subito — che ripara l'umore nel presente e lo peggiora nel futuro. Ecco perché la disciplina da sola serve poco: il problema non è il tempo, è il disagio.</p>` },
      { h: "Cosa funziona davvero", html: `<p>Se la radice è emotiva, la cura non è più forza di volontà ma meno disagio all'avvio. Funziona rendere il primo passo piccolissimo, limitare il tempo («solo cinque minuti»), togliere le tentazioni dal campo invece di resisterle. E funziona, controintuitivamente, l'auto-compassione: gli studi mostrano che perdonarsi una procrastinazione riduce la probabilità di ripeterla, perché toglie proprio quel disagio che spinge a rimandare di nuovo. Trattarsi con durezza, al contrario, alimenta il ciclo.</p>` }
    ],
    beyond: `<ul>
      <li><b>La spirale del benessere.</b> La procrastinazione cronica si lega a più stress, peggior salute e ritardi nelle cure: chi rimanda tende a rimandare anche dal medico. Il costo va oltre le scadenze mancate.</li>
      <li><b>Non tutti i rinvii sono uguali.</b> Steel distingue il rimandare per impulsività da chi dice di «lavorare meglio sotto pressione»: quest'ultima, ai dati, è più spesso una razionalizzazione che una vera strategia efficace.</li>
      <li><b>Le tre forme messe in dubbio.</b> Si parlava di procrastinatori «da eccitazione», «evitanti» e «decisionali»; lo studio del 2010 alla base di questa scala trovò poche prove del tipo da eccitazione.</li>
      <li><b>Perfezionismo.</b> La paura di non fare un lavoro perfetto è una via diretta alla procrastinazione: se l'unico esito accettabile è impeccabile, non iniziare protegge dall'imperfezione.</li>
    </ul>`,
    taratura: `<p>L'IPS misura bene un nucleo unico e coerente di procrastinazione, con buona affidabilità, ed è costruita per catturare la parte «pura», irrazionale, più che i rinvii sensati. Restano i limiti di ogni self-report: la procrastinazione è socialmente poco desiderabile, e c'è chi la sottostima e chi, sentendosi in colpa, la sovrastima. Le fasce di punteggio qui sono orientative, ricavate soprattutto da campioni studenteschi e occidentali; il confine tra un rinvio strategico e uno controproducente, poi, lo conosci meglio tu della scala.</p>`,
    reading: [
      "Steel, P. (2007). The nature of procrastination: a meta-analytic and theoretical review. <em>Psychological Bulletin</em>, 133, 65-94.",
      "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? <em>Personality and Individual Differences</em>, 48, 926-934.",
      "Sirois, F. & Pychyl, T. (2013). Procrastination and the priority of short-term mood regulation. <em>Social and Personality Psychology Compass</em>, 7, 115-127."
    ]
  },
  en: {
    title: "Procrastination, in depth",
    intro: `<p>The phenomenon is ancient: the Greeks called it <span class="t" data-tip="Akrasia: acting against your own better judgement while knowing what would be best to do. Socrates and Aristotle already discussed it.">akrasia</span>, weakness of will, doing the opposite of what we know is best. In psychology <span class="t" data-tip="Piers Steel, Canadian psychologist; his 2007 meta-analysis of hundreds of studies is the reference point on the topic, together with the theory he drew from it.">Piers Steel</span> brought it into focus with a meta-analysis (2007) and with this scale. The technical definition is precise: procrastination is a <span class="t" data-tip="The delay is freely chosen and the person expects to be worse off for choosing it. This is what sets it apart from a wise or unavoidable postponement.">voluntary, self-defeating delay</span> — putting off something you meant to do, while expecting to lose out. Not every postponement is one: delaying with judgement is wisdom, not procrastination.</p>`,
    blocks: [
      { h: "It is not laziness", html: `<p>The most stubborn misunderstanding is confusing it with <span class="t" data-tip="The lazy person does not want to act and does not suffer for it. The procrastinator wants to act, knows they should, and precisely for that reason feels bad while not doing it.">laziness</span>. They are opposites in experience: the lazy person is at peace with their inaction, the procrastinator is not. They want to act, know they should, promised themselves they would start — and do not, carrying a weight the lazy person does not know. Procrastination is an inner conflict, not an absence of motivation: it is the very gap between intention and action that defines it.</p>` },
      { h: "The procrastination equation", html: `<p>Steel summed up the causes in a formula, <span class="t" data-tip="Temporal Motivation Theory: motivation to do a task rises with the expectation of succeeding and with how much you value the reward, and falls with impulsiveness and with how far off the reward is.">Temporal Motivation Theory</span>. The urge to do something rises if you expect to succeed and if the outcome interests you, and falls with <span class="t" data-tip="The tendency to be swept along by the impulse of the moment and to prefer the immediate reward. It is the trait most tied to procrastination.">impulsiveness</span> and with the reward's distance in time. This is why you put off the far-off deadline and only get going at the last minute: as the deadline nears, the task's present value climbs until it overtakes the temptation. Those who procrastinate most are often those who <span class="t" data-tip="Temporal discounting: the tendency to strongly devalue future rewards relative to immediate ones. The steeper it is, the less the future weighs today.">discount the future</span> most steeply.</p>` },
      { h: "The real engine: emotions", html: `<p>The most recent shift moves the emphasis from time to emotions. According to <span class="t" data-tip="Fuschia Sirois and Timothy Pychyl (2013): procrastination is not a time-management problem but an emotion-regulation one. You put off in order not to feel the discomfort of the task.">Sirois and Pychyl</span>, you are not putting off the task: you are putting off the <em>emotion</em> the task makes you feel — boredom, anxiety, frustration, fear of not being good enough. Procrastinating is a short-range form of <span class="t" data-tip="Emotion regulation: the strategies by which we manage what we feel. Procrastination is a short-range one: it makes you feel better now and worse later.">emotion regulation</span> — giving in to feel good now — that repairs mood in the present and worsens it in the future. This is why discipline alone helps little: the problem is not time, it is discomfort.</p>` },
      { h: "What actually works", html: `<p>If the root is emotional, the remedy is not more willpower but less discomfort at the start. It helps to make the first step tiny, to limit the time ("just five minutes"), to remove temptations from the field rather than resisting them. And, counter-intuitively, self-compassion helps: studies show that forgiving yourself for a bout of procrastination lowers the chance of repeating it, because it removes the very discomfort that drives you to put things off again. Being harsh with yourself, by contrast, feeds the cycle.</p>` }
    ],
    beyond: `<ul>
      <li><b>The well-being spiral.</b> Chronic procrastination is tied to more stress, worse health and delayed care: those who put things off tend to put off the doctor too. The cost goes beyond missed deadlines.</li>
      <li><b>Not all delays are equal.</b> Steel distinguishes putting off out of impulsiveness from those who say they "work better under pressure": the latter, in the data, is more often a rationalisation than a genuinely effective strategy.</li>
      <li><b>The three forms in doubt.</b> People spoke of "arousal", "avoidant" and "decisional" procrastinators; the 2010 study behind this scale found little evidence for the arousal type.</li>
      <li><b>Perfectionism.</b> The fear of not doing a perfect job is a direct route to procrastination: if the only acceptable outcome is flawless, not starting protects you from imperfection.</li>
    </ul>`,
    taratura: `<p>The IPS measures a single, coherent core of procrastination well, with good reliability, and is built to capture the "pure", irrational part rather than sensible postponements. The limits of any self-report remain: procrastination is socially undesirable, and some underestimate it while others, feeling guilty, overestimate it. The score bands here are orientative, drawn mostly from student and Western samples; the line between a strategic delay and a self-defeating one, moreover, you know better than the scale does.</p>`,
    reading: [
      "Steel, P. (2007). The nature of procrastination: a meta-analytic and theoretical review. <em>Psychological Bulletin</em>, 133, 65-94.",
      "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? <em>Personality and Individual Differences</em>, 48, 926-934.",
      "Sirois, F. & Pychyl, T. (2013). Procrastination and the priority of short-term mood regulation. <em>Social and Personality Psychology Compass</em>, 7, 115-127."
    ]
  },
  pt: {
    title: "A procrastinação, em profundidade",
    intro: `<p>O fenômeno é antigo: os gregos o chamavam de <span class="t" data-tip="Akrasia: agir contra o próprio juízo melhor mesmo sabendo o que seria melhor fazer. Sócrates e Aristóteles já discutiam isso.">akrasia</span>, a fraqueza da vontade, fazer o contrário do que sabemos ser melhor. Na psicologia quem o põe em foco é <span class="t" data-tip="Piers Steel, psicólogo canadense; sua meta-análise de 2007 sobre centenas de estudos é a referência no tema, junto com a teoria que dela derivou.">Piers Steel</span>, com uma meta-análise (2007) e com esta escala. A definição técnica é precisa: a procrastinação é um <span class="t" data-tip="O atraso é escolhido livremente e a pessoa espera ficar pior por tê-lo escolhido. É isso que a distingue de um adiamento sábio ou inevitável.">atraso voluntário e contraproducente</span> — adiar algo que você pretendia fazer, mesmo esperando sair perdendo. Nem todo adiamento é isso: adiar com critério é sabedoria, não procrastinação.</p>`,
    blocks: [
      { h: "Não é preguiça", html: `<p>O mal-entendido mais enraizado é confundi-la com a <span class="t" data-tip="O preguiçoso não quer agir e não sofre com isso. O procrastinador quer agir, sabe que deveria, e justamente por isso passa mal enquanto não o faz.">preguiça</span>. São opostas na experiência: o preguiçoso está em paz com o seu não fazer, o procrastinador não. Quer fazer, sabe que deveria, prometeu a si mesmo começar — e não começa, com um peso que o preguiçoso não conhece. A procrastinação é um conflito interno, não uma ausência de motivação: é justamente o abismo entre intenção e ação que a define.</p>` },
      { h: "A equação da procrastinação", html: `<p>Steel resumiu as causas numa fórmula, a <span class="t" data-tip="Temporal Motivation Theory: a motivação para fazer uma tarefa cresce com a expectativa de conseguir e com o quanto se gosta da recompensa, e cai com a impulsividade e com o quão distante ela está no tempo.">teoria da motivação temporal</span>. A vontade de fazer uma coisa aumenta se você espera conseguir e se o resultado lhe interessa, e diminui com a <span class="t" data-tip="A tendência a se deixar levar pelo impulso do momento e a preferir a recompensa imediata. É o traço mais ligado à procrastinação.">impulsividade</span> e com a distância no tempo da recompensa. É por isso que você adia o prazo distante e só se ativa no fim: à medida que o prazo se aproxima, o valor da tarefa no presente sobe até superar a tentação. Quem mais procrastina é muitas vezes quem <span class="t" data-tip="Desconto temporal: a tendência a desvalorizar fortemente as recompensas futuras em relação às imediatas. Quanto mais íngreme, menos o futuro pesa hoje.">desvaloriza o futuro</span> de forma mais acentuada.</p>` },
      { h: "O verdadeiro motor: as emoções", html: `<p>A virada mais recente desloca o acento do tempo para as emoções. Segundo <span class="t" data-tip="Fuschia Sirois e Timothy Pychyl (2013): a procrastinação não é um problema de gestão do tempo mas de regulação das emoções. Adia-se para não sentir o desconforto da tarefa.">Sirois e Pychyl</span>, você não adia a tarefa: adia a <em>emoção</em> que a tarefa lhe provoca — tédio, ansiedade, frustração, medo de não estar à altura. Procrastinar é uma forma de <span class="t" data-tip="Regulação das emoções: as estratégias com que lidamos com o que sentimos. Procrastinar é uma de curto alcance: faz você ficar melhor agora e pior depois.">regulação das emoções</span> de curto alcance — ceder para ficar bem já — que conserta o humor no presente e o piora no futuro. É por isso que a disciplina sozinha ajuda pouco: o problema não é o tempo, é o desconforto.</p>` },
      { h: "O que realmente funciona", html: `<p>Se a raiz é emocional, a cura não é mais força de vontade mas menos desconforto no início. Funciona tornar o primeiro passo pequenininho, limitar o tempo («só cinco minutos»), tirar as tentações do campo em vez de resisti-las. E funciona, contraintuitivamente, a autocompaixão: os estudos mostram que se perdoar por uma procrastinação reduz a probabilidade de repeti-la, porque tira justamente aquele desconforto que empurra a adiar de novo. Tratar-se com dureza, ao contrário, alimenta o ciclo.</p>` }
    ],
    beyond: `<ul>
      <li><b>A espiral do bem-estar.</b> A procrastinação crônica se liga a mais estresse, pior saúde e atrasos nos cuidados: quem adia tende a adiar também a ida ao médico. O custo vai além dos prazos perdidos.</li>
      <li><b>Nem todo adiamento é igual.</b> Steel distingue o adiar por impulsividade de quem diz «trabalhar melhor sob pressão»: este último, nos dados, é mais frequentemente uma racionalização do que uma estratégia de fato eficaz.</li>
      <li><b>As três formas em dúvida.</b> Falava-se de procrastinadores «por excitação», «evitativos» e «decisionais»; o estudo de 2010 na base desta escala encontrou poucas provas do tipo por excitação.</li>
      <li><b>Perfeccionismo.</b> O medo de não fazer um trabalho perfeito é uma via direta para a procrastinação: se o único resultado aceitável é impecável, não começar protege da imperfeição.</li>
    </ul>`,
    taratura: `<p>A IPS mede bem um núcleo único e coerente de procrastinação, com boa confiabilidade, e é construída para captar a parte «pura», irracional, mais do que os adiamentos sensatos. Restam os limites de todo autorrelato: a procrastinação é socialmente pouco desejável, e há quem a subestime e quem, sentindo-se culpado, a superestime. As faixas de escore aqui são orientativas, derivadas sobretudo de amostras estudantis e ocidentais; a fronteira entre um adiamento estratégico e um contraproducente, aliás, você conhece melhor do que a escala.</p>`,
    reading: [
      "Steel, P. (2007). The nature of procrastination: a meta-analytic and theoretical review. <em>Psychological Bulletin</em>, 133, 65-94.",
      "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? <em>Personality and Individual Differences</em>, 48, 926-934.",
      "Sirois, F. & Pychyl, T. (2013). Procrastination and the priority of short-term mood regulation. <em>Social and Personality Psychology Compass</em>, 7, 115-127."
    ]
  }
};
