/* Irrational Procrastination Scale, IPS (Steel 2010) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.ips = {
  code: "IPS", theme: "plum", n: 9, reverse: [2, 6, 9],
  labels: { en: ["Very seldom or not true of me", "Seldom true of me", "Sometimes true of me", "Often true of me", "Very often true, or true of me"], it: ["Molto raramente o mai vero per me", "Raramente vero", "A volte vero", "Spesso vero", "Molto spesso o sempre vero per me"] },
  items: {
    en: ["I put things off so long that my well-being or efficiency unnecessarily suffers.", "If there is something I should do, I get to it before attending to lesser tasks.", "My life would be better if I did some activities or tasks earlier.", "When I should be doing one thing, I will do another.", "At the end of the day, I know I could have spent the time better.", "I spend my time wisely.", "I delay tasks beyond what is reasonable.", "I procrastinate.", "I do everything when I believe it needs to be done."],
    it: ["Rimando le cose così a lungo che il mio benessere o la mia efficienza ne soffrono inutilmente.", "Se c'è qualcosa che dovrei fare, la faccio prima di dedicarmi a compiti meno importanti.", "La mia vita sarebbe migliore se facessi alcune attività o compiti prima.", "Quando dovrei fare una cosa, ne faccio un'altra.", "A fine giornata so che avrei potuto usare meglio il tempo.", "Uso il mio tempo con saggezza.", "Rimando i compiti oltre il ragionevole.", "Procrastino.", "Faccio tutto quando credo che vada fatto."]
  },
  text: {
    it: { kicker: "Procrastinazione", title: "Quanto rimandi?", lede: "9 affermazioni, 1 minuto. L'IPS di Piers Steel misura la procrastinazione «irrazionale»: rimandare pur sapendo che ci si rimette.", meta: ["9 domande", "~1 minuto"], instr: "Per ogni frase indica quanto è vera per te, pensando a come ti comporti <b>di solito</b>.", how: "Il punteggio va da 9 a 45 (3 affermazioni sono invertite). La media negli adulti è intorno a 27; sopra 33 circa sei tra il quarto di persone che rimanda di più, sotto 21 tra chi rimanda meno. La procrastinazione cronica è legata più alla regolazione delle emozioni (evitare il disagio del compito) che alla gestione del tempo.", cite: "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? Personality and Individual Differences, 48, 926-934. Uso libero; traduzione italiana propria." },
    en: { kicker: "Procrastination", title: "How much do you put things off?", lede: "9 statements, 1 minute. Piers Steel's IPS measures “irrational” procrastination: delaying while knowing you will be worse off.", meta: ["9 questions", "~1 minute"], instr: "For each statement, indicate how true it is of you, thinking about how you <b>usually</b> behave.", how: "The score runs from 9 to 45 (3 statements are reverse-keyed). The adult mean is around 27; above about 33 you are in the quarter of people who procrastinate most, below 21 among those who procrastinate least. Chronic procrastination is tied more to emotion regulation (avoiding the discomfort of the task) than to time management.", cite: "Steel, P. (2010). Arousal, avoidant and decisional procrastinators: do they exist? Personality and Individual Differences, 48, 926-934. Free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Procrastinazione", en: "Procrastination" }, items: [1,2,3,4,5,6,7,8,9], mode: "sum", range: [9, 45],
    bands: [
      { max: 20, name: { it: "Bassa", en: "Low" }, text: { it: "Fai le cose quando vanno fatte: rimandare non è un tuo problema.", en: "You do things when they need doing: putting off is not your problem." } },
      { max: 33, name: { it: "Nella media", en: "Average" }, text: { it: "Rimandi come la maggior parte delle persone: qualche compito scivola, ma il grosso arriva in tempo.", en: "You put things off like most people: some tasks slip, but the bulk gets done on time." } },
      { max: 45, name: { it: "Alta", en: "High" }, text: { it: "Tra chi rimanda di più: il rinvio ti costa in benessere e risultati. Funziona meglio ridurre il disagio del primo passo (compiti piccoli, tempo limitato) che cercare più disciplina.", en: "Among those who procrastinate most: delay costs you in well-being and results. Reducing the discomfort of the first step (small tasks, limited time) works better than seeking more discipline." } }
    ] }]
};
