/* Mindful Attention Awareness Scale, MAAS (Brown & Ryan 2003) — libero per ricerca e uso non commerciale. IT: Veneziani & Voci (2015); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.maas = {
  code: "MAAS", theme: "teal", n: 15, sexNorms: false,
  norms: { tot: { all: { m: 4.20, sd: 0.69 } } },
  labels: {
    en: ["Almost always", "Very frequently", "Somewhat frequently", "Somewhat infrequently", "Very infrequently", "Almost never"],
    it: ["Quasi sempre", "Molto spesso", "Abbastanza spesso", "Abbastanza raramente", "Molto raramente", "Quasi mai"]
  },
  items: {
    en: ["I could be experiencing some emotion and not be conscious of it until some time later.", "I break or spill things because of carelessness, not paying attention, or thinking of something else.", "I find it difficult to stay focused on what's happening in the present.", "I tend to walk quickly to get where I'm going without paying attention to what I experience along the way.", "I tend not to notice feelings of physical tension or discomfort until they really grab my attention.", "I forget a person's name almost as soon as I've been told it for the first time.", "It seems I am “running on automatic,” without much awareness of what I'm doing.", "I rush through activities without being really attentive to them.", "I get so focused on the goal I want to achieve that I lose touch with what I'm doing right now to get there.", "I do jobs or tasks automatically, without being aware of what I'm doing.", "I find myself listening to someone with one ear, doing something else at the same time.", "I drive places on “automatic pilot” and then wonder why I went there.", "I find myself preoccupied with the future or the past.", "I find myself doing things without paying attention.", "I snack without being aware that I'm eating."],
    it: ["Potrei provare un'emozione e non esserne consapevole se non qualche tempo dopo.", "Rompo o rovescio le cose per distrazione, perché non presto attenzione o penso ad altro.", "Trovo difficile restare concentrato su quello che sta succedendo nel presente.", "Tendo a camminare in fretta per arrivare dove devo andare, senza fare caso a quello che vivo lungo la strada.", "Tendo a non accorgermi di sensazioni di tensione fisica o di disagio finché non catturano davvero la mia attenzione.", "Dimentico il nome di una persona quasi subito dopo che me l'hanno detto per la prima volta.", "Mi sembra di andare «col pilota automatico», senza molta consapevolezza di quello che faccio.", "Faccio le attività di corsa, senza esserci davvero attento.", "Mi concentro così tanto sull'obiettivo che voglio raggiungere da perdere il contatto con quello che sto facendo ora per arrivarci.", "Svolgo lavori o compiti in automatico, senza essere consapevole di quello che faccio.", "Mi capita di ascoltare qualcuno con un orecchio solo, facendo altro nello stesso momento.", "Guido fino a un posto «col pilota automatico» e poi mi chiedo perché ci sono andato.", "Mi ritrovo preoccupato per il futuro o per il passato.", "Mi ritrovo a fare le cose senza prestare attenzione.", "Faccio spuntini senza essere consapevole di stare mangiando."]
  },
  text: {
    it: { kicker: "Presenza mentale", title: "Quanto vivi col pilota automatico?", lede: "15 affermazioni, 2 minuti. La MAAS di Brown e Ryan misura la presenza mentale nella vita di tutti i giorni: quanto sei attento a quello che fai mentre lo fai.", meta: ["15 domande", "~2 minuti"], instr: "Per ogni frase indica <b>quanto spesso ti capita</b>, pensando alla tua esperienza reale, non a come vorresti essere.", how: "Il punteggio è la media delle 15 risposte, da 1 a 6; più è alto, più sei presente (tutte le frasi descrivono distrazione, quindi «quasi mai» vale di più). Negli adulti la media è intorno a 4,2, tra gli studenti 3,8. È una misura di tratto, ma cresce con la pratica di mindfulness.", cite: "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84, 822-848. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Mindful attention", title: "How much do you live on autopilot?", lede: "15 statements, 2 minutes. Brown and Ryan's MAAS measures mindful attention in everyday life: how present you are to what you do while you do it.", meta: ["15 questions", "~2 minutes"], instr: "For each statement, indicate <b>how often it happens to you</b>, thinking about your actual experience, not how you would like to be.", how: "The score is the mean of the 15 answers, from 1 to 6; the higher, the more present (all statements describe inattention, so “almost never” counts more). The adult mean is around 4.2, students 3.8. It is a trait measure, but it grows with mindfulness practice.", cite: "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84, 822-848. Free for non-commercial use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Presenza mentale", en: "Mindful attention" }, items: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], mode: "mean", range: [1, 6],
    bands: [
      { max: 3.5, name: { it: "Bassa", en: "Low" }, text: { it: "Molto pilota automatico: le giornate scorrono senza che tu ci sia davvero. È il terreno su cui la mindfulness dà i risultati più visibili.", en: "A lot of autopilot: days go by without you really being there. This is where mindfulness practice shows the most visible results." } },
      { max: 4.6, name: { it: "Nella media", en: "Average" }, text: { it: "Presente quanto la maggior parte degli adulti: attento quando conta, in automatico nella routine.", en: "As present as most adults: attentive when it counts, on autopilot in routine." } },
      { max: 6, name: { it: "Alta", en: "High" }, text: { it: "Sei nel presente più della maggior parte delle persone: senti quello che fai mentre lo fai.", en: "You are in the present more than most people: you notice what you do while you do it." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.maas.approf = {
  it: {
    title: "La presenza mentale, in profondità",
    intro: `<p>La <span class="t" data-tip="Attenzione non giudicante a quello che accade nel momento presente. Il termine traduce il pali sati; in psicologia entra soprattutto attraverso i programmi clinici degli anni Ottanta.">mindfulness</span> entra in psicologia con <span class="t" data-tip="Jon Kabat-Zinn, biologo molecolare, nel 1979 crea alla University of Massachusetts il primo protocollo laico di otto settimane per pazienti con dolore cronico e stress.">Kabat-Zinn</span> e il suo protocollo di riduzione dello stress, la <span class="t" data-tip="Mindfulness-Based Stress Reduction: corso di otto settimane con meditazione formale e pratiche quotidiane, oggi il programma mindfulness più studiato.">MBSR</span>. Ma come misuri, in una persona qualsiasi, quanta presenza mentale porta nella giornata? Nel 2003 <span class="t" data-tip="Kirk Warren Brown e Richard Ryan, psicologi statunitensi; Ryan è anche uno dei due padri della teoria dell'autodeterminazione.">Brown e Ryan</span> scelgono una via minimale: non misurare la meditazione, ma la sua controfigura quotidiana, il <span class="t" data-tip="Fare le cose senza esserci: guidare e non ricordare il tragitto, mangiare senza accorgersene. La MAAS conta quanto spesso capita.">pilota automatico</span>. La MAAS è un <span class="t" data-tip="Un solo punteggio, un solo fattore: tutte le 15 frasi misurano la stessa cosa, la frequenza della disattenzione.">fattore unico</span> di 15 frasi, tutte di segno negativo, che poi vengono ribaltate: meno pilota automatico dichiari, più alto è il punteggio.</p>`,
    blocks: [
      { h: "Attenzione e consapevolezza, non accettazione", html: `<p>La scelta di Brown e Ryan è deliberatamente stretta: la MAAS misura <b>attenzione e consapevolezza</b> del presente, cioè l'esserci, e non l'atteggiamento con cui ci stai — l'accettazione, il non giudizio, la gentilezza. Per gli autori la presenza viene prima: non puoi lavorare su un'emozione che non hai nemmeno notato. È una scelta che ha un prezzo, ed è la principale critica alla scala (vedi la <span class="t" data-tip="Il FFMQ scompone la mindfulness in cinque abilità distinte: osservare, descrivere, agire con consapevolezza, non giudicare, non reagire. Nasce anche per superare l'unidimensionalità della MAAS.">FFMQ</span>): misura soprattutto l'<em>assenza</em> di presenza, non tutte le sfaccettature di ciò che chiamiamo mindfulness.</p>` },
      { h: "La mente che vaga", html: `<p>Il pilota automatico ha un correlato nel cervello: la <span class="t" data-tip="Default mode network: l'insieme di aree che si attivano quando non siamo concentrati su un compito e la mente vaga tra ricordi, progetti e pensieri su di sé.">rete di default</span>, attiva quando la mente si stacca dal compito e parte a vagare. Uno studio con migliaia di rilevazioni sullo smartphone — <span class="t" data-tip="Matthew Killingsworth e Daniel Gilbert (2010): interpellando le persone a caso durante la giornata, trovarono che la mente vagava quasi la metà del tempo e che, quando vagava, l'umore era peggiore.">Killingsworth e Gilbert</span> — ha trovato che la mente umana vaga quasi metà del tempo, e che nei momenti di vagabondaggio l'umore tende a essere più basso, qualunque cosa si stia facendo. La MAAS coglie proprio la frequenza di questo scollamento.</p>` },
      { h: "Il ponte con l'autodeterminazione", html: `<p>Non è un caso che uno degli autori sia Richard Ryan, co-fondatore della <span class="t" data-tip="Teoria dell'autodeterminazione di Deci e Ryan: distingue le azioni che sentiamo nostre (autonome) da quelle che facciamo per pressione. Ne dipendono motivazione e benessere.">teoria dell'autodeterminazione</span>. Il legame è preciso: per agire in modo <span class="t" data-tip="Un comportamento è autonomo quando lo riconosciamo come nostro, non imposto dall'esterno o dall'ansia. È il cuore del benessere secondo Deci e Ryan.">autonomo</span> devi prima vedere da dove parte l'azione — l'impulso, l'abitudine, la pressione. Chi ha punteggi MAAS alti tende a comportarsi in modo più coerente con i propri valori e a reagire meno per automatismo. La presenza, in questa lettura, non è rilassamento: è la condizione per scegliere invece di limitarsi a reagire.</p>` },
      { h: "Tratto, ma allenabile", html: `<p>La MAAS nasce come misura di <span class="t" data-tip="Una tendenza relativamente stabile, che varia da persona a persona come un tratto di personalità, non un umore del momento.">tratto</span>: alcuni sono più presenti di natura, altri più distratti. Ma il tratto non è fisso — esiste anche una versione <span class="t" data-tip="La MAAS-state, che chiede quanto sei presente proprio adesso invece che in generale, usata per misurare l'effetto immediato di una pratica.">di stato</span>, e i punteggi salgono con le otto settimane di MBSR e con la pratica continuata. È uno dei motivi per cui è così usata negli studi clinici: dà un numero prima e dopo.</p>` }
    ],
    beyond: `<ul>
      <li><b>Il paradosso dell'autovalutazione.</b> Chiedere a qualcuno quanto è disattento ha un limite logico: chi è meno presente potrebbe essere anche meno capace di accorgersene. È un rischio noto delle misure self-report della mindfulness.</li>
      <li><b>Vagare non è sempre un male.</b> La mente che si stacca serve a pianificare, ricordare, immaginare: la creatività ne dipende. La MAAS misura la disattenzione involontaria nel quotidiano, non la riflessione utile.</li>
      <li><b>Presenza e benessere.</b> Punteggi alti si accompagnano a meno ruminazione, meno ansia e umore migliore; è una delle correlazioni più replicate, anche se resta correlazione.</li>
      <li><b>Non è svuotare la mente.</b> L'immagine popolare della mindfulness come assenza di pensieri è fuorviante: la MAAS misura quanto noti dove sei, non quanto silenzio hai in testa.</li>
    </ul>`,
    taratura: `<p>La MAAS è solida come misura di ciò che dichiara di misurare: un solo fattore, coerenza interna alta (attorno a .80-.87 negli studi) e correlazioni prevedibili con benessere e regolazione emotiva. Il limite è nel disegno, non nell'esecuzione: coprendo una sola sfaccettatura — l'attenzione al presente, per lo più in negativo — dice poco su accettazione e non giudizio, ed è questo che ha spinto verso scale multidimensionali come la FFMQ. Aggiungi il problema di ogni self-report sulla propria disattenzione e capisci perché il punteggio va letto come un indizio, non come una fotografia esatta della tua presenza mentale.</p>`,
    reading: [
      "Brown, K. W. & Ryan, R. M. (2003). The benefits of being present. <em>Journal of Personality and Social Psychology</em>, 84, 822-848.",
      "Kabat-Zinn, J., <em>Vivere momento per momento</em> (Full Catastrophe Living, 1990). Il testo che porta la mindfulness in clinica.",
      "Killingsworth, M. A. & Gilbert, D. T. (2010). A wandering mind is an unhappy mind. <em>Science</em>, 330, 932."
    ]
  },
  en: {
    title: "Mindful attention, in depth",
    intro: `<p><span class="t" data-tip="Non-judgemental attention to what is happening in the present moment. The word translates the Pali sati; it enters psychology mainly through the clinical programmes of the 1980s.">Mindfulness</span> enters psychology with <span class="t" data-tip="Jon Kabat-Zinn, molecular biologist, created in 1979 at the University of Massachusetts the first secular eight-week programme for patients with chronic pain and stress.">Kabat-Zinn</span> and his stress-reduction programme, <span class="t" data-tip="Mindfulness-Based Stress Reduction: an eight-week course of formal meditation and daily practice, today the most studied mindfulness programme.">MBSR</span>. But how do you measure, in an ordinary person, how much presence they bring to the day? In 2003 <span class="t" data-tip="Kirk Warren Brown and Richard Ryan, US psychologists; Ryan is also one of the two founders of self-determination theory.">Brown and Ryan</span> chose a minimal route: not to measure meditation, but its everyday shadow, the <span class="t" data-tip="Doing things without being there: driving and not recalling the route, eating without noticing. The MAAS counts how often it happens.">autopilot</span>. The MAAS is a <span class="t" data-tip="One score, one factor: all 15 statements measure the same thing, the frequency of inattention.">single factor</span> of 15 statements, all negatively worded and then reversed: the less autopilot you report, the higher the score.</p>`,
    blocks: [
      { h: "Attention and awareness, not acceptance", html: `<p>Brown and Ryan's choice is deliberately narrow: the MAAS measures <b>attention and awareness</b> of the present — being there — not the attitude you bring to it: acceptance, non-judgement, kindness. For the authors presence comes first: you cannot work on an emotion you have not even noticed. The choice has a price, and it is the main criticism of the scale (see the <span class="t" data-tip="The FFMQ breaks mindfulness into five distinct skills: observing, describing, acting with awareness, nonjudging, nonreacting. It was built partly to move past the MAAS single dimension.">FFMQ</span>): it measures mostly the <em>absence</em> of presence, not every facet of what we call mindfulness.</p>` },
      { h: "The wandering mind", html: `<p>Autopilot has a correlate in the brain: the <span class="t" data-tip="Default mode network: the set of areas that switch on when we are not focused on a task and the mind wanders among memories, plans and thoughts about ourselves.">default mode network</span>, active when the mind leaves the task and drifts. A study with thousands of smartphone samples — <span class="t" data-tip="Matthew Killingsworth and Daniel Gilbert (2010): pinging people at random through the day, they found the mind wandered almost half the time and that, when it wandered, mood was worse.">Killingsworth and Gilbert</span> — found the human mind wanders almost half the time, and that in those moments mood tends to be lower, whatever we are doing. The MAAS captures the frequency of this disconnection.</p>` },
      { h: "The bridge to self-determination", html: `<p>It is no accident that one author is Richard Ryan, co-founder of <span class="t" data-tip="Deci and Ryan's self-determination theory: it distinguishes actions we feel as our own (autonomous) from those we do under pressure. Motivation and well-being depend on it.">self-determination theory</span>. The link is precise: to act <span class="t" data-tip="A behaviour is autonomous when we recognise it as ours, not imposed from outside or by anxiety. It is the heart of well-being for Deci and Ryan.">autonomously</span> you first have to see where the action starts — the impulse, the habit, the pressure. People with high MAAS scores tend to behave more consistently with their values and to react less on automatic. Presence, on this reading, is not relaxation: it is the condition for choosing rather than merely reacting.</p>` },
      { h: "A trait, but trainable", html: `<p>The MAAS begins as a <span class="t" data-tip="A relatively stable tendency, varying from person to person like a personality trait, not a passing mood.">trait</span> measure: some people are more present by nature, others more distracted. But the trait is not fixed — there is also a <span class="t" data-tip="The state MAAS, which asks how present you are right now rather than in general, used to measure the immediate effect of a practice.">state version</span>, and scores rise with the eight weeks of MBSR and with continued practice. It is one reason it is so used in clinical studies: it gives a number before and after.</p>` }
    ],
    beyond: `<ul>
      <li><b>The self-report paradox.</b> Asking people how inattentive they are has a logical limit: those who are least present may also be least able to notice it. It is a known risk of self-report mindfulness measures.</li>
      <li><b>Wandering is not always bad.</b> A mind that leaves the task serves planning, memory, imagination: creativity depends on it. The MAAS measures involuntary everyday inattention, not useful reflection.</li>
      <li><b>Presence and well-being.</b> High scores go with less rumination, less anxiety and better mood; it is one of the most replicated correlations, though it stays a correlation.</li>
      <li><b>It is not emptying the mind.</b> The popular image of mindfulness as absence of thoughts is misleading: the MAAS measures how much you notice where you are, not how much silence is in your head.</li>
    </ul>`,
    taratura: `<p>The MAAS is solid as a measure of what it claims to measure: a single factor, high internal consistency (around .80-.87 across studies) and predictable correlations with well-being and emotion regulation. The limit is in the design, not the execution: covering a single facet — present-moment attention, mostly negatively worded — it says little about acceptance and non-judgement, and this is what pushed the field toward multidimensional scales like the FFMQ. Add the problem of any self-report on one's own inattention and you see why the score should be read as a hint, not an exact photograph of your presence of mind.</p>`,
    reading: [
      "Brown, K. W. & Ryan, R. M. (2003). The benefits of being present. <em>Journal of Personality and Social Psychology</em>, 84, 822-848.",
      "Kabat-Zinn, J., <em>Full Catastrophe Living</em> (1990). The book that brought mindfulness into the clinic.",
      "Killingsworth, M. A. & Gilbert, D. T. (2010). A wandering mind is an unhappy mind. <em>Science</em>, 330, 932."
    ]
  },
  pt: {
    title: "A atenção plena, em profundidade",
    intro: `<p>A <span class="t" data-tip="Atenção sem julgamento ao que acontece no momento presente. O termo traduz o pali sati; entra na psicologia sobretudo pelos programas clínicos dos anos 1980.">atenção plena</span> entra na psicologia com <span class="t" data-tip="Jon Kabat-Zinn, biólogo molecular, cria em 1979 na Universidade de Massachusetts o primeiro protocolo laico de oito semanas para pacientes com dor crônica e estresse.">Kabat-Zinn</span> e seu protocolo de redução do estresse, o <span class="t" data-tip="Mindfulness-Based Stress Reduction: curso de oito semanas com meditação formal e práticas diárias, hoje o programa de atenção plena mais estudado.">MBSR</span>. Mas como medir, numa pessoa qualquer, quanta presença ela traz ao dia? Em 2003 <span class="t" data-tip="Kirk Warren Brown e Richard Ryan, psicólogos norte-americanos; Ryan é também um dos dois fundadores da teoria da autodeterminação.">Brown e Ryan</span> escolheram um caminho mínimo: não medir a meditação, mas a sua sombra cotidiana, o <span class="t" data-tip="Fazer as coisas sem estar presente: dirigir e não lembrar o trajeto, comer sem perceber. A MAAS conta com que frequência isso acontece.">piloto automático</span>. A MAAS é um <span class="t" data-tip="Um só escore, um só fator: todas as 15 frases medem a mesma coisa, a frequência da desatenção.">fator único</span> de 15 frases, todas em sentido negativo e depois invertidas: quanto menos piloto automático você relata, mais alto o escore.</p>`,
    blocks: [
      { h: "Atenção e consciência, não aceitação", html: `<p>A escolha de Brown e Ryan é deliberadamente estreita: a MAAS mede <b>atenção e consciência</b> do presente — o estar presente — e não a atitude com que você está ali: a aceitação, o não julgamento, a gentileza. Para os autores a presença vem primeiro: não dá para trabalhar uma emoção que você nem notou. A escolha tem um preço, e é a principal crítica à escala (veja o <span class="t" data-tip="O FFMQ divide a atenção plena em cinco habilidades distintas: observar, descrever, agir com consciência, não julgar, não reagir. Nasce em parte para superar a unidimensionalidade da MAAS.">FFMQ</span>): mede sobretudo a <em>ausência</em> de presença, não todas as facetas do que chamamos de atenção plena.</p>` },
      { h: "A mente que vagueia", html: `<p>O piloto automático tem um correlato no cérebro: a <span class="t" data-tip="Rede de modo padrão: o conjunto de áreas que se ativam quando não estamos concentrados numa tarefa e a mente vagueia entre memórias, planos e pensamentos sobre nós mesmos.">rede de modo padrão</span>, ativa quando a mente se solta da tarefa e sai a vagar. Um estudo com milhares de coletas pelo smartphone — <span class="t" data-tip="Matthew Killingsworth e Daniel Gilbert (2010): abordando as pessoas ao acaso ao longo do dia, descobriram que a mente vagava quase metade do tempo e que, quando vagava, o humor era pior.">Killingsworth e Gilbert</span> — descobriu que a mente humana vagueia quase metade do tempo, e que nesses momentos o humor tende a ser mais baixo, faça o que fizer. A MAAS capta justamente a frequência dessa desconexão.</p>` },
      { h: "A ponte com a autodeterminação", html: `<p>Não é acaso que um dos autores seja Richard Ryan, cofundador da <span class="t" data-tip="Teoria da autodeterminação de Deci e Ryan: distingue as ações que sentimos como nossas (autônomas) daquelas que fazemos por pressão. Delas dependem motivação e bem-estar.">teoria da autodeterminação</span>. O elo é preciso: para agir de forma <span class="t" data-tip="Um comportamento é autônomo quando o reconhecemos como nosso, não imposto de fora ou pela ansiedade. É o coração do bem-estar para Deci e Ryan.">autônoma</span> você precisa antes ver de onde parte a ação — o impulso, o hábito, a pressão. Quem tem escores MAAS altos tende a agir de modo mais coerente com os próprios valores e a reagir menos por automatismo. A presença, nessa leitura, não é relaxamento: é a condição para escolher em vez de apenas reagir.</p>` },
      { h: "Traço, mas treinável", html: `<p>A MAAS nasce como medida de <span class="t" data-tip="Uma tendência relativamente estável, que varia de pessoa para pessoa como um traço de personalidade, não um humor do momento.">traço</span>: alguns são mais presentes por natureza, outros mais distraídos. Mas o traço não é fixo — existe também uma versão <span class="t" data-tip="A MAAS de estado, que pergunta o quanto você está presente agora mesmo em vez de em geral, usada para medir o efeito imediato de uma prática.">de estado</span>, e os escores sobem com as oito semanas de MBSR e com a prática continuada. É um dos motivos por que é tão usada em estudos clínicos: dá um número antes e depois.</p>` }
    ],
    beyond: `<ul>
      <li><b>O paradoxo da autoavaliação.</b> Perguntar a alguém o quanto é desatento tem um limite lógico: quem é menos presente pode ser também menos capaz de perceber. É um risco conhecido das medidas de autorrelato da atenção plena.</li>
      <li><b>Vaguear nem sempre é ruim.</b> A mente que se solta serve para planejar, lembrar, imaginar: a criatividade depende disso. A MAAS mede a desatenção involuntária do cotidiano, não a reflexão útil.</li>
      <li><b>Presença e bem-estar.</b> Escores altos acompanham menos ruminação, menos ansiedade e humor melhor; é uma das correlações mais replicadas, embora continue sendo correlação.</li>
      <li><b>Não é esvaziar a mente.</b> A imagem popular da atenção plena como ausência de pensamentos engana: a MAAS mede o quanto você percebe onde está, não quanto silêncio há na sua cabeça.</li>
    </ul>`,
    taratura: `<p>A MAAS é sólida como medida daquilo que se propõe a medir: um só fator, consistência interna alta (em torno de .80-.87 nos estudos) e correlações previsíveis com bem-estar e regulação emocional. O limite está no desenho, não na execução: cobrindo uma só faceta — a atenção ao presente, quase sempre em negativo — diz pouco sobre aceitação e não julgamento, e foi isso que empurrou o campo para escalas multidimensionais como o FFMQ. Some a isso o problema de todo autorrelato sobre a própria desatenção e se entende por que o escore deve ser lido como um indício, não como uma fotografia exata da sua presença mental.</p>`,
    reading: [
      "Brown, K. W. & Ryan, R. M. (2003). The benefits of being present. <em>Journal of Personality and Social Psychology</em>, 84, 822-848.",
      "Kabat-Zinn, J., <em>Viver a Catástrofe Total</em> (Full Catastrophe Living, 1990). O livro que leva a atenção plena à clínica.",
      "Killingsworth, M. A. & Gilbert, D. T. (2010). A wandering mind is an unhappy mind. <em>Science</em>, 330, 932."
    ]
  }
};
