/* Mindful Attention Awareness Scale, MAAS (Brown & Ryan 2003) — libero per ricerca e uso non commerciale. IT: Veneziani & Voci (2015); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.maas = {
  code: "MAAS", theme: "teal", n: 15, sexNorms: false,
  norms: { tot: { all: { m: 4.20, sd: 0.69 } } },
  labels: {
    en: ["Almost always", "Very frequently", "Somewhat frequently", "Somewhat infrequently", "Very infrequently", "Almost never"],
    it: ["Quasi sempre", "Molto spesso", "Abbastanza spesso", "Abbastanza raramente", "Molto raramente", "Quasi mai"]
  },
  items: {
    en: ["I could be experiencing some emotion and not be conscious of it until some time later.", "I break or spill things because of carelessness, not paying attention, or thinking of something else.", "I find it difficult to stay focused on what's happening in the present.", "I tend to walk quickly to get where I'm going without paying attention to what I experience along the way.", "I tend not to notice feelings of physical tension or discomfort until they really grab my attention.", "I forget a person's name almost as soon as I've been told it for the first time.", "It seems I am “running on automatic,” without much awareness of what I'm doing.", "I rush through activities without being really attentive to them.", "I get so focused on the goal I want to achieve that I lose touch with what I'm doing right now to get there.", "I do jobs or tasks automatically, without being aware of what I'm doing.", "I find myself listening to someone with one ear, doing something else at the same time.", "I drive places on “automatic pilot” and then wonder why I went there.", "I find myself preoccupied with the future or the past.", "I find myself doing things without paying attention.", "I snack without being aware that I'm eating."],
    it: ["Potrei provare un'emozione e non esserne consapevole se non qualche tempo dopo.", "Rompo o rovescio le cose per distrazione, perché non presto attenzione o penso ad altro.", "Trovo difficile restare concentrato su quello che sta succedendo nel presente.", "Tendo a camminare in fretta per arrivare dove devo andare, senza fare caso a quello che vivo lungo la strada.", "Tendo a non accorgermi di sensazioni di tensione fisica o di disagio finché non catturano davvero la mia attenzione.", "Dimentico il nome di una persona quasi subito dopo che me l'hanno detto per la prima volta.", "Mi sembra di andare «col pilota automatico», senza molta consapevolezza di quello che faccio.", "Faccio le attività di corsa, senza esserci davvero attento.", "Mi concentro così tanto sull'obiettivo che voglio raggiungere da perdere il contatto con quello che sto facendo ora per arrivarci.", "Svolgo lavori o compiti in automatico, senza essere consapevole di quello che faccio.", "Mi capita di ascoltare qualcuno con un orecchio solo, facendo altro nello stesso momento.", "Guido fino a un posto «col pilota automatico» e poi mi chiedo perché ci sono andato.", "Mi ritrovo preoccupato per il futuro o per il passato.", "Mi ritrovo a fare le cose senza prestare attenzione.", "Faccio spuntini senza essere consapevole di stare mangiando."]
  },
  text: {
    it: { kicker: "Presenza mentale", title: "Quanto vivi col pilota automatico?", lede: "15 affermazioni, 2 minuti. La MAAS di Brown e Ryan misura la presenza mentale nella vita di tutti i giorni: quanto sei attento a quello che fai mentre lo fai.", meta: ["15 domande", "~2 minuti"], instr: "Per ogni frase indica <b>quanto spesso ti capita</b>, pensando alla tua esperienza reale, non a come vorresti essere.", how: "Il punteggio è la media delle 15 risposte, da 1 a 6; più è alto, più sei presente (tutte le frasi descrivono distrazione, quindi «quasi mai» vale di più). Negli adulti la media è intorno a 4,2, tra gli studenti 3,8. È una misura di tratto, ma cresce con la pratica di mindfulness.", cite: "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84, 822-848. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Mindful attention", title: "How much do you live on autopilot?", lede: "15 statements, 2 minutes. Brown and Ryan's MAAS measures mindful attention in everyday life: how present you are to what you do while you do it.", meta: ["15 questions", "~2 minutes"], instr: "For each statement, indicate <b>how often it happens to you</b>, thinking about your actual experience, not how you would like to be.", how: "The score is the mean of the 15 answers, from 1 to 6; the higher, the more present (all statements describe inattention, so “almost never” counts more). The adult mean is around 4.2, students 3.8. It is a trait measure, but it grows with mindfulness practice.", cite: "Brown, K. W., & Ryan, R. M. (2003). The benefits of being present: mindfulness and its role in psychological well-being. Journal of Personality and Social Psychology, 84, 822-848. Free for non-commercial use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Presenza mentale", en: "Mindful attention" }, items: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], mode: "mean", range: [1, 6],
    bands: [
      { max: 3.5, name: { it: "Bassa", en: "Low" }, text: { it: "Molto pilota automatico: le giornate scorrono senza che tu ci sia davvero. È il terreno su cui la mindfulness dà i risultati più visibili.", en: "A lot of autopilot: days go by without you really being there. This is where mindfulness practice shows the most visible results." } },
      { max: 4.6, name: { it: "Nella media", en: "Average" }, text: { it: "Presente quanto la maggior parte degli adulti: attento quando conta, in automatico nella routine.", en: "As present as most adults: attentive when it counts, on autopilot in routine." } },
      { max: 6, name: { it: "Alta", en: "High" }, text: { it: "Sei nel presente più della maggior parte delle persone: senti quello che fai mentre lo fai.", en: "You are in the present more than most people: you notice what you do while you do it." } }
    ] }]
};
