/* Mini-IPIP (Donnellan, Oswald, Baird & Lucas 2006) — 20 item Big Five, pubblico dominio (International Personality Item Pool). IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.miniipip = {
  code: "Mini-IPIP", theme: "plum", n: 20, reverse: [6, 7, 8, 9, 10, 15, 16, 17, 18, 19, 20],
  labels: {
    en: ["Very inaccurate", "Moderately inaccurate", "Neither accurate nor inaccurate", "Moderately accurate", "Very accurate"],
    it: ["Per niente vero per me", "Poco vero", "Né vero né falso", "Abbastanza vero", "Molto vero per me"]
  },
  items: {
    en: ["I am the life of the party.", "I sympathize with others' feelings.", "I get chores done right away.", "I have frequent mood swings.", "I have a vivid imagination.", "I don't talk a lot.", "I am not interested in other people's problems.", "I often forget to put things back in their proper place.", "I am relaxed most of the time.", "I am not interested in abstract ideas.", "I talk to a lot of different people at parties.", "I feel others' emotions.", "I like order.", "I get upset easily.", "I have difficulty understanding abstract ideas.", "I keep in the background.", "I am not really interested in others.", "I make a mess of things.", "I seldom feel blue.", "I do not have a good imagination."],
    it: ["Sono l'anima della festa.", "Partecipo ai sentimenti degli altri.", "Sbrigo subito le faccende.", "Ho frequenti sbalzi d'umore.", "Ho un'immaginazione vivida.", "Non parlo molto.", "Non mi interessano i problemi degli altri.", "Spesso dimentico di rimettere le cose al loro posto.", "Sono rilassato la maggior parte del tempo.", "Non mi interessano le idee astratte.", "Alle feste parlo con molte persone diverse.", "Sento le emozioni degli altri.", "Mi piace l'ordine.", "Mi turbo facilmente.", "Faccio fatica a capire le idee astratte.", "Me ne sto in disparte.", "Non mi interessano davvero gli altri.", "Combino pasticci.", "Raramente mi sento giù.", "Non ho una buona immaginazione."]
  },
  text: {
    it: { kicker: "Big Five", title: "Che personalità hai?", lede: "20 affermazioni, 3 minuti. I cinque grandi tratti della personalità (estroversione, amicalità, coscienziosità, nevroticismo, apertura) con la scala Mini-IPIP, di pubblico dominio.", meta: ["20 domande", "~3 minuti", "5 tratti"], instr: "Per ogni frase indica <b>quanto ti descrive</b> come sei in generale, oggi, non come vorresti essere. Rispondi d'istinto.", how: "Cinque punteggi da 4 a 20, uno per tratto; 11 affermazioni sono invertite. Il punto medio è 12: sopra sei più del tipico verso quel tratto, sotto meno. I tratti non sono buoni o cattivi: descrivono tendenze, e ognuno ha vantaggi in contesti diversi. Con 4 domande per tratto la misura è affidabile ma grossolana; il questionario completo (IPIP-NEO) è molto più fine.", cite: "Donnellan, M. B., Oswald, F. L., Baird, B. M., & Lucas, R. E. (2006). The Mini-IPIP scales. Psychological Assessment, 18, 192-203. Item di pubblico dominio (ipip.ori.org); traduzione italiana propria, non validata." },
    en: { kicker: "Big Five", title: "What is your personality like?", lede: "20 statements, 3 minutes. The five big personality traits (extraversion, agreeableness, conscientiousness, neuroticism, openness) with the public-domain Mini-IPIP scale.", meta: ["20 questions", "~3 minutes", "5 traits"], instr: "For each statement, indicate <b>how well it describes you</b> as you generally are now, not as you wish to be. Answer instinctively.", how: "Five scores from 4 to 20, one per trait; 11 statements are reverse-keyed. The midpoint is 12: above it you lean more than typical towards that trait, below it less. Traits are not good or bad: they describe tendencies, each with advantages in different contexts. With 4 questions per trait the measure is reliable but coarse; the full IPIP-NEO is much finer.", cite: "Donnellan, M. B., Oswald, F. L., Baird, B. M., & Lucas, R. E. (2006). The Mini-IPIP scales. Psychological Assessment, 18, 192-203. Public-domain items (ipip.ori.org)." }
  },
  scales: [
    { key: "e", name: { it: "Estroversione", en: "Extraversion" }, items: [1, 6, 11, 16], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Riservato: ricarichi da solo, preferisci pochi legami profondi alla folla.", en: "Reserved: you recharge alone and prefer a few deep ties to a crowd." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Né timido né esuberante: socievole quando serve, tranquillo quando puoi.", en: "Neither shy nor exuberant: sociable when needed, quiet when you can be." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Espansivo: cerchi le persone, le feste, la parola. L'energia ti viene dagli altri.", en: "Outgoing: you seek people, parties and conversation. Your energy comes from others." } }] },
    { key: "a", name: { it: "Amicalità", en: "Agreeableness" }, items: [2, 7, 12, 17], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Diretto e competitivo: metti la sostanza prima della diplomazia.", en: "Direct and competitive: substance before diplomacy." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Empatico quanto basta, senza farti mettere i piedi in testa.", en: "Empathetic enough, without being walked over." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Caldo e fiducioso: senti gli altri e tendi ad aiutarli. Attento a non dimenticare te.", en: "Warm and trusting: you feel others and tend to help them. Careful not to forget yourself." } }] },
    { key: "c", name: { it: "Coscienziosità", en: "Conscientiousness" }, items: [3, 8, 13, 18], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Flessibile e spontaneo: l'ordine e le scadenze non sono il tuo forte, l'improvvisazione sì.", en: "Flexible and spontaneous: order and deadlines are not your strength, improvising is." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Organizzato quando conta, rilassato quando puoi.", en: "Organised when it counts, relaxed when you can be." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Metodico e affidabile: fai le cose subito e bene. Il rischio è il perfezionismo.", en: "Methodical and reliable: you do things promptly and well. The risk is perfectionism." } }] },
    { key: "n", name: { it: "Nevroticismo", en: "Neuroticism" }, items: [4, 9, 14, 19], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Basso", en: "Low" }, text: { it: "Stabile: le emozioni negative arrivano e passano senza travolgerti.", en: "Stable: negative emotions come and go without overwhelming you." } },
      { max: 14, name: { it: "Medio", en: "Average" }, text: { it: "Reattivo nella norma: qualche sbalzo, ma torni in equilibrio.", en: "Normally reactive: some swings, but you regain balance." } },
      { max: 20, name: { it: "Alto", en: "High" }, text: { it: "Sensibile allo stress: umore mutevole, preoccupazioni facili. Non è un difetto, ma chiede cura di sé.", en: "Stress-sensitive: changeable mood, quick to worry. Not a flaw, but it calls for self-care." } }] },
    { key: "o", name: { it: "Apertura / Intelletto", en: "Openness / Intellect" }, items: [5, 10, 15, 20], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Concreto e pratico: preferisci il tangibile alle idee astratte.", en: "Concrete and practical: you prefer the tangible to abstract ideas." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Curioso quanto basta, con i piedi per terra.", en: "Curious enough, with feet on the ground." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Immaginativo e attratto dalle idee: arte, teorie, novità.", en: "Imaginative and drawn to ideas: art, theories, novelty." } }] }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.miniipip.approf = {
  it: {
    title: "I Big Five, in breve",
    intro: `<p>Il Mini-IPIP misura i <span class="t" data-tip="I cinque tratti su cui la psicologia della personalità ha trovato ampio accordo: apertura, coscienziosità, estroversione, amicalità, nevroticismo. In inglese l'acronimo è OCEAN.">Big Five</span>, il modello di personalità più solido che abbiamo. Non nasce da una teoria calata dall'alto ma dall'<span class="t" data-tip="Ipotesi lessicale: se una differenza tra persone conta davvero, prima o poi la lingua le ha dato una parola. Studiando gli aggettivi di personalità si può quindi ricostruire la mappa dei tratti.">ipotesi lessicale</span>: <span class="t" data-tip="Gordon Allport e Henry Odbert nel 1936 contarono circa 18.000 termini di personalità nel dizionario inglese, il punto di partenza dell'approccio lessicale.">Allport</span> contò migliaia di aggettivi, e decenni di <span class="t" data-tip="Analisi fattoriale: tecnica statistica che raggruppa molte variabili correlate in poche dimensioni di fondo. Applicata agli aggettivi di personalità, fa emergere ripetutamente cinque grandi fattori.">analisi fattoriale</span> li hanno ridotti a cinque fattori. Le venti frasi di questo test vengono dall'<span class="t" data-tip="International Personality Item Pool: banca di item di personalità di pubblico dominio creata da Lewis Goldberg, alternativa libera ai questionari commerciali.">IPIP</span> di Goldberg, nella versione breve messa a punto da <span class="t" data-tip="Donnellan, Oswald, Baird e Lucas (2006): condensarono i Big Five in venti item, quattro per tratto, mantenendo buone proprietà psicometriche.">Donnellan e colleghi</span> nel 2006.</p>`,
    blocks: [
      { h: "Cinque assi, non cinque tipi", html: `<p>I cinque tratti sono <b>dimensioni continue</b>, non caselle: quasi tutti stanno nel mezzo, pochi agli estremi. L'<b>estroversione</b> è quanta energia trai dagli altri; l'<b>amicalità</b> quanto sei caldo e cooperativo; la <b>coscienziosità</b> quanto sei ordinato e affidabile; il <span class="t" data-tip="Nevroticismo: la tendenza a provare emozioni negative (ansia, tristezza, irritabilità) con facilità e intensità. Il suo opposto è la stabilità emotiva.">nevroticismo</span> quanto facilmente provi emozioni negative; l'<span class="t" data-tip="Apertura all'esperienza (o apertura/intelletto): curiosità intellettuale, immaginazione, gusto per le idee e la novità. È il fattore più dibattuto dei cinque.">apertura</span> quanto sei attratto da idee, arte e novità. Ognuno è un asse su cui ti collochi, non un'appartenenza.</p>` },
      { h: "Perché non il test delle 16 personalità", html: `<p>La differenza con l'<span class="t" data-tip="Myers-Briggs Type Indicator: popolarissimo test che assegna a uno di 16 tipi. Nato fuori dalla ricerca accademica, taglia in due tratti continui e ha una scarsa stabilità nel tempo.">MBTI</span> è di sostanza. L'MBTI ti mette in una di 16 caselle tagliando in due dimensioni che in realtà sono continue: due persone quasi identiche finiscono in tipi diversi, e rifacendo il test a distanza di settimane molti cambiano tipo. I Big Five non ti danno un'etichetta memorabile, ma reggono alla replica e prevedono, seppur modestamente, esiti reali come rendimento e salute.</p>` },
      { h: "Stabili ma non fissi: la maturità", html: `<p>Quanto cambiano i tratti? Due risposte diverse. La <span class="t" data-tip="Stabilità di rango: se sei più estroverso della media a vent'anni, tendi a restarlo a sessanta rispetto ai tuoi coetanei. Cresce con l'età ma non è mai totale.">stabilità di rango</span> è alta: la tua posizione rispetto agli altri cambia poco. Ma il <span class="t" data-tip="Principio di maturità (Roberts e colleghi): con l'età, in media, le persone diventano un po' più coscienziose e amichevoli e meno nevrotiche. Un cambiamento lento e normativo.">principio di maturità</span> dice che i livelli medi si spostano: invecchiando, in media, si diventa un po' più coscienziosi, più amichevoli e meno nevrotici. I tratti sono in parte ereditari — l'<span class="t" data-tip="Ereditarietà: quota della variabilità tra individui attribuibile alle differenze genetiche. Per i Big Five è stimata intorno al 40-50%; il resto è ambiente, soprattutto non condiviso.">ereditarietà</span> stimata è intorno al 40-50% — ma metà del quadro resta ambiente.</p>` }
    ],
    beyond: `<ul>
      <li><b>Metà geni, metà ambiente.</b> L'ereditarietà dei Big Five si aggira sul 40-50%. La parte ambientale è soprattutto <span class="t" data-tip="Ambiente non condiviso: le esperienze che rendono diversi fratelli cresciuti nella stessa casa (amicizie, eventi, caso), più influente dell'ambiente familiare condiviso.">non condivisa</span>: pesa più ciò che ti capita di unico che la famiglia in comune.</li>
      <li><b>Un tratto è una base rate, non un destino.</b> Alta coscienziosità sposta le probabilità (più puntualità, più costanza), non garantisce il singolo comportamento: descrive tendenze medie su tante situazioni, non cosa farai domani.</li>
      <li><b>Il sesto fattore.</b> Il modello <span class="t" data-tip="HEXACO: variante a sei fattori che aggiunge ai Big Five una dimensione di Onestà-Umiltà, utile per prevedere comportamenti come inganno e sfruttamento.">HEXACO</span> aggiunge l'Onestà-Umiltà: per alcuni fenomeni predice meglio dei cinque classici.</li>
      <li><b>Predicono cose reali.</b> Coscienziosità e (bassa) instabilità emotiva sono legate a salute e longevità; l'estroversione al reddito e al benessere sociale — con effetti reali ma di dimensione modesta.</li>
    </ul>`,
    taratura: `<p>Il modello a cinque fattori è tra i più replicati della psicologia, ma questa versione è volutamente <b>breve</b>: quattro item per tratto. Il vantaggio è la rapidità; il prezzo è una <span class="t" data-tip="Con poche domande per scala la coerenza interna scende: il Mini-IPIP resta accettabile, ma è meno preciso dei questionari lunghi come l'IPIP-50 o il NEO-PI-R.">precisione più bassa</span> rispetto ai questionari lunghi, e la scala di Apertura/Intelletto è la più debole a poche domande. È un autoresoconto: risente di come ti vedi e vuoi apparire. Infine, i Big Five prevedono molti esiti, ma con <span class="t" data-tip="Dimensione dell'effetto: quanto grande è una relazione, non solo se esiste. Per i tratti e gli esiti di vita gli effetti sono in genere da piccoli a moderati.">effetti da piccoli a moderati</span>: utili per capire tendenze, non per etichettare le persone.</p>`,
    reading: [
      "Donnellan, M. B., Oswald, F. L., Baird, B. M. & Lucas, R. E. (2006). The Mini-IPIP scales. <em>Psychological Assessment</em>, 18, 192-203.",
      "Roberts, B. W., Walton, K. E. & Viechtbauer, W. (2006). Patterns of mean-level change in personality traits across the life course. <em>Psychological Bulletin</em>, 132, 1-25.",
      "John, O. P., Naumann, L. P. & Soto, C. J. (2008). Paradigm shift to the integrative Big Five taxonomy. In <em>Handbook of Personality</em> (3ª ed.)."
    ]
  },
  en: {
    title: "The Big Five, in brief",
    intro: `<p>The Mini-IPIP measures the <span class="t" data-tip="The five traits on which personality psychology broadly agrees: openness, conscientiousness, extraversion, agreeableness, neuroticism. The acronym is OCEAN.">Big Five</span>, the most solid model of personality we have. It didn't come from a top-down theory but from the <span class="t" data-tip="Lexical hypothesis: if a difference between people really matters, language eventually gives it a word. Studying personality adjectives thus reconstructs the map of traits.">lexical hypothesis</span>: <span class="t" data-tip="Gordon Allport and Henry Odbert in 1936 counted about 18,000 personality terms in the English dictionary, the starting point of the lexical approach.">Allport</span> counted thousands of adjectives, and decades of <span class="t" data-tip="Factor analysis: a statistical technique that groups many correlated variables into a few underlying dimensions. Applied to personality adjectives, it repeatedly yields five broad factors.">factor analysis</span> boiled them down to five factors. The twenty statements here come from Goldberg's <span class="t" data-tip="International Personality Item Pool: a public-domain bank of personality items created by Lewis Goldberg, a free alternative to commercial questionnaires.">IPIP</span>, in the short version built by <span class="t" data-tip="Donnellan, Oswald, Baird and Lucas (2006) condensed the Big Five into twenty items, four per trait, keeping good psychometric properties.">Donnellan and colleagues</span> in 2006.</p>`,
    blocks: [
      { h: "Five axes, not five types", html: `<p>The five traits are <b>continuous dimensions</b>, not boxes: almost everyone sits in the middle, few at the extremes. <b>Extraversion</b> is how much energy you draw from others; <b>agreeableness</b> how warm and cooperative you are; <b>conscientiousness</b> how orderly and dependable; <span class="t" data-tip="Neuroticism: the tendency to feel negative emotions (anxiety, sadness, irritability) easily and intensely. Its opposite is emotional stability.">neuroticism</span> how readily you feel negative emotion; <span class="t" data-tip="Openness to experience (or openness/intellect): intellectual curiosity, imagination, a taste for ideas and novelty. It is the most debated of the five.">openness</span> how drawn you are to ideas, art and novelty. Each is an axis you sit on, not a membership.</p>` },
      { h: "Why not the 16-personalities test", html: `<p>The difference from the <span class="t" data-tip="Myers-Briggs Type Indicator: a hugely popular test that assigns you to one of 16 types. Born outside academic research, it cuts continuous traits in two and has poor stability over time.">MBTI</span> is substantive. The MBTI puts you in one of 16 boxes by slicing dimensions that are really continuous: two nearly identical people land in different types, and many switch type when they retake it weeks later. The Big Five give you no memorable label, but they survive replication and predict, modestly, real outcomes like performance and health.</p>` },
      { h: "Stable but not fixed: maturity", html: `<p>How much do traits change? Two different answers. <span class="t" data-tip="Rank-order stability: if you're more extraverted than average at twenty, you tend to stay so at sixty relative to your peers. It rises with age but is never total.">Rank-order stability</span> is high: your position relative to others changes little. But the <span class="t" data-tip="Maturity principle (Roberts and colleagues): with age, on average, people become a little more conscientious and agreeable and less neurotic. A slow, normative change.">maturity principle</span> says average levels shift: as we age, on average, we grow a bit more conscientious, more agreeable and less neurotic. Traits are partly inherited — estimated <span class="t" data-tip="Heritability: the share of variability between individuals attributable to genetic differences. For the Big Five it is estimated around 40-50%; the rest is environment, mostly non-shared.">heritability</span> is around 40-50% — but half the picture is environment.</p>` }
    ],
    beyond: `<ul>
      <li><b>Half genes, half environment.</b> The heritability of the Big Five runs about 40-50%. The environmental part is mostly <span class="t" data-tip="Non-shared environment: the experiences that make siblings raised in the same home different (friendships, events, chance), more influential than the shared family environment.">non-shared</span>: what happens uniquely to you matters more than the family you share.</li>
      <li><b>A trait is a base rate, not a destiny.</b> High conscientiousness shifts the odds (more punctuality, more consistency), it doesn't guarantee the single act: it describes average tendencies across many situations, not what you'll do tomorrow.</li>
      <li><b>The sixth factor.</b> The <span class="t" data-tip="HEXACO: a six-factor variant that adds an Honesty-Humility dimension to the Big Five, useful for predicting behaviours like deception and exploitation.">HEXACO</span> model adds Honesty-Humility: for some phenomena it predicts better than the classic five.</li>
      <li><b>They predict real things.</b> Conscientiousness and (low) emotional instability are tied to health and longevity; extraversion to income and social well-being — with real but modest effect sizes.</li>
    </ul>`,
    taratura: `<p>The five-factor model is among the most replicated in psychology, but this version is deliberately <b>short</b>: four items per trait. The upside is speed; the price is <span class="t" data-tip="With few questions per scale internal consistency drops: the Mini-IPIP stays acceptable, but is less precise than long questionnaires like the IPIP-50 or NEO-PI-R.">lower precision</span> than long questionnaires, and the Openness/Intellect scale is the weakest at few items. It's a self-report: it reflects how you see yourself and want to appear. Finally, the Big Five predict many outcomes, but with <span class="t" data-tip="Effect size: how large a relationship is, not just whether it exists. For traits and life outcomes the effects are usually small to moderate.">small-to-moderate effects</span>: useful for understanding tendencies, not for labelling people.</p>`,
    reading: [
      "Donnellan, M. B., Oswald, F. L., Baird, B. M. & Lucas, R. E. (2006). The Mini-IPIP scales. <em>Psychological Assessment</em>, 18, 192-203.",
      "Roberts, B. W., Walton, K. E. & Viechtbauer, W. (2006). Patterns of mean-level change in personality traits across the life course. <em>Psychological Bulletin</em>, 132, 1-25.",
      "John, O. P., Naumann, L. P. & Soto, C. J. (2008). Paradigm shift to the integrative Big Five taxonomy. In <em>Handbook of Personality</em> (3rd ed.)."
    ]
  },
  pt: {
    title: "Os Cinco Grandes, em breve",
    intro: `<p>O Mini-IPIP mede os <span class="t" data-tip="Os cinco traços sobre os quais a psicologia da personalidade concorda amplamente: abertura, conscienciosidade, extroversão, amabilidade, neuroticismo. A sigla em inglês é OCEAN.">Cinco Grandes</span> (Big Five), o modelo de personalidade mais sólido que temos. Não nasceu de uma teoria imposta de cima, mas da <span class="t" data-tip="Hipótese lexical: se uma diferença entre pessoas realmente importa, a língua cedo ou tarde lhe deu uma palavra. Estudar os adjetivos de personalidade reconstrói assim o mapa dos traços.">hipótese lexical</span>: <span class="t" data-tip="Gordon Allport e Henry Odbert, em 1936, contaram cerca de 18.000 termos de personalidade no dicionário inglês, o ponto de partida da abordagem lexical.">Allport</span> contou milhares de adjetivos, e décadas de <span class="t" data-tip="Análise fatorial: técnica estatística que agrupa muitas variáveis correlacionadas em poucas dimensões de fundo. Aplicada aos adjetivos de personalidade, faz emergir repetidamente cinco grandes fatores.">análise fatorial</span> os reduziram a cinco fatores. As vinte frases deste teste vêm do <span class="t" data-tip="International Personality Item Pool: banco de itens de personalidade de domínio público criado por Lewis Goldberg, alternativa livre aos questionários comerciais.">IPIP</span> de Goldberg, na versão curta elaborada por <span class="t" data-tip="Donnellan, Oswald, Baird e Lucas (2006) condensaram os Cinco Grandes em vinte itens, quatro por traço, mantendo boas propriedades psicométricas.">Donnellan e colegas</span> em 2006.</p>`,
    blocks: [
      { h: "Cinco eixos, não cinco tipos", html: `<p>Os cinco traços são <b>dimensões contínuas</b>, não caixas: quase todos ficam no meio, poucos nos extremos. A <b>extroversão</b> é quanta energia você tira dos outros; a <b>amabilidade</b>, o quanto você é caloroso e cooperativo; a <b>conscienciosidade</b>, o quanto é organizado e confiável; o <span class="t" data-tip="Neuroticismo: a tendência a sentir emoções negativas (ansiedade, tristeza, irritabilidade) com facilidade e intensidade. Seu oposto é a estabilidade emocional.">neuroticismo</span>, com que facilidade você sente emoções negativas; a <span class="t" data-tip="Abertura à experiência (ou abertura/intelecto): curiosidade intelectual, imaginação, gosto por ideias e novidade. É o fator mais debatido dos cinco.">abertura</span>, o quanto se atrai por ideias, arte e novidade. Cada um é um eixo em que você se posiciona, não um pertencimento.</p>` },
      { h: "Por que não o teste das 16 personalidades", html: `<p>A diferença para o <span class="t" data-tip="Myers-Briggs Type Indicator: teste popularíssimo que atribui a um de 16 tipos. Nascido fora da pesquisa acadêmica, corta em dois traços que são contínuos e tem baixa estabilidade no tempo.">MBTI</span> é de substância. O MBTI coloca você numa de 16 caixas cortando ao meio dimensões que na verdade são contínuas: duas pessoas quase idênticas caem em tipos diferentes, e muitos mudam de tipo ao refazer o teste semanas depois. Os Cinco Grandes não dão um rótulo memorável, mas resistem à replicação e preveem, ainda que modestamente, desfechos reais como desempenho e saúde.</p>` },
      { h: "Estáveis mas não fixos: a maturidade", html: `<p>Quanto os traços mudam? Duas respostas diferentes. A <span class="t" data-tip="Estabilidade de posto: se você é mais extrovertido que a média aos vinte, tende a continuar assim aos sessenta em relação aos seus pares. Cresce com a idade mas nunca é total.">estabilidade de posto</span> é alta: sua posição em relação aos outros muda pouco. Mas o <span class="t" data-tip="Princípio da maturidade (Roberts e colegas): com a idade, em média, as pessoas ficam um pouco mais conscienciosas e amáveis e menos neuróticas. Uma mudança lenta e normativa.">princípio da maturidade</span> diz que os níveis médios se deslocam: envelhecendo, em média, ficamos um pouco mais conscienciosos, mais amáveis e menos neuróticos. Os traços são em parte herdados — a <span class="t" data-tip="Herdabilidade: parcela da variabilidade entre indivíduos atribuível a diferenças genéticas. Para os Cinco Grandes é estimada em torno de 40-50%; o resto é ambiente, sobretudo não compartilhado.">herdabilidade</span> estimada gira em torno de 40-50% — mas metade do quadro continua sendo ambiente.</p>` }
    ],
    beyond: `<ul>
      <li><b>Metade genes, metade ambiente.</b> A herdabilidade dos Cinco Grandes gira em torno de 40-50%. A parte ambiental é sobretudo <span class="t" data-tip="Ambiente não compartilhado: as experiências que tornam diferentes irmãos criados na mesma casa (amizades, eventos, acaso), mais influentes que o ambiente familiar compartilhado.">não compartilhada</span>: pesa mais o que lhe acontece de único do que a família em comum.</li>
      <li><b>Um traço é uma taxa-base, não um destino.</b> Alta conscienciosidade desloca as probabilidades (mais pontualidade, mais constância), não garante o comportamento isolado: descreve tendências médias em muitas situações, não o que você fará amanhã.</li>
      <li><b>O sexto fator.</b> O modelo <span class="t" data-tip="HEXACO: variante de seis fatores que acrescenta aos Cinco Grandes uma dimensão de Honestidade-Humildade, útil para prever comportamentos como engano e exploração.">HEXACO</span> acrescenta a Honestidade-Humildade: para alguns fenômenos prevê melhor que os cinco clássicos.</li>
      <li><b>Preveem coisas reais.</b> Conscienciosidade e (baixa) instabilidade emocional ligam-se a saúde e longevidade; a extroversão à renda e ao bem-estar social — com efeitos reais mas de tamanho modesto.</li>
    </ul>`,
    taratura: `<p>O modelo de cinco fatores está entre os mais replicados da psicologia, mas esta versão é propositalmente <b>curta</b>: quatro itens por traço. A vantagem é a rapidez; o preço é uma <span class="t" data-tip="Com poucas perguntas por escala a consistência interna cai: o Mini-IPIP continua aceitável, mas é menos preciso que questionários longos como o IPIP-50 ou o NEO-PI-R.">precisão menor</span> que a dos questionários longos, e a escala de Abertura/Intelecto é a mais fraca com poucas perguntas. É um autorrelato: reflete como você se vê e quer parecer. Por fim, os Cinco Grandes preveem muitos desfechos, mas com <span class="t" data-tip="Tamanho do efeito: o quão grande é uma relação, não apenas se ela existe. Para traços e desfechos de vida os efeitos costumam ser de pequenos a moderados.">efeitos de pequenos a moderados</span>: úteis para entender tendências, não para rotular pessoas.</p>`,
    reading: [
      "Donnellan, M. B., Oswald, F. L., Baird, B. M. & Lucas, R. E. (2006). The Mini-IPIP scales. <em>Psychological Assessment</em>, 18, 192-203.",
      "Roberts, B. W., Walton, K. E. & Viechtbauer, W. (2006). Patterns of mean-level change in personality traits across the life course. <em>Psychological Bulletin</em>, 132, 1-25.",
      "John, O. P., Naumann, L. P. & Soto, C. J. (2008). Paradigm shift to the integrative Big Five taxonomy. In <em>Handbook of Personality</em> (3ª ed.)."
    ]
  }
};
