/* Mini-IPIP (Donnellan, Oswald, Baird & Lucas 2006) — 20 item Big Five, pubblico dominio (International Personality Item Pool). IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.miniipip = {
  code: "Mini-IPIP", theme: "plum", n: 20, reverse: [6, 7, 8, 9, 10, 15, 16, 17, 18, 19, 20],
  labels: {
    en: ["Very inaccurate", "Moderately inaccurate", "Neither accurate nor inaccurate", "Moderately accurate", "Very accurate"],
    it: ["Per niente vero per me", "Poco vero", "Né vero né falso", "Abbastanza vero", "Molto vero per me"]
  },
  items: {
    en: ["I am the life of the party.", "I sympathize with others' feelings.", "I get chores done right away.", "I have frequent mood swings.", "I have a vivid imagination.", "I don't talk a lot.", "I am not interested in other people's problems.", "I often forget to put things back in their proper place.", "I am relaxed most of the time.", "I am not interested in abstract ideas.", "I talk to a lot of different people at parties.", "I feel others' emotions.", "I like order.", "I get upset easily.", "I have difficulty understanding abstract ideas.", "I keep in the background.", "I am not really interested in others.", "I make a mess of things.", "I seldom feel blue.", "I do not have a good imagination."],
    it: ["Sono l'anima della festa.", "Partecipo ai sentimenti degli altri.", "Sbrigo subito le faccende.", "Ho frequenti sbalzi d'umore.", "Ho un'immaginazione vivida.", "Non parlo molto.", "Non mi interessano i problemi degli altri.", "Spesso dimentico di rimettere le cose al loro posto.", "Sono rilassato la maggior parte del tempo.", "Non mi interessano le idee astratte.", "Alle feste parlo con molte persone diverse.", "Sento le emozioni degli altri.", "Mi piace l'ordine.", "Mi turbo facilmente.", "Faccio fatica a capire le idee astratte.", "Me ne sto in disparte.", "Non mi interessano davvero gli altri.", "Combino pasticci.", "Raramente mi sento giù.", "Non ho una buona immaginazione."]
  },
  text: {
    it: { kicker: "Big Five", title: "Che personalità hai?", lede: "20 affermazioni, 3 minuti. I cinque grandi tratti della personalità (estroversione, amicalità, coscienziosità, nevroticismo, apertura) con la scala Mini-IPIP, di pubblico dominio.", meta: ["20 domande", "~3 minuti", "5 tratti"], instr: "Per ogni frase indica <b>quanto ti descrive</b> come sei in generale, oggi, non come vorresti essere. Rispondi d'istinto.", how: "Cinque punteggi da 4 a 20, uno per tratto; 11 affermazioni sono invertite. Il punto medio è 12: sopra sei più del tipico verso quel tratto, sotto meno. I tratti non sono buoni o cattivi: descrivono tendenze, e ognuno ha vantaggi in contesti diversi. Con 4 domande per tratto la misura è affidabile ma grossolana; il questionario completo (IPIP-NEO) è molto più fine.", cite: "Donnellan, M. B., Oswald, F. L., Baird, B. M., & Lucas, R. E. (2006). The Mini-IPIP scales. Psychological Assessment, 18, 192-203. Item di pubblico dominio (ipip.ori.org); traduzione italiana propria, non validata." },
    en: { kicker: "Big Five", title: "What is your personality like?", lede: "20 statements, 3 minutes. The five big personality traits (extraversion, agreeableness, conscientiousness, neuroticism, openness) with the public-domain Mini-IPIP scale.", meta: ["20 questions", "~3 minutes", "5 traits"], instr: "For each statement, indicate <b>how well it describes you</b> as you generally are now, not as you wish to be. Answer instinctively.", how: "Five scores from 4 to 20, one per trait; 11 statements are reverse-keyed. The midpoint is 12: above it you lean more than typical towards that trait, below it less. Traits are not good or bad: they describe tendencies, each with advantages in different contexts. With 4 questions per trait the measure is reliable but coarse; the full IPIP-NEO is much finer.", cite: "Donnellan, M. B., Oswald, F. L., Baird, B. M., & Lucas, R. E. (2006). The Mini-IPIP scales. Psychological Assessment, 18, 192-203. Public-domain items (ipip.ori.org)." }
  },
  scales: [
    { key: "e", name: { it: "Estroversione", en: "Extraversion" }, items: [1, 6, 11, 16], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Riservato: ricarichi da solo, preferisci pochi legami profondi alla folla.", en: "Reserved: you recharge alone and prefer a few deep ties to a crowd." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Né timido né esuberante: socievole quando serve, tranquillo quando puoi.", en: "Neither shy nor exuberant: sociable when needed, quiet when you can be." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Espansivo: cerchi le persone, le feste, la parola. L'energia ti viene dagli altri.", en: "Outgoing: you seek people, parties and conversation. Your energy comes from others." } }] },
    { key: "a", name: { it: "Amicalità", en: "Agreeableness" }, items: [2, 7, 12, 17], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Diretto e competitivo: metti la sostanza prima della diplomazia.", en: "Direct and competitive: substance before diplomacy." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Empatico quanto basta, senza farti mettere i piedi in testa.", en: "Empathetic enough, without being walked over." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Caldo e fiducioso: senti gli altri e tendi ad aiutarli. Attento a non dimenticare te.", en: "Warm and trusting: you feel others and tend to help them. Careful not to forget yourself." } }] },
    { key: "c", name: { it: "Coscienziosità", en: "Conscientiousness" }, items: [3, 8, 13, 18], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Flessibile e spontaneo: l'ordine e le scadenze non sono il tuo forte, l'improvvisazione sì.", en: "Flexible and spontaneous: order and deadlines are not your strength, improvising is." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Organizzato quando conta, rilassato quando puoi.", en: "Organised when it counts, relaxed when you can be." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Metodico e affidabile: fai le cose subito e bene. Il rischio è il perfezionismo.", en: "Methodical and reliable: you do things promptly and well. The risk is perfectionism." } }] },
    { key: "n", name: { it: "Nevroticismo", en: "Neuroticism" }, items: [4, 9, 14, 19], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Basso", en: "Low" }, text: { it: "Stabile: le emozioni negative arrivano e passano senza travolgerti.", en: "Stable: negative emotions come and go without overwhelming you." } },
      { max: 14, name: { it: "Medio", en: "Average" }, text: { it: "Reattivo nella norma: qualche sbalzo, ma torni in equilibrio.", en: "Normally reactive: some swings, but you regain balance." } },
      { max: 20, name: { it: "Alto", en: "High" }, text: { it: "Sensibile allo stress: umore mutevole, preoccupazioni facili. Non è un difetto, ma chiede cura di sé.", en: "Stress-sensitive: changeable mood, quick to worry. Not a flaw, but it calls for self-care." } }] },
    { key: "o", name: { it: "Apertura / Intelletto", en: "Openness / Intellect" }, items: [5, 10, 15, 20], mode: "sum", range: [4, 20], bands: [
      { max: 9, name: { it: "Bassa", en: "Low" }, text: { it: "Concreto e pratico: preferisci il tangibile alle idee astratte.", en: "Concrete and practical: you prefer the tangible to abstract ideas." } },
      { max: 14, name: { it: "Media", en: "Average" }, text: { it: "Curioso quanto basta, con i piedi per terra.", en: "Curious enough, with feet on the ground." } },
      { max: 20, name: { it: "Alta", en: "High" }, text: { it: "Immaginativo e attratto dalle idee: arte, teorie, novità.", en: "Imaginative and drawn to ideas: art, theories, novelty." } }] }
  ]
};
