/* Oldenburg Burnout Inventory, OLBI (Demerouti, Bakker et al. 2003; versione inglese Halbesleben & Demerouti 2005) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.olbi = {
  code: "OLBI", theme: "ocean", n: 16, reverse: [1, 5, 7, 10, 13, 14, 15, 16],
  labels: { en: ["Strongly disagree", "Disagree", "Agree", "Strongly agree"], it: ["Fortemente in disaccordo", "In disaccordo", "D'accordo", "Fortemente d'accordo"] },
  items: {
    en: ["I always find new and interesting aspects in my work.", "There are days when I feel tired before I arrive at work.", "It happens more and more often that I talk about my work in a negative way.", "After work, I tend to need more time than in the past in order to relax and feel better.", "I can tolerate the pressure of my work very well.", "Lately, I tend to think less at work and do my job almost mechanically.", "I find my work to be a positive challenge.", "During my work, I often feel emotionally drained.", "Over time, one can become disconnected from this type of work.", "After working, I have enough energy for my leisure activities.", "Sometimes I feel sickened by my work tasks.", "After my work, I usually feel worn out and weary.", "This is the only type of work that I can imagine myself doing.", "Usually, I can manage the amount of my work well.", "I feel more and more engaged in my work.", "When I work, I usually feel energized."],
    it: ["Trovo sempre aspetti nuovi e interessanti nel mio lavoro.", "Ci sono giorni in cui mi sento stanco prima ancora di arrivare al lavoro.", "Mi capita sempre più spesso di parlare del mio lavoro in modo negativo.", "Dopo il lavoro tendo ad avere bisogno di più tempo rispetto al passato per rilassarmi e stare meglio.", "Riesco a tollerare molto bene la pressione del mio lavoro.", "Ultimamente tendo a pensare meno al lavoro e a fare il mio compito quasi meccanicamente.", "Trovo che il mio lavoro sia una sfida positiva.", "Durante il lavoro mi sento spesso svuotato emotivamente.", "Col tempo ci si può distaccare da questo tipo di lavoro.", "Dopo il lavoro ho abbastanza energia per le mie attività del tempo libero.", "A volte i miei compiti lavorativi mi disgustano.", "Dopo il lavoro di solito mi sento esausto e sfinito.", "Questo è l'unico tipo di lavoro in cui riesco a immaginarmi.", "Di solito riesco a gestire bene la quantità del mio lavoro.", "Mi sento sempre più coinvolto nel mio lavoro.", "Quando lavoro, di solito mi sento pieno di energia."]
  },
  text: {
    it: { kicker: "Burnout", title: "Quanto ti sta consumando il lavoro?", lede: "16 affermazioni, 3 minuti. L'OLBI misura le due facce del burnout: l'esaurimento (energia finita) e il disimpegno (distacco dal lavoro). È l'alternativa libera al Maslach Burnout Inventory.", meta: ["16 domande", "~3 minuti", "2 dimensioni"], instr: "Le frasi riguardano il tuo <b>lavoro attuale</b> (o studio). Per ognuna indica quanto sei d'accordo; metà sono formulate al positivo.", how: "Due punteggi da 8 a 32 (esaurimento e disimpegno) e un totale da 16 a 64; 8 affermazioni positive sono invertite. Soglie usate in letteratura per il totale: fino a 43 basso, 44–51 moderato, 52 e oltre alto. Per le sottoscale, sopra 2,25 di media (18 su 32) l'esaurimento è alto, sopra 2,1 (17) il disimpegno. Il burnout è una condizione legata al lavoro, non un disturbo: la risposta sta nel carico, nel controllo e nel senso di quello che fai.", cite: "Demerouti, E., Bakker, A. B., Vardakou, I., & Kantas, A. (2003). The convergent validity of two burnout instruments. European Journal of Psychological Assessment, 19, 12-23. Uso libero; traduzione italiana propria." },
    en: { kicker: "Burnout", title: "How much is work wearing you down?", lede: "16 statements, 3 minutes. The OLBI measures the two faces of burnout: exhaustion (energy gone) and disengagement (distance from work). It is the free alternative to the Maslach Burnout Inventory.", meta: ["16 questions", "~3 minutes", "2 dimensions"], instr: "The statements concern your <b>current work</b> (or studies). Indicate how much you agree with each; half are positively worded.", how: "Two scores from 8 to 32 (exhaustion and disengagement) and a total from 16 to 64; 8 positive statements are reverse-keyed. Thresholds used in the literature for the total: up to 43 low, 44–51 moderate, 52 and above high. For the subscales, a mean above 2.25 (18 out of 32) is high exhaustion, above 2.1 (17) high disengagement. Burnout is a work-related condition, not a disorder: the answer lies in workload, control and the meaning of what you do.", cite: "Demerouti, E., Bakker, A. B., Vardakou, I., & Kantas, A. (2003). The convergent validity of two burnout instruments. European Journal of Psychological Assessment, 19, 12-23. Free to use." }
  },
  main: "tot",
  scales: [
    { key: "tot", name: { it: "Burnout totale", en: "Total burnout" }, items: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], mode: "sum", range: [16, 64], bands: [
      { max: 43, name: { it: "Basso", en: "Low" }, text: { it: "Il lavoro pesa nella norma: stanchezza e distacco restano gestibili.", en: "Work weighs on you within the norm: tiredness and distance remain manageable." } },
      { max: 51, name: { it: "Moderato", en: "Moderate" }, text: { it: "Segnali di logoramento: energia in calo o senso del lavoro che si affievolisce. È il momento di guardare carico, pause e margini di controllo, prima che diventi cronico.", en: "Signs of wear: energy dropping or the meaning of work fading. Time to look at load, breaks and margins of control, before it becomes chronic." } },
      { max: 64, name: { it: "Alto", en: "High" }, text: { it: "Nella fascia del burnout: esaurimento e distacco insieme. Non è debolezza, è un segnale che le condizioni vanno cambiate; parlarne con il medico e, se possibile, con chi decide il tuo carico, è la mossa giusta.", en: "In the burnout range: exhaustion and disengagement together. Not weakness, a signal that conditions must change; talking to a doctor and, if possible, to whoever sets your workload is the right move." } }] },
    { key: "ex", name: { it: "Esaurimento", en: "Exhaustion" }, items: [2,4,5,8,10,12,14,16], mode: "sum", range: [8, 32], bands: [
      { max: 17, name: { it: "Basso", en: "Low" }, text: { it: "Le energie reggono il carico.", en: "Your energy holds up under the load." } },
      { max: 32, name: { it: "Alto", en: "High" }, text: { it: "Stanchezza che non si recupera: il corpo chiede meno carico e più pausa.", en: "Tiredness that doesn't recover: the body is asking for less load and more rest." } }] },
    { key: "dis", name: { it: "Disimpegno", en: "Disengagement" }, items: [1,3,6,7,9,11,13,15], mode: "sum", range: [8, 32], bands: [
      { max: 16, name: { it: "Basso", en: "Low" }, text: { it: "Il lavoro ha ancora senso e interesse per te.", en: "Work still holds meaning and interest for you." } },
      { max: 32, name: { it: "Alto", en: "High" }, text: { it: "Ti sei distaccato: il lavoro è diventato meccanico e ne parli in negativo. Spesso è la difesa dall'esaurimento.", en: "You have disengaged: work has become mechanical and you talk about it negatively. Often it is the defence against exhaustion." } }] }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.olbi.approf = {
  it: {
    title: "Il burnout, tra esaurimento e distacco",
    intro: `<p>L'OLBI misura il <span class="t" data-tip="Uno stato di logoramento legato al lavoro, non una malattia. Nell'ICD-11 dell'OMS è un fenomeno occupazionale con tre segni: esaurimento, distanza mentale o cinismo verso il lavoro, ridotta efficacia.">burnout</span> lungo due assi: l'<b>esaurimento</b> (l'energia finita) e il <b>disimpegno</b> (il distacco dal lavoro in sé). Nasce nei Paesi Bassi dal gruppo di Demerouti come alternativa libera al più famoso <span class="t" data-tip="Maslach Burnout Inventory, di Christina Maslach: lo strumento storico e più usato per il burnout, ma a pagamento e nato per le professioni di aiuto. L'OLBI ne è l'alternativa gratuita e più generale.">MBI</span>. È uno strumento di <span class="t" data-tip="Un questionario di autovalutazione che segnala il logoramento, non un test che assegna una diagnosi clinica. Un risultato alto è un invito a guardare le condizioni di lavoro.">autovalutazione</span>, non una diagnosi.</p>`,
    blocks: [
      { h: "Le due facce del burnout", html: `<p>L'<span class="t" data-tip="La sensazione di essere svuotati: stanchezza fisica, cognitiva ed emotiva che non si recupera con il riposo normale. È la faccia energetica del burnout.">esaurimento</span> è la faccia energetica: ti senti prosciugato, e il riposo non basta più a ricaricarti. Il <span class="t" data-tip="Il distacco e l'atteggiamento negativo verso il lavoro in sé: farlo in modo meccanico, parlarne male, perdere interesse. È la faccia relazionale del burnout, vicina al cinismo.">disimpegno</span> è la faccia relazionale: prendi le distanze dal lavoro, lo fai in automatico, ne parli in negativo. A differenza dell'MBI, l'OLBI include per ogni asse sia frasi positive sia negative, così misura anche il polo opposto — il coinvolgimento — non solo il logoramento.</p>` },
      { h: "OLBI e MBI", html: `<p>L'<span class="t" data-tip="Christina Maslach, la psicologa che ha definito il burnout negli anni 70-80. Il suo MBI misura tre dimensioni: esaurimento emotivo, depersonalizzazione, ridotta realizzazione personale.">MBI di Maslach</span> è lo standard storico, con tre dimensioni, pensato soprattutto per le professioni di aiuto (sanità, scuola, servizi). L'OLBI ne è l'alternativa gratuita: due dimensioni invece di tre, e applicabile a qualunque tipo di lavoro, non solo a chi si occupa di persone. I due strumenti convergono bene, ma leggono lo stesso fenomeno con lenti un po' diverse.</p>` },
      { h: "Da dove viene: domande e risorse", html: `<p>L'OLBI si legge dentro il modello <span class="t" data-tip="Job Demands-Resources (Demerouti, Bakker): ogni lavoro ha richieste (carico, pressione, scadenze) e risorse (controllo, sostegno, feedback, senso). Il burnout nasce quando le richieste restano alte e le risorse basse a lungo.">domande-risorse</span>: ogni lavoro ha richieste (carico, pressione, scadenze) e risorse (autonomia, sostegno, riconoscimento, senso). Secondo il modello, le richieste croniche alimentano soprattutto l'esaurimento, mentre la mancanza di risorse alimenta soprattutto il disimpegno. Per questo la risposta al burnout non è solo individuale: sta nelle condizioni del lavoro, non solo nella cura di sé.</p>` },
      { h: "Cos'è, e cosa non è", html: `<p>Nell'<span class="t" data-tip="La classificazione internazionale delle malattie dell'OMS, in vigore dal 2022. Colloca il burnout tra i fattori che influenzano la salute legati al lavoro, non tra le malattie: è un fenomeno occupazionale.">ICD-11</span> il burnout è definito come un fenomeno legato al contesto lavorativo, <b>non una malattia</b>. Si sovrappone in parte alla depressione, ma se ne distingue per un tratto chiave: il burnout è specifico del lavoro e tende ad alleggerirsi quando cambia il contesto, mentre la depressione è pervasiva e tocca ogni ambito della vita. Distinguere i due è compito di un professionista.</p>` }
    ],
    beyond: `<ul>
      <li><b>Burnout e depressione.</b> Si sovrappongono e alti punteggi di burnout correlano con la depressione, ma il burnout resta ancorato al lavoro. Quando il distacco e la stanchezza invadono tutta la vita, la lettura cambia e vale un colloquio.</li>
      <li><b>Il disimpegno come difesa.</b> Spesso il distacco non è cinismo di carattere: è il modo in cui la mente si protegge da un esaurimento che dura troppo. Compare dopo, non prima.</li>
      <li><b>La risposta è strutturale.</b> Dormire e riposare aiuta, ma il burnout torna se carico, controllo e senso del lavoro non cambiano. Le leve più forti sono l'autonomia, il sostegno e il riconoscimento.</li>
      <li><b>Il polo positivo: il coinvolgimento.</b> L'opposto del burnout non è la calma, ma l'<span class="t" data-tip="Work engagement (Schaufeli): uno stato positivo fatto di energia, dedizione e assorbimento nel lavoro. È il polo opposto del burnout sullo stesso continuum.">engagement</span> — energia e dedizione. L'OLBI, con i suoi item positivi, prova a misurare anche questo.</li>
    </ul>`,
    taratura: `<p>L'OLBI ha buone proprietà psicometriche e una struttura a due fattori (esaurimento e disimpegno) confermata in più Paesi e lingue. Due limiti onesti. Primo: per il burnout <b>non esiste una soglia clinica condivisa</b> — le fasce usate variano tra gli studi, e l'OLBI resta uno strumento di ricerca e autovalutazione, non un test diagnostico. Secondo: si sovrappone parecchio alle misure di depressione, il che apre un dibattito sulla sua <span class="t" data-tip="La capacità di uno strumento di distinguere un costrutto da un altro simile. Per il burnout è discussa: quanto è davvero diverso dalla depressione legata al lavoro?">validità discriminante</span>. È un'autodescrizione legata al lavoro attuale: fotografa un logoramento, non una malattia.</p>`,
    reading: [
      "Demerouti, E., Bakker, A. B., Vardakou, I. & Kantas, A. (2003). The convergent validity of two burnout instruments. <em>European Journal of Psychological Assessment</em>, 19, 12-23.",
      "Halbesleben, J. R. B. & Demerouti, E. (2005). The construct validity of the OLBI. <em>Work & Stress</em>, 19, 208-220.",
      "Maslach, C., Schaufeli, W. B. & Leiter, M. P. (2001). Job burnout. <em>Annual Review of Psychology</em>, 52, 397-422."
    ]
  },
  en: {
    title: "Burnout, between exhaustion and disengagement",
    intro: `<p>The OLBI measures <span class="t" data-tip="A state of work-related wear, not an illness. In the WHO's ICD-11 it is an occupational phenomenon with three signs: exhaustion, mental distance or cynicism toward work, and reduced efficacy.">burnout</span> along two axes: <b>exhaustion</b> (energy gone) and <b>disengagement</b> (distance from the work itself). It came out of Demerouti's group in the Netherlands as a free alternative to the more famous <span class="t" data-tip="Maslach Burnout Inventory, by Christina Maslach: the historic and most-used burnout tool, but paid and originally built for the helping professions. The OLBI is the free, more general alternative.">MBI</span>. It is a <span class="t" data-tip="A self-assessment questionnaire that flags wear, not a test that assigns a clinical diagnosis. A high result is an invitation to look at working conditions.">self-assessment</span> tool, not a diagnosis.</p>`,
    blocks: [
      { h: "The two faces of burnout", html: `<p><span class="t" data-tip="The sense of being emptied out: physical, cognitive and emotional tiredness that ordinary rest no longer restores. It is the energy face of burnout.">Exhaustion</span> is the energy face: you feel drained, and rest no longer recharges you. <span class="t" data-tip="Distancing and a negative attitude toward the work itself: doing it mechanically, speaking badly of it, losing interest. It is the relational face of burnout, close to cynicism.">Disengagement</span> is the relational face: you pull away from work, do it on autopilot, speak about it negatively. Unlike the MBI, the OLBI includes both positively and negatively worded items on each axis, so it also measures the opposite pole — engagement — not just the wear.</p>` },
      { h: "OLBI and MBI", html: `<p>Maslach's <span class="t" data-tip="Christina Maslach, the psychologist who defined burnout in the 1970s-80s. Her MBI measures three dimensions: emotional exhaustion, depersonalisation, reduced personal accomplishment.">MBI</span> is the historic standard, with three dimensions, built mainly for the helping professions (health, schools, services). The OLBI is the free alternative: two dimensions instead of three, and applicable to any kind of work, not only to people-facing roles. The two tools converge well, but read the same phenomenon through slightly different lenses.</p>` },
      { h: "Where it comes from: demands and resources", html: `<p>The OLBI reads within the <span class="t" data-tip="Job Demands-Resources (Demerouti, Bakker): every job has demands (workload, pressure, deadlines) and resources (control, support, feedback, meaning). Burnout arises when demands stay high and resources low for a long time.">demands-resources</span> model: every job has demands (workload, pressure, deadlines) and resources (autonomy, support, recognition, meaning). In the model, chronic demands feed exhaustion above all, while a lack of resources feeds disengagement above all. So the answer to burnout is not only individual: it lies in working conditions, not just in self-care.</p>` },
      { h: "What it is, and what it isn't", html: `<p>In the <span class="t" data-tip="The WHO's international classification of diseases, in force since 2022. It places burnout among work-related factors influencing health, not among diseases: it is an occupational phenomenon.">ICD-11</span> burnout is defined as a phenomenon tied to the work context, <b>not an illness</b>. It overlaps partly with depression, but differs by one key trait: burnout is work-specific and tends to ease when the context changes, whereas depression is pervasive and touches every area of life. Telling the two apart is a professional's job.</p>` }
    ],
    beyond: `<ul>
      <li><b>Burnout and depression.</b> They overlap and high burnout scores correlate with depression, but burnout stays anchored to work. When distance and tiredness invade the whole of life, the reading changes and a conversation is worthwhile.</li>
      <li><b>Disengagement as a defence.</b> Distance is often not trait cynicism: it is the mind's way of protecting itself from an exhaustion that has lasted too long. It comes after, not before.</li>
      <li><b>The answer is structural.</b> Sleep and rest help, but burnout returns if workload, control and the meaning of work don't change. The strongest levers are autonomy, support and recognition.</li>
      <li><b>The positive pole: engagement.</b> The opposite of burnout is not calm but <span class="t" data-tip="Work engagement (Schaufeli): a positive state of energy, dedication and absorption in work. It is the opposite pole of burnout on the same continuum.">engagement</span> — energy and dedication. The OLBI, with its positive items, tries to measure this too.</li>
    </ul>`,
    taratura: `<p>The OLBI has good psychometric properties and a two-factor structure (exhaustion and disengagement) confirmed across several countries and languages. Two honest limits. First: for burnout there is <b>no agreed clinical threshold</b> — the bands used vary between studies, and the OLBI remains a research and self-assessment tool, not a diagnostic test. Second: it overlaps considerably with depression measures, which opens a debate about its <span class="t" data-tip="A tool's ability to tell one construct from another similar one. For burnout it is contested: how truly different is it from work-related depression?">discriminant validity</span>. It is a self-report tied to your current job: it photographs wear, not an illness.</p>`,
    reading: [
      "Demerouti, E., Bakker, A. B., Vardakou, I. & Kantas, A. (2003). The convergent validity of two burnout instruments. <em>European Journal of Psychological Assessment</em>, 19, 12-23.",
      "Halbesleben, J. R. B. & Demerouti, E. (2005). The construct validity of the OLBI. <em>Work & Stress</em>, 19, 208-220.",
      "Maslach, C., Schaufeli, W. B. & Leiter, M. P. (2001). Job burnout. <em>Annual Review of Psychology</em>, 52, 397-422."
    ]
  },
  pt: {
    title: "O burnout, entre exaustão e desligamento",
    intro: `<p>O OLBI mede o <span class="t" data-tip="Um estado de desgaste ligado ao trabalho, não uma doença. Na CID-11 da OMS é um fenômeno ocupacional com três sinais: exaustão, distância mental ou cinismo em relação ao trabalho, e eficácia reduzida.">burnout</span> ao longo de dois eixos: a <b>exaustão</b> (a energia esgotada) e o <b>desligamento</b> (o distanciamento do trabalho em si). Surgiu na Holanda, do grupo de Demerouti, como alternativa gratuita ao mais famoso <span class="t" data-tip="Maslach Burnout Inventory, de Christina Maslach: a ferramenta histórica e mais usada para o burnout, mas paga e criada para as profissões de ajuda. O OLBI é a alternativa gratuita e mais geral.">MBI</span>. É um instrumento de <span class="t" data-tip="Um questionário de autoavaliação que sinaliza o desgaste, não um teste que atribui um diagnóstico clínico. Um resultado alto é um convite a olhar as condições de trabalho.">autoavaliação</span>, não um diagnóstico.</p>`,
    blocks: [
      { h: "As duas faces do burnout", html: `<p>A <span class="t" data-tip="A sensação de estar esvaziado: cansaço físico, cognitivo e emocional que o descanso normal não recupera. É a face energética do burnout.">exaustão</span> é a face energética: você se sente drenado, e o descanso já não recarrega. O <span class="t" data-tip="O distanciamento e a atitude negativa em relação ao próprio trabalho: fazê-lo de modo mecânico, falar mal dele, perder o interesse. É a face relacional do burnout, próxima do cinismo.">desligamento</span> é a face relacional: você se afasta do trabalho, o faz no automático, fala dele em tom negativo. Diferente do MBI, o OLBI inclui em cada eixo tanto frases positivas quanto negativas, então mede também o polo oposto — o engajamento — e não só o desgaste.</p>` },
      { h: "OLBI e MBI", html: `<p>O <span class="t" data-tip="Christina Maslach, a psicóloga que definiu o burnout nos anos 70-80. Seu MBI mede três dimensões: exaustão emocional, despersonalização, realização pessoal reduzida.">MBI de Maslach</span> é o padrão histórico, com três dimensões, pensado sobretudo para as profissões de ajuda (saúde, escola, serviços). O OLBI é a alternativa gratuita: duas dimensões em vez de três, e aplicável a qualquer tipo de trabalho, não só a quem lida com pessoas. Os dois instrumentos convergem bem, mas leem o mesmo fenômeno com lentes um pouco diferentes.</p>` },
      { h: "De onde vem: demandas e recursos", html: `<p>O OLBI se lê dentro do modelo <span class="t" data-tip="Job Demands-Resources (Demerouti, Bakker): todo trabalho tem demandas (carga, pressão, prazos) e recursos (controle, apoio, feedback, sentido). O burnout surge quando as demandas ficam altas e os recursos baixos por muito tempo.">demandas-recursos</span>: todo trabalho tem demandas (carga, pressão, prazos) e recursos (autonomia, apoio, reconhecimento, sentido). Segundo o modelo, as demandas crônicas alimentam sobretudo a exaustão, enquanto a falta de recursos alimenta sobretudo o desligamento. Por isso a resposta ao burnout não é só individual: está nas condições do trabalho, não apenas no autocuidado.</p>` },
      { h: "O que é, e o que não é", html: `<p>Na <span class="t" data-tip="A classificação internacional de doenças da OMS, em vigor desde 2022. Coloca o burnout entre os fatores que influenciam a saúde ligados ao trabalho, não entre as doenças: é um fenômeno ocupacional.">CID-11</span> o burnout é definido como um fenômeno ligado ao contexto de trabalho, <b>não uma doença</b>. Sobrepõe-se em parte à depressão, mas dela se distingue por um traço-chave: o burnout é específico do trabalho e tende a aliviar quando o contexto muda, enquanto a depressão é pervasiva e atinge todas as áreas da vida. Distinguir os dois é tarefa de um profissional.</p>` }
    ],
    beyond: `<ul>
      <li><b>Burnout e depressão.</b> Sobrepõem-se e pontuações altas de burnout correlacionam com a depressão, mas o burnout permanece ancorado ao trabalho. Quando o distanciamento e o cansaço invadem toda a vida, a leitura muda e vale uma conversa.</li>
      <li><b>O desligamento como defesa.</b> Muitas vezes o distanciamento não é cinismo de caráter: é o modo como a mente se protege de uma exaustão que dura demais. Aparece depois, não antes.</li>
      <li><b>A resposta é estrutural.</b> Dormir e descansar ajuda, mas o burnout volta se carga, controle e sentido do trabalho não mudam. As alavancas mais fortes são a autonomia, o apoio e o reconhecimento.</li>
      <li><b>O polo positivo: o engajamento.</b> O oposto do burnout não é a calma, mas o <span class="t" data-tip="Work engagement (Schaufeli): um estado positivo feito de energia, dedicação e absorção no trabalho. É o polo oposto do burnout no mesmo continuum.">engajamento</span> — energia e dedicação. O OLBI, com seus itens positivos, tenta medir também isso.</li>
    </ul>`,
    taratura: `<p>O OLBI tem boas propriedades psicométricas e uma estrutura de dois fatores (exaustão e desligamento) confirmada em vários países e línguas. Dois limites honestos. Primeiro: para o burnout <b>não existe um ponto de corte clínico consensual</b> — as faixas usadas variam entre os estudos, e o OLBI continua sendo um instrumento de pesquisa e autoavaliação, não um teste diagnóstico. Segundo: sobrepõe-se bastante às medidas de depressão, o que abre um debate sobre a sua <span class="t" data-tip="A capacidade de um instrumento de distinguir um construto de outro parecido. Para o burnout é discutida: o quanto ele é realmente diferente da depressão ligada ao trabalho?">validade discriminante</span>. É uma autodescrição ligada ao trabalho atual: fotografa um desgaste, não uma doença.</p>`,
    reading: [
      "Demerouti, E., Bakker, A. B., Vardakou, I. & Kantas, A. (2003). The convergent validity of two burnout instruments. <em>European Journal of Psychological Assessment</em>, 19, 12-23.",
      "Halbesleben, J. R. B. & Demerouti, E. (2005). The construct validity of the OLBI. <em>Work & Stress</em>, 19, 208-220.",
      "Maslach, C., Schaufeli, W. B. & Leiter, M. P. (2001). Job burnout. <em>Annual Review of Psychology</em>, 52, 397-422."
    ]
  }
};
