/* Oldenburg Burnout Inventory, OLBI (Demerouti, Bakker et al. 2003; versione inglese Halbesleben & Demerouti 2005) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.olbi = {
  code: "OLBI", theme: "ocean", n: 16, reverse: [1, 5, 7, 10, 13, 14, 15, 16],
  labels: { en: ["Strongly disagree", "Disagree", "Agree", "Strongly agree"], it: ["Fortemente in disaccordo", "In disaccordo", "D'accordo", "Fortemente d'accordo"] },
  items: {
    en: ["I always find new and interesting aspects in my work.", "There are days when I feel tired before I arrive at work.", "It happens more and more often that I talk about my work in a negative way.", "After work, I tend to need more time than in the past in order to relax and feel better.", "I can tolerate the pressure of my work very well.", "Lately, I tend to think less at work and do my job almost mechanically.", "I find my work to be a positive challenge.", "During my work, I often feel emotionally drained.", "Over time, one can become disconnected from this type of work.", "After working, I have enough energy for my leisure activities.", "Sometimes I feel sickened by my work tasks.", "After my work, I usually feel worn out and weary.", "This is the only type of work that I can imagine myself doing.", "Usually, I can manage the amount of my work well.", "I feel more and more engaged in my work.", "When I work, I usually feel energized."],
    it: ["Trovo sempre aspetti nuovi e interessanti nel mio lavoro.", "Ci sono giorni in cui mi sento stanco prima ancora di arrivare al lavoro.", "Mi capita sempre più spesso di parlare del mio lavoro in modo negativo.", "Dopo il lavoro tendo ad avere bisogno di più tempo rispetto al passato per rilassarmi e stare meglio.", "Riesco a tollerare molto bene la pressione del mio lavoro.", "Ultimamente tendo a pensare meno al lavoro e a fare il mio compito quasi meccanicamente.", "Trovo che il mio lavoro sia una sfida positiva.", "Durante il lavoro mi sento spesso svuotato emotivamente.", "Col tempo ci si può distaccare da questo tipo di lavoro.", "Dopo il lavoro ho abbastanza energia per le mie attività del tempo libero.", "A volte i miei compiti lavorativi mi disgustano.", "Dopo il lavoro di solito mi sento esausto e sfinito.", "Questo è l'unico tipo di lavoro in cui riesco a immaginarmi.", "Di solito riesco a gestire bene la quantità del mio lavoro.", "Mi sento sempre più coinvolto nel mio lavoro.", "Quando lavoro, di solito mi sento pieno di energia."]
  },
  text: {
    it: { kicker: "Burnout", title: "Quanto ti sta consumando il lavoro?", lede: "16 affermazioni, 3 minuti. L'OLBI misura le due facce del burnout: l'esaurimento (energia finita) e il disimpegno (distacco dal lavoro). È l'alternativa libera al Maslach Burnout Inventory.", meta: ["16 domande", "~3 minuti", "2 dimensioni"], instr: "Le frasi riguardano il tuo <b>lavoro attuale</b> (o studio). Per ognuna indica quanto sei d'accordo; metà sono formulate al positivo.", how: "Due punteggi da 8 a 32 (esaurimento e disimpegno) e un totale da 16 a 64; 8 affermazioni positive sono invertite. Soglie usate in letteratura per il totale: fino a 43 basso, 44–51 moderato, 52 e oltre alto. Per le sottoscale, sopra 2,25 di media (18 su 32) l'esaurimento è alto, sopra 2,1 (17) il disimpegno. Il burnout è una condizione legata al lavoro, non un disturbo: la risposta sta nel carico, nel controllo e nel senso di quello che fai.", cite: "Demerouti, E., Bakker, A. B., Vardakou, I., & Kantas, A. (2003). The convergent validity of two burnout instruments. European Journal of Psychological Assessment, 19, 12-23. Uso libero; traduzione italiana propria." },
    en: { kicker: "Burnout", title: "How much is work wearing you down?", lede: "16 statements, 3 minutes. The OLBI measures the two faces of burnout: exhaustion (energy gone) and disengagement (distance from work). It is the free alternative to the Maslach Burnout Inventory.", meta: ["16 questions", "~3 minutes", "2 dimensions"], instr: "The statements concern your <b>current work</b> (or studies). Indicate how much you agree with each; half are positively worded.", how: "Two scores from 8 to 32 (exhaustion and disengagement) and a total from 16 to 64; 8 positive statements are reverse-keyed. Thresholds used in the literature for the total: up to 43 low, 44–51 moderate, 52 and above high. For the subscales, a mean above 2.25 (18 out of 32) is high exhaustion, above 2.1 (17) high disengagement. Burnout is a work-related condition, not a disorder: the answer lies in workload, control and the meaning of what you do.", cite: "Demerouti, E., Bakker, A. B., Vardakou, I., & Kantas, A. (2003). The convergent validity of two burnout instruments. European Journal of Psychological Assessment, 19, 12-23. Free to use." }
  },
  main: "tot",
  scales: [
    { key: "tot", name: { it: "Burnout totale", en: "Total burnout" }, items: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], mode: "sum", range: [16, 64], bands: [
      { max: 43, name: { it: "Basso", en: "Low" }, text: { it: "Il lavoro pesa nella norma: stanchezza e distacco restano gestibili.", en: "Work weighs on you within the norm: tiredness and distance remain manageable." } },
      { max: 51, name: { it: "Moderato", en: "Moderate" }, text: { it: "Segnali di logoramento: energia in calo o senso del lavoro che si affievolisce. È il momento di guardare carico, pause e margini di controllo, prima che diventi cronico.", en: "Signs of wear: energy dropping or the meaning of work fading. Time to look at load, breaks and margins of control, before it becomes chronic." } },
      { max: 64, name: { it: "Alto", en: "High" }, text: { it: "Nella fascia del burnout: esaurimento e distacco insieme. Non è debolezza, è un segnale che le condizioni vanno cambiate; parlarne con il medico e, se possibile, con chi decide il tuo carico, è la mossa giusta.", en: "In the burnout range: exhaustion and disengagement together. Not weakness, a signal that conditions must change; talking to a doctor and, if possible, to whoever sets your workload is the right move." } }] },
    { key: "ex", name: { it: "Esaurimento", en: "Exhaustion" }, items: [2,4,5,8,10,12,14,16], mode: "sum", range: [8, 32], bands: [
      { max: 17, name: { it: "Basso", en: "Low" }, text: { it: "Le energie reggono il carico.", en: "Your energy holds up under the load." } },
      { max: 32, name: { it: "Alto", en: "High" }, text: { it: "Stanchezza che non si recupera: il corpo chiede meno carico e più pausa.", en: "Tiredness that doesn't recover: the body is asking for less load and more rest." } }] },
    { key: "dis", name: { it: "Disimpegno", en: "Disengagement" }, items: [1,3,6,7,9,11,13,15], mode: "sum", range: [8, 32], bands: [
      { max: 16, name: { it: "Basso", en: "Low" }, text: { it: "Il lavoro ha ancora senso e interesse per te.", en: "Work still holds meaning and interest for you." } },
      { max: 32, name: { it: "Alto", en: "High" }, text: { it: "Ti sei distaccato: il lavoro è diventato meccanico e ne parli in negativo. Spesso è la difesa dall'esaurimento.", en: "You have disengaged: work has become mechanical and you talk about it negatively. Often it is the defence against exhaustion." } }] }
  ]
};
