/* PHQ-9 (Kroenke, Spitzer & Williams 2001) — Pfizer, uso libero senza permesso. Versione italiana ufficiale (phqscreeners). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.phq9 = {
  code: "PHQ-9", theme: "slate", sensitive: true, n: 9, values: [0, 1, 2, 3],
  labels: { en: ["Not at all", "Several days", "More than half the days", "Nearly every day"], it: ["Mai", "Alcuni giorni", "Più della metà dei giorni", "Quasi ogni giorno"] },
  items: {
    en: ["Little interest or pleasure in doing things", "Feeling down, depressed, or hopeless", "Trouble falling or staying asleep, or sleeping too much", "Feeling tired or having little energy", "Poor appetite or overeating", "Feeling bad about yourself — or that you are a failure or have let yourself or your family down", "Trouble concentrating on things, such as reading the newspaper or watching television", "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual", "Thoughts that you would be better off dead or of hurting yourself in some way"],
    it: ["Scarso interesse o piacere nel fare le cose", "Sentirsi giù, depresso o disperato", "Difficoltà ad addormentarsi o a dormire senza interruzioni, oppure dormire troppo", "Sentirsi stanco o avere poca energia", "Scarso appetito o mangiare troppo", "Avere una scarsa opinione di sé, o sentirsi un fallito o aver deluso se stesso o la propria famiglia", "Difficoltà a concentrarsi sulle cose, per esempio leggere il giornale o guardare la televisione", "Muoversi o parlare così lentamente da poter essere notato da altre persone; o al contrario, essere così irrequieto o agitato da muoversi molto più del solito", "Pensare che sarebbe meglio essere morto o farsi del male in qualche modo"]
  },
  text: {
    it: { kicker: "Umore · screening", title: "Come va l'umore, nelle ultime due settimane?", lede: "9 domande, 2 minuti. Il PHQ-9 è il questionario di screening per la depressione più usato nella medicina di base. Serve a capire se vale la pena parlarne con qualcuno, non a fare diagnosi.", meta: ["9 domande", "~2 minuti", "Screening"], instr: "Nelle <b>ultime due settimane</b>, con quale frequenza ti hanno dato fastidio i seguenti problemi?", how: "Il punteggio va da 0 a 27: 0–4 minimo, 5–9 lieve, 10–14 moderato, 15–19 moderatamente grave, 20–27 grave. Da 10 in su i medici approfondiscono con un colloquio. Un punteggio alto non è una diagnosi: dice che i sintomi ci sono e pesano. Se hai risposto diversamente da «mai» all'ultima domanda, parlane oggi con qualcuno, a prescindere dal totale.", cite: "Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: validity of a brief depression severity measure. Journal of General Internal Medicine, 16, 606-613. © Pfizer, uso libero." },
    en: { kicker: "Mood · screening", title: "How has your mood been, over the last two weeks?", lede: "9 questions, 2 minutes. The PHQ-9 is the most widely used depression screening questionnaire in primary care. It helps you see whether it is worth talking to someone; it is not a diagnosis.", meta: ["9 questions", "~2 minutes", "Screening"], instr: "Over the <b>last two weeks</b>, how often have you been bothered by the following problems?", how: "The score runs from 0 to 27: 0–4 minimal, 5–9 mild, 10–14 moderate, 15–19 moderately severe, 20–27 severe. From 10 up, clinicians follow up with an interview. A high score is not a diagnosis: it says symptoms are present and weigh on you. If you answered anything other than “not at all” to the last question, talk to someone today, regardless of the total.", cite: "Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: validity of a brief depression severity measure. Journal of General Internal Medicine, 16, 606-613. © Pfizer, free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Sintomi depressivi", en: "Depressive symptoms" }, items: [1,2,3,4,5,6,7,8,9], mode: "sum", range: [0, 27],
    bands: [
      { max: 4, name: { it: "Minimo", en: "Minimal" }, text: { it: "Sintomi minimi o assenti nelle ultime due settimane.", en: "Minimal or no symptoms over the last two weeks." } },
      { max: 9, name: { it: "Lieve", en: "Mild" }, text: { it: "Sintomi lievi: un periodo un po' pesante. Di solito si osserva come va; se continua per settimane, vale un colloquio.", en: "Mild symptoms: a somewhat heavy period. Usually one watches how it goes; if it continues for weeks, a conversation is worthwhile." } },
      { max: 14, name: { it: "Moderato", en: "Moderate" }, text: { it: "Sintomi moderati: la soglia da cui i medici approfondiscono. Parlarne con il medico di base o con uno psicologo è la mossa sensata.", en: "Moderate symptoms: the threshold at which clinicians follow up. Talking to your GP or a psychologist is the sensible move." } },
      { max: 19, name: { it: "Moderatamente grave", en: "Moderately severe" }, text: { it: "Sintomi che incidono sulla vita quotidiana. Non aspettare che passi da solo: un professionista può aiutarti, e in fretta.", en: "Symptoms that affect daily life. Don't wait for it to pass on its own: a professional can help, and quickly." } },
      { max: 27, name: { it: "Grave", en: "Severe" }, text: { it: "Sintomi gravi. Chiedi aiuto oggi: medico, psicologo o i numeri qui sotto. Non sei tenuto a farcela da solo.", en: "Severe symptoms. Ask for help today: a doctor, a psychologist or the numbers below. You don't have to manage this alone." } }
    ] }]
};
