/* PHQ-9 (Kroenke, Spitzer & Williams 2001) — Pfizer, uso libero senza permesso. Versione italiana ufficiale (phqscreeners). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.phq9 = {
  code: "PHQ-9", theme: "slate", sensitive: true, n: 9, values: [0, 1, 2, 3],
  labels: { en: ["Not at all", "Several days", "More than half the days", "Nearly every day"], it: ["Mai", "Alcuni giorni", "Più della metà dei giorni", "Quasi ogni giorno"] },
  items: {
    en: ["Little interest or pleasure in doing things", "Feeling down, depressed, or hopeless", "Trouble falling or staying asleep, or sleeping too much", "Feeling tired or having little energy", "Poor appetite or overeating", "Feeling bad about yourself — or that you are a failure or have let yourself or your family down", "Trouble concentrating on things, such as reading the newspaper or watching television", "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual", "Thoughts that you would be better off dead or of hurting yourself in some way"],
    it: ["Scarso interesse o piacere nel fare le cose", "Sentirsi giù, depresso o disperato", "Difficoltà ad addormentarsi o a dormire senza interruzioni, oppure dormire troppo", "Sentirsi stanco o avere poca energia", "Scarso appetito o mangiare troppo", "Avere una scarsa opinione di sé, o sentirsi un fallito o aver deluso se stesso o la propria famiglia", "Difficoltà a concentrarsi sulle cose, per esempio leggere il giornale o guardare la televisione", "Muoversi o parlare così lentamente da poter essere notato da altre persone; o al contrario, essere così irrequieto o agitato da muoversi molto più del solito", "Pensare che sarebbe meglio essere morto o farsi del male in qualche modo"]
  },
  text: {
    it: { kicker: "Umore · screening", title: "Come va l'umore, nelle ultime due settimane?", lede: "9 domande, 2 minuti. Il PHQ-9 è il questionario di screening per la depressione più usato nella medicina di base. Serve a capire se vale la pena parlarne con qualcuno, non a fare diagnosi.", meta: ["9 domande", "~2 minuti", "Screening"], instr: "Nelle <b>ultime due settimane</b>, con quale frequenza ti hanno dato fastidio i seguenti problemi?", how: "Il punteggio va da 0 a 27: 0–4 minimo, 5–9 lieve, 10–14 moderato, 15–19 moderatamente grave, 20–27 grave. Da 10 in su i medici approfondiscono con un colloquio. Un punteggio alto non è una diagnosi: dice che i sintomi ci sono e pesano. Se hai risposto diversamente da «mai» all'ultima domanda, parlane oggi con qualcuno, a prescindere dal totale.", cite: "Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: validity of a brief depression severity measure. Journal of General Internal Medicine, 16, 606-613. © Pfizer, uso libero." },
    en: { kicker: "Mood · screening", title: "How has your mood been, over the last two weeks?", lede: "9 questions, 2 minutes. The PHQ-9 is the most widely used depression screening questionnaire in primary care. It helps you see whether it is worth talking to someone; it is not a diagnosis.", meta: ["9 questions", "~2 minutes", "Screening"], instr: "Over the <b>last two weeks</b>, how often have you been bothered by the following problems?", how: "The score runs from 0 to 27: 0–4 minimal, 5–9 mild, 10–14 moderate, 15–19 moderately severe, 20–27 severe. From 10 up, clinicians follow up with an interview. A high score is not a diagnosis: it says symptoms are present and weigh on you. If you answered anything other than “not at all” to the last question, talk to someone today, regardless of the total.", cite: "Kroenke, K., Spitzer, R. L., & Williams, J. B. W. (2001). The PHQ-9: validity of a brief depression severity measure. Journal of General Internal Medicine, 16, 606-613. © Pfizer, free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Sintomi depressivi", en: "Depressive symptoms" }, items: [1,2,3,4,5,6,7,8,9], mode: "sum", range: [0, 27],
    bands: [
      { max: 4, name: { it: "Minimo", en: "Minimal" }, text: { it: "Sintomi minimi o assenti nelle ultime due settimane.", en: "Minimal or no symptoms over the last two weeks." } },
      { max: 9, name: { it: "Lieve", en: "Mild" }, text: { it: "Sintomi lievi: un periodo un po' pesante. Di solito si osserva come va; se continua per settimane, vale un colloquio.", en: "Mild symptoms: a somewhat heavy period. Usually one watches how it goes; if it continues for weeks, a conversation is worthwhile." } },
      { max: 14, name: { it: "Moderato", en: "Moderate" }, text: { it: "Sintomi moderati: la soglia da cui i medici approfondiscono. Parlarne con il medico di base o con uno psicologo è la mossa sensata.", en: "Moderate symptoms: the threshold at which clinicians follow up. Talking to your GP or a psychologist is the sensible move." } },
      { max: 19, name: { it: "Moderatamente grave", en: "Moderately severe" }, text: { it: "Sintomi che incidono sulla vita quotidiana. Non aspettare che passi da solo: un professionista può aiutarti, e in fretta.", en: "Symptoms that affect daily life. Don't wait for it to pass on its own: a professional can help, and quickly." } },
      { max: 27, name: { it: "Grave", en: "Severe" }, text: { it: "Sintomi gravi. Chiedi aiuto oggi: medico, psicologo o i numeri qui sotto. Non sei tenuto a farcela da solo.", en: "Severe symptoms. Ask for help today: a doctor, a psychologist or the numbers below. You don't have to manage this alone." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.phq9.approf = {
  it: {
    title: "La depressione, oltre il punteggio",
    intro: `<p>Il PHQ-9 nasce da uno strumento più grande, il <span class="t" data-tip="Primary Care Evaluation of Mental Disorders: un'intervista diagnostica strutturata degli anni '90, pensata perché il medico di base potesse riconoscere i disturbi mentali più comuni. Il PHQ ne è la versione che il paziente compila da solo.">PRIME-MD</span> di Spitzer, ridotto a un questionario che si compila da soli. La sua idea è pulita: le nove domande ricalcano <b>uno a uno</b> i nove sintomi con cui il <span class="t" data-tip="Diagnostic and Statistical Manual of Mental Disorders dell'American Psychiatric Association, il catalogo con cui si definiscono i disturbi. In Europa il riferimento parallelo è l'ICD-11 dell'OMS.">DSM</span> definisce l'<span class="t" data-tip="La depressione clinica vera e propria: umore depresso o perdita di piacere per almeno due settimane, con altri sintomi, sofferenza e compromissione della vita quotidiana.">episodio depressivo maggiore</span>. Resta però uno strumento di <span class="t" data-tip="Un filtro rapido che segnala chi merita un approfondimento, non un test che decide chi ha una malattia. Un risultato alto è un invito a parlarne, non un verdetto.">screening</span>: dice se i sintomi ci sono e quanto pesano, non se hai una diagnosi.</p>`,
    blocks: [
      { h: "Nove sintomi, una diagnosi", html: `<p>Il DSM chiede almeno cinque dei nove sintomi presenti per almeno due settimane, e almeno uno dei due <span class="t" data-tip="I due sintomi senza i quali non si parla di depressione maggiore: l'umore depresso e l'anedonia. Gli altri sette si aggiungono a questi, non li sostituiscono.">sintomi cardine</span> — umore depresso o perdita di piacere — deve esserci. Le prime due domande del PHQ-9 misurano proprio questi due; le altre sette coprono sonno, appetito, energia, concentrazione, autovalutazione, rallentamento o agitazione e pensieri di morte. Per questo il punteggio non è arbitrario: chi lo ottiene alto tende ad avere davvero il quadro che il manuale descrive. Ma il questionario conta i sintomi, non li interpreta: solo un colloquio può escludere altre cause e confermare.</p>` },
      { h: "Le soglie e cosa misurano", html: `<p>Il totale va da 0 a 27, con quattro gradini: 5 (lieve), 10 (moderato), 15 (moderatamente grave), 20 (grave). La soglia che pesa di più è <b>10</b>: da lì in su conviene approfondire. A quel <span class="t" data-tip="Il valore soglia oltre il quale il risultato è considerato positivo. Abbassarlo trova più casi veri ma anche più falsi allarmi; alzarlo fa il contrario.">cut-off</span> il PHQ-9 mostra buona <span class="t" data-tip="La capacità di individuare chi ha davvero il disturbo, cioè pochi casi che sfuggono.">sensibilità</span> e buona <span class="t" data-tip="La capacità di escludere chi non ha il disturbo, cioè pochi falsi allarmi.">specificità</span> (entrambe intorno all'88% nello studio originale). Le soglie non trasformano un numero in una malattia: dicono quanto i sintomi si allontanano dalla media e quanto è sensato andare a fondo.</p>` },
      { h: "L'anedonia, il segnale più affidabile", html: `<p>La prima domanda — scarso interesse o piacere nel fare le cose — misura l'<span class="t" data-tip="Dal greco senza piacere: la perdita della capacità di provare gusto per cose che prima piacevano. È spesso il primo segnale e il più specifico della depressione, più del pianto.">anedonia</span>, ed è spesso l'indicatore più utile. La tristezza è un'emozione che tutti provano; l'anedonia è lo spegnimento del piacere e della spinta, e distingue meglio un calo passeggero da qualcosa di clinico. Non è pigrizia né debolezza di volontà: è il motore della motivazione che gira a vuoto. Quando qualcuno smette di cercare ciò che gli piaceva, quel segnale pesa più di quanto sembri.</p>` },
      { h: "La domanda 9", html: `<p>L'ultima domanda riguarda i <span class="t" data-tip="Pensieri che sarebbe meglio essere morti o di farsi del male. Sono più comuni di quanto si creda e non significano che una persona agirà, ma vanno sempre presi sul serio e mai lasciati soli.">pensieri di morte o di farsi del male</span>. Va letta a parte: qualunque risposta diversa da mai merita attenzione <b>a prescindere dal totale</b>. Da sola non predice cosa farà una persona, ma è un segnale da non ignorare mai. Se ti riconosci in questa domanda, parlane oggi con qualcuno di cui ti fidi, con il medico o con una linea di ascolto: non è un peso da reggere da solo.</p>` }
    ],
    beyond: `<ul>
      <li><b>La sovrapposizione con il corpo.</b> Sonno, appetito, energia e concentrazione cambiano anche in molte malattie fisiche e in gravidanza. In chi ha una patologia medica il PHQ-9 può gonfiarsi senza che ci sia depressione: il numero va sempre letto nel contesto.</li>
      <li><b>Le versioni più corte.</b> Le prime due domande da sole formano il PHQ-2, uno screening ultra-rapido: se scatta, si prosegue con le altre sette. È il filtro usato in molti ambulatori quando il tempo è poco.</li>
      <li><b>Uno stato, non un tratto.</b> La depressione è per lo più episodica e tende a tornare; il PHQ-9 fotografa le ultime due settimane. Ripeterlo nel tempo serve a seguire l'andamento, non a incollare un'etichetta.</li>
      <li><b>Si tratta, e bene.</b> Per le forme lievi-moderate psicoterapia e farmaci hanno efficacia simile e insieme fanno meglio; anche l'esercizio fisico ha effetti reali. Il senso dello screening è arrivarci presto.</li>
    </ul>`,
    taratura: `<p>Il PHQ-9 è tra gli strumenti di screening più validati e usati al mondo, con buona attendibilità e soglie replicate in molte lingue. Due limiti onesti. Primo: è uno screening, non una diagnosi. Nella popolazione generale, dove la depressione è meno frequente, molti punteggi sopra 10 non corrispondono a un episodio depressivo maggiore, perché il <span class="t" data-tip="La probabilità che, con un test positivo, la persona abbia davvero il disturbo. Cala quando il disturbo è raro nel gruppo esaminato: per questo lo screening va sempre confermato.">valore predittivo positivo</span> scende quando si passa dall'ambulatorio alla popolazione generale. Secondo: è un'autodescrizione, sensibile all'umore del momento e al modo in cui il disagio si esprime in culture diverse. Serve per aprire una conversazione, non per chiuderla.</p>`,
    reading: [
      "Kroenke, K., Spitzer, R. L. & Williams, J. B. W. (2001). The PHQ-9. <em>Journal of General Internal Medicine</em>, 16, 606-613.",
      "Manea, L., Gilbody, S. & McMillan, D. (2012). Optimal cut-off score for the PHQ-9. <em>CMAJ</em>, 184, E191-E196.",
      "Frances, A., <em>Saving Normal</em> (2013). Sull'inflazione diagnostica e sui limiti delle etichette."
    ]
  },
  en: {
    title: "Depression, beyond the score",
    intro: `<p>The PHQ-9 comes from a larger instrument, Spitzer's <span class="t" data-tip="Primary Care Evaluation of Mental Disorders: a structured diagnostic interview from the 1990s, built so a family doctor could recognise the commonest mental disorders. The PHQ is the version the patient fills in alone.">PRIME-MD</span>, boiled down to a self-report questionnaire. Its idea is clean: the nine questions map <b>one to one</b> onto the nine symptoms the <span class="t" data-tip="Diagnostic and Statistical Manual of Mental Disorders of the American Psychiatric Association, the catalogue that defines disorders. In Europe the parallel reference is the WHO's ICD-11.">DSM</span> uses to define a <span class="t" data-tip="Clinical depression proper: depressed mood or loss of pleasure for at least two weeks, with other symptoms, distress and impairment of daily life.">major depressive episode</span>. It stays, though, a <span class="t" data-tip="A quick filter that flags who deserves a closer look, not a test that decides who has an illness. A high result is an invitation to talk, not a verdict.">screening</span> tool: it says whether symptoms are present and how much they weigh, not whether you have a diagnosis.</p>`,
    blocks: [
      { h: "Nine symptoms, one diagnosis", html: `<p>The DSM asks for at least five of nine symptoms present for at least two weeks, and at least one of the two <span class="t" data-tip="The two symptoms without which there is no major depression: depressed mood and anhedonia. The other seven add to these, they don't replace them.">cardinal symptoms</span> — depressed mood or loss of pleasure — must be there. The first two PHQ-9 questions measure exactly those two; the other seven cover sleep, appetite, energy, concentration, self-worth, slowing or agitation, and thoughts of death. So the score is not arbitrary: a high scorer tends to genuinely show the picture the manual describes. But the questionnaire counts symptoms, it doesn't interpret them: only an interview can rule out other causes and confirm.</p>` },
      { h: "The thresholds and what they measure", html: `<p>The total runs from 0 to 27, in four steps: 5 (mild), 10 (moderate), 15 (moderately severe), 20 (severe). The threshold that matters most is <b>10</b>: from there up, following up is advised. At that <span class="t" data-tip="The threshold above which a result counts as positive. Lowering it finds more true cases but also more false alarms; raising it does the reverse.">cut-off</span> the PHQ-9 shows good <span class="t" data-tip="The ability to catch those who really have the disorder, so few cases slip through.">sensitivity</span> and good <span class="t" data-tip="The ability to rule out those who don't have the disorder, so few false alarms.">specificity</span> (both around 88% in the original study). The thresholds don't turn a number into an illness: they say how far the symptoms sit from the average, and how reasonable it is to look deeper.</p>` },
      { h: "Anhedonia, the most reliable sign", html: `<p>The first question — little interest or pleasure in doing things — measures <span class="t" data-tip="From the Greek for without pleasure: the loss of the capacity to enjoy things that used to please. It is often the first and most specific sign of depression, more than tears.">anhedonia</span>, and it is often the most useful indicator. Sadness is an emotion everyone feels; anhedonia is the switching-off of pleasure and drive, and it separates a passing dip from something clinical better. It isn't laziness or weak will: it is the engine of motivation running empty. When someone stops seeking what they used to enjoy, that sign weighs more than it seems.</p>` },
      { h: "Question 9", html: `<p>The last question is about <span class="t" data-tip="Thoughts that you would be better off dead or of hurting yourself. They are more common than people think and do not mean a person will act, but they must always be taken seriously and never left alone.">thoughts of death or self-harm</span>. Read it on its own: any answer other than not at all deserves attention <b>regardless of the total</b>. Alone it does not predict what a person will do, but it is a signal never to ignore. If this question describes you, talk to someone you trust, a doctor, or a helpline today: it is not a weight to carry alone.</p>` }
    ],
    beyond: `<ul>
      <li><b>Overlap with the body.</b> Sleep, appetite, energy and concentration also change in many physical illnesses and in pregnancy. In people with a medical condition the PHQ-9 can inflate without depression being present: the number must always be read in context.</li>
      <li><b>The shorter versions.</b> The first two questions alone form the PHQ-2, an ultra-quick screen: if it triggers, you go on to the other seven. It is the filter used in many clinics when time is short.</li>
      <li><b>A state, not a trait.</b> Depression is mostly episodic and tends to return; the PHQ-9 photographs the last two weeks. Repeating it over time tracks the trend, it doesn't glue on a label.</li>
      <li><b>It is treatable, and well.</b> For mild-to-moderate forms psychotherapy and medication work about equally and do better together; exercise has real effects too. The point of screening is to get there early.</li>
    </ul>`,
    taratura: `<p>The PHQ-9 is among the most validated and widely used screening tools in the world, with good reliability and thresholds replicated across many languages. Two honest limits. First: it is a screen, not a diagnosis. In the general population, where depression is less frequent, many scores above 10 do not correspond to a major depressive episode, because the <span class="t" data-tip="The probability that, given a positive test, the person truly has the disorder. It drops when the disorder is rare in the group tested: this is why screening must always be confirmed.">positive predictive value</span> falls as you move from the clinic to the general population. Second: it is a self-report, sensitive to today's mood and to how distress is expressed across cultures. It is for opening a conversation, not closing one.</p>`,
    reading: [
      "Kroenke, K., Spitzer, R. L. & Williams, J. B. W. (2001). The PHQ-9. <em>Journal of General Internal Medicine</em>, 16, 606-613.",
      "Manea, L., Gilbody, S. & McMillan, D. (2012). Optimal cut-off score for the PHQ-9. <em>CMAJ</em>, 184, E191-E196.",
      "Frances, A., <em>Saving Normal</em> (2013). On diagnostic inflation and the limits of labels."
    ]
  },
  pt: {
    title: "A depressão, além da pontuação",
    intro: `<p>O PHQ-9 nasce de um instrumento maior, o <span class="t" data-tip="Primary Care Evaluation of Mental Disorders: uma entrevista diagnóstica estruturada dos anos 90, pensada para que o médico de família reconhecesse os transtornos mentais mais comuns. O PHQ é a versão que o paciente preenche sozinho.">PRIME-MD</span> de Spitzer, reduzido a um questionário de autopreenchimento. A ideia é limpa: as nove perguntas correspondem <b>uma a uma</b> aos nove sintomas com que o <span class="t" data-tip="Diagnostic and Statistical Manual of Mental Disorders da Associação Psiquiátrica Americana, o catálogo que define os transtornos. Na Europa a referência paralela é a CID-11 da OMS.">DSM</span> define o <span class="t" data-tip="A depressão clínica propriamente dita: humor deprimido ou perda de prazer por pelo menos duas semanas, com outros sintomas, sofrimento e prejuízo na vida diária.">episódio depressivo maior</span>. Mas continua sendo um instrumento de <span class="t" data-tip="Um filtro rápido que sinaliza quem merece uma avaliação mais detalhada, não um teste que decide quem tem uma doença. Um resultado alto é um convite a conversar, não um veredito.">triagem</span>: diz se os sintomas existem e o quanto pesam, não se você tem um diagnóstico.</p>`,
    blocks: [
      { h: "Nove sintomas, um diagnóstico", html: `<p>O DSM exige pelo menos cinco dos nove sintomas presentes por pelo menos duas semanas, e ao menos um dos dois <span class="t" data-tip="Os dois sintomas sem os quais não se fala em depressão maior: o humor deprimido e a anedonia. Os outros sete se somam a eles, não os substituem.">sintomas cardinais</span> — humor deprimido ou perda de prazer — deve estar presente. As duas primeiras perguntas do PHQ-9 medem justamente esses dois; as outras sete cobrem sono, apetite, energia, concentração, autoavaliação, lentidão ou agitação e pensamentos de morte. Por isso a pontuação não é arbitrária: quem pontua alto tende a apresentar de fato o quadro que o manual descreve. Mas o questionário conta os sintomas, não os interpreta: só uma entrevista pode excluir outras causas e confirmar.</p>` },
      { h: "As faixas e o que medem", html: `<p>O total vai de 0 a 27, em quatro degraus: 5 (leve), 10 (moderado), 15 (moderadamente grave), 20 (grave). A faixa que mais pesa é <b>10</b>: dali para cima recomenda-se aprofundar. Nesse <span class="t" data-tip="O valor limiar acima do qual o resultado é considerado positivo. Baixá-lo encontra mais casos verdadeiros, mas também mais alarmes falsos; elevá-lo faz o contrário.">ponto de corte</span> o PHQ-9 mostra boa <span class="t" data-tip="A capacidade de identificar quem realmente tem o transtorno, ou seja, poucos casos escapam.">sensibilidade</span> e boa <span class="t" data-tip="A capacidade de excluir quem não tem o transtorno, ou seja, poucos alarmes falsos.">especificidade</span> (ambas em torno de 88% no estudo original). As faixas não transformam um número em doença: dizem o quanto os sintomas se afastam da média e o quanto faz sentido investigar.</p>` },
      { h: "A anedonia, o sinal mais confiável", html: `<p>A primeira pergunta — pouco interesse ou prazer em fazer as coisas — mede a <span class="t" data-tip="Do grego sem prazer: a perda da capacidade de sentir gosto por coisas que antes agradavam. É muitas vezes o primeiro e mais específico sinal da depressão, mais que o choro.">anedonia</span>, e costuma ser o indicador mais útil. A tristeza é uma emoção que todos sentem; a anedonia é o desligamento do prazer e do impulso, e distingue melhor uma queda passageira de algo clínico. Não é preguiça nem falta de vontade: é o motor da motivação girando em falso. Quando alguém deixa de procurar o que lhe agradava, esse sinal pesa mais do que parece.</p>` },
      { h: "A pergunta 9", html: `<p>A última pergunta trata dos <span class="t" data-tip="Pensamentos de que seria melhor estar morto ou de se ferir. São mais comuns do que se pensa e não significam que a pessoa vá agir, mas devem sempre ser levados a sério e nunca deixados de lado.">pensamentos de morte ou de se ferir</span>. Deve ser lida à parte: qualquer resposta diferente de nunca merece atenção <b>independentemente do total</b>. Sozinha não prevê o que a pessoa fará, mas é um sinal que nunca se ignora. Se você se reconhece nessa pergunta, converse hoje com alguém de confiança, com o médico ou com uma linha de apoio: não é um peso para carregar sozinho.</p>` }
    ],
    beyond: `<ul>
      <li><b>A sobreposição com o corpo.</b> Sono, apetite, energia e concentração também mudam em muitas doenças físicas e na gravidez. Em quem tem uma condição médica o PHQ-9 pode inflar sem que haja depressão: o número deve sempre ser lido no contexto.</li>
      <li><b>As versões mais curtas.</b> As duas primeiras perguntas sozinhas formam o PHQ-2, uma triagem ultrarrápida: se dispara, segue-se com as outras sete. É o filtro usado em muitos serviços quando o tempo é curto.</li>
      <li><b>Um estado, não um traço.</b> A depressão é em geral episódica e tende a voltar; o PHQ-9 fotografa as últimas duas semanas. Repeti-lo ao longo do tempo acompanha a evolução, não cola um rótulo.</li>
      <li><b>Tem tratamento, e bom.</b> Nas formas leves a moderadas psicoterapia e medicação têm eficácia parecida e juntas funcionam melhor; o exercício físico também tem efeitos reais. O sentido da triagem é chegar cedo.</li>
    </ul>`,
    taratura: `<p>O PHQ-9 está entre os instrumentos de triagem mais validados e usados no mundo, com boa confiabilidade e faixas replicadas em muitas línguas. Dois limites honestos. Primeiro: é uma triagem, não um diagnóstico. Na população geral, onde a depressão é menos frequente, muitas pontuações acima de 10 não correspondem a um episódio depressivo maior, porque o <span class="t" data-tip="A probabilidade de que, com um teste positivo, a pessoa realmente tenha o transtorno. Cai quando o transtorno é raro no grupo avaliado: por isso a triagem deve sempre ser confirmada.">valor preditivo positivo</span> diminui ao passar do consultório para a população geral. Segundo: é uma autodescrição, sensível ao humor do momento e ao modo como o sofrimento se expressa em culturas diferentes. Serve para abrir uma conversa, não para encerrá-la.</p>`,
    reading: [
      "Kroenke, K., Spitzer, R. L. & Williams, J. B. W. (2001). The PHQ-9. <em>Journal of General Internal Medicine</em>, 16, 606-613.",
      "Manea, L., Gilbody, S. & McMillan, D. (2012). Optimal cut-off score for the PHQ-9. <em>CMAJ</em>, 184, E191-E196.",
      "Frances, A., <em>Saving Normal</em> (2013). Sobre a inflação diagnóstica e os limites dos rótulos."
    ]
  }
};
