/* Perceived Stress Scale, PSS-10 (Cohen, Kamarck & Mermelstein 1983; Cohen & Williamson 1988) — libero per uso non profit. IT: Mondo, Sechi & Cabras (2019). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.pss10 = {
  code: "PSS-10", theme: "ocean", n: 10, values: [0, 1, 2, 3, 4], reverse: [4, 5, 7, 8],
  labels: {
    en: ["Never", "Almost never", "Sometimes", "Fairly often", "Very often"],
    it: ["Mai", "Quasi mai", "Qualche volta", "Abbastanza spesso", "Molto spesso"]
  },
  items: {
    en: ["In the last month, how often have you been upset because of something that happened unexpectedly?", "In the last month, how often have you felt that you were unable to control the important things in your life?", "In the last month, how often have you felt nervous and stressed?", "In the last month, how often have you felt confident about your ability to handle your personal problems?", "In the last month, how often have you felt that things were going your way?", "In the last month, how often have you found that you could not cope with all the things that you had to do?", "In the last month, how often have you been able to control irritations in your life?", "In the last month, how often have you felt that you were on top of things?", "In the last month, how often have you been angered because of things that were outside of your control?", "In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?"],
    it: ["Nell'ultimo mese, quanto spesso ti sei sentito turbato per qualcosa che è successo inaspettatamente?", "Nell'ultimo mese, quanto spesso hai sentito di non riuscire a controllare le cose importanti della tua vita?", "Nell'ultimo mese, quanto spesso ti sei sentito nervoso e stressato?", "Nell'ultimo mese, quanto spesso ti sei sentito sicuro della tua capacità di gestire i tuoi problemi personali?", "Nell'ultimo mese, quanto spesso hai sentito che le cose stavano andando per il verso giusto?", "Nell'ultimo mese, quanto spesso hai scoperto di non riuscire a far fronte a tutte le cose che dovevi fare?", "Nell'ultimo mese, quanto spesso sei riuscito a controllare le irritazioni della tua vita?", "Nell'ultimo mese, quanto spesso hai sentito di avere tutto sotto controllo?", "Nell'ultimo mese, quanto spesso ti sei arrabbiato per cose che erano fuori dal tuo controllo?", "Nell'ultimo mese, quanto spesso hai sentito che le difficoltà si accumulavano al punto da non riuscire a superarle?"]
  },
  text: {
    it: { kicker: "Stress percepito", title: "Quanto ti senti sotto pressione?", lede: "10 domande, 2 minuti. La PSS di Cohen misura quanto, nell'ultimo mese, hai sentito la tua vita imprevedibile, incontrollabile e sovraccarica.", meta: ["10 domande", "~2 minuti"], instr: "Le domande riguardano i tuoi sentimenti e pensieri <b>nell'ultimo mese</b>. Per ognuna indica quanto spesso ti sei sentito o hai pensato in quel modo. Rispondi velocemente: conta l'impressione complessiva.", how: "Il punteggio va da 0 a 40 (quattro domande sono invertite). Fasce di uso comune: 0–13 stress basso, 14–26 moderato, 27–40 alto. La media nella popolazione generale è intorno a 13–16 e sale nei periodi difficili: la PSS misura lo stato del mese, non un tratto stabile.", cite: "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24, 385-396. Uso libero non profit." },
    en: { kicker: "Perceived stress", title: "How much pressure are you under?", lede: "10 questions, 2 minutes. Cohen's PSS measures how unpredictable, uncontrollable and overloaded your life has felt over the last month.", meta: ["10 questions", "~2 minutes"], instr: "The questions ask about your feelings and thoughts <b>during the last month</b>. For each, indicate how often you felt or thought that way. Answer quickly: the overall impression is what counts.", how: "The score runs from 0 to 40 (four questions are reverse-keyed). Commonly used bands: 0–13 low stress, 14–26 moderate, 27–40 high. The general-population mean is around 13–16 and rises in hard times: the PSS measures this month's state, not a stable trait.", cite: "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24, 385-396. Free for non-profit use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Stress percepito", en: "Perceived stress" }, items: [1,2,3,4,5,6,7,8,9,10], mode: "sum", range: [0, 40],
    bands: [
      { max: 13, name: { it: "Basso", en: "Low" }, text: { it: "Nell'ultimo mese hai sentito la vita abbastanza prevedibile e gestibile.", en: "Over the last month life has felt fairly predictable and manageable." } },
      { max: 26, name: { it: "Moderato", en: "Moderate" }, text: { it: "Un carico di stress nella norma o un po' sopra: qualche momento in cui le cose sembravano sfuggire di mano. Guarda cosa lo alimenta e cosa puoi lasciar andare.", en: "A normal or slightly elevated stress load: some moments when things seemed to slip out of hand. Look at what feeds it and what you can let go." } },
      { max: 40, name: { it: "Alto", en: "High" }, text: { it: "Stress alto: la vita è sembrata imprevedibile e sovraccarica per gran parte del mese. Se dura, il corpo e il sonno ne risentono: chiedere aiuto o alleggerire qualcosa è la mossa giusta.", en: "High stress: life has felt unpredictable and overloaded for much of the month. If it lasts, body and sleep suffer: asking for help or lightening the load is the right move." } }
    ] }]
};
