/* Perceived Stress Scale, PSS-10 (Cohen, Kamarck & Mermelstein 1983; Cohen & Williamson 1988) — libero per uso non profit. IT: Mondo, Sechi & Cabras (2019). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.pss10 = {
  code: "PSS-10", theme: "ocean", n: 10, values: [0, 1, 2, 3, 4], reverse: [4, 5, 7, 8],
  labels: {
    en: ["Never", "Almost never", "Sometimes", "Fairly often", "Very often"],
    it: ["Mai", "Quasi mai", "Qualche volta", "Abbastanza spesso", "Molto spesso"]
  },
  items: {
    en: ["In the last month, how often have you been upset because of something that happened unexpectedly?", "In the last month, how often have you felt that you were unable to control the important things in your life?", "In the last month, how often have you felt nervous and stressed?", "In the last month, how often have you felt confident about your ability to handle your personal problems?", "In the last month, how often have you felt that things were going your way?", "In the last month, how often have you found that you could not cope with all the things that you had to do?", "In the last month, how often have you been able to control irritations in your life?", "In the last month, how often have you felt that you were on top of things?", "In the last month, how often have you been angered because of things that were outside of your control?", "In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?"],
    it: ["Nell'ultimo mese, quanto spesso ti sei sentito turbato per qualcosa che è successo inaspettatamente?", "Nell'ultimo mese, quanto spesso hai sentito di non riuscire a controllare le cose importanti della tua vita?", "Nell'ultimo mese, quanto spesso ti sei sentito nervoso e stressato?", "Nell'ultimo mese, quanto spesso ti sei sentito sicuro della tua capacità di gestire i tuoi problemi personali?", "Nell'ultimo mese, quanto spesso hai sentito che le cose stavano andando per il verso giusto?", "Nell'ultimo mese, quanto spesso hai scoperto di non riuscire a far fronte a tutte le cose che dovevi fare?", "Nell'ultimo mese, quanto spesso sei riuscito a controllare le irritazioni della tua vita?", "Nell'ultimo mese, quanto spesso hai sentito di avere tutto sotto controllo?", "Nell'ultimo mese, quanto spesso ti sei arrabbiato per cose che erano fuori dal tuo controllo?", "Nell'ultimo mese, quanto spesso hai sentito che le difficoltà si accumulavano al punto da non riuscire a superarle?"]
  },
  text: {
    it: { kicker: "Stress percepito", title: "Quanto ti senti sotto pressione?", lede: "10 domande, 2 minuti. La PSS di Cohen misura quanto, nell'ultimo mese, hai sentito la tua vita imprevedibile, incontrollabile e sovraccarica.", meta: ["10 domande", "~2 minuti"], instr: "Le domande riguardano i tuoi sentimenti e pensieri <b>nell'ultimo mese</b>. Per ognuna indica quanto spesso ti sei sentito o hai pensato in quel modo. Rispondi velocemente: conta l'impressione complessiva.", how: "Il punteggio va da 0 a 40 (quattro domande sono invertite). Fasce di uso comune: 0–13 stress basso, 14–26 moderato, 27–40 alto. La media nella popolazione generale è intorno a 13–16 e sale nei periodi difficili: la PSS misura lo stato del mese, non un tratto stabile.", cite: "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24, 385-396. Uso libero non profit." },
    en: { kicker: "Perceived stress", title: "How much pressure are you under?", lede: "10 questions, 2 minutes. Cohen's PSS measures how unpredictable, uncontrollable and overloaded your life has felt over the last month.", meta: ["10 questions", "~2 minutes"], instr: "The questions ask about your feelings and thoughts <b>during the last month</b>. For each, indicate how often you felt or thought that way. Answer quickly: the overall impression is what counts.", how: "The score runs from 0 to 40 (four questions are reverse-keyed). Commonly used bands: 0–13 low stress, 14–26 moderate, 27–40 high. The general-population mean is around 13–16 and rises in hard times: the PSS measures this month's state, not a stable trait.", cite: "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24, 385-396. Free for non-profit use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Stress percepito", en: "Perceived stress" }, items: [1,2,3,4,5,6,7,8,9,10], mode: "sum", range: [0, 40],
    bands: [
      { max: 13, name: { it: "Basso", en: "Low" }, text: { it: "Nell'ultimo mese hai sentito la vita abbastanza prevedibile e gestibile.", en: "Over the last month life has felt fairly predictable and manageable." } },
      { max: 26, name: { it: "Moderato", en: "Moderate" }, text: { it: "Un carico di stress nella norma o un po' sopra: qualche momento in cui le cose sembravano sfuggire di mano. Guarda cosa lo alimenta e cosa puoi lasciar andare.", en: "A normal or slightly elevated stress load: some moments when things seemed to slip out of hand. Look at what feeds it and what you can let go." } },
      { max: 40, name: { it: "Alto", en: "High" }, text: { it: "Stress alto: la vita è sembrata imprevedibile e sovraccarica per gran parte del mese. Se dura, il corpo e il sonno ne risentono: chiedere aiuto o alleggerire qualcosa è la mossa giusta.", en: "High stress: life has felt unpredictable and overloaded for much of the month. If it lasts, body and sleep suffer: asking for help or lightening the load is the right move." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.pss10.approf = {
  it: {
    title: "Lo stress percepito, non quello reale",
    intro: `<p>La PSS di Cohen ha un'idea precisa: non misura quanto ti succede, ma quanto <b>senti</b> di poterlo gestire. Poggia sulla teoria di <span class="t" data-tip="Richard Lazarus (1922-2002), psicologo che ridefinì lo stress come una transazione tra persona e ambiente: non l'evento in sé, ma il giudizio che ne diamo.">Lazarus</span>, secondo cui lo stress nasce dalla <span class="t" data-tip="La valutazione cognitiva (appraisal): il giudizio automatico su quanto una situazione sia minacciosa e su quanto ci sentiamo capaci di affrontarla. È questo giudizio, non l'evento, a generare lo stress.">valutazione</span> che facciamo di una situazione. Per questo è uno strumento di <span class="t" data-tip="Un filtro che misura un vissuto soggettivo, non un test diagnostico. Fotografa quanto pesa il mese, non se hai un disturbo.">screening</span> del vissuto, non un contatore di eventi.</p>`,
    blocks: [
      { h: "Non conta cosa ti succede, ma come lo leggi", html: `<p>Per Lazarus la stessa situazione stressa persone diverse in modo diverso, a seconda di due giudizi rapidi e automatici: la <span class="t" data-tip="Il primo giudizio: questa situazione è una minaccia, una perdita o una sfida per me?">valutazione primaria</span> — è una minaccia? — e la <span class="t" data-tip="Il secondo giudizio: ho le risorse per farcela? Quando la risposta è no, lo stress sale, a parità di evento.">valutazione secondaria</span> — riesco a farcela? Lo stress nasce dallo squilibrio tra le richieste percepite e le risorse percepite. La PSS misura il risultato di questi giudizi, non gli eventi che li hanno innescati.</p>` },
      { h: "Le tre parole chiave", html: `<p>Cohen ha costruito le domande intorno a tre ingredienti che rendono stressante una richiesta: l'<span class="t" data-tip="Quando non si sa cosa aspettarsi. L'incertezza tiene il corpo in allerta più della difficoltà stessa.">imprevedibilità</span>, l'<span class="t" data-tip="Quando si sente di non avere le leve per cambiare le cose. È il fattore più tossico: lo stress incontrollabile logora più di quello intenso ma gestibile.">incontrollabilità</span> e il <span class="t" data-tip="Quando le richieste superano le risorse disponibili — troppe cose, troppo poco tempo o energia.">sovraccarico</span>. Non è l'intensità di un evento a pesare di più, ma il senso di non poterlo prevedere né controllare. È questa la firma dello stress che fa male nel tempo.</p>` },
      { h: "Gli item invertiti", html: `<p>Metà delle domande sono formulate al positivo — quanto ti sei sentito sicuro di gestire i problemi, quanto hai sentito di avere tutto sotto controllo — e vengono <span class="t" data-tip="Domande scritte al positivo, il cui punteggio viene ribaltato prima di sommarlo. Servono a misurare non solo la pressione sentita, ma anche il senso di padronanza, e a smascherare chi risponde in automatico.">conteggiate al contrario</span>. Così la scala misura due cose insieme: la pressione percepita e il senso di padronanza. Chi si sente sotto pressione ma capace ottiene un profilo diverso da chi si sente travolto e impotente.</p>` },
      { h: "Percezione, non misura oggettiva", html: `<p>È la forza e il limite dello strumento. Due persone con la stessa vita possono ottenere punteggi diversi, perché la PSS cattura il <b>carico soggettivo</b> — ed è proprio quello che incide su sonno, umore e corpo, più degli eventi contati da fuori. Ma non è un misuratore oggettivo di stress: un punteggio alto dice che stai vivendo il mese come pesante, non che la tua vita sia oggettivamente più dura di un'altra.</p>` }
    ],
    beyond: `<ul>
      <li><b>Uno stato, non un tratto.</b> Le domande riguardano l'ultimo mese; il punteggio sale e scende con i periodi. La media nella popolazione generale si aggira intorno a 13-16 e cresce nei momenti difficili.</li>
      <li><b>La percezione conta per la salute.</b> Lo stress percepito è associato a esiti fisici (sonno, sistema immunitario, cuore), a volte più degli stressori oggettivi. Sono però associazioni correlazionali, non prove che la percezione da sola causi la malattia.</li>
      <li><b>La valutazione si può allenare.</b> La <span class="t" data-tip="Rivalutazione cognitiva: rileggere una situazione in modo meno minaccioso o più gestibile. È una delle strategie di regolazione emotiva con più supporto.">rivalutazione</span> — leggere una situazione come sfida invece che come minaccia — abbassa lo stress percepito senza cambiare gli eventi.</li>
      <li><b>Esistono versioni più corte.</b> La PSS ha anche forme a 4 e 14 item; la 10 è quella con il miglior equilibrio tra brevità e affidabilità.</li>
    </ul>`,
    taratura: `<p>La PSS-10 è tra le misure di stress percepito più usate al mondo, con buona attendibilità e norme in molte lingue. Due limiti onesti. Primo: misura una percezione, e si sovrappone all'<span class="t" data-tip="Il tratto di personalità che descrive la tendenza a provare emozioni negative. Chi è alto tende a riferire più stress percepito a parità di eventi.">affetto negativo</span> e al nevroticismo — chi tende a vedere nero riporta più stress a parità di situazione. Secondo: si discute se sommarla in un unico totale o leggerla come due fattori (pressione e padronanza, per via degli item invertiti). Non è uno strumento clinico né diagnostico: descrive l'intensità del vissuto del mese, utile a guardarsi e, se serve, a parlarne con un professionista.</p>`,
    reading: [
      "Cohen, S., Kamarck, T. & Mermelstein, R. (1983). A global measure of perceived stress. <em>Journal of Health and Social Behavior</em>, 24, 385-396.",
      "Cohen, S. & Williamson, G. (1988). Perceived stress in a probability sample of the US. In <em>The Social Psychology of Health</em>.",
      "Lazarus, R. S. & Folkman, S. (1984). <em>Stress, Appraisal, and Coping</em>. Springer."
    ]
  },
  en: {
    title: "Perceived stress, not the real kind",
    intro: `<p>Cohen's PSS has a precise idea: it does not measure how much happens to you, but how much you <b>feel</b> able to handle it. It rests on <span class="t" data-tip="Richard Lazarus (1922-2002), the psychologist who redefined stress as a transaction between person and environment: not the event itself, but the judgement we make of it.">Lazarus</span>'s theory, in which stress arises from the <span class="t" data-tip="Cognitive appraisal: the automatic judgement of how threatening a situation is and how able we feel to face it. It is this judgement, not the event, that generates stress.">appraisal</span> we make of a situation. So it is a <span class="t" data-tip="A filter that measures a subjective experience, not a diagnostic test. It photographs how heavy the month feels, not whether you have a disorder.">screening</span> tool for the experience, not an event counter.</p>`,
    blocks: [
      { h: "It's not what happens, but how you read it", html: `<p>For Lazarus the same situation stresses different people differently, depending on two quick, automatic judgements: <span class="t" data-tip="The first judgement: is this situation a threat, a loss or a challenge for me?">primary appraisal</span> — is it a threat? — and <span class="t" data-tip="The second judgement: do I have the resources to cope? When the answer is no, stress rises, for the same event.">secondary appraisal</span> — can I cope? Stress arises from the imbalance between perceived demands and perceived resources. The PSS measures the result of these judgements, not the events that set them off.</p>` },
      { h: "The three key words", html: `<p>Cohen built the questions around three ingredients that make a demand stressful: <span class="t" data-tip="When you can't tell what to expect. Uncertainty keeps the body on alert more than the difficulty itself.">unpredictability</span>, <span class="t" data-tip="When you feel you have no levers to change things. It is the most toxic factor: uncontrollable stress wears you down more than intense but manageable stress.">uncontrollability</span> and <span class="t" data-tip="When demands exceed available resources — too many things, too little time or energy.">overload</span>. It is not the intensity of an event that weighs most, but the sense of not being able to predict or control it. That is the signature of the stress that harms over time.</p>` },
      { h: "The reverse items", html: `<p>Half the questions are positively worded — how confident you felt in handling problems, how much you felt on top of things — and are <span class="t" data-tip="Positively worded questions whose scores are flipped before summing. They measure not just felt pressure but the sense of mastery, and expose those answering on autopilot.">reverse-scored</span>. So the scale measures two things at once: felt pressure and a sense of mastery. Someone who feels under pressure but capable gets a different profile from someone who feels overwhelmed and powerless.</p>` },
      { h: "Perception, not an objective measure", html: `<p>This is the tool's strength and its limit. Two people with the same life can score differently, because the PSS captures the <b>subjective load</b> — and that is exactly what affects sleep, mood and body, more than events counted from outside. But it is not an objective stress meter: a high score says you are experiencing the month as heavy, not that your life is objectively harder than someone else's.</p>` }
    ],
    beyond: `<ul>
      <li><b>A state, not a trait.</b> The questions ask about the last month; the score rises and falls with the period. The general-population mean sits around 13-16 and climbs in hard times.</li>
      <li><b>Perception matters for health.</b> Perceived stress is associated with physical outcomes (sleep, immune system, heart), sometimes more than objective stressors. These are correlational associations, though, not proof that perception alone causes illness.</li>
      <li><b>Appraisal can be trained.</b> <span class="t" data-tip="Cognitive reappraisal: re-reading a situation as less threatening or more manageable. It is one of the best-supported emotion-regulation strategies.">Reappraisal</span> — reading a situation as a challenge rather than a threat — lowers perceived stress without changing the events.</li>
      <li><b>Shorter versions exist.</b> The PSS also has 4- and 14-item forms; the 10-item one has the best balance of brevity and reliability.</li>
    </ul>`,
    taratura: `<p>The PSS-10 is among the most widely used perceived-stress measures in the world, with good reliability and norms in many languages. Two honest limits. First: it measures a perception, and overlaps with <span class="t" data-tip="The personality trait describing the tendency to feel negative emotions. High scorers tend to report more perceived stress for the same events.">negative affect</span> and neuroticism — people who tend to see the worst report more stress for the same situation. Second: it is debated whether to sum it into a single total or read it as two factors (pressure and mastery, because of the reverse items). It is not a clinical or diagnostic tool: it describes the intensity of the month's experience, useful for self-reflection and, if needed, for talking to a professional.</p>`,
    reading: [
      "Cohen, S., Kamarck, T. & Mermelstein, R. (1983). A global measure of perceived stress. <em>Journal of Health and Social Behavior</em>, 24, 385-396.",
      "Cohen, S. & Williamson, G. (1988). Perceived stress in a probability sample of the US. In <em>The Social Psychology of Health</em>.",
      "Lazarus, R. S. & Folkman, S. (1984). <em>Stress, Appraisal, and Coping</em>. Springer."
    ]
  },
  pt: {
    title: "O estresse percebido, não o real",
    intro: `<p>A PSS de Cohen tem uma ideia precisa: não mede quanto lhe acontece, mas o quanto você <b>sente</b> que pode lidar com isso. Apoia-se na teoria de <span class="t" data-tip="Richard Lazarus (1922-2002), psicólogo que redefiniu o estresse como uma transação entre pessoa e ambiente: não o evento em si, mas o juízo que fazemos dele.">Lazarus</span>, segundo a qual o estresse nasce da <span class="t" data-tip="A avaliação cognitiva (appraisal): o julgamento automático de quão ameaçadora é uma situação e de quão capazes nos sentimos de enfrentá-la. É esse juízo, não o evento, que gera o estresse.">avaliação</span> que fazemos de uma situação. Por isso é um instrumento de <span class="t" data-tip="Um filtro que mede uma vivência subjetiva, não um teste diagnóstico. Fotografa o quanto o mês pesa, não se você tem um transtorno.">triagem</span> da vivência, não um contador de eventos.</p>`,
    blocks: [
      { h: "Não importa o que acontece, mas como você lê", html: `<p>Para Lazarus, a mesma situação estressa pessoas diferentes de modos diferentes, conforme dois juízos rápidos e automáticos: a <span class="t" data-tip="O primeiro juízo: esta situação é uma ameaça, uma perda ou um desafio para mim?">avaliação primária</span> — é uma ameaça? — e a <span class="t" data-tip="O segundo juízo: tenho recursos para dar conta? Quando a resposta é não, o estresse sobe, para o mesmo evento.">avaliação secundária</span> — consigo lidar? O estresse nasce do desequilíbrio entre as demandas percebidas e os recursos percebidos. A PSS mede o resultado desses juízos, não os eventos que os dispararam.</p>` },
      { h: "As três palavras-chave", html: `<p>Cohen construiu as perguntas em torno de três ingredientes que tornam uma demanda estressante: a <span class="t" data-tip="Quando não se sabe o que esperar. A incerteza mantém o corpo em alerta mais do que a própria dificuldade.">imprevisibilidade</span>, a <span class="t" data-tip="Quando se sente não ter alavancas para mudar as coisas. É o fator mais tóxico: o estresse incontrolável desgasta mais do que o intenso, mas administrável.">incontrolabilidade</span> e a <span class="t" data-tip="Quando as demandas superam os recursos disponíveis — coisas demais, tempo ou energia de menos.">sobrecarga</span>. Não é a intensidade de um evento que mais pesa, mas a sensação de não poder prevê-lo nem controlá-lo. Essa é a assinatura do estresse que faz mal com o tempo.</p>` },
      { h: "Os itens invertidos", html: `<p>Metade das perguntas é formulada no positivo — o quanto você se sentiu seguro para lidar com os problemas, o quanto sentiu ter tudo sob controle — e são <span class="t" data-tip="Perguntas escritas no positivo, cuja pontuação é invertida antes de somar. Servem para medir não só a pressão sentida, mas também o senso de domínio, e para desmascarar quem responde no automático.">pontuadas ao contrário</span>. Assim a escala mede duas coisas ao mesmo tempo: a pressão percebida e o senso de domínio. Quem se sente sob pressão, mas capaz, obtém um perfil diferente de quem se sente esmagado e impotente.</p>` },
      { h: "Percepção, não medida objetiva", html: `<p>É a força e o limite do instrumento. Duas pessoas com a mesma vida podem obter pontuações diferentes, porque a PSS capta a <b>carga subjetiva</b> — e é justamente ela que incide sobre sono, humor e corpo, mais do que os eventos contados de fora. Mas não é um medidor objetivo de estresse: uma pontuação alta diz que você está vivendo o mês como pesado, não que a sua vida seja objetivamente mais dura que a de outra pessoa.</p>` }
    ],
    beyond: `<ul>
      <li><b>Um estado, não um traço.</b> As perguntas se referem ao último mês; a pontuação sobe e desce com os períodos. A média na população geral fica em torno de 13-16 e cresce nos momentos difíceis.</li>
      <li><b>A percepção conta para a saúde.</b> O estresse percebido está associado a desfechos físicos (sono, sistema imunológico, coração), às vezes mais que os estressores objetivos. Mas são associações correlacionais, não prova de que a percepção sozinha cause a doença.</li>
      <li><b>A avaliação pode ser treinada.</b> A <span class="t" data-tip="Reavaliação cognitiva: reler uma situação de modo menos ameaçador ou mais administrável. É uma das estratégias de regulação emocional com mais respaldo.">reavaliação</span> — ler uma situação como desafio em vez de ameaça — reduz o estresse percebido sem mudar os eventos.</li>
      <li><b>Existem versões mais curtas.</b> A PSS também tem formas de 4 e 14 itens; a de 10 é a que tem o melhor equilíbrio entre brevidade e confiabilidade.</li>
    </ul>`,
    taratura: `<p>A PSS-10 está entre as medidas de estresse percebido mais usadas no mundo, com boa confiabilidade e normas em muitas línguas. Dois limites honestos. Primeiro: mede uma percepção, e se sobrepõe ao <span class="t" data-tip="O traço de personalidade que descreve a tendência a sentir emoções negativas. Quem pontua alto tende a relatar mais estresse percebido para os mesmos eventos.">afeto negativo</span> e ao neuroticismo — quem tende a ver tudo negro relata mais estresse na mesma situação. Segundo: discute-se se deve ser somada num único total ou lida como dois fatores (pressão e domínio, por causa dos itens invertidos). Não é um instrumento clínico nem diagnóstico: descreve a intensidade da vivência do mês, útil para se olhar e, se preciso, para conversar com um profissional.</p>`,
    reading: [
      "Cohen, S., Kamarck, T. & Mermelstein, R. (1983). A global measure of perceived stress. <em>Journal of Health and Social Behavior</em>, 24, 385-396.",
      "Cohen, S. & Williamson, G. (1988). Perceived stress in a probability sample of the US. In <em>The Social Psychology of Health</em>.",
      "Lazarus, R. S. & Folkman, S. (1984). <em>Stress, Appraisal, and Coping</em>. Springer."
    ]
  }
};
