/* Relationship Questionnaire, RQ (Bartholomew & Horowitz 1991) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.rq = {
  code: "RQ", theme: "default", n: 4, pick: true,
  labels: {
    en: ["Not at all like me", "Very little like me", "Somewhat unlike me", "Neutral", "Somewhat like me", "Quite like me", "Very much like me"],
    it: ["Per niente come me", "Molto poco come me", "Un po' diverso da me", "Neutrale", "Un po' come me", "Abbastanza come me", "Proprio come me"]
  },
  items: {
    en: ["It is easy for me to become emotionally close to others. I am comfortable depending on them and having them depend on me. I don't worry about being alone or having others not accept me.", "I am uncomfortable getting close to others. I want emotionally close relationships, but I find it difficult to trust others completely, or to depend on them. I worry that I will be hurt if I allow myself to become too close to others.", "I want to be completely emotionally intimate with others, but I often find that others are reluctant to get as close as I would like. I am uncomfortable being without close relationships, but I sometimes worry that others don't value me as much as I value them.", "I am comfortable without close emotional relationships. It is very important to me to feel independent and self-sufficient, and I prefer not to depend on others or have others depend on me."],
    it: ["Per me è facile diventare emotivamente vicino agli altri. Mi sento a mio agio a dipendere da loro e a farli dipendere da me. Non mi preoccupo di restare solo o di non essere accettato dagli altri.", "Mi sento a disagio ad avvicinarmi agli altri. Desidero relazioni emotivamente vicine, ma trovo difficile fidarmi completamente degli altri o dipendere da loro. Temo di essere ferito se mi permetto di avvicinarmi troppo.", "Voglio essere completamente intimo con gli altri sul piano emotivo, ma spesso trovo che gli altri siano riluttanti ad avvicinarsi quanto vorrei io. Mi sento a disagio senza relazioni strette, ma a volte temo che gli altri non mi apprezzino quanto io apprezzo loro.", "Mi sento a mio agio senza relazioni emotivamente strette. Per me è molto importante sentirmi indipendente e autosufficiente, e preferisco non dipendere dagli altri né far dipendere gli altri da me."]
  },
  text: {
    it: { kicker: "Attaccamento in 4 profili", title: "Quale descrizione ti somiglia?", lede: "4 descrizioni, 1 minuto. Il Relationship Questionnaire di Bartholomew: valuti quanto ti somiglia ciascuno dei quattro stili di attaccamento. Il complemento veloce dell'ECR-R.", meta: ["4 descrizioni", "~1 minuto"], instr: "Leggi ogni descrizione e indica <b>quanto ti somiglia</b> nel modo in cui vivi le relazioni strette, da 1 (per niente) a 7 (proprio come me). Tutte e quattro ricevono un voto.", how: "Il profilo con il voto più alto è il tuo stile prevalente; se due sono vicini, sei tra i due. Sicuro = a mio agio con vicinanza e autonomia; Timoroso = desidero vicinanza ma la temo; Preoccupato = cerco molta vicinanza e temo di non essere ricambiato; Distanziante = sto bene senza dipendere da nessuno. Gli autori considerano gli stili dimensioni continue, non caselle. Per una misura più fine usa l'ECR-R (36 domande).", cite: "Bartholomew, K., & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. Journal of Personality and Social Psychology, 61, 226-244. Uso libero; traduzione italiana propria." },
    en: { kicker: "Attachment in 4 profiles", title: "Which description sounds like you?", lede: "4 descriptions, 1 minute. Bartholomew's Relationship Questionnaire: you rate how much each of the four attachment styles is like you. The quick companion to the ECR-R.", meta: ["4 descriptions", "~1 minute"], instr: "Read each description and indicate <b>how much it is like you</b> in the way you experience close relationships, from 1 (not at all) to 7 (very much like me). All four get a rating.", how: "The profile with the highest rating is your prevailing style; if two are close, you sit between them. Secure = at ease with closeness and autonomy; Fearful = want closeness but fear it; Preoccupied = seek a lot of closeness and fear not being valued back; Dismissing = fine without depending on anyone. The authors treat styles as continuous dimensions, not boxes. For a finer measure use the ECR-R (36 questions).", cite: "Bartholomew, K., & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. Journal of Personality and Social Psychology, 61, 226-244. Free to use." }
  },
  scales: [
    { key: "sec", name: { it: "Sicuro", en: "Secure" }, items: [1], mode: "sum", range: [1, 7], desc: { it: "A mio agio con la vicinanza e con l'autonomia.", en: "At ease with closeness and with autonomy." } },
    { key: "fear", name: { it: "Timoroso", en: "Fearful" }, items: [2], mode: "sum", range: [1, 7], desc: { it: "Desidero la vicinanza ma temo di essere ferito.", en: "I want closeness but fear being hurt." } },
    { key: "pre", name: { it: "Preoccupato", en: "Preoccupied" }, items: [3], mode: "sum", range: [1, 7], desc: { it: "Cerco molta vicinanza e temo di non essere ricambiato.", en: "I seek a lot of closeness and fear not being valued back." } },
    { key: "dis", name: { it: "Distanziante", en: "Dismissing" }, items: [4], mode: "sum", range: [1, 7], desc: { it: "Sto bene senza dipendere da nessuno.", en: "I'm fine without depending on anyone." } }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.rq.approf = {
  it: {
    title: "L'attaccamento in quattro ritratti",
    intro: `<p>Il <span class="t" data-tip="Relationship Questionnaire: quattro brevi paragrafi, uno per stile; per ognuno indichi quanto ti somiglia. Deriva da un questionario precedente degli stessi autori.">RQ</span> nasce nel 1991, quando <span class="t" data-tip="Kim Bartholomew e Leonard Horowitz: proposero di leggere l'attaccamento adulto come l'incrocio di due giudizi di fondo, uno su di sé e uno sugli altri.">Bartholomew e Horowitz</span> ripresero l'intuizione di <span class="t" data-tip="John Bowlby (1907-1990): il bambino costruisce dai primi legami un modello di come funzionano le relazioni, che chiamò modello operativo interno.">Bowlby</span> e la trasformarono in un piccolo sistema a due assi. L'idea è che ogni stile sia la combinazione di un <span class="t" data-tip="Modello di sé: mi sento degno di amore e cura, oppure no. È l'asse imparentato con l'ansia da abbandono.">modello di sé</span> (positivo o negativo) e di un <span class="t" data-tip="Modello dell'altro: gli altri sono affidabili e disponibili, oppure no. È l'asse imparentato con l'evitamento della vicinanza.">modello dell'altro</span>. Dall'incrocio escono quattro ritratti, e tu dici quanto ciascuno ti somiglia.</p>`,
    blocks: [
      { h: "I due modelli dietro i quattro ritratti", html: `<p>Due assi a due valori danno quattro caselle. <b>Sicuro</b>: sé positivo, altro positivo (a mio agio con la vicinanza e con l'autonomia). <b>Preoccupato</b>: sé negativo, altro positivo (ho bisogno degli altri ma temo di non valere abbastanza). <b>Distanziante</b>: sé positivo, altro negativo (sto bene da solo, meglio non dipendere). <b>Timoroso</b>: sé negativo, altro negativo (vorrei la vicinanza ma la temo). I due assi corrispondono a grandi linee all'<b>ansia</b> (modello di sé) e all'<b>evitamento</b> (modello dell'altro) che l'ECR-R misura in modo continuo.</p>` },
      { h: "Perché quattro stili e non tre", html: `<p>La ricerca sull'attaccamento infantile parlava di tre pattern: sicuro, ansioso, evitante. Il contributo di Bartholomew fu <b>spezzare in due l'evitamento</b>. Chi tiene la distanza può farlo per autosufficienza e una buona immagine di sé (<span class="t" data-tip="Distanziante: modello di sé positivo, modello dell'altro negativo. Non teme l'abbandono, sminuisce il bisogno di legami.">distanziante</span>) oppure per paura del rifiuto pur desiderando la vicinanza (<span class="t" data-tip="Timoroso: modello di sé e dell'altro entrambi negativi. È il pattern più legato a esperienze precoci di paura dentro il legame.">timoroso</span>). Sono due mondi diversi sotto la stessa etichetta, e distinguerli è il lascito più utile del modello a quattro categorie.</p>` },
      { h: "Un ritratto, non una misura fine", html: `<p>Il RQ funziona per <span class="t" data-tip="Prototipo: una descrizione tipica e riconoscibile di uno stile. Ti riconosci per somiglianza globale, non rispondendo a molte domande separate.">prototipi</span>: giudichi quanto ti somiglia un intero paragrafo. È il suo pregio — un minuto e una fotografia leggibile — ed è anche il suo limite. Un paragrafo impacchetta più cose in una sola risposta e non permette di calcolare la <span class="t" data-tip="Coerenza interna: quanto le domande di una stessa scala si muovono insieme. Con un solo paragrafo per stile non è calcolabile, ed è una delle ragioni per cui il RQ è meno affidabile dell'ECR-R.">coerenza interna</span>. Per una stima precisa delle due dimensioni conviene l'<span class="t" data-tip="Experiences in Close Relationships – Revised: 36 domande, due punteggi continui di ansia ed evitamento, molto più affidabili del RQ.">ECR-R</span>.</p>` }
    ],
    beyond: `<ul>
      <li><b>Il quarto stile e il trauma.</b> Il timoroso (entrambi i modelli negativi) è il ritratto più legato a esperienze precoci in cui chi doveva proteggere era anche fonte di paura; da adulto dà relazioni vieni-qui/vattene.</li>
      <li><b>Gli stessi quattro degli assi.</b> I ritratti del RQ non sono un altro sistema: sono i quattro quadranti dello stesso piano ansia/evitamento che l'ECR-R misura con più finezza.</li>
      <li><b>Autovalutazione contro intervista.</b> Il RQ è autoriferito e cattura ciò che sai di te; l'<span class="t" data-tip="Adult Attachment Interview di Mary Main: coglie processi meno consapevoli attraverso la coerenza del racconto, e può non coincidere con l'autovalutazione.">Adult Attachment Interview</span> coglie processi meno consapevoli e a volte discorda.</li>
      <li><b>Non sei una casella.</b> Gli autori trattano gli stili come dimensioni continue: è normale somigliare a due ritratti, o cambiare a seconda della relazione.</li>
    </ul>`,
    taratura: `<p>Il RQ va preso per quello che è: uno strumento breve e comodo, non una misura di precisione. Con un solo prototipo per stile non se ne può stimare la coerenza interna, e la <span class="t" data-tip="Stabilità test-retest: quanto lo stesso risultato si ripete rifacendo il test a distanza di tempo. Per i prototipi del RQ è modesta.">stabilità nel tempo</span> è modesta; la <span class="t" data-tip="Validità convergente: quanto una misura si accorda con altre che dovrebbero misurare la stessa cosa.">concordanza</span> con le misure dimensionali è solo moderata. È utile come specchio veloce e come introduzione, ma per ricerca o per una lettura fine delle proprie dimensioni l'ECR-R resta la scelta migliore. Nulla di tutto questo è una diagnosi.</p>`,
    reading: [
      "Bartholomew, K. & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. <em>Journal of Personality and Social Psychology</em>, 61, 226-244.",
      "Griffin, D. & Bartholomew, K. (1994). Models of the self and other: fundamental dimensions underlying measures of adult attachment. <em>Journal of Personality and Social Psychology</em>, 67, 430-445.",
      "Ravitz, P. et al. (2010). Adult attachment measures: a 25-year review. <em>Journal of Psychosomatic Research</em>, 69, 419-432."
    ]
  },
  en: {
    title: "Attachment in four portraits",
    intro: `<p>The <span class="t" data-tip="Relationship Questionnaire: four short paragraphs, one per style; for each you rate how much it is like you. It grows out of an earlier questionnaire by the same authors.">RQ</span> appeared in 1991, when <span class="t" data-tip="Kim Bartholomew and Leonard Horowitz proposed reading adult attachment as the crossing of two underlying judgements, one about the self and one about others.">Bartholomew and Horowitz</span> took <span class="t" data-tip="John Bowlby (1907-1990): from early bonds a child builds a model of how relationships work, which he called the internal working model.">Bowlby's</span> insight and turned it into a small two-axis system. The idea: each style is the combination of a <span class="t" data-tip="Model of self: I feel worthy of love and care, or I don't. This is the axis related to abandonment anxiety.">model of self</span> (positive or negative) and a <span class="t" data-tip="Model of other: others are reliable and available, or they aren't. This is the axis related to avoidance of closeness.">model of other</span>. Crossing them yields four portraits, and you say how much each is like you.</p>`,
    blocks: [
      { h: "The two models behind the four portraits", html: `<p>Two axes at two values give four cells. <b>Secure</b>: positive self, positive other (at ease with closeness and autonomy). <b>Preoccupied</b>: negative self, positive other (I need others but fear I'm not worth enough). <b>Dismissing</b>: positive self, negative other (I'm fine alone, better not to depend). <b>Fearful</b>: negative self, negative other (I want closeness but fear it). The two axes map broadly onto the <b>anxiety</b> (model of self) and <b>avoidance</b> (model of other) that the ECR-R measures continuously.</p>` },
      { h: "Why four styles, not three", html: `<p>Infant-attachment research spoke of three patterns: secure, anxious, avoidant. Bartholomew's contribution was to <b>split avoidance in two</b>. Someone who keeps their distance may do so out of self-sufficiency and a good self-image (<span class="t" data-tip="Dismissing: positive model of self, negative model of other. Doesn't fear abandonment, plays down the need for bonds.">dismissing</span>) or out of fear of rejection while still wanting closeness (<span class="t" data-tip="Fearful: both models negative. It's the pattern most tied to early experiences of fear inside the bond.">fearful</span>). Two different worlds under one label, and telling them apart is the four-category model's most useful legacy.</p>` },
      { h: "A portrait, not a fine measure", html: `<p>The RQ works by <span class="t" data-tip="Prototype: a typical, recognisable description of a style. You recognise yourself by overall resemblance, not by answering many separate questions.">prototypes</span>: you rate how much a whole paragraph is like you. That's its strength — one minute, a readable snapshot — and also its limit. A paragraph bundles several things into one answer and doesn't let you compute <span class="t" data-tip="Internal consistency: how much the items of one scale move together. With a single paragraph per style it can't be computed, one reason the RQ is less reliable than the ECR-R.">internal consistency</span>. For a precise estimate of the two dimensions, the <span class="t" data-tip="Experiences in Close Relationships – Revised: 36 questions, two continuous scores of anxiety and avoidance, far more reliable than the RQ.">ECR-R</span> is the better tool.</p>` }
    ],
    beyond: `<ul>
      <li><b>The fourth style and trauma.</b> The fearful portrait (both models negative) is the one most linked to early experiences where the protector was also a source of fear; in adults it produces come-here/go-away relationships.</li>
      <li><b>The same four as the axes.</b> The RQ portraits aren't a rival system: they are the four quadrants of the same anxiety/avoidance plane the ECR-R measures more finely.</li>
      <li><b>Self-report versus interview.</b> The RQ is self-reported and captures what you know about yourself; the <span class="t" data-tip="Mary Main's Adult Attachment Interview captures less conscious processes through narrative coherence, and can disagree with self-report.">Adult Attachment Interview</span> taps less conscious processes and sometimes disagrees.</li>
      <li><b>You're not a box.</b> The authors treat the styles as continuous dimensions: resembling two portraits, or shifting from one relationship to another, is normal.</li>
    </ul>`,
    taratura: `<p>Take the RQ for what it is: a short, convenient instrument, not a precision measure. With a single prototype per style you can't estimate internal consistency, and <span class="t" data-tip="Test-retest stability: how far the same result repeats when you take the test again later. For the RQ prototypes it is modest.">stability over time</span> is modest; agreement with dimensional measures is only moderate. It's useful as a quick mirror and an introduction, but for research or a fine reading of your own dimensions the ECR-R remains the better choice. None of this is a diagnosis.</p>`,
    reading: [
      "Bartholomew, K. & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. <em>Journal of Personality and Social Psychology</em>, 61, 226-244.",
      "Griffin, D. & Bartholomew, K. (1994). Models of the self and other: fundamental dimensions underlying measures of adult attachment. <em>Journal of Personality and Social Psychology</em>, 67, 430-445.",
      "Ravitz, P. et al. (2010). Adult attachment measures: a 25-year review. <em>Journal of Psychosomatic Research</em>, 69, 419-432."
    ]
  },
  pt: {
    title: "O apego em quatro retratos",
    intro: `<p>O <span class="t" data-tip="Relationship Questionnaire: quatro parágrafos curtos, um por estilo; para cada um você avalia o quanto se parece com você. Deriva de um questionário anterior dos mesmos autores.">RQ</span> surge em 1991, quando <span class="t" data-tip="Kim Bartholomew e Leonard Horowitz propuseram ler o apego adulto como o cruzamento de dois julgamentos de fundo, um sobre si e um sobre os outros.">Bartholomew e Horowitz</span> retomaram a intuição de <span class="t" data-tip="John Bowlby (1907-1990): a partir dos primeiros vínculos a criança constrói um modelo de como os relacionamentos funcionam, que ele chamou de modelo operacional interno.">Bowlby</span> e a transformaram num pequeno sistema de dois eixos. A ideia: cada estilo é a combinação de um <span class="t" data-tip="Modelo de si: eu me sinto digno de amor e cuidado, ou não. É o eixo aparentado com a ansiedade de abandono.">modelo de si</span> (positivo ou negativo) e de um <span class="t" data-tip="Modelo do outro: os outros são confiáveis e disponíveis, ou não. É o eixo aparentado com a evitação da proximidade.">modelo do outro</span>. Do cruzamento saem quatro retratos, e você diz o quanto cada um se parece com você.</p>`,
    blocks: [
      { h: "Os dois modelos por trás dos quatro retratos", html: `<p>Dois eixos com dois valores dão quatro caixas. <b>Seguro</b>: si positivo, outro positivo (à vontade com proximidade e autonomia). <b>Preocupado</b>: si negativo, outro positivo (preciso dos outros mas temo não valer o bastante). <b>Desligado</b>: si positivo, outro negativo (estou bem sozinho, melhor não depender). <b>Amedrontado</b>: si negativo, outro negativo (quero a proximidade mas a temo). Os dois eixos correspondem, em linhas gerais, à <b>ansiedade</b> (modelo de si) e à <b>evitação</b> (modelo do outro) que o ECR-R mede de forma contínua.</p>` },
      { h: "Por que quatro estilos e não três", html: `<p>A pesquisa sobre apego infantil falava de três padrões: seguro, ansioso, evitativo. A contribuição de Bartholomew foi <b>dividir a evitação em dois</b>. Quem mantém distância pode fazê-lo por autossuficiência e boa imagem de si (<span class="t" data-tip="Desligado: modelo de si positivo, modelo do outro negativo. Não teme o abandono, minimiza a necessidade de vínculos.">desligado</span>) ou por medo da rejeição, ainda desejando a proximidade (<span class="t" data-tip="Amedrontado: ambos os modelos negativos. É o padrão mais ligado a experiências precoces de medo dentro do vínculo.">amedrontado</span>). Dois mundos diferentes sob o mesmo rótulo, e distingui-los é o legado mais útil do modelo de quatro categorias.</p>` },
      { h: "Um retrato, não uma medida fina", html: `<p>O RQ funciona por <span class="t" data-tip="Protótipo: uma descrição típica e reconhecível de um estilo. Você se reconhece por semelhança global, não respondendo a muitas perguntas separadas.">protótipos</span>: você avalia o quanto um parágrafo inteiro se parece com você. Essa é a sua força — um minuto, uma fotografia legível — e também o seu limite. Um parágrafo junta várias coisas numa só resposta e não permite calcular a <span class="t" data-tip="Consistência interna: o quanto os itens de uma mesma escala se movem juntos. Com um único parágrafo por estilo não é calculável, uma das razões pelas quais o RQ é menos confiável que o ECR-R.">consistência interna</span>. Para uma estimativa precisa das duas dimensões, o <span class="t" data-tip="Experiences in Close Relationships – Revised: 36 perguntas, dois escores contínuos de ansiedade e evitação, bem mais confiáveis que o RQ.">ECR-R</span> é a ferramenta melhor.</p>` }
    ],
    beyond: `<ul>
      <li><b>O quarto estilo e o trauma.</b> O retrato amedrontado (ambos os modelos negativos) é o mais ligado a experiências precoces em que quem devia proteger era também fonte de medo; no adulto produz relações vem-cá/vai-embora.</li>
      <li><b>Os mesmos quatro dos eixos.</b> Os retratos do RQ não são outro sistema: são os quatro quadrantes do mesmo plano ansiedade/evitação que o ECR-R mede com mais finura.</li>
      <li><b>Autorrelato contra entrevista.</b> O RQ é autorreferido e capta o que você sabe de si; a <span class="t" data-tip="Adult Attachment Interview, de Mary Main, capta processos menos conscientes pela coerência do relato, e pode discordar do autorrelato.">Adult Attachment Interview</span> capta processos menos conscientes e às vezes discorda.</li>
      <li><b>Você não é uma caixa.</b> Os autores tratam os estilos como dimensões contínuas: parecer-se com dois retratos, ou mudar de um relacionamento para outro, é normal.</li>
    </ul>`,
    taratura: `<p>Tome o RQ pelo que ele é: um instrumento breve e cômodo, não uma medida de precisão. Com um único protótipo por estilo não se estima a consistência interna, e a <span class="t" data-tip="Estabilidade teste-reteste: o quanto o mesmo resultado se repete ao refazer o teste depois. Para os protótipos do RQ é modesta.">estabilidade no tempo</span> é modesta; a concordância com as medidas dimensionais é apenas moderada. É útil como espelho rápido e como introdução, mas para pesquisa ou uma leitura fina das próprias dimensões o ECR-R continua sendo a melhor escolha. Nada disso é um diagnóstico.</p>`,
    reading: [
      "Bartholomew, K. & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. <em>Journal of Personality and Social Psychology</em>, 61, 226-244.",
      "Griffin, D. & Bartholomew, K. (1994). Models of the self and other: fundamental dimensions underlying measures of adult attachment. <em>Journal of Personality and Social Psychology</em>, 67, 430-445.",
      "Ravitz, P. et al. (2010). Adult attachment measures: a 25-year review. <em>Journal of Psychosomatic Research</em>, 69, 419-432."
    ]
  }
};
