/* Relationship Questionnaire, RQ (Bartholomew & Horowitz 1991) — libero. IT: traduzione propria. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.rq = {
  code: "RQ", theme: "default", n: 4, pick: true,
  labels: {
    en: ["Not at all like me", "Very little like me", "Somewhat unlike me", "Neutral", "Somewhat like me", "Quite like me", "Very much like me"],
    it: ["Per niente come me", "Molto poco come me", "Un po' diverso da me", "Neutrale", "Un po' come me", "Abbastanza come me", "Proprio come me"]
  },
  items: {
    en: ["It is easy for me to become emotionally close to others. I am comfortable depending on them and having them depend on me. I don't worry about being alone or having others not accept me.", "I am uncomfortable getting close to others. I want emotionally close relationships, but I find it difficult to trust others completely, or to depend on them. I worry that I will be hurt if I allow myself to become too close to others.", "I want to be completely emotionally intimate with others, but I often find that others are reluctant to get as close as I would like. I am uncomfortable being without close relationships, but I sometimes worry that others don't value me as much as I value them.", "I am comfortable without close emotional relationships. It is very important to me to feel independent and self-sufficient, and I prefer not to depend on others or have others depend on me."],
    it: ["Per me è facile diventare emotivamente vicino agli altri. Mi sento a mio agio a dipendere da loro e a farli dipendere da me. Non mi preoccupo di restare solo o di non essere accettato dagli altri.", "Mi sento a disagio ad avvicinarmi agli altri. Desidero relazioni emotivamente vicine, ma trovo difficile fidarmi completamente degli altri o dipendere da loro. Temo di essere ferito se mi permetto di avvicinarmi troppo.", "Voglio essere completamente intimo con gli altri sul piano emotivo, ma spesso trovo che gli altri siano riluttanti ad avvicinarsi quanto vorrei io. Mi sento a disagio senza relazioni strette, ma a volte temo che gli altri non mi apprezzino quanto io apprezzo loro.", "Mi sento a mio agio senza relazioni emotivamente strette. Per me è molto importante sentirmi indipendente e autosufficiente, e preferisco non dipendere dagli altri né far dipendere gli altri da me."]
  },
  text: {
    it: { kicker: "Attaccamento in 4 profili", title: "Quale descrizione ti somiglia?", lede: "4 descrizioni, 1 minuto. Il Relationship Questionnaire di Bartholomew: valuti quanto ti somiglia ciascuno dei quattro stili di attaccamento. Il complemento veloce dell'ECR-R.", meta: ["4 descrizioni", "~1 minuto"], instr: "Leggi ogni descrizione e indica <b>quanto ti somiglia</b> nel modo in cui vivi le relazioni strette, da 1 (per niente) a 7 (proprio come me). Tutte e quattro ricevono un voto.", how: "Il profilo con il voto più alto è il tuo stile prevalente; se due sono vicini, sei tra i due. Sicuro = a mio agio con vicinanza e autonomia; Timoroso = desidero vicinanza ma la temo; Preoccupato = cerco molta vicinanza e temo di non essere ricambiato; Distanziante = sto bene senza dipendere da nessuno. Gli autori considerano gli stili dimensioni continue, non caselle. Per una misura più fine usa l'ECR-R (36 domande).", cite: "Bartholomew, K., & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. Journal of Personality and Social Psychology, 61, 226-244. Uso libero; traduzione italiana propria." },
    en: { kicker: "Attachment in 4 profiles", title: "Which description sounds like you?", lede: "4 descriptions, 1 minute. Bartholomew's Relationship Questionnaire: you rate how much each of the four attachment styles is like you. The quick companion to the ECR-R.", meta: ["4 descriptions", "~1 minute"], instr: "Read each description and indicate <b>how much it is like you</b> in the way you experience close relationships, from 1 (not at all) to 7 (very much like me). All four get a rating.", how: "The profile with the highest rating is your prevailing style; if two are close, you sit between them. Secure = at ease with closeness and autonomy; Fearful = want closeness but fear it; Preoccupied = seek a lot of closeness and fear not being valued back; Dismissing = fine without depending on anyone. The authors treat styles as continuous dimensions, not boxes. For a finer measure use the ECR-R (36 questions).", cite: "Bartholomew, K., & Horowitz, L. M. (1991). Attachment styles among young adults: a test of a four-category model. Journal of Personality and Social Psychology, 61, 226-244. Free to use." }
  },
  scales: [
    { key: "sec", name: { it: "Sicuro", en: "Secure" }, items: [1], mode: "sum", range: [1, 7], desc: { it: "A mio agio con la vicinanza e con l'autonomia.", en: "At ease with closeness and with autonomy." } },
    { key: "fear", name: { it: "Timoroso", en: "Fearful" }, items: [2], mode: "sum", range: [1, 7], desc: { it: "Desidero la vicinanza ma temo di essere ferito.", en: "I want closeness but fear being hurt." } },
    { key: "pre", name: { it: "Preoccupato", en: "Preoccupied" }, items: [3], mode: "sum", range: [1, 7], desc: { it: "Cerco molta vicinanza e temo di non essere ricambiato.", en: "I seek a lot of closeness and fear not being valued back." } },
    { key: "dis", name: { it: "Distanziante", en: "Dismissing" }, items: [4], mode: "sum", range: [1, 7], desc: { it: "Sto bene senza dipendere da nessuno.", en: "I'm fine without depending on anyone." } }
  ]
};
