/* Rosenberg Self-Esteem Scale (Rosenberg 1965) — pubblico dominio. IT: Prezza, Trombaccia & Armento (1997). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.rses = {
  code: "RSES", theme: "sun", n: 10, values: [0, 1, 2, 3], reverse: [2, 5, 6, 8, 9],
  labels: {
    en: ["Strongly disagree", "Disagree", "Agree", "Strongly agree"],
    it: ["Fortemente in disaccordo", "In disaccordo", "D'accordo", "Fortemente d'accordo"]
  },
  items: {
    en: ["On the whole, I am satisfied with myself.", "At times I think I am no good at all.", "I feel that I have a number of good qualities.", "I am able to do things as well as most other people.", "I feel I do not have much to be proud of.", "I certainly feel useless at times.", "I feel that I'm a person of worth, at least on an equal plane with others.", "I wish I could have more respect for myself.", "All in all, I am inclined to feel that I am a failure.", "I take a positive attitude toward myself."],
    it: ["Nel complesso sono soddisfatto di me stesso.", "A volte penso di non valere niente.", "Sento di avere un certo numero di buone qualità.", "Sono capace di fare le cose come la maggior parte delle altre persone.", "Sento di non avere molto di cui andare fiero.", "Certe volte mi sento davvero inutile.", "Sento di essere una persona di valore, almeno quanto gli altri.", "Vorrei avere più rispetto per me stesso.", "Tutto sommato, tendo a pensare di essere un fallito.", "Ho un atteggiamento positivo verso me stesso."]
  },
  text: {
    it: { kicker: "Autostima", title: "Quanto ti stimi?", lede: "10 affermazioni, 1 minuto. La scala di Rosenberg è la misura dell'autostima globale più usata al mondo.", meta: ["10 domande", "~1 minuto"], instr: "Per ogni frase indica quanto sei d'accordo, pensando a come ti senti <b>in generale</b>.", how: "Il punteggio va da 0 a 30. Nella popolazione generale la maggior parte delle persone sta tra 15 e 25; sotto 15 l'autostima è bassa. Cinque affermazioni sono invertite. È un'istantanea di come ti vedi, non un giudizio su quanto vali.", cite: "Rosenberg, M. (1965). Society and the adolescent self-image. Princeton University Press. Versione italiana: Prezza, Trombaccia & Armento (1997). Strumento di pubblico dominio." },
    en: { kicker: "Self-esteem", title: "How much do you value yourself?", lede: "10 statements, 1 minute. The Rosenberg scale is the most widely used measure of global self-esteem.", meta: ["10 questions", "~1 minute"], instr: "For each statement, indicate how much you agree, thinking about how you feel <b>in general</b>.", how: "The score runs from 0 to 30. In the general population most people fall between 15 and 25; below 15 self-esteem is low. Five statements are reverse-keyed. It is a snapshot of how you see yourself, not a verdict on your worth.", cite: "Rosenberg, M. (1965). Society and the adolescent self-image. Princeton University Press. Public-domain instrument." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Autostima", en: "Self-esteem" }, items: [1,2,3,4,5,6,7,8,9,10], mode: "sum", range: [0, 30],
    bands: [
      { max: 14, name: { it: "Bassa", en: "Low" }, text: { it: "Sotto la fascia tipica: tendi a vederti con occhi severi. L'autostima cambia con le esperienze e con il modo in cui ti parli; se pesa, un percorso con un professionista aiuta.", en: "Below the typical range: you tend to see yourself harshly. Self-esteem shifts with experience and with how you talk to yourself; if it weighs on you, working with a professional helps." } },
      { max: 25, name: { it: "Nella media", en: "Average" }, text: { it: "Nella fascia in cui sta la maggior parte delle persone: una visione di te complessivamente equilibrata, con alti e bassi normali.", en: "In the range where most people fall: an overall balanced view of yourself, with normal ups and downs." } },
      { max: 30, name: { it: "Alta", en: "High" }, text: { it: "Sopra la fascia tipica: ti vedi con fiducia e ti riconosci valore. Bene, finché resta ancorata alla realtà e non ti impedisce di ascoltare le critiche.", en: "Above the typical range: you see yourself with confidence and recognise your worth. Good, as long as it stays anchored to reality and lets you hear criticism." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.rses.approf = {
  it: {
    title: "L'autostima, in profondità",
    intro: `<p>La scala la costruisce nel 1965 <span class="t" data-tip="Morris Rosenberg (1922-1992), sociologo americano. La sviluppò studiando migliaia di adolescenti; è oggi la misura di autostima più usata al mondo.">Morris Rosenberg</span>, e non era uno psicologo ma un sociologo interessato all'immagine di sé degli adolescenti. Misura l'<span class="t" data-tip="L'atteggiamento complessivo verso sé stessi come persona: non quanto sei bravo in una cosa specifica, ma quanto ti approvi nel complesso.">autostima globale</span> — non quanto ti senti capace in una singola area, ma il giudizio di fondo su te stesso come persona. Dieci frasi, cinque positive e cinque negative, ed è così breve e robusta che dopo sessant'anni resta lo standard. Ma proprio perché il concetto è entrato nel linguaggio comune, attorno all'autostima si sono accumulati parecchi malintesi.</p>`,
    blocks: [
      { h: "Un giudizio globale", html: `<p>L'autostima che misura Rosenberg è <b>globale</b>: una sintesi, non la somma di quanto ti senti bravo al lavoro, in amore, nello sport. Puoi avere un'ottima <span class="t" data-tip="La stima di sé in un ambito specifico: mi sento capace come genitore, come studente. È distinta dall'autostima globale e si combina con essa in modo complesso.">autostima di dominio</span> in un'area e un giudizio di fondo comunque basso, o viceversa. È un atteggiamento verso sé come oggetto — lo stesso «me» può essere approvato o rifiutato — e cambia più lentamente delle valutazioni sui singoli risultati.</p>` },
      { h: "Il mito dell'autostima", html: `<p>Negli anni Ottanta e Novanta nasce un intero movimento convinto che alzare l'autostima dei ragazzi avrebbe migliorato voti, comportamento e vita. Nel 2003 una revisione ampia guidata da <span class="t" data-tip="Roy Baumeister e colleghi (2003): passarono in rassegna migliaia di studi e conclusero che l'alta autostima non causa buoni risultati; semmai i buoni risultati alzano l'autostima.">Baumeister</span> smontò la premessa: l'alta autostima <em>non</em> produce migliori risultati scolastici o lavorativi. Quando i due vanno insieme, di solito è il successo ad alzare l'autostima, non il contrario. È una <span class="t" data-tip="Scambiare la direzione del rapporto: l'autostima sembra la causa perché arriva insieme al successo, ma è spesso la conseguenza.">confusione tra causa ed effetto</span> costata anni di programmi ben intenzionati e poco efficaci.</p>` },
      { h: "Non è narcisismo", html: `<p>Alta autostima non vuol dire <span class="t" data-tip="Il narcisismo è un bisogno costante di ammirazione unito a una grandiosità fragile. Correla poco con l'autostima sana e reagisce con rabbia alle critiche.">narcisismo</span>. Chi ha un'autostima sana si sente a posto senza aver bisogno di sentirsi superiore; il narcisista ha un'immagine gonfia ma fragile, che difende con aggressività quando viene toccata. Anzi, la ricerca di Baumeister mostrò che la violenza si lega più spesso a un'autostima <em>alta ma minacciata</em> che a un'autostima bassa: non è chi si sente poco, ma chi si sente molto e viene contraddetto, a reagire male.</p>` },
      { h: "Stabile o reattiva", html: `<p>Conta anche come l'autostima si muove nel tempo. Un conto è un'autostima alta e <span class="t" data-tip="Autostima sicura: alta e poco reattiva agli eventi. Non ha bisogno di continue conferme e regge le critiche senza crollare.">stabile</span>, un altro un'autostima alta ma <span class="t" data-tip="Autostima contingente: dipende dal risultato del momento, dall'approvazione, dall'aspetto. Sale e crolla di continuo ed è più fragile di un'autostima media ma stabile.">contingente</span>, appesa all'ultimo risultato o all'ultimo like. La seconda è più fragile della prima e a volte più fragile di un'autostima media ma solida. La RSES fotografa il livello, non questa oscillazione: due persone con lo stesso punteggio possono viverlo in modi molto diversi.</p>` }
    ],
    beyond: `<ul>
      <li><b>Cinque item invertiti.</b> Le frasi negative (come «a volte penso di non valere niente») non sono un doppione: servono a non farti rispondere in automatico e catturano un lato diverso, il rifiuto di sé, distinto dall'accettazione.</li>
      <li><b>Differenze culturali.</b> I punteggi medi sono più alti nei paesi individualisti; in culture collettiviste l'autocritica è più accettata e i punteggi scendono, senza che questo significhi più sofferenza.</li>
      <li><b>Autostima e depressione.</b> Bassa autostima e umore depresso si alimentano a vicenda; la RSES è sensibile all'umore del momento, quindi un punteggio basso in un periodo difficile non è un tratto fisso.</li>
      <li><b>L'alternativa dell'auto-compassione.</b> Alcuni ricercatori propongono di spostare l'attenzione dall'autostima, che chiede di sentirsi sopra la media, all'auto-compassione, che non richiede confronto.</li>
    </ul>`,
    taratura: `<p>La RSES è tra le scale più validate della psicologia: coerenza interna alta, stabilità nel tempo buona, tradotta e tarata in decine di lingue. I limiti sono di interpretazione più che di misura. È pensata come unidimensionale, ma gli item positivi e negativi a volte formano due gruppi, un artefatto del modo di rispondere più che due autostime diverse. E il punteggio risente dell'umore del momento e della <span class="t" data-tip="La tendenza a rispondere come si pensa sia giusto o desiderabile, che nell'autostima gonfia i punteggi verso l'alto.">desiderabilità sociale</span>: è un'istantanea onesta ma influenzabile, non una misura del tuo valore.</p>`,
    reading: [
      "Rosenberg, M. (1965). <em>Society and the Adolescent Self-Image</em>. Princeton University Press.",
      "Baumeister, R. F. et al. (2003). Does high self-esteem cause better performance? <em>Psychological Science in the Public Interest</em>, 4, 1-44.",
      "Orth, U. & Robins, R. W. (2014). The development of self-esteem. <em>Current Directions in Psychological Science</em>, 23, 381-387."
    ]
  },
  en: {
    title: "Self-esteem, in depth",
    intro: `<p>The scale was built in 1965 by <span class="t" data-tip="Morris Rosenberg (1922-1992), American sociologist. He developed it studying thousands of adolescents; it is today the most used measure of self-esteem in the world.">Morris Rosenberg</span>, and he was not a psychologist but a sociologist interested in the self-image of adolescents. It measures <span class="t" data-tip="The overall attitude toward yourself as a person: not how good you are at a specific thing, but how much you approve of yourself on the whole.">global self-esteem</span> — not how capable you feel in one area, but the underlying judgement of yourself as a person. Ten statements, five positive and five negative, and it is so brief and robust that after sixty years it remains the standard. But precisely because the concept entered everyday language, plenty of misunderstandings have gathered around self-esteem.</p>`,
    blocks: [
      { h: "A global judgement", html: `<p>The self-esteem Rosenberg measures is <b>global</b>: a synthesis, not the sum of how good you feel at work, in love, in sport. You can have excellent <span class="t" data-tip="Self-esteem in a specific area: I feel capable as a parent, as a student. It is distinct from global self-esteem and combines with it in complex ways.">domain self-esteem</span> in one area and a low underlying judgement anyway, or the reverse. It is an attitude toward the self as an object — the same "me" can be approved or rejected — and it changes more slowly than the appraisals of single outcomes.</p>` },
      { h: "The self-esteem myth", html: `<p>In the 1980s and 1990s a whole movement grew convinced that raising children's self-esteem would improve grades, behaviour and life. In 2003 a broad review led by <span class="t" data-tip="Roy Baumeister and colleagues (2003): they reviewed thousands of studies and concluded that high self-esteem does not cause good outcomes; if anything, good outcomes raise self-esteem.">Baumeister</span> dismantled the premise: high self-esteem does <em>not</em> produce better school or work results. When the two go together, it is usually success that raises self-esteem, not the reverse. It is a <span class="t" data-tip="Mistaking the direction of the relationship: self-esteem looks like the cause because it arrives with success, but it is often the consequence.">confusion of cause and effect</span> that cost years of well-meaning, ineffective programmes.</p>` },
      { h: "It is not narcissism", html: `<p>High self-esteem does not mean <span class="t" data-tip="Narcissism is a constant need for admiration coupled with fragile grandiosity. It correlates little with healthy self-esteem and reacts to criticism with anger.">narcissism</span>. Someone with healthy self-esteem feels fine without needing to feel superior; the narcissist has an inflated but fragile image, defended aggressively when touched. In fact, Baumeister's research showed that violence is more often tied to <em>high but threatened</em> self-esteem than to low self-esteem: it is not those who feel small, but those who feel big and are contradicted, who react badly.</p>` },
      { h: "Stable or reactive", html: `<p>How self-esteem moves over time matters too. High and <span class="t" data-tip="Secure self-esteem: high and little reactive to events. It does not need constant confirmation and withstands criticism without collapsing.">stable</span> self-esteem is one thing; high but <span class="t" data-tip="Contingent self-esteem: it depends on the outcome of the moment, on approval, on appearance. It rises and crashes constantly and is more fragile than a moderate but stable self-esteem.">contingent</span> self-esteem, hanging on the last result or the last like, is another. The second is more fragile than the first and sometimes more fragile than a moderate but solid self-esteem. The RSES captures the level, not this swing: two people with the same score may live it in very different ways.</p>` }
    ],
    beyond: `<ul>
      <li><b>Five reverse items.</b> The negative statements (like "at times I think I am no good at all") are not a duplicate: they keep you from answering on automatic and capture a different side, self-rejection, distinct from self-acceptance.</li>
      <li><b>Cultural differences.</b> Mean scores are higher in individualist countries; in collectivist cultures self-criticism is more accepted and scores fall, without this meaning more suffering.</li>
      <li><b>Self-esteem and depression.</b> Low self-esteem and depressed mood feed each other; the RSES is sensitive to the mood of the moment, so a low score in a hard period is not a fixed trait.</li>
      <li><b>The self-compassion alternative.</b> Some researchers propose shifting attention from self-esteem, which asks you to feel above average, to self-compassion, which requires no comparison.</li>
    </ul>`,
    taratura: `<p>The RSES is among the most validated scales in psychology: high internal consistency, good stability over time, translated and normed in dozens of languages. Its limits are of interpretation more than of measurement. It is meant to be unidimensional, but the positive and negative items sometimes form two groups, an artefact of the way people respond rather than two different self-esteems. And the score is affected by the mood of the moment and by <span class="t" data-tip="The tendency to answer as one thinks is right or desirable, which in self-esteem inflates scores upward.">social desirability</span>: it is an honest but influenceable snapshot, not a measure of your worth.</p>`,
    reading: [
      "Rosenberg, M. (1965). <em>Society and the Adolescent Self-Image</em>. Princeton University Press.",
      "Baumeister, R. F. et al. (2003). Does high self-esteem cause better performance? <em>Psychological Science in the Public Interest</em>, 4, 1-44.",
      "Orth, U. & Robins, R. W. (2014). The development of self-esteem. <em>Current Directions in Psychological Science</em>, 23, 381-387."
    ]
  },
  pt: {
    title: "A autoestima, em profundidade",
    intro: `<p>A escala é construída em 1965 por <span class="t" data-tip="Morris Rosenberg (1922-1992), sociólogo americano. Desenvolveu-a estudando milhares de adolescentes; é hoje a medida de autoestima mais usada no mundo.">Morris Rosenberg</span>, e ele não era psicólogo mas sociólogo, interessado na imagem de si dos adolescentes. Mede a <span class="t" data-tip="A atitude global em relação a si mesmo como pessoa: não o quanto você é bom numa coisa específica, mas o quanto se aprova no conjunto.">autoestima global</span> — não o quanto você se sente capaz numa área, mas o julgamento de fundo sobre si mesmo como pessoa. Dez frases, cinco positivas e cinco negativas, e é tão breve e robusta que, depois de sessenta anos, continua sendo o padrão. Mas justamente porque o conceito entrou na linguagem comum, em torno da autoestima acumularam-se vários mal-entendidos.</p>`,
    blocks: [
      { h: "Um julgamento global", html: `<p>A autoestima que Rosenberg mede é <b>global</b>: uma síntese, não a soma de quanto você se sente bom no trabalho, no amor, no esporte. Você pode ter uma ótima <span class="t" data-tip="A estima de si num âmbito específico: sinto-me capaz como pai, como estudante. É distinta da autoestima global e se combina com ela de modo complexo.">autoestima de domínio</span> numa área e, ainda assim, um julgamento de fundo baixo, ou o contrário. É uma atitude em relação a si como objeto — o mesmo «eu» pode ser aprovado ou rejeitado — e muda mais devagar que as avaliações sobre resultados isolados.</p>` },
      { h: "O mito da autoestima", html: `<p>Nos anos 1980 e 1990 nasce um movimento inteiro convencido de que elevar a autoestima dos jovens melhoraria notas, comportamento e vida. Em 2003 uma ampla revisão liderada por <span class="t" data-tip="Roy Baumeister e colegas (2003): revisaram milhares de estudos e concluíram que a alta autoestima não causa bons resultados; no máximo os bons resultados elevam a autoestima.">Baumeister</span> desmontou a premissa: a alta autoestima <em>não</em> produz melhores resultados escolares ou de trabalho. Quando os dois andam juntos, geralmente é o sucesso que eleva a autoestima, não o contrário. É uma <span class="t" data-tip="Trocar a direção da relação: a autoestima parece a causa porque chega junto com o sucesso, mas é muitas vezes a consequência.">confusão entre causa e efeito</span> que custou anos de programas bem-intencionados e pouco eficazes.</p>` },
      { h: "Não é narcisismo", html: `<p>Alta autoestima não quer dizer <span class="t" data-tip="O narcisismo é uma necessidade constante de admiração unida a uma grandiosidade frágil. Correlaciona pouco com a autoestima saudável e reage com raiva às críticas.">narcisismo</span>. Quem tem uma autoestima saudável se sente bem sem precisar se sentir superior; o narcisista tem uma imagem inflada mas frágil, que defende com agressividade quando é tocada. Aliás, a pesquisa de Baumeister mostrou que a violência se liga mais a uma autoestima <em>alta mas ameaçada</em> do que a uma autoestima baixa: não é quem se sente pouco, mas quem se sente muito e é contrariado, que reage mal.</p>` },
      { h: "Estável ou reativa", html: `<p>Conta também como a autoestima se move no tempo. Uma coisa é uma autoestima alta e <span class="t" data-tip="Autoestima segura: alta e pouco reativa aos eventos. Não precisa de confirmações constantes e aguenta as críticas sem desabar.">estável</span>, outra uma autoestima alta mas <span class="t" data-tip="Autoestima contingente: depende do resultado do momento, da aprovação, da aparência. Sobe e desaba o tempo todo e é mais frágil que uma autoestima média mas estável.">contingente</span>, presa ao último resultado ou ao último like. A segunda é mais frágil que a primeira e às vezes mais frágil que uma autoestima média mas sólida. A RSES fotografa o nível, não essa oscilação: duas pessoas com o mesmo escore podem vivê-lo de modos bem diferentes.</p>` }
    ],
    beyond: `<ul>
      <li><b>Cinco itens invertidos.</b> As frases negativas (como «às vezes penso que não valho nada») não são uma repetição: servem para não deixar você responder no automático e captam um lado diferente, a rejeição de si, distinto da aceitação.</li>
      <li><b>Diferenças culturais.</b> Os escores médios são mais altos em países individualistas; em culturas coletivistas a autocrítica é mais aceita e os escores caem, sem que isso signifique mais sofrimento.</li>
      <li><b>Autoestima e depressão.</b> Baixa autoestima e humor deprimido se alimentam mutuamente; a RSES é sensível ao humor do momento, então um escore baixo num período difícil não é um traço fixo.</li>
      <li><b>A alternativa da autocompaixão.</b> Alguns pesquisadores propõem deslocar a atenção da autoestima, que pede para você se sentir acima da média, para a autocompaixão, que não exige comparação.</li>
    </ul>`,
    taratura: `<p>A RSES está entre as escalas mais validadas da psicologia: consistência interna alta, boa estabilidade no tempo, traduzida e normatizada em dezenas de línguas. Os limites são de interpretação mais que de medida. É pensada como unidimensional, mas os itens positivos e negativos às vezes formam dois grupos, um artefato do modo de responder mais que duas autoestimas diferentes. E o escore sofre com o humor do momento e com a <span class="t" data-tip="A tendência a responder como se pensa ser certo ou desejável, que na autoestima infla os escores para cima.">desejabilidade social</span>: é uma fotografia honesta mas influenciável, não uma medida do seu valor.</p>`,
    reading: [
      "Rosenberg, M. (1965). <em>Society and the Adolescent Self-Image</em>. Princeton University Press.",
      "Baumeister, R. F. et al. (2003). Does high self-esteem cause better performance? <em>Psychological Science in the Public Interest</em>, 4, 1-44.",
      "Orth, U. & Robins, R. W. (2014). The development of self-esteem. <em>Current Directions in Psychological Science</em>, 23, 381-387."
    ]
  }
};
