/* Self-Compassion Scale – Short Form, SCS-SF (Raes, Pommier, Neff & Van Gucht 2011) — libero per ricerca/uso non commerciale. IT: Veneziani et al. (2017); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.scssf = {
  code: "SCS-SF", theme: "rose", n: 12, reverse: [1, 4, 8, 9, 11, 12],
  labels: { en: ["Almost never", "Rarely", "Sometimes", "Often", "Almost always"], it: ["Quasi mai", "Raramente", "A volte", "Spesso", "Quasi sempre"] },
  items: {
    en: ["When I fail at something important to me I become consumed by feelings of inadequacy.", "I try to be understanding and patient towards those aspects of my personality I don't like.", "When something painful happens I try to take a balanced view of the situation.", "When I'm feeling down, I tend to feel like most other people are probably happier than I am.", "I try to see my failings as part of the human condition.", "When I'm going through a very hard time, I give myself the caring and tenderness I need.", "When something upsets me I try to keep my emotions in balance.", "When I fail at something that's important to me, I tend to feel alone in my failure.", "When I'm feeling down I tend to obsess and fixate on everything that's wrong.", "When I feel inadequate in some way, I try to remind myself that feelings of inadequacy are shared by most people.", "I'm disapproving and judgmental about my own flaws and inadequacies.", "I'm intolerant and impatient towards those aspects of my personality I don't like."],
    it: ["Quando fallisco in qualcosa di importante per me, vengo divorato da sentimenti di inadeguatezza.", "Cerco di essere comprensivo e paziente verso gli aspetti della mia personalità che non mi piacciono.", "Quando succede qualcosa di doloroso, cerco di avere una visione equilibrata della situazione.", "Quando mi sento giù, tendo a pensare che la maggior parte delle altre persone sia probabilmente più felice di me.", "Cerco di vedere i miei fallimenti come parte della condizione umana.", "Quando attraverso un periodo molto difficile, mi do la cura e la tenerezza di cui ho bisogno.", "Quando qualcosa mi turba, cerco di mantenere le emozioni in equilibrio.", "Quando fallisco in qualcosa di importante per me, tendo a sentirmi solo nel mio fallimento.", "Quando mi sento giù, tendo a fissarmi in modo ossessivo su tutto ciò che non va.", "Quando mi sento inadeguato in qualche modo, cerco di ricordarmi che i sentimenti di inadeguatezza sono condivisi dalla maggior parte delle persone.", "Sono critico e severo verso i miei difetti e le mie inadeguatezze.", "Sono intollerante e impaziente verso gli aspetti della mia personalità che non mi piacciono."]
  },
  text: {
    it: { kicker: "Auto-compassione", title: "Come ti tratti quando sbagli?", lede: "12 affermazioni, 2 minuti. La scala di Kristin Neff misura l'auto-compassione: gentilezza verso di sé, senso di umanità condivisa e presenza mentale, contro autocritica, isolamento e iper-identificazione.", meta: ["12 domande", "~2 minuti"], instr: "Per ogni frase indica <b>con quale frequenza ti comporti così</b> nei momenti difficili.", how: "Il punteggio è la media delle 12 affermazioni, da 1 a 5 (6 sono invertite). Indicazioni dell'autrice: 1–2,5 auto-compassione bassa, 2,5–3,5 moderata, 3,5–5 alta. La media negli adulti è intorno a 3. Non è indulgenza: chi si tratta con gentilezza nei fallimenti tende a riprovare di più, non di meno.", cite: "Raes, F., Pommier, E., Neff, K. D., & Van Gucht, D. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. Clinical Psychology & Psychotherapy, 18, 250-255. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Self-compassion", title: "How do you treat yourself when you fail?", lede: "12 statements, 2 minutes. Kristin Neff's scale measures self-compassion: kindness towards yourself, a sense of common humanity and mindfulness, versus self-judgement, isolation and over-identification.", meta: ["12 questions", "~2 minutes"], instr: "For each statement, indicate <b>how often you behave that way</b> in difficult moments.", how: "The score is the mean of the 12 statements, from 1 to 5 (6 are reverse-keyed). The author's guidance: 1–2.5 low self-compassion, 2.5–3.5 moderate, 3.5–5 high. The adult mean is around 3. It is not indulgence: people who treat themselves kindly after failure tend to try again more, not less.", cite: "Raes, F., Pommier, E., Neff, K. D., & Van Gucht, D. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. Clinical Psychology & Psychotherapy, 18, 250-255. Free for non-commercial use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Auto-compassione", en: "Self-compassion" }, items: [1,2,3,4,5,6,7,8,9,10,11,12], mode: "mean", range: [1, 5],
    bands: [
      { max: 2.5, name: { it: "Bassa", en: "Low" }, text: { it: "Nei momenti difficili sei duro con te stesso, ti senti solo nel fallimento e ci rimugini. È il terreno su cui crescono ansia e umore basso; l'auto-compassione si allena, e in fretta.", en: "In hard moments you are harsh with yourself, feel alone in failure and ruminate on it. This is the ground where anxiety and low mood grow; self-compassion can be trained, and quickly." } },
      { max: 3.5, name: { it: "Moderata", en: "Moderate" }, text: { it: "A volte ti tratti con gentilezza, a volte con severità: come la maggior parte delle persone.", en: "Sometimes you treat yourself kindly, sometimes harshly: like most people." } },
      { max: 5, name: { it: "Alta", en: "High" }, text: { it: "Quando sbagli ti tratti come tratteresti un amico: con cura, prospettiva e senza drammi. È uno dei predittori più solidi del benessere.", en: "When you fail you treat yourself as you would a friend: with care, perspective and no drama. One of the most robust predictors of well-being." } }
    ] }]
};
