/* Self-Compassion Scale – Short Form, SCS-SF (Raes, Pommier, Neff & Van Gucht 2011) — libero per ricerca/uso non commerciale. IT: Veneziani et al. (2017); qui traduzione propria vicina alla versione validata. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.scssf = {
  code: "SCS-SF", theme: "rose", n: 12, reverse: [1, 4, 8, 9, 11, 12],
  labels: { en: ["Almost never", "Rarely", "Sometimes", "Often", "Almost always"], it: ["Quasi mai", "Raramente", "A volte", "Spesso", "Quasi sempre"] },
  items: {
    en: ["When I fail at something important to me I become consumed by feelings of inadequacy.", "I try to be understanding and patient towards those aspects of my personality I don't like.", "When something painful happens I try to take a balanced view of the situation.", "When I'm feeling down, I tend to feel like most other people are probably happier than I am.", "I try to see my failings as part of the human condition.", "When I'm going through a very hard time, I give myself the caring and tenderness I need.", "When something upsets me I try to keep my emotions in balance.", "When I fail at something that's important to me, I tend to feel alone in my failure.", "When I'm feeling down I tend to obsess and fixate on everything that's wrong.", "When I feel inadequate in some way, I try to remind myself that feelings of inadequacy are shared by most people.", "I'm disapproving and judgmental about my own flaws and inadequacies.", "I'm intolerant and impatient towards those aspects of my personality I don't like."],
    it: ["Quando fallisco in qualcosa di importante per me, vengo divorato da sentimenti di inadeguatezza.", "Cerco di essere comprensivo e paziente verso gli aspetti della mia personalità che non mi piacciono.", "Quando succede qualcosa di doloroso, cerco di avere una visione equilibrata della situazione.", "Quando mi sento giù, tendo a pensare che la maggior parte delle altre persone sia probabilmente più felice di me.", "Cerco di vedere i miei fallimenti come parte della condizione umana.", "Quando attraverso un periodo molto difficile, mi do la cura e la tenerezza di cui ho bisogno.", "Quando qualcosa mi turba, cerco di mantenere le emozioni in equilibrio.", "Quando fallisco in qualcosa di importante per me, tendo a sentirmi solo nel mio fallimento.", "Quando mi sento giù, tendo a fissarmi in modo ossessivo su tutto ciò che non va.", "Quando mi sento inadeguato in qualche modo, cerco di ricordarmi che i sentimenti di inadeguatezza sono condivisi dalla maggior parte delle persone.", "Sono critico e severo verso i miei difetti e le mie inadeguatezze.", "Sono intollerante e impaziente verso gli aspetti della mia personalità che non mi piacciono."]
  },
  text: {
    it: { kicker: "Auto-compassione", title: "Come ti tratti quando sbagli?", lede: "12 affermazioni, 2 minuti. La scala di Kristin Neff misura l'auto-compassione: gentilezza verso di sé, senso di umanità condivisa e presenza mentale, contro autocritica, isolamento e iper-identificazione.", meta: ["12 domande", "~2 minuti"], instr: "Per ogni frase indica <b>con quale frequenza ti comporti così</b> nei momenti difficili.", how: "Il punteggio è la media delle 12 affermazioni, da 1 a 5 (6 sono invertite). Indicazioni dell'autrice: 1–2,5 auto-compassione bassa, 2,5–3,5 moderata, 3,5–5 alta. La media negli adulti è intorno a 3. Non è indulgenza: chi si tratta con gentilezza nei fallimenti tende a riprovare di più, non di meno.", cite: "Raes, F., Pommier, E., Neff, K. D., & Van Gucht, D. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. Clinical Psychology & Psychotherapy, 18, 250-255. Uso libero non commerciale; traduzione italiana propria." },
    en: { kicker: "Self-compassion", title: "How do you treat yourself when you fail?", lede: "12 statements, 2 minutes. Kristin Neff's scale measures self-compassion: kindness towards yourself, a sense of common humanity and mindfulness, versus self-judgement, isolation and over-identification.", meta: ["12 questions", "~2 minutes"], instr: "For each statement, indicate <b>how often you behave that way</b> in difficult moments.", how: "The score is the mean of the 12 statements, from 1 to 5 (6 are reverse-keyed). The author's guidance: 1–2.5 low self-compassion, 2.5–3.5 moderate, 3.5–5 high. The adult mean is around 3. It is not indulgence: people who treat themselves kindly after failure tend to try again more, not less.", cite: "Raes, F., Pommier, E., Neff, K. D., & Van Gucht, D. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. Clinical Psychology & Psychotherapy, 18, 250-255. Free for non-commercial use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Auto-compassione", en: "Self-compassion" }, items: [1,2,3,4,5,6,7,8,9,10,11,12], mode: "mean", range: [1, 5],
    bands: [
      { max: 2.5, name: { it: "Bassa", en: "Low" }, text: { it: "Nei momenti difficili sei duro con te stesso, ti senti solo nel fallimento e ci rimugini. È il terreno su cui crescono ansia e umore basso; l'auto-compassione si allena, e in fretta.", en: "In hard moments you are harsh with yourself, feel alone in failure and ruminate on it. This is the ground where anxiety and low mood grow; self-compassion can be trained, and quickly." } },
      { max: 3.5, name: { it: "Moderata", en: "Moderate" }, text: { it: "A volte ti tratti con gentilezza, a volte con severità: come la maggior parte delle persone.", en: "Sometimes you treat yourself kindly, sometimes harshly: like most people." } },
      { max: 5, name: { it: "Alta", en: "High" }, text: { it: "Quando sbagli ti tratti come tratteresti un amico: con cura, prospettiva e senza drammi. È uno dei predittori più solidi del benessere.", en: "When you fail you treat yourself as you would a friend: with care, perspective and no drama. One of the most robust predictors of well-being." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.scssf.approf = {
  it: {
    title: "L'auto-compassione, in profondità",
    intro: `<p>Il concetto è recente: lo introduce <span class="t" data-tip="Kristin Neff, psicologa dell'Università del Texas ad Austin; a inizio anni Duemila porta nella psicologia accademica un'idea di radice buddhista e la rende misurabile.">Kristin Neff</span> nel 2003, attingendo alla tradizione buddhista e traducendola in un costrutto misurabile. L'<span class="t" data-tip="Trattare sé stessi, nei momenti di fallimento o dolore, con la stessa cura che si darebbe a un amico. Non è pena di sé né indulgenza.">auto-compassione</span> è definita da tre componenti, ognuna con un polo caldo e uno freddo: <b>gentilezza verso sé</b> contro <b>autogiudizio</b>, <b>umanità comune</b> contro <b>isolamento</b>, <b>presenza mentale</b> contro <b>iper-identificazione</b>. La <span class="t" data-tip="Self-Compassion Scale – Short Form: 12 item, forma breve validata da Raes e colleghi nel 2011 a partire dai 26 item originali di Neff.">forma breve</span> di Raes e colleghi (2011) misura tutte e sei le facce con dodici frasi.</p>`,
    blocks: [
      { h: "Le tre coppie", html: `<p>La <b>gentilezza verso sé</b> è parlarsi con calore invece che con durezza quando le cose vanno male; il suo opposto, l'<span class="t" data-tip="La voce interna critica che, davanti a un errore, attacca la persona invece del comportamento: non ho sbagliato, sono sbagliato.">autogiudizio</span>, attacca chi sei, non cosa hai fatto. L'<b>umanità comune</b> è ricordare che sbagliare e soffrire fa parte dell'essere umani; il suo opposto, l'<span class="t" data-tip="La sensazione, nel dolore, di essere gli unici a cui capita, mentre tutti gli altri se la cavano. Restringe e chiude.">isolamento</span>, ti fa sentire l'unico a cui va storto. La <b>presenza mentale</b> è tenere il dolore in equilibrio invece di esserne travolti; il suo opposto è l'<span class="t" data-tip="Fondersi con l'emozione negativa al punto da diventare quell'emozione: non sono triste, tutto è nero. La ruminazione ne è la forma tipica.">iper-identificazione</span>.</p>` },
      { h: "Non è autostima", html: `<p>La differenza con l'<span class="t" data-tip="Il giudizio globale sul proprio valore: quanto mi stimo. Dipende spesso dal successo e dal confronto con gli altri.">autostima</span> è il cuore della proposta di Neff. L'autostima è una <em>valutazione</em>: rispondi alla domanda «quanto valgo?», e la risposta sale e scende con i successi e con il confronto con gli altri. L'auto-compassione non è una valutazione ma un <em>modo di trattarti</em>, e vale proprio quando le cose vanno male, cioè quando l'autostima ti abbandona. Per questo tende a essere più stabile e a non portarsi dietro i lati oscuri dell'autostima alta, come il <span class="t" data-tip="Nella teoria di Neff, l'auto-compassione dà i benefici dell'autostima senza il bisogno di sentirsi superiori o di difendersi dalle critiche.">bisogno di sentirsi superiori</span>.</p>` },
      { h: "Un fattore o due?", html: `<p>Il punto più discusso è statistico ma pesa sull'interpretazione. Neff propone un punteggio unico; altri ricercatori sostengono che i sei elementi si raggruppino in <span class="t" data-tip="La tesi dei due fattori: da un lato la risposta compassionevole (gentilezza, umanità, presenza), dall'altro quella non compassionevole (giudizio, isolamento, iper-identificazione). Sommarle confonderebbe due cose diverse.">due fattori</span> — la risposta compassionevole e quella non compassionevole — e che sommarli in un totale nasconda informazione. C'è di più: i tre poli freddi correlano parecchio con il <span class="t" data-tip="Nevroticismo: il tratto di personalità che indica quanto si tende a provare emozioni negative. I suoi item somigliano molto a quelli dell'autogiudizio e dell'iper-identificazione.">nevroticismo</span>, tanto che parte di ciò che la scala misura potrebbe essere semplicemente <em>bassa</em> emotività negativa. Il dibattito non è chiuso.</p>` },
      { h: "Non è indulgenza", html: `<p>L'obiezione più comune è che trattarsi con gentilezza porti a mollare la presa. I dati vanno nella direzione opposta: chi si tratta con auto-compassione dopo un fallimento tende a riprovare di più, a prendersi la responsabilità senza sprofondare, a rimandare meno per paura di sbagliare. La durezza con sé, che sembra motivare, spesso paralizza. L'auto-compassione non abbassa gli standard: cambia cosa succede quando non li raggiungi.</p>` }
    ],
    beyond: `<ul>
      <li><b>Si allena in fretta.</b> Programmi come il Mindful Self-Compassion (Neff e Germer) alzano i punteggi in otto settimane; è tra i costrutti più modificabili con la pratica.</li>
      <li><b>Differenze di genere.</b> In media gli uomini riportano auto-compassione lievemente più alta delle donne, anche se la differenza è piccola e non universale.</li>
      <li><b>Il confine con l'autoindulgenza.</b> La stessa Neff distingue l'auto-compassione, che vuole il tuo bene a lungo termine, dall'assecondarsi nel breve: darsi conforto non è darsi ragione.</li>
      <li><b>Compassione ricevuta e data.</b> Chi fatica con l'auto-compassione spesso fatica anche a ricevere quella degli altri; è un tema che tocca da vicino l'attaccamento.</li>
    </ul>`,
    taratura: `<p>La versione breve è pratica e correla quasi perfettamente con la totale sul punteggio complessivo, ma proprio sulle singole sottoscale — due item ciascuna — è troppo corta per essere affidabile: usala per il totale, non per confrontare le sei componenti tra loro. Sul piano teorico resta aperto se l'auto-compassione sia una cosa sola o due, e quanto si sovrapponga al nevroticismo. Le soglie indicate dall'autrice sono orientative e ricavate soprattutto da campioni occidentali e studenteschi.</p>`,
    reading: [
      "Neff, K. D. (2003). Self-compassion: an alternative conceptualization of a healthy attitude toward oneself. <em>Self and Identity</em>, 2, 85-101.",
      "Raes, F. et al. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. <em>Clinical Psychology & Psychotherapy</em>, 18, 250-255.",
      "Neff, K., <em>Self-Compassion</em> (2011). Divulgativo, scritto dall'autrice."
    ]
  },
  en: {
    title: "Self-compassion, in depth",
    intro: `<p>The concept is recent: <span class="t" data-tip="Kristin Neff, psychologist at the University of Texas at Austin; in the early 2000s she brought an idea of Buddhist origin into academic psychology and made it measurable.">Kristin Neff</span> introduced it in 2003, drawing on the Buddhist tradition and translating it into a measurable construct. <span class="t" data-tip="Treating yourself, in moments of failure or pain, with the same care you would give a friend. It is neither self-pity nor indulgence.">Self-compassion</span> is defined by three components, each with a warm pole and a cold one: <b>self-kindness</b> versus <b>self-judgement</b>, <b>common humanity</b> versus <b>isolation</b>, <b>mindfulness</b> versus <b>over-identification</b>. The <span class="t" data-tip="Self-Compassion Scale – Short Form: 12 items, the short form validated by Raes and colleagues in 2011 from Neff's original 26 items.">short form</span> by Raes and colleagues (2011) measures all six faces with twelve statements.</p>`,
    blocks: [
      { h: "The three pairs", html: `<p><b>Self-kindness</b> is speaking to yourself with warmth rather than harshness when things go wrong; its opposite, <span class="t" data-tip="The inner critical voice that, faced with a mistake, attacks the person rather than the behaviour: I didn't make a mistake, I am a mistake.">self-judgement</span>, attacks who you are, not what you did. <b>Common humanity</b> is remembering that failing and suffering are part of being human; its opposite, <span class="t" data-tip="The sense, in pain, of being the only one it happens to while everyone else copes. It narrows and closes off.">isolation</span>, makes you feel you are the only one for whom things go wrong. <b>Mindfulness</b> is holding pain in balance rather than being overwhelmed by it; its opposite is <span class="t" data-tip="Fusing with the negative emotion to the point of becoming it: I am not sad, everything is black. Rumination is its typical form.">over-identification</span>.</p>` },
      { h: "It is not self-esteem", html: `<p>The difference from <span class="t" data-tip="The global judgement of your own worth: how much you value yourself. It often depends on success and on comparison with others.">self-esteem</span> is the heart of Neff's proposal. Self-esteem is an <em>evaluation</em>: you answer the question "how much am I worth?", and the answer rises and falls with successes and with comparison to others. Self-compassion is not an evaluation but a <em>way of treating yourself</em>, and it counts precisely when things go badly — that is, when self-esteem deserts you. This is why it tends to be more stable and to avoid the dark sides of high self-esteem, like the <span class="t" data-tip="In Neff's theory, self-compassion gives the benefits of self-esteem without the need to feel superior or to defend against criticism.">need to feel superior</span>.</p>` },
      { h: "One factor or two?", html: `<p>The most debated point is statistical but weighs on interpretation. Neff proposes a single score; other researchers argue the six elements group into <span class="t" data-tip="The two-factor case: on one side the compassionate response (kindness, humanity, mindfulness), on the other the uncompassionate one (judgement, isolation, over-identification). Summing them would blur two different things.">two factors</span> — the compassionate response and the uncompassionate one — and that summing them into a total hides information. There is more: the three cold poles correlate heavily with <span class="t" data-tip="Neuroticism: the personality trait indicating how much one tends to feel negative emotions. Its items closely resemble those of self-judgement and over-identification.">neuroticism</span>, so much that part of what the scale measures might simply be <em>low</em> negative emotionality. The debate is not settled.</p>` },
      { h: "It is not indulgence", html: `<p>The most common objection is that treating yourself kindly leads you to let go of the reins. The data point the other way: people who treat themselves with self-compassion after failure tend to try again more, to take responsibility without sinking, to procrastinate less out of fear of getting it wrong. Harshness with yourself, which seems to motivate, often paralyses. Self-compassion does not lower your standards: it changes what happens when you fall short of them.</p>` }
    ],
    beyond: `<ul>
      <li><b>It trains quickly.</b> Programmes like Mindful Self-Compassion (Neff and Germer) raise scores in eight weeks; it is among the most modifiable constructs with practice.</li>
      <li><b>Gender differences.</b> On average men report slightly higher self-compassion than women, though the difference is small and not universal.</li>
      <li><b>The border with self-indulgence.</b> Neff herself distinguishes self-compassion, which wants your long-term good, from indulging yourself in the short term: giving yourself comfort is not giving yourself an excuse.</li>
      <li><b>Compassion received and given.</b> Those who struggle with self-compassion often struggle to receive it from others too; it is a theme close to attachment.</li>
    </ul>`,
    taratura: `<p>The short form is practical and correlates almost perfectly with the full scale on the overall score, but on the individual subscales — two items each — it is too short to be reliable: use it for the total, not to compare the six components with one another. Theoretically it remains open whether self-compassion is one thing or two, and how far it overlaps with neuroticism. The thresholds given by the author are orientative and drawn mostly from Western and student samples.</p>`,
    reading: [
      "Neff, K. D. (2003). Self-compassion: an alternative conceptualization of a healthy attitude toward oneself. <em>Self and Identity</em>, 2, 85-101.",
      "Raes, F. et al. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. <em>Clinical Psychology & Psychotherapy</em>, 18, 250-255.",
      "Neff, K., <em>Self-Compassion</em> (2011). Popular, written by the author."
    ]
  },
  pt: {
    title: "A autocompaixão, em profundidade",
    intro: `<p>O conceito é recente: <span class="t" data-tip="Kristin Neff, psicóloga da Universidade do Texas em Austin; no início dos anos 2000 trouxe para a psicologia acadêmica uma ideia de raiz budista e a tornou mensurável.">Kristin Neff</span> o introduz em 2003, bebendo na tradição budista e traduzindo-a num construto mensurável. A <span class="t" data-tip="Tratar a si mesmo, nos momentos de fracasso ou dor, com o mesmo cuidado que se daria a um amigo. Não é pena de si nem indulgência.">autocompaixão</span> é definida por três componentes, cada um com um polo quente e um frio: <b>gentileza consigo</b> contra <b>autojulgamento</b>, <b>humanidade comum</b> contra <b>isolamento</b>, <b>atenção plena</b> contra <b>superidentificação</b>. A <span class="t" data-tip="Self-Compassion Scale – Short Form: 12 itens, forma breve validada por Raes e colegas em 2011 a partir dos 26 itens originais de Neff.">forma breve</span> de Raes e colegas (2011) mede todas as seis faces com doze frases.</p>`,
    blocks: [
      { h: "Os três pares", html: `<p>A <b>gentileza consigo</b> é falar consigo com calor em vez de dureza quando as coisas vão mal; seu oposto, o <span class="t" data-tip="A voz interna crítica que, diante de um erro, ataca a pessoa em vez do comportamento: não errei, eu sou o erro.">autojulgamento</span>, ataca quem você é, não o que você fez. A <b>humanidade comum</b> é lembrar que errar e sofrer faz parte de ser humano; seu oposto, o <span class="t" data-tip="A sensação, na dor, de ser o único a quem isso acontece, enquanto todos os outros dão conta. Estreita e fecha.">isolamento</span>, faz você se sentir o único a quem dá errado. A <b>atenção plena</b> é manter a dor em equilíbrio em vez de ser tomado por ela; seu oposto é a <span class="t" data-tip="Fundir-se com a emoção negativa a ponto de se tornar aquela emoção: não estou triste, tudo é preto. A ruminação é sua forma típica.">superidentificação</span>.</p>` },
      { h: "Não é autoestima", html: `<p>A diferença em relação à <span class="t" data-tip="O julgamento global do próprio valor: o quanto me estimo. Depende muitas vezes do sucesso e da comparação com os outros.">autoestima</span> é o coração da proposta de Neff. A autoestima é uma <em>avaliação</em>: você responde à pergunta «quanto valho?», e a resposta sobe e desce com os sucessos e com a comparação com os outros. A autocompaixão não é uma avaliação mas um <em>modo de se tratar</em>, e vale justamente quando as coisas vão mal, ou seja, quando a autoestima o abandona. Por isso tende a ser mais estável e a não carregar os lados sombrios da autoestima alta, como a <span class="t" data-tip="Na teoria de Neff, a autocompaixão dá os benefícios da autoestima sem a necessidade de se sentir superior ou de se defender das críticas.">necessidade de se sentir superior</span>.</p>` },
      { h: "Um fator ou dois?", html: `<p>O ponto mais discutido é estatístico mas pesa na interpretação. Neff propõe um escore único; outros pesquisadores sustentam que os seis elementos se agrupam em <span class="t" data-tip="A tese dos dois fatores: de um lado a resposta compassiva (gentileza, humanidade, atenção plena), de outro a não compassiva (julgamento, isolamento, superidentificação). Somá-las confundiria duas coisas diferentes.">dois fatores</span> — a resposta compassiva e a não compassiva — e que somá-los num total esconde informação. Há mais: os três polos frios correlacionam bastante com o <span class="t" data-tip="Neuroticismo: o traço de personalidade que indica o quanto se tende a sentir emoções negativas. Seus itens se parecem muito com os do autojulgamento e da superidentificação.">neuroticismo</span>, a ponto de parte do que a escala mede poder ser simplesmente <em>baixa</em> emotividade negativa. O debate não está encerrado.</p>` },
      { h: "Não é indulgência", html: `<p>A objeção mais comum é que se tratar com gentileza leva a afrouxar. Os dados vão na direção oposta: quem se trata com autocompaixão após um fracasso tende a tentar de novo mais, a assumir a responsabilidade sem afundar, a procrastinar menos por medo de errar. A dureza consigo, que parece motivar, muitas vezes paralisa. A autocompaixão não abaixa os padrões: muda o que acontece quando você não os alcança.</p>` }
    ],
    beyond: `<ul>
      <li><b>Treina-se rápido.</b> Programas como o Mindful Self-Compassion (Neff e Germer) elevam os escores em oito semanas; está entre os construtos mais modificáveis com a prática.</li>
      <li><b>Diferenças de gênero.</b> Em média os homens relatam autocompaixão levemente mais alta que as mulheres, embora a diferença seja pequena e não universal.</li>
      <li><b>A fronteira com a autoindulgência.</b> A própria Neff distingue a autocompaixão, que quer o seu bem a longo prazo, de se acomodar no curto: dar-se conforto não é dar-se razão.</li>
      <li><b>Compaixão recebida e dada.</b> Quem tem dificuldade com a autocompaixão muitas vezes também custa a receber a dos outros; é um tema que toca de perto o apego.</li>
    </ul>`,
    taratura: `<p>A versão breve é prática e correlaciona quase perfeitamente com a total no escore geral, mas justamente nas subescalas individuais — dois itens cada — é curta demais para ser confiável: use-a para o total, não para comparar os seis componentes entre si. No plano teórico continua em aberto se a autocompaixão é uma coisa só ou duas, e o quanto se sobrepõe ao neuroticismo. Os limiares indicados pela autora são orientativos e derivados sobretudo de amostras ocidentais e estudantis.</p>`,
    reading: [
      "Neff, K. D. (2003). Self-compassion: an alternative conceptualization of a healthy attitude toward oneself. <em>Self and Identity</em>, 2, 85-101.",
      "Raes, F. et al. (2011). Construction and factorial validation of a short form of the Self-Compassion Scale. <em>Clinical Psychology & Psychotherapy</em>, 18, 250-255.",
      "Neff, K., <em>Self-Compassion</em> (2011). Divulgação, escrito pela autora."
    ]
  }
};
