/* Short Dark Triad, SD3 (Jones & Paulhus 2014) — libero per ricerca con citazione. IT: traduzione propria (esiste la validazione di Somma et al. 2020). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.sd3 = {
  code: "SD3", theme: "slate", n: 27, reverse: [11, 15, 17, 20, 25],
  labels: { en: ["Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree"], it: ["Fortemente in disaccordo", "In disaccordo", "Né d'accordo né in disaccordo", "D'accordo", "Fortemente d'accordo"] },
  items: {
    en: ["It's not wise to tell your secrets.", "I like to use clever manipulation to get my way.", "Whatever it takes, you must get the important people on your side.", "Avoid direct conflict with others because they may be useful in the future.", "It's wise to keep track of information that you can use against people later.", "You should wait for the right time to get back at people.", "There are things you should hide from other people because they don't need to know.", "Make sure your plans benefit you, not others.", "Most people can be manipulated.", "People see me as a natural leader.", "I hate being the center of attention.", "Many group activities tend to be dull without me.", "I know that I am special because everyone keeps telling me so.", "I like to get acquainted with important people.", "I feel embarrassed if someone compliments me.", "I have been compared to famous people.", "I am an average person.", "I insist on getting the respect I deserve.", "I like to get revenge on authorities.", "I avoid dangerous situations.", "Payback needs to be quick and nasty.", "People often say I'm out of control.", "It's true that I can be mean to others.", "People who mess with me always regret it.", "I have never gotten into trouble with the law.", "I enjoy having sex with people I hardly know.", "I'll say anything to get what I want."],
    it: ["Non è saggio raccontare i propri segreti.", "Mi piace usare un'astuta manipolazione per ottenere quello che voglio.", "Costi quel che costi, bisogna avere le persone importanti dalla propria parte.", "Evita il conflitto diretto con gli altri, perché potrebbero esserti utili in futuro.", "È saggio tenere traccia delle informazioni che potrai usare contro le persone più avanti.", "Bisogna aspettare il momento giusto per vendicarsi delle persone.", "Ci sono cose che dovresti nascondere agli altri perché non hanno bisogno di saperle.", "Assicurati che i tuoi piani vadano a vantaggio tuo, non degli altri.", "La maggior parte delle persone può essere manipolata.", "Le persone mi vedono come un leader nato.", "Odio essere al centro dell'attenzione.", "Molte attività di gruppo tendono a essere noiose senza di me.", "So di essere speciale perché tutti continuano a dirmelo.", "Mi piace fare conoscenza con persone importanti.", "Mi sento in imbarazzo se qualcuno mi fa un complimento.", "Sono stato paragonato a persone famose.", "Sono una persona nella media.", "Pretendo di ottenere il rispetto che merito.", "Mi piace vendicarmi delle autorità.", "Evito le situazioni pericolose.", "La vendetta deve essere rapida e cattiva.", "Le persone dicono spesso che sono fuori controllo.", "È vero che posso essere cattivo con gli altri.", "Chi si mette contro di me se ne pente sempre.", "Non ho mai avuto guai con la legge.", "Mi piace fare sesso con persone che conosco appena.", "Direi qualsiasi cosa pur di ottenere quello che voglio."]
  },
  text: {
    it: { kicker: "Triade oscura", title: "Quanto sei «oscuro»?", lede: "27 affermazioni, 4 minuti. La Short Dark Triad misura i tre tratti «oscuri» della personalità: machiavellismo, narcisismo e psicopatia, in versione non clinica.", meta: ["27 domande", "~4 minuti", "3 tratti"], instr: "Per ogni frase indica quanto sei d'accordo. Rispondi con sincerità: nessuno la vede se non la condividi tu.", how: "Tre punteggi da 1 a 5, ciascuno la media di 9 affermazioni (5 sono invertite). Medie nei campioni di Paulhus: machiavellismo 3,1, narcisismo 2,8, psicopatia 2,4. Sopra circa una deviazione standard (3,9 / 3,7 / 3,4) sei chiaramente sopra la norma. Sono tratti di personalità, non diagnosi: tutti ne hanno un po', e in dosi moderate alcuni aiutano (negoziare, guidare, rischiare).", cite: "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): a brief measure of dark personality traits. Assessment, 21, 28-41. Uso libero per ricerca con citazione; traduzione italiana propria." },
    en: { kicker: "Dark triad", title: "How “dark” are you?", lede: "27 statements, 4 minutes. The Short Dark Triad measures the three “dark” personality traits: Machiavellianism, narcissism and psychopathy, in their non-clinical form.", meta: ["27 questions", "~4 minutes", "3 traits"], instr: "For each statement, indicate how much you agree. Be honest: nobody sees it unless you share it.", how: "Three scores from 1 to 5, each the mean of 9 statements (5 are reverse-keyed). Means in Paulhus's samples: Machiavellianism 3.1, narcissism 2.8, psychopathy 2.4. Above roughly one standard deviation (3.9 / 3.7 / 3.4) you are clearly above the norm. These are personality traits, not diagnoses: everyone has some, and in moderate doses some help (negotiating, leading, taking risks).", cite: "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): a brief measure of dark personality traits. Assessment, 21, 28-41. Free for research use with citation." }
  },
  scales: [
    { key: "mach", name: { it: "Machiavellismo", en: "Machiavellianism" }, items: [1,2,3,4,5,6,7,8,9], mode: "mean", range: [1, 5], bands: [
      { max: 2.3, name: { it: "Basso", en: "Low" }, text: { it: "Poco strategico e poco cinico: dici le cose come stanno e non giochi sul lungo termine con le persone.", en: "Not very strategic or cynical: you say things as they are and don't play the long game with people." } },
      { max: 3.86, name: { it: "Nella media", en: "Average" }, text: { it: "Una dose normale di pragmatismo: sai che le persone si possono influenzare e a volte lo fai.", en: "A normal dose of pragmatism: you know people can be influenced and sometimes you do it." } },
      { max: 5, name: { it: "Alto", en: "High" }, text: { it: "Calcolatore e cinico: le relazioni sono anche strumenti. Efficace nel breve, corrosivo per la fiducia nel lungo.", en: "Calculating and cynical: relationships are also tools. Effective short-term, corrosive to trust long-term." } }] },
    { key: "narc", name: { it: "Narcisismo", en: "Narcissism" }, items: [10,11,12,13,14,15,16,17,18], mode: "mean", range: [1, 5], bands: [
      { max: 1.9, name: { it: "Basso", en: "Low" }, text: { it: "Poca voglia di stare al centro: ti vedi come uno tra tanti, forse ti sottovaluti.", en: "Little wish to be centre stage: you see yourself as one of many, perhaps undervaluing yourself." } },
      { max: 3.68, name: { it: "Nella media", en: "Average" }, text: { it: "Un'autostima sana con un pizzico di vanità: normale.", en: "Healthy self-regard with a pinch of vanity: normal." } },
      { max: 5, name: { it: "Alto", en: "High" }, text: { it: "Ti senti speciale e vuoi che si veda. Carisma e leadership, ma anche fragilità alle critiche.", en: "You feel special and want it seen. Charisma and leadership, but also fragility to criticism." } }] },
    { key: "psy", name: { it: "Psicopatia", en: "Psychopathy" }, items: [19,20,21,22,23,24,25,26,27], mode: "mean", range: [1, 5], bands: [
      { max: 1.4, name: { it: "Bassa", en: "Low" }, text: { it: "Prudente e controllato: impulsività e durezza non fanno per te.", en: "Cautious and controlled: impulsiveness and callousness are not your thing." } },
      { max: 3.4, name: { it: "Nella media", en: "Average" }, text: { it: "Qualche impulso e qualche spigolo, nella norma.", en: "Some impulses and some sharp edges, within the norm." } },
      { max: 5, name: { it: "Alta", en: "High" }, text: { it: "Impulsivo, in cerca di brividi, poco toccato dalle conseguenze sugli altri. È il tratto che più costa nelle relazioni.", en: "Impulsive, thrill-seeking, little touched by the consequences for others. The trait that costs most in relationships." } }] }
  ]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.sd3.approf = {
  it: {
    title: "La Triade Oscura, in profondità",
    intro: `<p>L'espressione «triade oscura» nasce nel 2002 con <span class="t" data-tip="Delroy Paulhus e Kevin Williams: notarono che tre tratti studiati separatamente — machiavellismo, narcisismo e psicopatia — erano parenti stretti, e proposero di studiarli insieme.">Paulhus e Williams</span>, che raggrupparono tre tratti fino ad allora studiati a parte: il <span class="t" data-tip="Dal Principe di Machiavelli: la tendenza a manipolare in modo freddo e strategico, con una visione cinica delle persone come mezzi. Christie e Geis ne fecero un tratto misurabile negli anni '70.">machiavellismo</span>, il <span class="t" data-tip="Qui inteso come tratto di personalità, non come disturbo: grandiosità, senso di superiorità, bisogno di ammirazione. Diverso dal narcisismo patologico clinico.">narcisismo</span> e la <span class="t" data-tip="Nella versione dei tratti: impulsività, ricerca di brividi e freddezza emotiva. Da non confondere con la psicopatia clinica, che si valuta con strumenti come la PCL-R di Robert Hare.">psicopatia</span>. La SD3 li misura tutti e tre con 27 frasi. La parola «oscuro» non è un giudizio morale: indica tratti socialmente sgraditi ma <b>normali</b>, presenti in tutti in dosi diverse.</p>`,
    blocks: [
      { h: "Tre tratti, un nucleo", html: `<p>I tre non sono la stessa cosa, ma condividono un cuore comune: la <span class="t" data-tip="Callousness, in inglese: freddezza affettiva, scarsa empatia, indifferenza al danno che si fa agli altri. È il filo che unisce i tre tratti oscuri.">freddezza affettiva</span> e la disponibilità a manipolare. Alcuni ricercatori hanno chiamato questo denominatore comune il <span class="t" data-tip="Il fattore D, o nucleo oscuro della personalità: la tendenza generale a mettere il proprio interesse davanti a quello degli altri, giustificandolo. Sotto ai vari tratti oscuri ci sarebbe questo unico motore.">nucleo oscuro</span> della personalità — la tendenza di fondo a massimizzare il proprio interesse a spese altrui, con una giustificazione pronta. Sopra questo nucleo, ogni tratto aggiunge il suo colore: strategia fredda (machiavellismo), bisogno di ammirazione (narcisismo), impulsività (psicopatia).</p>` },
      { h: "Subclinico e continuo", html: `<p>Il punto più frainteso: questi sono tratti <span class="t" data-tip="Subclinico: presente nella popolazione normale, sotto la soglia di un disturbo diagnosticabile. La SD3 non fa diagnosi e non individua psicopatici clinici.">subclinici</span> e <span class="t" data-tip="Continuo: distribuito su una scala graduale, non un interruttore acceso o spento. Tutti hanno un punteggio; nessuno è dentro o fuori una categoria.">continui</span>, non diagnosi. Non esistono «gli psicopatici» e «i normali» come due gruppi separati: c'è una scala, e ciascuno sta da qualche parte. In dosi moderate alcuni di questi tratti tornano perfino utili — l'assertività per negoziare, la freddezza per decidere sotto pressione, la sicurezza per guidare. Un punteggio alto descrive una tendenza, non certifica un pericolo.</p>` },
      { h: "Narcisismo: due volti", html: `<p>Il narcisismo non è uno solo. C'è quello <span class="t" data-tip="Narcisismo grandioso: sicurezza, dominanza, esibizione, autostima gonfia. È estroverso e sicuro di sé; è quello che la SD3 misura.">grandioso</span> — sicuro, dominante, che si mette in mostra — e quello <span class="t" data-tip="Narcisismo vulnerabile: stessa grandiosità di fondo, ma fragile, ipersensibile alle critiche, ritirato e ansioso. È molto meno colto dai questionari come la SD3.">vulnerabile</span> — fragile, ipersensibile alle critiche, ritirato. Sotto c'è la stessa grandiosità, ma la faccia esterna è opposta. La SD3 coglie soprattutto il primo: chi ha molto narcisismo vulnerabile può ottenere un punteggio basso pur soffrendo molto per il tema. È un limite da tenere presente nel leggere il risultato.</p>` },
      { h: "La psicopatia è quella che costa", html: `<p>Dei tre, la psicopatia è il predittore più tossico. È il tratto più legato ad aggressività, comportamenti a rischio, rotture e problemi con le regole, perché unisce due ingredienti pericolosi: l'impulsività (agire senza freni) e la freddezza (non essere toccati dalle conseguenze sugli altri). Il narcisismo grandioso ha almeno un lato adattivo — carisma, energia — e il machiavellismo è calcolatore ma prudente. La psicopatia, no: è quella che, nelle relazioni e nel lavoro, lascia i danni maggiori.</p>` }
    ],
    beyond: `<ul>
      <li><b>Distinti ma sovrapposti.</b> Machiavellismo e psicopatia condividono molto (freddezza, disonestà); li separa soprattutto l'impulsività, alta nella psicopatia e bassa nel machiavellico, che aspetta il momento giusto.</li>
      <li><b>Il lato adattivo.</b> In dosi contenute alcuni tratti aiutano: leader, negoziatori e imprenditori hanno spesso punteggi un po' sopra la media. È la questione della «giusta dose», non della presenza o assenza.</li>
      <li><b>La triade luminosa</b> (Kaufman): l'opposto non è «zero tratti oscuri» ma un profilo attivo di fiducia negli altri, empatia e trattare le persone come fini. Non è semplicemente il negativo della triade oscura.</li>
      <li><b>Differenze di genere.</b> In media gli uomini ottengono punteggi un po' più alti, soprattutto sulla psicopatia; la differenza è modesta e c'è ampia sovrapposizione tra le persone.</li>
    </ul>`,
    taratura: `<p>La SD3 è breve, pratica e ampiamente usata, con un'attendibilità accettabile per uno strumento di 27 item; la sottoscala della psicopatia tende a essere la più debole. Il limite più serio è comune a tutti i test su tratti sgraditi: si basa sull'autovalutazione, e chi ha davvero questi tratti ha ottime ragioni per non ammetterli o per manipolare le risposte — la desiderabilità sociale abbassa i punteggi veri. E va ribadito: subclinico non è clinico. Un punteggio alto non fa di nessuno uno psicopatico nel senso della PCL-R; misura una tendenza nella popolazione normale, non una diagnosi.</p>`,
    reading: [
      "Jones, D. N. & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3). <em>Assessment</em>, 21, 28-41.",
      "Paulhus, D. L. & Williams, K. M. (2002). The Dark Triad of personality. <em>Journal of Research in Personality</em>, 36, 556-563.",
      "Moshagen, M., Hilbig, B. E. & Zettler, I. (2018). The dark core of personality. <em>Psychological Review</em>, 125, 656-688."
    ]
  },
  en: {
    title: "The Dark Triad, in depth",
    intro: `<p>The phrase «dark triad» was coined in 2002 by <span class="t" data-tip="Delroy Paulhus and Kevin Williams: they noticed that three traits studied separately — Machiavellianism, narcissism and psychopathy — were close relatives, and proposed studying them together.">Paulhus and Williams</span>, who grouped three traits until then studied apart: <span class="t" data-tip="From Machiavelli's Prince: the tendency to manipulate coldly and strategically, with a cynical view of people as means. Christie and Geis made it a measurable trait in the 1970s.">Machiavellianism</span>, <span class="t" data-tip="Here understood as a personality trait, not a disorder: grandiosity, sense of superiority, need for admiration. Different from clinical pathological narcissism.">narcissism</span> and <span class="t" data-tip="In the trait version: impulsivity, thrill-seeking and emotional coldness. Not to be confused with clinical psychopathy, assessed with tools like Robert Hare's PCL-R.">psychopathy</span>. The SD3 measures all three with 27 statements. The word «dark» is not a moral verdict: it marks socially disliked but <b>normal</b> traits, present in everyone in varying doses.</p>`,
    blocks: [
      { h: "Three traits, one core", html: `<p>The three are not the same thing, but they share a common heart: <span class="t" data-tip="Callousness: emotional coldness, low empathy, indifference to the harm done to others. It is the thread that ties the three dark traits together.">callousness</span> and a willingness to manipulate. Some researchers have called this common denominator the <span class="t" data-tip="The D factor, or dark core of personality: the general tendency to place one's own interest ahead of others', with a ready justification. Beneath the various dark traits would lie this single engine.">dark core</span> of personality — the underlying drive to maximise self-interest at others' expense, with a justification at hand. On top of this core, each trait adds its colour: cold strategy (Machiavellianism), need for admiration (narcissism), impulsivity (psychopathy).</p>` },
      { h: "Subclinical and continuous", html: `<p>The most misread point: these are <span class="t" data-tip="Subclinical: present in the normal population, below the threshold of a diagnosable disorder. The SD3 makes no diagnosis and does not identify clinical psychopaths.">subclinical</span> and <span class="t" data-tip="Continuous: spread on a graded scale, not an on-off switch. Everyone has a score; nobody is inside or outside a category.">continuous</span> traits, not diagnoses. There is no «the psychopaths» and «the normal people» as two separate groups: there is a scale, and each of us sits somewhere on it. In moderate doses some of these traits are even useful — assertiveness to negotiate, coolness to decide under pressure, confidence to lead. A high score describes a tendency, it does not certify a danger.</p>` },
      { h: "Narcissism: two faces", html: `<p>Narcissism is not one thing. There is the <span class="t" data-tip="Grandiose narcissism: confidence, dominance, showing off, inflated self-esteem. Extraverted and self-assured; this is what the SD3 measures.">grandiose</span> kind — confident, dominant, on show — and the <span class="t" data-tip="Vulnerable narcissism: the same underlying grandiosity, but fragile, hypersensitive to criticism, withdrawn and anxious. Much less captured by questionnaires like the SD3.">vulnerable</span> kind — fragile, hypersensitive to criticism, withdrawn. Underneath lies the same grandiosity, but the outward face is opposite. The SD3 mostly catches the first: someone high in vulnerable narcissism may score low while suffering deeply over the theme. A limit worth keeping in mind when reading the result.</p>` },
      { h: "Psychopathy is the costly one", html: `<p>Of the three, psychopathy is the most toxic predictor. It is the trait most tied to aggression, risky behaviour, breakups and trouble with rules, because it combines two dangerous ingredients: impulsivity (acting without brakes) and callousness (being untouched by the consequences for others). Grandiose narcissism has at least an adaptive side — charisma, energy — and Machiavellianism is calculating but cautious. Psychopathy is not: it is the one that, in relationships and at work, leaves the greatest damage.</p>` }
    ],
    beyond: `<ul>
      <li><b>Distinct but overlapping.</b> Machiavellianism and psychopathy share a lot (coldness, dishonesty); what mostly separates them is impulsivity, high in psychopathy and low in the Machiavellian, who waits for the right moment.</li>
      <li><b>The adaptive side.</b> In modest doses some traits help: leaders, negotiators and entrepreneurs often score a little above average. It is a question of the «right dose», not of presence or absence.</li>
      <li><b>The light triad</b> (Kaufman): the opposite is not «zero dark traits» but an active profile of trust in others, empathy and treating people as ends. It is not simply the negative of the dark triad.</li>
      <li><b>Gender differences.</b> On average men score a little higher, especially on psychopathy; the difference is modest and there is wide overlap between people.</li>
    </ul>`,
    taratura: `<p>The SD3 is brief, practical and widely used, with acceptable reliability for a 27-item tool; the psychopathy subscale tends to be the weakest. The most serious limit is shared by all tests of disliked traits: it rests on self-report, and people who truly have these traits have every reason not to admit them or to manipulate their answers — social desirability lowers the true scores. And it bears repeating: subclinical is not clinical. A high score makes no one a psychopath in the PCL-R sense; it measures a tendency in the normal population, not a diagnosis.</p>`,
    reading: [
      "Jones, D. N. & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3). <em>Assessment</em>, 21, 28-41.",
      "Paulhus, D. L. & Williams, K. M. (2002). The Dark Triad of personality. <em>Journal of Research in Personality</em>, 36, 556-563.",
      "Moshagen, M., Hilbig, B. E. & Zettler, I. (2018). The dark core of personality. <em>Psychological Review</em>, 125, 656-688."
    ]
  },
  pt: {
    title: "A Tríade Sombria, em profundidade",
    intro: `<p>A expressão «tríade sombria» surgiu em 2002 com <span class="t" data-tip="Delroy Paulhus e Kevin Williams: notaram que três traços estudados em separado — maquiavelismo, narcisismo e psicopatia — eram parentes próximos, e propuseram estudá-los juntos.">Paulhus e Williams</span>, que agruparam três traços até então estudados à parte: o <span class="t" data-tip="Do Príncipe de Maquiavel: a tendência a manipular de forma fria e estratégica, com uma visão cínica das pessoas como meios. Christie e Geis o tornaram um traço mensurável nos anos 70.">maquiavelismo</span>, o <span class="t" data-tip="Aqui entendido como traço de personalidade, não como transtorno: grandiosidade, senso de superioridade, necessidade de admiração. Diferente do narcisismo patológico clínico.">narcisismo</span> e a <span class="t" data-tip="Na versão dos traços: impulsividade, busca de emoções fortes e frieza emocional. Não confundir com a psicopatia clínica, avaliada com instrumentos como a PCL-R de Robert Hare.">psicopatia</span>. A SD3 mede os três com 27 frases. A palavra «sombrio» não é um juízo moral: indica traços socialmente malvistos mas <b>normais</b>, presentes em todos em doses diferentes.</p>`,
    blocks: [
      { h: "Três traços, um núcleo", html: `<p>Os três não são a mesma coisa, mas compartilham um coração comum: a <span class="t" data-tip="Callousness, em inglês: frieza afetiva, pouca empatia, indiferença ao dano causado aos outros. É o fio que une os três traços sombrios.">frieza afetiva</span> e a disposição para manipular. Alguns pesquisadores chamaram esse denominador comum de <span class="t" data-tip="O fator D, ou núcleo sombrio da personalidade: a tendência geral a colocar o próprio interesse à frente do dos outros, justificando-o. Sob os vários traços sombrios estaria esse único motor.">núcleo sombrio</span> da personalidade — a tendência de fundo a maximizar o próprio interesse às custas alheias, com uma justificativa pronta. Sobre esse núcleo, cada traço acrescenta sua cor: estratégia fria (maquiavelismo), necessidade de admiração (narcisismo), impulsividade (psicopatia).</p>` },
      { h: "Subclínico e contínuo", html: `<p>O ponto mais mal compreendido: estes são traços <span class="t" data-tip="Subclínico: presente na população normal, abaixo do limiar de um transtorno diagnosticável. A SD3 não faz diagnóstico e não identifica psicopatas clínicos.">subclínicos</span> e <span class="t" data-tip="Contínuo: distribuído numa escala gradual, não um interruptor ligado ou desligado. Todos têm uma pontuação; ninguém está dentro ou fora de uma categoria.">contínuos</span>, não diagnósticos. Não existem «os psicopatas» e «os normais» como dois grupos separados: há uma escala, e cada um está em algum ponto dela. Em doses moderadas alguns desses traços chegam a ser úteis — a assertividade para negociar, a frieza para decidir sob pressão, a segurança para liderar. Uma pontuação alta descreve uma tendência, não atesta um perigo.</p>` },
      { h: "Narcisismo: dois rostos", html: `<p>O narcisismo não é um só. Há o <span class="t" data-tip="Narcisismo grandioso: segurança, dominância, exibição, autoestima inflada. É extrovertido e autoconfiante; é o que a SD3 mede.">grandioso</span> — seguro, dominante, que se exibe — e o <span class="t" data-tip="Narcisismo vulnerável: a mesma grandiosidade de fundo, mas frágil, hipersensível às críticas, retraído e ansioso. Bem menos captado por questionários como a SD3.">vulnerável</span> — frágil, hipersensível às críticas, retraído. Por baixo está a mesma grandiosidade, mas a face externa é oposta. A SD3 capta sobretudo o primeiro: quem tem muito narcisismo vulnerável pode obter uma pontuação baixa mesmo sofrendo bastante com o tema. É um limite a ter em mente ao ler o resultado.</p>` },
      { h: "A psicopatia é a que custa", html: `<p>Dos três, a psicopatia é o preditor mais tóxico. É o traço mais ligado à agressividade, aos comportamentos de risco, aos rompimentos e aos problemas com regras, porque une dois ingredientes perigosos: a impulsividade (agir sem freios) e a frieza (não ser tocado pelas consequências sobre os outros). O narcisismo grandioso tem ao menos um lado adaptativo — carisma, energia — e o maquiavelismo é calculista mas prudente. A psicopatia, não: é a que, nos relacionamentos e no trabalho, deixa os maiores danos.</p>` }
    ],
    beyond: `<ul>
      <li><b>Distintos mas sobrepostos.</b> Maquiavelismo e psicopatia compartilham muito (frieza, desonestidade); o que mais os separa é a impulsividade, alta na psicopatia e baixa no maquiavélico, que espera o momento certo.</li>
      <li><b>O lado adaptativo.</b> Em doses contidas alguns traços ajudam: líderes, negociadores e empreendedores costumam pontuar um pouco acima da média. É a questão da «dose certa», não da presença ou ausência.</li>
      <li><b>A tríade luminosa</b> (Kaufman): o oposto não é «zero traços sombrios» mas um perfil ativo de confiança nos outros, empatia e tratar as pessoas como fins. Não é simplesmente o negativo da tríade sombria.</li>
      <li><b>Diferenças de gênero.</b> Em média os homens pontuam um pouco mais alto, sobretudo na psicopatia; a diferença é modesta e há ampla sobreposição entre as pessoas.</li>
    </ul>`,
    taratura: `<p>A SD3 é breve, prática e amplamente usada, com uma confiabilidade aceitável para um instrumento de 27 itens; a subescala da psicopatia tende a ser a mais fraca. O limite mais sério é comum a todos os testes de traços malvistos: baseia-se na autoavaliação, e quem de fato tem esses traços tem ótimas razões para não admiti-los ou para manipular as respostas — a desejabilidade social rebaixa as pontuações reais. E vale repetir: subclínico não é clínico. Uma pontuação alta não faz de ninguém um psicopata no sentido da PCL-R; mede uma tendência na população normal, não um diagnóstico.</p>`,
    reading: [
      "Jones, D. N. & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3). <em>Assessment</em>, 21, 28-41.",
      "Paulhus, D. L. & Williams, K. M. (2002). The Dark Triad of personality. <em>Journal of Research in Personality</em>, 36, 556-563.",
      "Moshagen, M., Hilbig, B. E. & Zettler, I. (2018). The dark core of personality. <em>Psychological Review</em>, 125, 656-688."
    ]
  }
};
