/* Short Dark Triad, SD3 (Jones & Paulhus 2014) — libero per ricerca con citazione. IT: traduzione propria (esiste la validazione di Somma et al. 2020). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.sd3 = {
  code: "SD3", theme: "slate", n: 27, reverse: [11, 15, 17, 20, 25],
  labels: { en: ["Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree"], it: ["Fortemente in disaccordo", "In disaccordo", "Né d'accordo né in disaccordo", "D'accordo", "Fortemente d'accordo"] },
  items: {
    en: ["It's not wise to tell your secrets.", "I like to use clever manipulation to get my way.", "Whatever it takes, you must get the important people on your side.", "Avoid direct conflict with others because they may be useful in the future.", "It's wise to keep track of information that you can use against people later.", "You should wait for the right time to get back at people.", "There are things you should hide from other people because they don't need to know.", "Make sure your plans benefit you, not others.", "Most people can be manipulated.", "People see me as a natural leader.", "I hate being the center of attention.", "Many group activities tend to be dull without me.", "I know that I am special because everyone keeps telling me so.", "I like to get acquainted with important people.", "I feel embarrassed if someone compliments me.", "I have been compared to famous people.", "I am an average person.", "I insist on getting the respect I deserve.", "I like to get revenge on authorities.", "I avoid dangerous situations.", "Payback needs to be quick and nasty.", "People often say I'm out of control.", "It's true that I can be mean to others.", "People who mess with me always regret it.", "I have never gotten into trouble with the law.", "I enjoy having sex with people I hardly know.", "I'll say anything to get what I want."],
    it: ["Non è saggio raccontare i propri segreti.", "Mi piace usare un'astuta manipolazione per ottenere quello che voglio.", "Costi quel che costi, bisogna avere le persone importanti dalla propria parte.", "Evita il conflitto diretto con gli altri, perché potrebbero esserti utili in futuro.", "È saggio tenere traccia delle informazioni che potrai usare contro le persone più avanti.", "Bisogna aspettare il momento giusto per vendicarsi delle persone.", "Ci sono cose che dovresti nascondere agli altri perché non hanno bisogno di saperle.", "Assicurati che i tuoi piani vadano a vantaggio tuo, non degli altri.", "La maggior parte delle persone può essere manipolata.", "Le persone mi vedono come un leader nato.", "Odio essere al centro dell'attenzione.", "Molte attività di gruppo tendono a essere noiose senza di me.", "So di essere speciale perché tutti continuano a dirmelo.", "Mi piace fare conoscenza con persone importanti.", "Mi sento in imbarazzo se qualcuno mi fa un complimento.", "Sono stato paragonato a persone famose.", "Sono una persona nella media.", "Pretendo di ottenere il rispetto che merito.", "Mi piace vendicarmi delle autorità.", "Evito le situazioni pericolose.", "La vendetta deve essere rapida e cattiva.", "Le persone dicono spesso che sono fuori controllo.", "È vero che posso essere cattivo con gli altri.", "Chi si mette contro di me se ne pente sempre.", "Non ho mai avuto guai con la legge.", "Mi piace fare sesso con persone che conosco appena.", "Direi qualsiasi cosa pur di ottenere quello che voglio."]
  },
  text: {
    it: { kicker: "Triade oscura", title: "Quanto sei «oscuro»?", lede: "27 affermazioni, 4 minuti. La Short Dark Triad misura i tre tratti «oscuri» della personalità: machiavellismo, narcisismo e psicopatia, in versione non clinica.", meta: ["27 domande", "~4 minuti", "3 tratti"], instr: "Per ogni frase indica quanto sei d'accordo. Rispondi con sincerità: nessuno la vede se non la condividi tu.", how: "Tre punteggi da 1 a 5, ciascuno la media di 9 affermazioni (5 sono invertite). Medie nei campioni di Paulhus: machiavellismo 3,1, narcisismo 2,8, psicopatia 2,4. Sopra circa una deviazione standard (3,9 / 3,7 / 3,4) sei chiaramente sopra la norma. Sono tratti di personalità, non diagnosi: tutti ne hanno un po', e in dosi moderate alcuni aiutano (negoziare, guidare, rischiare).", cite: "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): a brief measure of dark personality traits. Assessment, 21, 28-41. Uso libero per ricerca con citazione; traduzione italiana propria." },
    en: { kicker: "Dark triad", title: "How “dark” are you?", lede: "27 statements, 4 minutes. The Short Dark Triad measures the three “dark” personality traits: Machiavellianism, narcissism and psychopathy, in their non-clinical form.", meta: ["27 questions", "~4 minutes", "3 traits"], instr: "For each statement, indicate how much you agree. Be honest: nobody sees it unless you share it.", how: "Three scores from 1 to 5, each the mean of 9 statements (5 are reverse-keyed). Means in Paulhus's samples: Machiavellianism 3.1, narcissism 2.8, psychopathy 2.4. Above roughly one standard deviation (3.9 / 3.7 / 3.4) you are clearly above the norm. These are personality traits, not diagnoses: everyone has some, and in moderate doses some help (negotiating, leading, taking risks).", cite: "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): a brief measure of dark personality traits. Assessment, 21, 28-41. Free for research use with citation." }
  },
  scales: [
    { key: "mach", name: { it: "Machiavellismo", en: "Machiavellianism" }, items: [1,2,3,4,5,6,7,8,9], mode: "mean", range: [1, 5], bands: [
      { max: 2.3, name: { it: "Basso", en: "Low" }, text: { it: "Poco strategico e poco cinico: dici le cose come stanno e non giochi sul lungo termine con le persone.", en: "Not very strategic or cynical: you say things as they are and don't play the long game with people." } },
      { max: 3.86, name: { it: "Nella media", en: "Average" }, text: { it: "Una dose normale di pragmatismo: sai che le persone si possono influenzare e a volte lo fai.", en: "A normal dose of pragmatism: you know people can be influenced and sometimes you do it." } },
      { max: 5, name: { it: "Alto", en: "High" }, text: { it: "Calcolatore e cinico: le relazioni sono anche strumenti. Efficace nel breve, corrosivo per la fiducia nel lungo.", en: "Calculating and cynical: relationships are also tools. Effective short-term, corrosive to trust long-term." } }] },
    { key: "narc", name: { it: "Narcisismo", en: "Narcissism" }, items: [10,11,12,13,14,15,16,17,18], mode: "mean", range: [1, 5], bands: [
      { max: 1.9, name: { it: "Basso", en: "Low" }, text: { it: "Poca voglia di stare al centro: ti vedi come uno tra tanti, forse ti sottovaluti.", en: "Little wish to be centre stage: you see yourself as one of many, perhaps undervaluing yourself." } },
      { max: 3.68, name: { it: "Nella media", en: "Average" }, text: { it: "Un'autostima sana con un pizzico di vanità: normale.", en: "Healthy self-regard with a pinch of vanity: normal." } },
      { max: 5, name: { it: "Alto", en: "High" }, text: { it: "Ti senti speciale e vuoi che si veda. Carisma e leadership, ma anche fragilità alle critiche.", en: "You feel special and want it seen. Charisma and leadership, but also fragility to criticism." } }] },
    { key: "psy", name: { it: "Psicopatia", en: "Psychopathy" }, items: [19,20,21,22,23,24,25,26,27], mode: "mean", range: [1, 5], bands: [
      { max: 1.4, name: { it: "Bassa", en: "Low" }, text: { it: "Prudente e controllato: impulsività e durezza non fanno per te.", en: "Cautious and controlled: impulsiveness and callousness are not your thing." } },
      { max: 3.4, name: { it: "Nella media", en: "Average" }, text: { it: "Qualche impulso e qualche spigolo, nella norma.", en: "Some impulses and some sharp edges, within the norm." } },
      { max: 5, name: { it: "Alta", en: "High" }, text: { it: "Impulsivo, in cerca di brividi, poco toccato dalle conseguenze sugli altri. È il tratto che più costa nelle relazioni.", en: "Impulsive, thrill-seeking, little touched by the consequences for others. The trait that costs most in relationships." } }] }
  ]
};
