/* Satisfaction With Life Scale (Diener, Emmons, Larsen & Griffin 1985) — libero. IT: Di Fabio & Gori (2016). */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.swls = {
  code: "SWLS", theme: "sun", n: 5,
  labels: {
    en: ["Strongly disagree", "Disagree", "Slightly disagree", "Neither agree nor disagree", "Slightly agree", "Agree", "Strongly agree"],
    it: ["Fortemente in disaccordo", "In disaccordo", "Leggermente in disaccordo", "Né d'accordo né in disaccordo", "Leggermente d'accordo", "D'accordo", "Fortemente d'accordo"]
  },
  items: {
    en: ["In most ways my life is close to my ideal.", "The conditions of my life are excellent.", "I am satisfied with my life.", "So far I have gotten the important things I want in life.", "If I could live my life over, I would change almost nothing."],
    it: ["Per molti aspetti la mia vita è vicina al mio ideale.", "Le condizioni della mia vita sono eccellenti.", "Sono soddisfatto della mia vita.", "Finora ho ottenuto le cose importanti che voglio dalla vita.", "Se potessi rivivere la mia vita, non cambierei quasi nulla."]
  },
  text: {
    it: { kicker: "Soddisfazione per la vita", title: "Quanto sei soddisfatto della tua vita?", lede: "5 affermazioni, 1 minuto. La SWLS di Diener misura il giudizio complessivo che dai alla tua vita, non l'umore del momento.", meta: ["5 domande", "~1 minuto"], instr: "Per ogni frase indica quanto sei d'accordo. Rispondi con sincerità: non ci sono risposte giuste o sbagliate.", how: "Il punteggio va da 5 a 35. Le fasce dell'autore: 31–35 estremamente soddisfatto, 26–30 soddisfatto, 21–25 leggermente soddisfatto, 20 neutro, 15–19 leggermente insoddisfatto, 10–14 insoddisfatto, 5–9 estremamente insoddisfatto. La media nella popolazione adulta occidentale è intorno a 23–25.", cite: "Diener, E., Emmons, R. A., Larsen, R. J., & Griffin, S. (1985). The Satisfaction With Life Scale. Journal of Personality Assessment, 49, 71-75. Uso libero." },
    en: { kicker: "Life satisfaction", title: "How satisfied are you with your life?", lede: "5 statements, 1 minute. Diener's SWLS measures your overall judgement of your life, not today's mood.", meta: ["5 questions", "~1 minute"], instr: "For each statement, indicate how much you agree. Be honest: there are no right or wrong answers.", how: "The score runs from 5 to 35. The author's bands: 31–35 extremely satisfied, 26–30 satisfied, 21–25 slightly satisfied, 20 neutral, 15–19 slightly dissatisfied, 10–14 dissatisfied, 5–9 extremely dissatisfied. The Western adult average is around 23–25.", cite: "Diener, E., Emmons, R. A., Larsen, R. J., & Griffin, S. (1985). The Satisfaction With Life Scale. Journal of Personality Assessment, 49, 71-75. Free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Soddisfazione", en: "Satisfaction" }, items: [1,2,3,4,5], mode: "sum", range: [5, 35],
    bands: [
      { max: 9, name: { it: "Estremamente insoddisfatto", en: "Extremely dissatisfied" }, text: { it: "La tua vita, oggi, è molto lontana da come la vorresti. Spesso dietro c'è un problema concreto e recente (salute, lavoro, relazioni): vale la pena guardarlo da vicino, anche con un aiuto.", en: "Your life today is very far from how you would want it. Often there is a concrete, recent problem behind this (health, work, relationships): worth looking at closely, with help if needed." } },
      { max: 14, name: { it: "Insoddisfatto", en: "Dissatisfied" }, text: { it: "Diverse aree della tua vita non vanno come vorresti. Individuare quale pesa di più è il primo passo.", en: "Several areas of your life are not going as you would like. Identifying which weighs most is the first step." } },
      { max: 19, name: { it: "Leggermente insoddisfatto", en: "Slightly dissatisfied" }, text: { it: "Qualcosa non torna, ma nel complesso regge: c'è un'area in cui vorresti di più.", en: "Something is off, but overall it holds: there is an area where you want more." } },
      { max: 20, name: { it: "Neutro", en: "Neutral" }, text: { it: "Né soddisfatto né insoddisfatto: una vita che va, senza entusiasmo e senza grandi pesi.", en: "Neither satisfied nor dissatisfied: a life that goes on, without enthusiasm and without heavy burdens." } },
      { max: 25, name: { it: "Leggermente soddisfatto", en: "Slightly satisfied" }, text: { it: "Nella media: la maggior parte delle cose va bene, con qualche area che vorresti migliorare.", en: "Average: most things are going well, with some area you would like to improve." } },
      { max: 30, name: { it: "Soddisfatto", en: "Satisfied" }, text: { it: "Sei contento della tua vita: le aree principali funzionano e quello che manca è di dettaglio.", en: "You are happy with your life: the main areas work and what is missing is detail." } },
      { max: 35, name: { it: "Estremamente soddisfatto", en: "Extremely satisfied" }, text: { it: "Ami la tua vita così com'è: raro e prezioso.", en: "You love your life as it is: rare and precious." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.swls.approf = {
  it: {
    title: "La soddisfazione di vita, in profondità",
    intro: `<p><span class="t" data-tip="Ed Diener (1946-2021), psicologo americano soprannominato Dr. Happiness. Sostenne che la felicità poteva essere studiata con lo stesso rigore di qualsiasi altro fenomeno, e costruì gli strumenti per farlo.">Diener</span> partì da un'idea semplice: il <span class="t" data-tip="Il modo in cui una persona valuta la propria vita, col pensiero e con le emozioni. Diener lo propose come alternativa misurabile alla parola felicità, troppo vaga per la ricerca.">benessere soggettivo</span> non è una cosa sola. Si scompone in una <span class="t" data-tip="Il giudizio ragionato e complessivo sulla propria vita: nel suo insieme, va come vorrei? Riflette i tuoi standard, non l'umore di oggi.">componente cognitiva</span> — il bilancio che fai della tua vita nel suo insieme — e una <span class="t" data-tip="Il flusso delle emozioni piacevoli e spiacevoli, giorno per giorno. Cambia in fretta e non coincide col giudizio: si può giudicare buona la propria vita e avere una giornata storta.">componente affettiva</span>, fatta di emozioni positive e negative. La SWLS misura solo la prima, di proposito: chiede un bilancio, non uno stato d'animo. Per questo cinque affermazioni generiche bastano.</p>`,
    blocks: [
      { h: "Due benessere in uno", html: `<p>Perché tenere separate le due parti? Perché divergono. Una persona può provare molte emozioni intense — alti e bassi frequenti — e comunque giudicare la propria vita eccellente; un'altra, più piatta emotivamente, può dirsi soddisfattissima. Il giudizio globale pesa il senso, la coerenza con i valori, il confronto con le aspettative; l'affetto pesa il momento. Contano anche cose diverse: il reddito, per esempio, sposta il giudizio cognitivo più di quanto sposti l'umore quotidiano. Chiedere «sei soddisfatto?» e «ti senti bene?» non è la stessa domanda.</p>` },
      { h: "Il set point e il tapis roulant edonico", html: `<p>La scoperta più spiazzante è che la soddisfazione tende a tornare a un livello di base. <span class="t" data-tip="Philip Brickman e colleghi, 1978: confrontarono vincitori di lotterie e persone rimaste paralizzate da un incidente. A distanza di tempo le differenze di felicità erano molto più piccole del previsto.">Brickman</span> confrontò vincitori di lotterie e persone diventate paraplegiche: dopo un po', i livelli di soddisfazione erano molto più vicini di quanto chiunque avrebbe scommesso. Lo chiamò <span class="t" data-tip="L'idea che ci si abitui in fretta sia alle cose belle sia a quelle brutte, tornando verso un livello personale di base, come camminare su un tapis roulant senza avanzare.">tapis roulant edonico</span>: ci si abitua, e il <span class="t" data-tip="Il livello di soddisfazione a cui una persona tende a tornare dopo gli eventi, in parte temperamentale ed ereditario. Non è una condanna, ma spiega perché i grandi colpi di fortuna sfiadano.">set point</span> ci riporta indietro. Una quota consistente delle differenze tra persone è temperamentale, e questo spiega perché inseguire il prossimo traguardo raramente sposta l'ago in modo stabile.</p>` },
      { h: "Ma non ci si adatta a tutto", html: `<p>Il tapis roulant è stato preso troppo alla lettera. <span class="t" data-tip="Richard Lucas: usando studi che seguono le stesse persone per molti anni, mostrò che ad alcuni eventi non ci si adatta del tutto.">Lucas</span>, seguendo le stesse persone per anni, ha mostrato che alcuni eventi spostano il set point in modo duraturo: la disoccupazione prolungata, la vedovanza, certe disabilità lasciano un livello medio più basso anche dopo molto tempo. L'adattamento è reale ma parziale, e varia da persona a persona. La lettura onesta non è «tanto torna tutto come prima», ma: a molte cose ci si abitua, ad alcune no.</p>` },
      { h: "Un giudizio, non una fotografia", html: `<p>Poiché è una valutazione globale, la SWLS è sensibile al <span class="t" data-tip="Il modo in cui una domanda è posta o incorniciata. Cambiare l'ordine delle domande o il contesto sposta le risposte, anche quando la vita della persona non è cambiata.">frame</span>. <span class="t" data-tip="Norbert Schwarz e Fritz Strack: chiesero prima quanti appuntamenti romantici la persona avesse avuto, poi quanto fosse soddisfatta della vita. Il primo dato colorava il secondo. Anche il bel tempo alza il punteggio, se non si nomina il tempo.">Schwarz e Strack</span> hanno mostrato che l'ordine delle domande, l'umore o persino il tempo che fa influenzano il punteggio. Si aggancia alla <span class="t" data-tip="Kahneman: niente nella vita è importante quanto sembra mentre ci stai pensando. Se ti fanno pensare al reddito o al clima, quel fattore gonfia il giudizio per il solo fatto di essere sotto i riflettori.">focusing illusion</span>: qualunque cosa metti a fuoco diventa temporaneamente più importante. Un solo punteggio è quindi indicativo, non una sentenza; ripeterlo in momenti diversi dice di più.</p>` }
    ],
    beyond: `<ul>
      <li><b>Soldi e soddisfazione.</b> Il reddito alza il giudizio sulla vita più dell'umore quotidiano, con rendimenti calanti: raddoppiare lo stipendio non raddoppia la soddisfazione, e sopra una certa soglia l'effetto si assottiglia.</li>
      <li><b>La curva a U dell'età.</b> In molti Paesi la soddisfazione cala verso la mezza età e risale dopo: gli anni più duri, in media, sono intorno ai 45-50, non la vecchiaia.</li>
      <li><b>Top-down e bottom-up.</b> Le persone soddisfatte tendono a giudicare bene anche i singoli ambiti (top-down: il temperamento colora tutto), non solo il contrario. Il tratto tira il giudizio, non solo i fatti.</li>
      <li><b>Cultura.</b> Chi cresce in culture individualiste giudica la vita sulle proprie emozioni; in culture più collettiviste pesano di più l'armonia sociale e le aspettative della famiglia. La stessa vita riceve punteggi diversi.</li>
    </ul>`,
    taratura: `<p>La SWLS è la misura di soddisfazione di vita più usata al mondo, breve e ben tarata (coerenza interna alta, intorno a .85; buona stabilità nel breve periodo). Il limite è nella natura stessa del costrutto: è un giudizio globale, e quindi si lascia spostare dall'umore, dall'ordine delle domande, dal contesto — un punteggio isolato va preso con cautela. Misura la parte cognitiva del benessere, non l'affetto né il senso della vita, che vanno indagati a parte. Le fasce dell'autore sono orientative, non soglie cliniche: la media occidentale è intorno a 23-25.</p>`,
    reading: [
      "Diener, E., Emmons, R. A., Larsen, R. J. & Griffin, S. (1985). The Satisfaction With Life Scale. <em>Journal of Personality Assessment</em>, 49, 71-75.",
      "Diener, E., Lucas, R. E. & Oishi, S. (2018). Advances and open questions in the science of subjective well-being. <em>Collabra: Psychology</em>, 4(1).",
      "Kahneman, D., <em>Pensieri lenti e veloci</em> (2011). Sull'adattamento e la focusing illusion."
    ]
  },
  en: {
    title: "Life satisfaction, in depth",
    intro: `<p><span class="t" data-tip="Ed Diener (1946-2021), American psychologist nicknamed Dr. Happiness. He argued happiness could be studied as rigorously as anything else, and built the tools to do it.">Diener</span> began with a simple idea: <span class="t" data-tip="How a person evaluates their own life, in thought and emotion. Diener offered it as a measurable alternative to the word happiness, too vague for research.">subjective well-being</span> is not one thing. It splits into a <span class="t" data-tip="The reasoned, overall judgement of one's life: taken as a whole, is it going as I want? It reflects your standards, not today's mood.">cognitive component</span> — the overall verdict you pass on your life — and an <span class="t" data-tip="The stream of pleasant and unpleasant emotions, day to day. It shifts quickly and doesn't track the judgement: you can rate your life good and have a rotten day.">affective component</span>, made of positive and negative emotions. The SWLS measures only the first, on purpose: it asks for a verdict, not a mood. That's why five broad statements are enough.</p>`,
    blocks: [
      { h: "Two kinds of well-being", html: `<p>Why keep the two apart? Because they diverge. One person can feel many intense emotions — frequent highs and lows — and still judge their life excellent; another, flatter emotionally, may report deep satisfaction. The global judgement weighs meaning, coherence with values, the gap against expectations; affect weighs the moment. Different things drive them: income, for instance, moves the cognitive judgement more than it moves daily mood. Asking «are you satisfied?» and «do you feel good?» is not the same question.</p>` },
      { h: "The set point and the hedonic treadmill", html: `<p>The most unsettling finding is that satisfaction tends to return to a baseline. <span class="t" data-tip="Philip Brickman and colleagues, 1978: they compared lottery winners with people paralysed by accidents. Over time the happiness gap was far smaller than anyone expected.">Brickman</span> compared lottery winners with people who became paraplegic: after a while, satisfaction levels were much closer than anyone would have bet. He called it the <span class="t" data-tip="The idea that we adapt quickly to good and bad alike, drifting back to a personal baseline, like walking on a treadmill without moving forward.">hedonic treadmill</span>: we adapt, and the <span class="t" data-tip="The satisfaction level a person tends to return to after events, partly temperamental and heritable. Not a sentence, but it explains why big windfalls fade.">set point</span> pulls us back. A sizeable share of the differences between people is temperamental, which is why chasing the next milestone rarely moves the needle for long.</p>` },
      { h: "But you don't adapt to everything", html: `<p>The treadmill was taken too literally. <span class="t" data-tip="Richard Lucas: using studies that follow the same people for many years, he showed that some events are never fully adapted to.">Lucas</span>, following the same people for years, showed that some events shift the set point durably: prolonged unemployment, widowhood, some disabilities leave a lower average even long after. Adaptation is real but partial, and varies from person to person. The honest reading is not «it all goes back to normal», but: to many things you adapt, to some you don't.</p>` },
      { h: "A judgement, not a snapshot", html: `<p>Because it is a global evaluation, the SWLS is sensitive to the <span class="t" data-tip="How a question is posed or framed. Changing the order of questions or the context shifts answers, even when the person's life hasn't changed.">frame</span>. <span class="t" data-tip="Norbert Schwarz and Fritz Strack: asking first how many romantic dates someone had, then how satisfied they were with life, let the first colour the second. Good weather also raises the score, unless the weather is mentioned.">Schwarz and Strack</span> showed that question order, mood, even the weather sway the score. It connects to the <span class="t" data-tip="Kahneman: nothing in life is as important as you think it is while you are thinking about it. Prompted to think about income or climate, that factor inflates the judgement just by being in the spotlight.">focusing illusion</span>: whatever you focus on becomes temporarily more important. A single score is therefore indicative, not a verdict; repeating it at different times says more.</p>` }
    ],
    beyond: `<ul>
      <li><b>Money and satisfaction.</b> Income lifts the life judgement more than daily mood, with diminishing returns: doubling your salary doesn't double satisfaction, and above a certain level the effect thins out.</li>
      <li><b>The U-shape of age.</b> In many countries satisfaction dips toward midlife and rises after: the hardest years, on average, are around 45-50, not old age.</li>
      <li><b>Top-down and bottom-up.</b> Satisfied people tend to rate individual domains well too (top-down: temperament colours everything), not just the reverse. The trait pulls the judgement, not only the facts.</li>
      <li><b>Culture.</b> People raised in individualist cultures judge life by their own emotions; in more collectivist ones, social harmony and family expectations weigh more. The same life gets different scores.</li>
    </ul>`,
    taratura: `<p>The SWLS is the most used life-satisfaction measure in the world, brief and well calibrated (high internal consistency, around .85; good short-term stability). Its limit is in the construct itself: it is a global judgement, so it lets itself be swayed by mood, question order, context — a single score should be read with care. It measures the cognitive side of well-being, not affect nor life's meaning, which must be probed separately. The author's bands are indicative, not clinical thresholds: the Western average is around 23-25.</p>`,
    reading: [
      "Diener, E., Emmons, R. A., Larsen, R. J. & Griffin, S. (1985). The Satisfaction With Life Scale. <em>Journal of Personality Assessment</em>, 49, 71-75.",
      "Diener, E., Lucas, R. E. & Oishi, S. (2018). Advances and open questions in the science of subjective well-being. <em>Collabra: Psychology</em>, 4(1).",
      "Kahneman, D., <em>Thinking, Fast and Slow</em> (2011). On adaptation and the focusing illusion."
    ]
  },
  pt: {
    title: "A satisfação com a vida, em profundidade",
    intro: `<p><span class="t" data-tip="Ed Diener (1946-2021), psicólogo americano apelidado de Dr. Happiness. Defendeu que a felicidade podia ser estudada com o mesmo rigor de qualquer outro fenômeno, e criou as ferramentas para isso.">Diener</span> partiu de uma ideia simples: o <span class="t" data-tip="O modo como uma pessoa avalia a própria vida, com o pensamento e com as emoções. Diener o propôs como alternativa mensurável à palavra felicidade, vaga demais para a pesquisa.">bem-estar subjetivo</span> não é uma coisa só. Divide-se numa <span class="t" data-tip="O julgamento ponderado e global da própria vida: no conjunto, está indo como eu gostaria? Reflete os seus padrões, não o humor de hoje.">componente cognitiva</span> — o balanço que você faz da sua vida como um todo — e numa <span class="t" data-tip="O fluxo das emoções agradáveis e desagradáveis, dia após dia. Muda depressa e não coincide com o julgamento: dá para julgar boa a própria vida e ter um dia ruim.">componente afetiva</span>, feita de emoções positivas e negativas. A SWLS mede só a primeira, de propósito: pede um balanço, não um estado de ânimo. Por isso cinco afirmações genéricas bastam.</p>`,
    blocks: [
      { h: "Dois bem-estares num só", html: `<p>Por que separar as duas partes? Porque divergem. Uma pessoa pode sentir muitas emoções intensas — altos e baixos frequentes — e ainda assim julgar a própria vida excelente; outra, mais plana emocionalmente, pode se dizer muito satisfeita. O julgamento global pesa o sentido, a coerência com os valores, a distância em relação às expectativas; o afeto pesa o momento. Coisas diferentes os movem: a renda, por exemplo, desloca o julgamento cognitivo mais do que o humor do dia a dia. Perguntar «você está satisfeito?» e «você se sente bem?» não é a mesma pergunta.</p>` },
      { h: "O set point e a esteira hedônica", html: `<p>A descoberta mais desconcertante é que a satisfação tende a voltar a um nível de base. <span class="t" data-tip="Philip Brickman e colegas, 1978: compararam ganhadores de loteria e pessoas paralisadas por acidentes. Com o tempo, a diferença de felicidade era muito menor do que se esperava.">Brickman</span> comparou ganhadores de loteria com pessoas que ficaram paraplégicas: depois de um tempo, os níveis de satisfação estavam muito mais próximos do que qualquer um apostaria. Ele chamou isso de <span class="t" data-tip="A ideia de que nos acostumamos depressa tanto ao bom quanto ao ruim, voltando a um nível pessoal de base, como andar numa esteira sem avançar.">esteira hedônica</span>: a gente se acostuma, e o <span class="t" data-tip="O nível de satisfação ao qual a pessoa tende a voltar depois dos eventos, em parte temperamental e hereditário. Não é uma condenação, mas explica por que grandes golpes de sorte desbotam.">set point</span> nos puxa de volta. Uma parte considerável das diferenças entre pessoas é temperamental, o que explica por que perseguir a próxima meta raramente move o ponteiro de forma estável.</p>` },
      { h: "Mas não nos adaptamos a tudo", html: `<p>A esteira foi levada ao pé da letra demais. <span class="t" data-tip="Richard Lucas: usando estudos que acompanham as mesmas pessoas por muitos anos, mostrou que a alguns eventos não nos adaptamos por completo.">Lucas</span>, acompanhando as mesmas pessoas por anos, mostrou que alguns eventos deslocam o set point de forma duradoura: o desemprego prolongado, a viuvez, certas deficiências deixam uma média mais baixa mesmo muito tempo depois. A adaptação é real, mas parcial, e varia de pessoa para pessoa. A leitura honesta não é «no fim tudo volta ao normal», mas: a muitas coisas a gente se acostuma, a algumas não.</p>` },
      { h: "Um julgamento, não uma fotografia", html: `<p>Por ser uma avaliação global, a SWLS é sensível ao <span class="t" data-tip="O modo como uma pergunta é feita ou enquadrada. Mudar a ordem das perguntas ou o contexto desloca as respostas, mesmo quando a vida da pessoa não mudou.">enquadramento</span>. <span class="t" data-tip="Norbert Schwarz e Fritz Strack: perguntar primeiro quantos encontros românticos a pessoa teve e depois o quanto estava satisfeita com a vida fazia o primeiro dado colorir o segundo. O bom tempo também eleva a pontuação, se o tempo não for mencionado.">Schwarz e Strack</span> mostraram que a ordem das perguntas, o humor ou até o tempo influenciam a pontuação. Liga-se à <span class="t" data-tip="Kahneman: nada na vida é tão importante quanto parece enquanto você está pensando nisso. Se te fazem pensar na renda ou no clima, aquele fator infla o julgamento só por estar sob os holofotes.">ilusão de foco</span>: aquilo em que você foca fica temporariamente mais importante. Uma única pontuação é, portanto, indicativa, não uma sentença; repeti-la em momentos diferentes diz mais.</p>` }
    ],
    beyond: `<ul>
      <li><b>Dinheiro e satisfação.</b> A renda eleva o julgamento sobre a vida mais do que o humor do dia a dia, com retornos decrescentes: dobrar o salário não dobra a satisfação, e acima de certo nível o efeito afina.</li>
      <li><b>A curva em U da idade.</b> Em muitos países a satisfação cai rumo à meia-idade e sobe depois: os anos mais duros, em média, são por volta dos 45-50, não a velhice.</li>
      <li><b>Top-down e bottom-up.</b> Pessoas satisfeitas tendem a avaliar bem também os domínios isolados (top-down: o temperamento colore tudo), não só o contrário. O traço puxa o julgamento, não apenas os fatos.</li>
      <li><b>Cultura.</b> Quem cresce em culturas individualistas julga a vida pelas próprias emoções; em culturas mais coletivistas pesam mais a harmonia social e as expectativas da família. A mesma vida recebe notas diferentes.</li>
    </ul>`,
    taratura: `<p>A SWLS é a medida de satisfação com a vida mais usada no mundo, breve e bem calibrada (consistência interna alta, em torno de .85; boa estabilidade no curto prazo). O limite está na natureza do próprio construto: é um julgamento global e, por isso, se deixa deslocar pelo humor, pela ordem das perguntas, pelo contexto — uma pontuação isolada deve ser lida com cautela. Mede a parte cognitiva do bem-estar, não o afeto nem o sentido da vida, que precisam ser investigados à parte. As faixas do autor são orientativas, não limiares clínicos: a média ocidental fica em torno de 23-25.</p>`,
    reading: [
      "Diener, E., Emmons, R. A., Larsen, R. J. & Griffin, S. (1985). The Satisfaction With Life Scale. <em>Journal of Personality Assessment</em>, 49, 71-75.",
      "Diener, E., Lucas, R. E. & Oishi, S. (2018). Advances and open questions in the science of subjective well-being. <em>Collabra: Psychology</em>, 4(1).",
      "Kahneman, D., <em>Rápido e devagar</em> (2011). Sobre a adaptação e a ilusão de foco."
    ]
  }
};
