/* UCLA Loneliness Scale, versione a 3 item (Hughes, Waite, Hawkley & Cacioppo 2004) — libero. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.ucla3 = {
  code: "UCLA-3", theme: "ocean", n: 3,
  labels: { en: ["Hardly ever", "Some of the time", "Often"], it: ["Quasi mai", "Qualche volta", "Spesso"] },
  items: {
    en: ["How often do you feel that you lack companionship?", "How often do you feel left out?", "How often do you feel isolated from others?"],
    it: ["Quanto spesso senti che ti manca compagnia?", "Quanto spesso ti senti escluso?", "Quanto spesso ti senti isolato dagli altri?"]
  },
  text: {
    it: { kicker: "Solitudine", title: "Quanto ti senti solo?", lede: "3 domande, 30 secondi. La versione breve della scala UCLA, usata nei grandi studi sull'invecchiamento e sulla salute.", meta: ["3 domande", "~30 secondi"], instr: "Per ogni domanda indica quanto spesso ti senti così, pensando all'<b>ultimo periodo</b>.", how: "Il punteggio va da 3 a 9. Negli studi di popolazione 6 o più viene considerato «solitudine»; la media è intorno a 4. La solitudine percepita è diversa dall'essere soli: si può stare bene da soli e sentirsi soli in mezzo agli altri.", cite: "Hughes, M. E., Waite, L. J., Hawkley, L. C., & Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys. Research on Aging, 26, 655-672. Uso libero." },
    en: { kicker: "Loneliness", title: "How lonely do you feel?", lede: "3 questions, 30 seconds. The short version of the UCLA scale, used in large studies on ageing and health.", meta: ["3 questions", "~30 seconds"], instr: "For each question, indicate how often you feel that way, thinking about the <b>recent period</b>.", how: "The score runs from 3 to 9. In population studies 6 or more is considered “lonely”; the mean is around 4. Perceived loneliness is different from being alone: one can be fine alone and feel lonely among others.", cite: "Hughes, M. E., Waite, L. J., Hawkley, L. C., & Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys. Research on Aging, 26, 655-672. Free to use." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Solitudine", en: "Loneliness" }, items: [1,2,3], mode: "sum", range: [3, 9],
    bands: [
      { max: 3, name: { it: "Nessuna", en: "None" }, text: { it: "Non ti senti solo: compagnia e appartenenza ci sono.", en: "You don't feel lonely: companionship and belonging are there." } },
      { max: 5, name: { it: "Bassa", en: "Low" }, text: { it: "Qualche momento di solitudine, come capita a quasi tutti.", en: "Some moments of loneliness, as happens to almost everyone." } },
      { max: 9, name: { it: "Solitudine", en: "Lonely" }, text: { it: "Sopra la soglia usata negli studi: la mancanza di legami pesa. La solitudine cronica incide sulla salute quanto altri fattori di rischio noti; investire in un legame, anche piccolo, è la cosa più efficace.", en: "Above the threshold used in studies: the lack of ties weighs on you. Chronic loneliness affects health as much as other known risk factors; investing in one tie, even a small one, is the most effective thing." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.ucla3.approf = {
  it: {
    title: "La solitudine, in profondità",
    intro: `<p><span class="t" data-tip="John Cacioppo (1951-2018), fondatore della neuroscienza sociale. Il suo libro Loneliness (2008) ha cambiato il modo di guardare la solitudine, spostandola dal registro morale a quello biologico.">Cacioppo</span> ha ribaltato il senso comune: la solitudine non è un difetto di carattere né una colpa, è un <span class="t" data-tip="Un segnale evoluto come la fame o la sete: dice che manca qualcosa di necessario. Per un primate, restare fuori dal gruppo significava pericolo, quindi il corpo impara a segnalarlo.">segnale biologico</span>, come la fame o la sete. La fame dice «mangia»; la solitudine dice «ricuci un legame». Il punto decisivo è che questo segnale non dipende da quante persone hai intorno, ma dallo <span class="t" data-tip="La differenza tra i legami che hai e quelli che vorresti. Se il divario è ampio scatta la solitudine, anche in mezzo alla gente; se è nullo, si sta bene anche da soli.">scarto</span> tra i legami che hai e quelli che desideri. Ecco perché si può essere soli a una festa e non soli in una casa vuota.</p>`,
    blocks: [
      { h: "Percepita, non contata", html: `<p>La distinzione che sfugge sempre: la solitudine è <span class="t" data-tip="La solitudine percepita è un vissuto soggettivo: come mi sento rispetto ai legami che vorrei. Due persone con la stessa rete sociale possono sentirsi molto diverse.">percepita</span>, l'<span class="t" data-tip="L'isolamento oggettivo è un dato di fatto: quante persone vedi, con che frequenza. Si misura contando; la solitudine no.">isolamento</span> è oggettivo. Uno si misura chiedendo come ti senti, l'altro contando i contatti — e i due non coincidono. Ci sono persone molto sole in reti affollate e persone appagate con pochissimi legami. Questo test misura il primo, non il secondo: non quanti amici hai, ma quanto ti manca compagnia. È una scelta precisa, perché è il vissuto, non il numero, a pesare sulla salute.</p>` },
      { h: "Distorce il radar", html: `<p>Il secondo effetto è più subdolo. Chi è solo a lungo diventa <span class="t" data-tip="Ipervigilanza sociale: il cervello, in stato di allerta, dà più peso ai segnali di minaccia. Un volto neutro sembra ostile, un silenzio sembra rifiuto.">ipervigile</span> verso la minaccia sociale: legge la neutralità come rifiuto, si aspetta il peggio dagli altri, e per proteggersi si ritira. Ma il ritiro conferma la solitudine, che aumenta la vigilanza — ed è un anello che si stringe da solo. È lo stesso circolo vizioso della coppia ansioso-evitante, ma tutto dentro una persona sola. Capire che è il radar a essersi tarato sulla minaccia, e non il mondo a essere diventato ostile, è il primo passo per uscirne.</p>` },
      { h: "Il costo sul corpo", html: `<p>Il segnale, se resta acceso a lungo, logora. <span class="t" data-tip="Julianne Holt-Lunstad: le sue meta-analisi, che mettono insieme centinaia di studi su milioni di persone, sono tra le più citate della psicologia della salute.">Holt-Lunstad</span> ha raccolto centinaia di studi e trovato che l'isolamento e la solitudine pesano sulla <span class="t" data-tip="La mortalità è il rischio di morire in un dato periodo. Nelle meta-analisi l'effetto della solitudine cronica è paragonabile a quello di fattori di rischio noti e presi sul serio dalla medicina.">mortalità</span> quanto altri fattori di rischio che prendiamo molto sul serio. La solitudine cronica alza gli ormoni dello stress, frammenta il sonno, alimenta l'infiammazione. Non è un lusso emotivo: è un tema di salute pubblica, e per questo entra oggi nei grandi studi su invecchiamento e benessere.</p>` },
      { h: "Perché solo tre domande", html: `<p>La versione breve nasce per i <span class="t" data-tip="Grandi indagini su migliaia o milioni di persone, dove ogni domanda in più costa tempo e denaro. Servono strumenti cortissimi ma affidabili.">grandi sondaggi</span>, dove non c'è spazio per venti item. E c'è un'astuzia: le tre domande non contengono mai la parola «solo». Chiedono se ti manca compagnia, se ti senti escluso, se ti senti isolato — perché ammettere di sentirsi soli porta con sé uno stigma che falserebbe le risposte. Aggirare la parola misura meglio la cosa.</p>` }
    ],
    beyond: `<ul>
      <li><b>Due solitudini diverse</b> (Weiss): quella <em>emotiva</em>, la mancanza di un legame intimo, non si cura con più gente intorno; quella <em>sociale</em>, la mancanza di una rete o di un gruppo, sì. Sono bisogni distinti, e confonderli è il motivo per cui «esci di più» spesso non funziona.</li>
      <li><b>È contagiosa</b> (Cacioppo, Fowler & Christakis): nelle reti sociali la solitudine si propaga di persona in persona, perché chi è solo tende a spingere via anche chi gli sta vicino.</li>
      <li><b>Sola non vuol dire triste.</b> Stare bene da soli è una capacità, non un problema. Il test non misura quanto tempo passi solo, ma quanto quello che hai si discosta da quello che vorresti.</li>
      <li><b>I legami si recuperano.</b> Le persone sopravvalutano quanto un messaggio a un vecchio amico sarà sgradito e sottovalutano quanto sarà gradito: riallacciare un legame decaduto è più facile di quanto sembri.</li>
    </ul>`,
    taratura: `<p>La versione a 3 item riproduce bene la scala completa a 20 item (le due correlano molto strettamente) ed è ottima per gli scopi per cui è nata: grandi survey e confronti tra gruppi. È però uno strumento grezzo — tre domande, nessuna parola «solo» — pensato per la popolazione, non per la valutazione del singolo. La soglia di 6 usata negli studi è una convenzione statistica, non una diagnosi: non esiste una «diagnosi di solitudine». Il punteggio inoltre oscilla nel tempo, perché la solitudine è uno stato, non un tratto fisso. E misura la percezione, non la rete reale: dice come ti senti, non chi hai.</p>`,
    reading: [
      "Hughes, M. E., Waite, L. J., Hawkley, L. C. & Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys. <em>Research on Aging</em>, 26, 655-672.",
      "Cacioppo, J. T. & Patrick, W., <em>Loneliness: Human Nature and the Need for Social Connection</em> (2008).",
      "Holt-Lunstad, J. et al. (2015). Loneliness and social isolation as risk factors for mortality. <em>Perspectives on Psychological Science</em>, 10, 227-237."
    ]
  },
  en: {
    title: "Loneliness, in depth",
    intro: `<p><span class="t" data-tip="John Cacioppo (1951-2018), founder of social neuroscience. His book Loneliness (2008) changed how we see the state, moving it from a moral register to a biological one.">Cacioppo</span> turned common sense on its head: loneliness is not a character flaw or a fault, it is a <span class="t" data-tip="A signal evolved like hunger or thirst: it says something necessary is missing. For a primate, being outside the group meant danger, so the body learns to flag it.">biological signal</span>, like hunger or thirst. Hunger says «eat»; loneliness says «mend a bond». The decisive point is that this signal does not depend on how many people are around you, but on the <span class="t" data-tip="The gap between the bonds you have and the ones you want. A wide gap triggers loneliness, even in a crowd; no gap, and you are fine alone.">gap</span> between the ties you have and the ties you want. That is why you can be lonely at a party and not lonely in an empty house.</p>`,
    blocks: [
      { h: "Perceived, not counted", html: `<p>The distinction people always miss: loneliness is <span class="t" data-tip="Perceived loneliness is a subjective experience: how I feel about the bonds I want. Two people with the same social network can feel very differently.">perceived</span>, <span class="t" data-tip="Objective isolation is a fact: how many people you see, how often. It is measured by counting; loneliness is not.">isolation</span> is objective. One is measured by asking how you feel, the other by counting your contacts — and the two do not coincide. There are deeply lonely people in crowded networks and contented people with very few ties. This test measures the first, not the second: not how many friends you have, but how much you miss companionship. That is a deliberate choice, because it is the experience, not the number, that weighs on health.</p>` },
      { h: "It distorts the radar", html: `<p>The second effect is subtler. Someone lonely for a long time becomes <span class="t" data-tip="Social hypervigilance: the brain, on alert, gives more weight to threat cues. A neutral face looks hostile, a silence looks like rejection.">hypervigilant</span> to social threat: they read neutrality as rejection, expect the worst of others, and withdraw to protect themselves. But withdrawal confirms the loneliness, which raises the vigilance — a loop that tightens on its own. It is the same vicious circle as the anxious-avoidant couple, but all inside one lonely person. Grasping that it is the radar that has tuned itself to threat, not the world that has turned hostile, is the first step out.</p>` },
      { h: "The cost on the body", html: `<p>The signal, left on too long, wears you down. <span class="t" data-tip="Julianne Holt-Lunstad: her meta-analyses, pooling hundreds of studies over millions of people, are among the most cited in health psychology.">Holt-Lunstad</span> gathered hundreds of studies and found that isolation and loneliness weigh on <span class="t" data-tip="Mortality is the risk of dying in a given period. In the meta-analyses, the effect of chronic loneliness is comparable to well-known risk factors that medicine takes seriously.">mortality</span> as much as other risk factors we take very seriously. Chronic loneliness raises stress hormones, fragments sleep, feeds inflammation. It is not an emotional luxury: it is a public-health matter, which is why it now enters the big studies on ageing and well-being.</p>` },
      { h: "Why only three questions", html: `<p>The short version was made for <span class="t" data-tip="Large surveys of thousands or millions of people, where every extra question costs time and money. They need very short but reliable instruments.">large surveys</span>, where there is no room for twenty items. And there is a trick: the three questions never contain the word «lonely». They ask whether you lack companionship, feel left out, feel isolated — because admitting you feel lonely carries a stigma that would skew the answers. Going around the word measures the thing better.</p>` }
    ],
    beyond: `<ul>
      <li><b>Two different lonelinesses</b> (Weiss): <em>emotional</em> loneliness, the lack of one intimate bond, is not cured by more people around; <em>social</em> loneliness, the lack of a network or group, is. They are distinct needs, and confusing them is why «get out more» often fails.</li>
      <li><b>It's contagious</b> (Cacioppo, Fowler & Christakis): in social networks loneliness spreads from person to person, because the lonely tend to push away even those close to them.</li>
      <li><b>Alone doesn't mean sad.</b> Being fine on your own is a skill, not a problem. The test measures not how much time you spend alone, but how far what you have departs from what you want.</li>
      <li><b>Bonds can be recovered.</b> People overestimate how unwelcome a message to an old friend will be and underestimate how welcome: rekindling a faded tie is easier than it seems.</li>
    </ul>`,
    taratura: `<p>The 3-item version reproduces the full 20-item scale well (the two correlate very closely) and is excellent for what it was made for: large surveys and group comparisons. But it is a blunt tool — three questions, no word «lonely» — designed for populations, not individual assessment. The threshold of 6 used in studies is a statistical convention, not a diagnosis: there is no «diagnosis of loneliness». The score also swings over time, because loneliness is a state, not a fixed trait. And it measures perception, not the real network: it tells you how you feel, not who you have.</p>`,
    reading: [
      "Hughes, M. E., Waite, L. J., Hawkley, L. C. & Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys. <em>Research on Aging</em>, 26, 655-672.",
      "Cacioppo, J. T. & Patrick, W., <em>Loneliness: Human Nature and the Need for Social Connection</em> (2008).",
      "Holt-Lunstad, J. et al. (2015). Loneliness and social isolation as risk factors for mortality. <em>Perspectives on Psychological Science</em>, 10, 227-237."
    ]
  },
  pt: {
    title: "A solidão, em profundidade",
    intro: `<p><span class="t" data-tip="John Cacioppo (1951-2018), fundador da neurociência social. Seu livro Loneliness (2008) mudou o modo de ver a solidão, deslocando-a do registro moral para o biológico.">Cacioppo</span> virou o senso comum do avesso: a solidão não é um defeito de caráter nem uma culpa, é um <span class="t" data-tip="Um sinal evoluído como a fome ou a sede: diz que falta algo necessário. Para um primata, ficar fora do grupo significava perigo, então o corpo aprende a sinalizar isso.">sinal biológico</span>, como a fome ou a sede. A fome diz «coma»; a solidão diz «reate um vínculo». O ponto decisivo é que esse sinal não depende de quantas pessoas há ao seu redor, mas da <span class="t" data-tip="A diferença entre os vínculos que você tem e os que gostaria de ter. Se a distância é grande, dispara a solidão, mesmo no meio das pessoas; se é nula, dá para estar bem sozinho.">distância</span> entre os vínculos que você tem e os que deseja. É por isso que se pode estar só numa festa e não estar só numa casa vazia.</p>`,
    blocks: [
      { h: "Percebida, não contada", html: `<p>A distinção que sempre escapa: a solidão é <span class="t" data-tip="A solidão percebida é uma vivência subjetiva: como me sinto em relação aos vínculos que gostaria. Duas pessoas com a mesma rede social podem se sentir muito diferentes.">percebida</span>, o <span class="t" data-tip="O isolamento objetivo é um dado de fato: quantas pessoas você vê, com que frequência. Mede-se contando; a solidão não.">isolamento</span> é objetivo. Um se mede perguntando como você se sente, o outro contando os contatos — e os dois não coincidem. Há pessoas muito sós em redes cheias e pessoas satisfeitas com pouquíssimos vínculos. Este teste mede o primeiro, não o segundo: não quantos amigos você tem, mas o quanto lhe falta companhia. É uma escolha precisa, porque é a vivência, não o número, que pesa sobre a saúde.</p>` },
      { h: "Distorce o radar", html: `<p>O segundo efeito é mais sorrateiro. Quem está só por muito tempo fica <span class="t" data-tip="Hipervigilância social: o cérebro, em alerta, dá mais peso aos sinais de ameaça. Um rosto neutro parece hostil, um silêncio parece rejeição.">hipervigilante</span> à ameaça social: lê a neutralidade como rejeição, espera o pior dos outros e, para se proteger, se retrai. Mas a retração confirma a solidão, que aumenta a vigilância — um ciclo que se aperta sozinho. É o mesmo círculo vicioso do casal ansioso-evitativo, mas todo dentro de uma pessoa só. Entender que foi o radar que se calibrou na ameaça, e não o mundo que ficou hostil, é o primeiro passo para sair.</p>` },
      { h: "O custo no corpo", html: `<p>O sinal, se fica ligado por muito tempo, desgasta. <span class="t" data-tip="Julianne Holt-Lunstad: suas meta-análises, que reúnem centenas de estudos sobre milhões de pessoas, estão entre as mais citadas da psicologia da saúde.">Holt-Lunstad</span> reuniu centenas de estudos e descobriu que o isolamento e a solidão pesam sobre a <span class="t" data-tip="A mortalidade é o risco de morrer num dado período. Nas meta-análises, o efeito da solidão crônica é comparável ao de fatores de risco conhecidos e levados a sério pela medicina.">mortalidade</span> tanto quanto outros fatores de risco que levamos muito a sério. A solidão crônica eleva os hormônios do estresse, fragmenta o sono, alimenta a inflamação. Não é um luxo emocional: é uma questão de saúde pública, e por isso entra hoje nos grandes estudos sobre envelhecimento e bem-estar.</p>` },
      { h: "Por que só três perguntas", html: `<p>A versão breve nasceu para os <span class="t" data-tip="Grandes pesquisas com milhares ou milhões de pessoas, em que cada pergunta a mais custa tempo e dinheiro. São necessários instrumentos curtíssimos, mas confiáveis.">grandes levantamentos</span>, onde não há espaço para vinte itens. E há uma astúcia: as três perguntas nunca contêm a palavra «só». Perguntam se lhe falta companhia, se você se sente excluído, se você se sente isolado — porque admitir que se sente só carrega um estigma que distorceria as respostas. Contornar a palavra mede melhor a coisa.</p>` }
    ],
    beyond: `<ul>
      <li><b>Duas solidões diferentes</b> (Weiss): a <em>emocional</em>, a falta de um vínculo íntimo, não se cura com mais gente ao redor; a <em>social</em>, a falta de uma rede ou de um grupo, sim. São necessidades distintas, e confundi-las é o motivo de «saia mais» muitas vezes não funcionar.</li>
      <li><b>É contagiosa</b> (Cacioppo, Fowler & Christakis): nas redes sociais a solidão se propaga de pessoa em pessoa, porque quem está só tende a afastar até quem lhe está próximo.</li>
      <li><b>Só não quer dizer triste.</b> Estar bem sozinho é uma capacidade, não um problema. O teste não mede quanto tempo você passa só, mas o quanto o que você tem se afasta do que gostaria.</li>
      <li><b>Os vínculos se recuperam.</b> As pessoas superestimam o quanto uma mensagem a um velho amigo será indesejada e subestimam o quanto será bem-vinda: reatar um laço enfraquecido é mais fácil do que parece.</li>
    </ul>`,
    taratura: `<p>A versão de 3 itens reproduz bem a escala completa de 20 itens (as duas se correlacionam muito estreitamente) e é ótima para o que foi criada: grandes surveys e comparações entre grupos. Mas é um instrumento grosseiro — três perguntas, nenhuma palavra «só» — pensado para a população, não para a avaliação do indivíduo. O limiar de 6 usado nos estudos é uma convenção estatística, não um diagnóstico: não existe um «diagnóstico de solidão». A pontuação também oscila no tempo, porque a solidão é um estado, não um traço fixo. E mede a percepção, não a rede real: diz como você se sente, não quem você tem.</p>`,
    reading: [
      "Hughes, M. E., Waite, L. J., Hawkley, L. C. & Cacioppo, J. T. (2004). A short scale for measuring loneliness in large surveys. <em>Research on Aging</em>, 26, 655-672.",
      "Cacioppo, J. T. & Patrick, W., <em>Loneliness: Human Nature and the Need for Social Connection</em> (2008).",
      "Holt-Lunstad, J. et al. (2015). Loneliness and social isolation as risk factors for mortality. <em>Perspectives on Psychological Science</em>, 10, 227-237."
    ]
  }
};
