/* WHO-5 Well-Being Index (WHO / Psychiatric Research Unit, Hillerød 1998) — pubblico dominio, versione italiana ufficiale. */
window.PSY_TESTS = window.PSY_TESTS || {};
PSY_TESTS.who5 = {
  code: "WHO-5", theme: "sun", n: 5, values: [0, 1, 2, 3, 4, 5],
  labels: {
    en: ["At no time", "Some of the time", "Less than half of the time", "More than half of the time", "Most of the time", "All of the time"],
    it: ["Mai", "Ogni tanto", "Meno della metà del tempo", "Più della metà del tempo", "La maggior parte del tempo", "Sempre"]
  },
  items: {
    en: ["I have felt cheerful and in good spirits.", "I have felt calm and relaxed.", "I have felt active and vigorous.", "I woke up feeling fresh and rested.", "My daily life has been filled with things that interest me."],
    it: ["Mi sono sentito allegro e di buon umore.", "Mi sono sentito calmo e rilassato.", "Mi sono sentito attivo ed energico.", "Mi sono svegliato sentendomi fresco e riposato.", "La mia vita quotidiana è stata piena di cose che mi interessano."]
  },
  text: {
    it: { kicker: "Benessere", title: "Come sono andate le ultime due settimane?", lede: "5 domande, 1 minuto. Il WHO-5 dell'Organizzazione Mondiale della Sanità è la misura di benessere più breve e diffusa.", meta: ["5 domande", "~1 minuto"], instr: "Per ogni frase indica con quale frequenza ti sei sentito così <b>nelle ultime due settimane</b>.", how: "Il punteggio grezzo (0–25) viene moltiplicato per 4: 0 è il peggior benessere immaginabile, 100 il migliore. Sotto 50 il benessere è ridotto e vale la pena approfondire; 28 o meno è la soglia usata per lo screening della depressione. Nella popolazione generale la media è intorno a 60–70.", cite: "WHO (1998). Wellbeing measures in primary health care / The DepCare Project. Psychiatric Research Unit, WHO Collaborating Centre, Hillerød. Pubblico dominio." },
    en: { kicker: "Well-being", title: "How have the last two weeks been?", lede: "5 questions, 1 minute. The World Health Organization's WHO-5 is the shortest and most widely used well-being measure.", meta: ["5 questions", "~1 minute"], instr: "For each statement, indicate how often you have felt that way <b>over the last two weeks</b>.", how: "The raw score (0–25) is multiplied by 4: 0 is the worst imaginable well-being, 100 the best. Below 50 well-being is reduced and worth looking into; 28 or less is the threshold used to screen for depression. The general-population mean is around 60–70.", cite: "WHO (1998). Wellbeing measures in primary health care / The DepCare Project. Psychiatric Research Unit, WHO Collaborating Centre, Hillerød. Public domain." }
  },
  main: "tot",
  scales: [{ key: "tot", name: { it: "Benessere", en: "Well-being" }, items: [1,2,3,4,5], mode: "sum", multiply: 4, range: [0, 100],
    bands: [
      { max: 28, name: { it: "Molto basso", en: "Very low" }, text: { it: "Sotto la soglia di screening: nelle ultime due settimane il benessere è stato molto scarso. Non è una diagnosi, ma è il punto in cui i medici consigliano di parlarne con qualcuno.", en: "Below the screening threshold: well-being over the last two weeks has been very poor. Not a diagnosis, but the point at which clinicians advise talking to someone." } },
      { max: 50, name: { it: "Ridotto", en: "Reduced" }, text: { it: "Benessere ridotto: qualcosa ha pesato in queste due settimane. Vale la pena capire cosa e, se dura, chiedere aiuto.", en: "Reduced well-being: something has weighed on you these two weeks. Worth understanding what, and asking for help if it lasts." } },
      { max: 72, name: { it: "Nella media", en: "Average" }, text: { it: "Nella fascia della popolazione generale: giornate con alti e bassi, complessivamente in equilibrio.", en: "In the general-population range: days with ups and downs, overall balanced." } },
      { max: 100, name: { it: "Alto", en: "High" }, text: { it: "Due settimane buone: energia, calma e interesse per le cose. Tienitelo stretto.", en: "Two good weeks: energy, calm and interest in things. Hold on to it." } }
    ] }]
};

/* ---- Approfondimento (IT/EN/PT; le altre lingue ricadono su IT) ---- */
PSY_TESTS.who5.approf = {
  it: {
    title: "Il benessere, in profondità",
    intro: `<p>Il WHO-5 nasce nel 1998 dentro un progetto dell'<span class="t" data-tip="Organizzazione Mondiale della Sanità. Il questionario nacque dal progetto DepCare, pensato per lo screening del benessere e della depressione nelle cure di base.">OMS</span> ed è quasi controcorrente: mentre la maggior parte dei questionari conta i sintomi — quanto stai male — questo conta il <span class="t" data-tip="Il benessere edonico: la presenza di stati positivi come buon umore, calma, energia e interesse. È l'opposto di misurare l'assenza di problemi.">benessere positivo</span>. Le cinque frasi sono tutte formulate al positivo (allegro, calmo, energico, riposato, interessato) e chiedono con quale frequenza le hai provate nelle <span class="t" data-tip="La finestra fissa delle ultime due settimane serve a catturare uno stato recente e stabile, non l'umore di un singolo giorno né un ricordo lontano e sfocato.">ultime due settimane</span>. È tra le misure di benessere più usate e tradotte al mondo, proprio perché è breve e chiara.</p>`,
    blocks: [
      { h: "Misurare ciò che c'è, non ciò che manca", html: `<p>La differenza chiave: stare bene non è semplicemente non stare male. <span class="t" data-tip="Corey Keyes: propose che salute mentale e disturbo mentale non siano gli estremi di una stessa linea, ma due dimensioni distinte. Si può avere pochi sintomi e comunque languire, o convivere con un disturbo e avere buoni livelli di benessere.">Keyes</span> ha mostrato che salute mentale e disturbo mentale non sono i due poli di un'unica linea, ma due assi separati: si può avere pochi sintomi e comunque <span class="t" data-tip="Languishing: uno stato di stagnazione e vuoto, senza malattia conclamata. Non è depressione, ma non è nemmeno pieno benessere; Keyes lo contrappone al flourishing, il fiorire.">languire</span>, ed è possibile convivere con un disturbo mantenendo un discreto benessere. Il WHO-5 misura questo secondo asse, quello positivo, che i questionari sui sintomi lasciano fuori.</p>` },
      { h: "Uno strumento a doppio uso", html: `<p>Curiosamente, misurare il benessere funziona anche come <span class="t" data-tip="Screening: un test rapido che segnala chi è opportuno valutare meglio. Non pone diagnosi: separa chi probabilmente sta bene da chi conviene approfondire.">screening</span> per la depressione. Punteggi bassi (indicativamente sotto 50 su 100, con la soglia più severa a 28) sono un segnale che vale la pena approfondire. Questo è possibile perché la perdita di benessere positivo — niente più piacere, energia, interesse — è uno dei primi segni depressivi. Attenzione però: un punteggio basso <b>non è una diagnosi</b>. È un semaforo che dice «guarda meglio», non un verdetto.</p>` },
      { h: "Edonico ed eudaimonico", html: `<p>Il WHO-5 cattura il benessere <span class="t" data-tip="Benessere edonico: sentirsi bene, provare piacere e calma, stare di buon umore. È l'antica idea di felicità come esperienza piacevole.">edonico</span> — sentirsi bene qui e ora. È solo metà della storia. L'altra metà è il benessere <span class="t" data-tip="Benessere eudaimonico: il senso di significato, crescita, autonomia e scopo. Deriva da Aristotele; Carol Ryff ne ha proposto una misura moderna. Una vita può essere significativa senza essere sempre piacevole.">eudaimonico</span>: senso, scopo, crescita, cose che possono esserci anche in periodi non piacevoli. Una persona impegnata in un compito difficile e importante può avere un WHO-5 modesto e una vita piena di significato. Il test misura come ti senti, non quanto conta ciò che fai.</p>` },
      { h: "Perché due settimane e cinque frasi", html: `<p>La finestra delle due settimane è la stessa usata dai criteri diagnostici per la depressione: abbastanza lunga da superare la giornata storta, abbastanza corta da restare un ricordo affidabile. E cinque frasi bastano perché il benessere edonico, misurato così, si comporta come una singola dimensione coerente: le cinque domande tirano tutte nella stessa direzione. È la ragione per cui uno strumento tanto breve regge il confronto con questionari molto più lunghi.</p>` }
    ],
    beyond: `<ul>
      <li><b>Non è una diagnosi.</b> Il WHO-5 dice quanto benessere hai provato, non perché. Un punteggio basso può nascere da depressione, ma anche da stress, lutto, malattia fisica o una settimana semplicemente pesante.</li>
      <li><b>Sensibile al cambiamento.</b> È molto usato per seguire nel tempo l'effetto di terapie e trattamenti, perché coglie i miglioramenti anche quando i sintomi non sono ancora spariti.</li>
      <li><b>Oltre la psichiatria.</b> Viene impiegato nel diabete e in altre malattie croniche, dove il benessere basso predice esiti peggiori: il corpo e l'umore non sono compartimenti separati.</li>
      <li><b>Languire non è deprimersi.</b> La stagnazione senza malattia — sentirsi vuoti, «né bene né male» — è uno stato a sé, e Keyes lo considera un fattore di rischio per problemi futuri.</li>
    </ul>`,
    taratura: `<p>Il WHO-5 è ben validato: una vasta rassegna ha raccolto centinaia di studi e lo giudica un buon indicatore di benessere e un discreto strumento di screening per la depressione, in molte lingue e contesti. I limiti sono quelli della brevità e del formato: cinque frasi al positivo colgono l'edonico ma non il senso della vita, e la formulazione tutta positiva può favorire risposte «di comodo» in chi tende ad assecondare. Le soglie (50 e 28) sono convenzioni utili, non confini netti, e lo screening va sempre confermato da una valutazione. Nella popolazione generale la media è intorno a 60-70.</p>`,
    reading: [
      "WHO (1998). <em>Wellbeing measures in primary health care / The DepCare Project</em>. Psychiatric Research Unit, Hillerød.",
      "Topp, C. W., Østergaard, S. D., Søndergaard, S. & Bech, P. (2015). The WHO-5 Well-Being Index: a systematic review. <em>Psychotherapy and Psychosomatics</em>, 84, 167-176.",
      "Keyes, C. L. M. (2002). The mental health continuum: from languishing to flourishing in life. <em>Journal of Health and Social Behavior</em>, 43, 207-222."
    ]
  },
  en: {
    title: "Well-being, in depth",
    intro: `<p>The WHO-5 was born in 1998 inside a <span class="t" data-tip="World Health Organization. The questionnaire came out of the DepCare project, designed to screen well-being and depression in primary care.">WHO</span> project and runs almost against the grain: while most questionnaires count symptoms — how badly you are doing — this one counts <span class="t" data-tip="Hedonic well-being: the presence of positive states like good mood, calm, energy and interest. The opposite of measuring the absence of problems.">positive well-being</span>. All five statements are phrased positively (cheerful, calm, active, rested, interested) and ask how often you have felt that way in the <span class="t" data-tip="The fixed window of the last two weeks captures a recent, stable state, not a single day's mood nor a distant, blurry memory.">last two weeks</span>. It is among the most used and most translated well-being measures in the world, precisely because it is short and clear.</p>`,
    blocks: [
      { h: "Measuring what's there, not what's missing", html: `<p>The key difference: being well is not simply not being unwell. <span class="t" data-tip="Corey Keyes: he argued that mental health and mental illness are not the two ends of one line, but two distinct dimensions. You can have few symptoms and still languish, or live with a disorder and keep good well-being.">Keyes</span> showed that mental health and mental illness are not two poles of a single line but two separate axes: you can have few symptoms and still <span class="t" data-tip="Languishing: a state of stagnation and emptiness, without full-blown illness. Not depression, but not full well-being either; Keyes contrasts it with flourishing.">languish</span>, and you can live with a disorder while keeping decent well-being. The WHO-5 measures this second, positive axis, which symptom questionnaires leave out.</p>` },
      { h: "A dual-use instrument", html: `<p>Curiously, measuring well-being also works as a <span class="t" data-tip="Screening: a quick test that flags who is worth assessing more closely. It makes no diagnosis: it separates those probably fine from those worth a closer look.">screen</span> for depression. Low scores (roughly below 50 out of 100, with the stricter threshold at 28) are a signal worth following up. This works because the loss of positive well-being — no more pleasure, energy, interest — is one of the earliest depressive signs. But beware: a low score is <b>not a diagnosis</b>. It is a traffic light saying «look closer», not a verdict.</p>` },
      { h: "Hedonic and eudaimonic", html: `<p>The WHO-5 captures <span class="t" data-tip="Hedonic well-being: feeling good, experiencing pleasure and calm, being in good spirits. The old idea of happiness as pleasant experience.">hedonic</span> well-being — feeling good here and now. That is only half the story. The other half is <span class="t" data-tip="Eudaimonic well-being: the sense of meaning, growth, autonomy and purpose. It goes back to Aristotle; Carol Ryff proposed a modern measure. A life can be meaningful without always being pleasant.">eudaimonic</span> well-being: meaning, purpose, growth — things that can be present even in unpleasant periods. Someone deep in a hard, important task may have a modest WHO-5 and a life full of meaning. The test measures how you feel, not how much what you do matters.</p>` },
      { h: "Why two weeks and five statements", html: `<p>The two-week window is the same one used by the diagnostic criteria for depression: long enough to outlast a bad day, short enough to remain a reliable memory. And five statements are enough because hedonic well-being, measured this way, behaves like a single coherent dimension: the five questions all pull in the same direction. That is why so brief a tool holds up against far longer questionnaires.</p>` }
    ],
    beyond: `<ul>
      <li><b>Not a diagnosis.</b> The WHO-5 tells you how much well-being you felt, not why. A low score can come from depression, but also from stress, grief, physical illness or simply a heavy week.</li>
      <li><b>Sensitive to change.</b> It is widely used to track the effect of therapies and treatments over time, because it catches improvements even before symptoms have fully cleared.</li>
      <li><b>Beyond psychiatry.</b> It is used in diabetes and other chronic illnesses, where low well-being predicts worse outcomes: body and mood are not separate compartments.</li>
      <li><b>Languishing isn't depression.</b> Stagnation without illness — feeling empty, «neither good nor bad» — is a state of its own, and Keyes treats it as a risk factor for future problems.</li>
    </ul>`,
    taratura: `<p>The WHO-5 is well validated: a large review gathered hundreds of studies and rated it a good indicator of well-being and a decent screen for depression, across many languages and settings. Its limits are those of brevity and format: five positive statements capture the hedonic side but not life's meaning, and the all-positive wording can invite «easy» agreement from people prone to acquiesce. The thresholds (50 and 28) are useful conventions, not sharp boundaries, and any screen must be confirmed by an assessment. In the general population the mean is around 60-70.</p>`,
    reading: [
      "WHO (1998). <em>Wellbeing measures in primary health care / The DepCare Project</em>. Psychiatric Research Unit, Hillerød.",
      "Topp, C. W., Østergaard, S. D., Søndergaard, S. & Bech, P. (2015). The WHO-5 Well-Being Index: a systematic review. <em>Psychotherapy and Psychosomatics</em>, 84, 167-176.",
      "Keyes, C. L. M. (2002). The mental health continuum: from languishing to flourishing in life. <em>Journal of Health and Social Behavior</em>, 43, 207-222."
    ]
  },
  pt: {
    title: "O bem-estar, em profundidade",
    intro: `<p>O WHO-5 nasceu em 1998 dentro de um projeto da <span class="t" data-tip="Organização Mundial da Saúde. O questionário surgiu do projeto DepCare, pensado para rastrear bem-estar e depressão na atenção primária.">OMS</span> e vai quase na contramão: enquanto a maioria dos questionários conta sintomas — o quanto você está mal — este conta o <span class="t" data-tip="O bem-estar hedônico: a presença de estados positivos como bom humor, calma, energia e interesse. O oposto de medir a ausência de problemas.">bem-estar positivo</span>. As cinco frases são todas formuladas no positivo (alegre, calmo, ativo, descansado, interessado) e perguntam com que frequência você se sentiu assim nas <span class="t" data-tip="A janela fixa das últimas duas semanas capta um estado recente e estável, não o humor de um único dia nem uma lembrança distante e embaçada.">últimas duas semanas</span>. É uma das medidas de bem-estar mais usadas e traduzidas do mundo, justamente por ser breve e clara.</p>`,
    blocks: [
      { h: "Medir o que há, não o que falta", html: `<p>A diferença-chave: estar bem não é simplesmente não estar mal. <span class="t" data-tip="Corey Keyes: propôs que saúde mental e transtorno mental não são os extremos de uma mesma linha, mas duas dimensões distintas. Dá para ter poucos sintomas e mesmo assim definhar, ou conviver com um transtorno e ter bom bem-estar.">Keyes</span> mostrou que saúde mental e transtorno mental não são os dois polos de uma única linha, mas dois eixos separados: dá para ter poucos sintomas e ainda assim <span class="t" data-tip="Languishing: um estado de estagnação e vazio, sem doença declarada. Não é depressão, mas também não é pleno bem-estar; Keyes o contrapõe ao florescer.">definhar</span>, e é possível conviver com um transtorno mantendo um bem-estar razoável. O WHO-5 mede esse segundo eixo, o positivo, que os questionários de sintomas deixam de fora.</p>` },
      { h: "Um instrumento de duplo uso", html: `<p>Curiosamente, medir o bem-estar também funciona como <span class="t" data-tip="Rastreio: um teste rápido que sinaliza quem vale a pena avaliar melhor. Não faz diagnóstico: separa quem provavelmente está bem de quem convém investigar.">rastreio</span> para a depressão. Pontuações baixas (indicativamente abaixo de 50 em 100, com o limiar mais rígido em 28) são um sinal que vale a pena investigar. Isso é possível porque a perda de bem-estar positivo — sem mais prazer, energia, interesse — é um dos primeiros sinais depressivos. Mas atenção: uma pontuação baixa <b>não é um diagnóstico</b>. É um semáforo que diz «olhe melhor», não um veredito.</p>` },
      { h: "Hedônico e eudaimônico", html: `<p>O WHO-5 capta o bem-estar <span class="t" data-tip="Bem-estar hedônico: sentir-se bem, ter prazer e calma, estar de bom humor. A antiga ideia de felicidade como experiência agradável.">hedônico</span> — sentir-se bem aqui e agora. É só metade da história. A outra metade é o bem-estar <span class="t" data-tip="Bem-estar eudaimônico: o senso de significado, crescimento, autonomia e propósito. Vem de Aristóteles; Carol Ryff propôs uma medida moderna. Uma vida pode ter sentido sem ser sempre agradável.">eudaimônico</span>: sentido, propósito, crescimento — coisas que podem existir mesmo em períodos pouco agradáveis. Alguém mergulhado numa tarefa difícil e importante pode ter um WHO-5 modesto e uma vida cheia de significado. O teste mede como você se sente, não o quanto importa aquilo que você faz.</p>` },
      { h: "Por que duas semanas e cinco frases", html: `<p>A janela de duas semanas é a mesma usada pelos critérios diagnósticos da depressão: longa o bastante para superar o dia ruim, curta o bastante para continuar uma lembrança confiável. E cinco frases bastam porque o bem-estar hedônico, medido assim, se comporta como uma única dimensão coerente: as cinco perguntas puxam todas na mesma direção. É por isso que uma ferramenta tão breve resiste à comparação com questionários bem mais longos.</p>` }
    ],
    beyond: `<ul>
      <li><b>Não é um diagnóstico.</b> O WHO-5 diz quanto bem-estar você sentiu, não por quê. Uma pontuação baixa pode vir de depressão, mas também de estresse, luto, doença física ou simplesmente uma semana pesada.</li>
      <li><b>Sensível à mudança.</b> É muito usado para acompanhar ao longo do tempo o efeito de terapias e tratamentos, porque capta melhoras mesmo antes de os sintomas sumirem.</li>
      <li><b>Além da psiquiatria.</b> É empregado no diabetes e em outras doenças crônicas, onde o bem-estar baixo prediz piores desfechos: corpo e humor não são compartimentos separados.</li>
      <li><b>Definhar não é deprimir.</b> A estagnação sem doença — sentir-se vazio, «nem bem nem mal» — é um estado à parte, e Keyes o trata como fator de risco para problemas futuros.</li>
    </ul>`,
    taratura: `<p>O WHO-5 é bem validado: uma ampla revisão reuniu centenas de estudos e o considera um bom indicador de bem-estar e um razoável instrumento de rastreio para a depressão, em muitas línguas e contextos. Os limites são os da brevidade e do formato: cinco frases no positivo captam o hedônico, mas não o sentido da vida, e a formulação toda positiva pode favorecer respostas «de conveniência» em quem tende a concordar. Os limiares (50 e 28) são convenções úteis, não fronteiras nítidas, e o rastreio sempre precisa ser confirmado por uma avaliação. Na população geral a média fica em torno de 60-70.</p>`,
    reading: [
      "WHO (1998). <em>Wellbeing measures in primary health care / The DepCare Project</em>. Psychiatric Research Unit, Hillerød.",
      "Topp, C. W., Østergaard, S. D., Søndergaard, S. & Bech, P. (2015). The WHO-5 Well-Being Index: a systematic review. <em>Psychotherapy and Psychosomatics</em>, 84, 167-176.",
      "Keyes, C. L. M. (2002). The mental health continuum: from languishing to flourishing in life. <em>Journal of Health and Social Behavior</em>, 43, 207-222."
    ]
  }
};
